### ISSUE TITLE
Smokeview: cycle button for viewpoints broken

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#10069]
In the Viewpoints section of the Motion/View/Render panel of Smokeview, there is a button "Cycle", which is intended to cycle through the named viewpoints. This worked in version 6.7.15 (the version released with FDS 6.7.5) but not in 6.7.16.  (The break coincided with the arrival of the default views XMAX etc., I think. Sorry, I haven't tested 6.7.17.) The broken behaviour in 6.7.16 is that repeated presses give a limited number of view changes -- I think none, if there are no user-defined views -- and then no change.

**Comment by gforney** [comment]
I"ll take a look

**Comment by gforney** [comment]
should be fixed in smokeview posted here.  let me know if there is still a problem.  Note there are now 3 cycle buttons, one for user viewpoints, one for default viewpionts and one for all viewpoints .  
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by gforney** [comment]
"Note there are" not "Not there are"

**Comment by obscureed** [comment]
Great, thanks. It will take me a week or so to find time to test this.

**Comment by obscureed** [comment]
Yes, that works for me (tested on Linux) -- thanks!

**Comment by gforney** [comment]
thanks for reporting back
