### ISSUE TITLE
HRR and temperature

### ISSUE THREAD

**Issue by Evil-Doctor** [firemodels/fds#10081]
Hello everyone, I am doing a simulation of propane combustion, mainly analyzing the indoor temperature and flame height. When I set the wall as the experimental parameter, the HRR will not reach my set value, and the temperature measured by the thermocouple will always be Decrease, but this does not match the actual measured value?
![image](https://user-images.githubusercontent.com/81680065/144012071-ba02d7e8-9937-4031-bacb-8384131c673f.png)
![image](https://user-images.githubusercontent.com/81680065/144012129-89636578-a5e0-4310-80a8-047129d0a248.png)
[](url)
[0.01.txt](https://github.com/firemodels/fds/files/7624123/0.01.txt)

**Comment by rmcdermo** [comment]
You have a few "no no"s in your input file:
1. Don't set LOCK_TIME_STEP=T.  There is usually not a good reason to set DT either.  Let FDS pick the time step.
2. Don't use 2 MISC lines.
3. If your fuel is propane, then use FUEL='PROPANE', which will use all the correct thermal properties.

Beyond this, you have not demonstrated anything wrong with the code.  You are asking us to do your validation work for you.  It is often difficult to reconcile simulation and experiment.  Often heat flux through compartment walls is an issue for matching temperatures.  But if you do not have the proper ventilation, you will not get a high enough HRR and then lower temperatures.  I would start by making sure you have HRR = MLR * HOC.

This issue is better suited for the discussion forum.  Please continue the thread there unless you identify a bug in the code.  Thanks
