### ISSUE TITLE
Depressurisation in a balanced lobby 

### ISSUE THREAD

**Issue by 00Maida** [firemodels/fds#10311]
Hello,

I've run into a strange phenomena when modelling a balanced system with a ceiling inlet and extract vent placed in a lobby. 

I wasn't sure if this was a problem with FDS or an error in my expectations.

I've tried numerous sensitivity arrangements with different surfaces, turbulence models, leakage conditions from fire doors (which of course helped but still seeing a level of depressurisation).

I understand that the flow rates maybe somewhat high with respect to the lobby size, although I wouldn't have anticipated depressurisation levels of this magnitude (-4Pa) given a balanced system.  

Would much appreciate any assistance/clarity with this.

See below the fds input data - basic box model:

Model_1.fds

Generated by PyroSim - Version 2021.4.1201
09-Feb-2022 17:12:28

&HEAD CHID='Model_1'/
&TIME T_END=50.0/
&DUMP DT_SLCF=1.0/
&MISC SIMULATION_MODE='LES'/
&COMB SUPPRESSION=.FALSE./

&MESH ID='Lobby-02', IJK=20,53,30, XB=4.7,6.7,-1.2,4.1,0.0,3.0/

&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      CO_YIELD=0.04,
      SOOT_YIELD=0.1,
      HEAT_OF_COMBUSTION=2.0E+4,
      RADIATIVE_FRACTION=0.35/

&DEVC ID='Pressure  - Lobby 2', QUANTITY='PRESSURE', XYZ=5.6,1.5,1.5/
&DEVC ID='Extract', QUANTITY='VOLUME FLOW', XB=5.4,6.0,2.3,2.9,3.0,3.0/
&DEVC ID='Inlet', QUANTITY='VOLUME FLOW', XB=5.4,6.0,-0.4,0.2,3.0,3.0/

&MATL ID='GYPSUM PLASTER',
      FYI='Quintiere, Fire Behavior - NIST NRC Validation',
      SPECIFIC_HEAT=0.84,
      CONDUCTIVITY=0.48,
      DENSITY=1440.0/

&SURF ID='Gypsum',
      RGB=146,239,225,
      DEFAULT=.TRUE.,
      BACKING='VOID',
      MATL_ID(1,1)='GYPSUM PLASTER',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=0.1/
&SURF ID='Inlet',
      COLOR='GREEN',
      EMISSIVITY=1.0,
      VOLUME_FLOW=-1.0,
      TAU_V=-10.0/
&SURF ID='Extract',
      RGB=255,51,255,
      EMISSIVITY=1.0,
      VOLUME_FLOW=1.0,
      TAU_V=-10.0/

&OBST ID='Obstruction', XB=4.7,4.9,-1.0,3.9,0.0,3.0, SURF_ID='Gypsum'/ 
&OBST ID='Obstruction', XB=4.7,6.7,-1.2,-1.0,0.0,3.0, SURF_ID='Gypsum'/ 
&OBST ID='Obstruction', XB=4.7,6.7,3.9,4.1,0.0,3.0, SURF_ID='Gypsum'/ 
&OBST ID='Obstruction', XB=6.5,6.7,-1.0,3.9,0.0,3.0, SURF_ID='Gypsum'/ 

&VENT ID='Inlet', SURF_ID='Inlet', XB=5.4,6.0,-0.4,0.2,3.0,3.0/ 
&VENT ID='Extract', SURF_ID='Extract', XB=5.4,6.0,2.3,2.9,3.0,3.0/ 

&SLCF QUANTITY='TEMPERATURE', PBZ=1.5/
&SLCF QUANTITY='VISIBILITY', PBZ=1.5/
&SLCF QUANTITY='PRESSURE', PBZ=1.5/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBZ=1.5/
&SLCF QUANTITY='PRESSURE', PBZ=2.0/
&SLCF QUANTITY='TEMPERATURE', PBZ=2.0/
&SLCF QUANTITY='VISIBILITY', PBZ=2.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBZ=2.0/
&SLCF QUANTITY='TEMPERATURE', PBX=1.5/
&SLCF QUANTITY='VISIBILITY', PBX=1.5/
&SLCF QUANTITY='PRESSURE', PBX=1.5/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBX=1.5/
&SLCF QUANTITY='PRESSURE', PBY=3.3/
&SLCF QUANTITY='TEMPERATURE', PBY=3.3/
&SLCF QUANTITY='VISIBILITY', PBY=3.3/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=3.3/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBX=5.6/
&SLCF QUANTITY='TEMPERATURE', PBX=5.6/
&SLCF QUANTITY='VISIBILITY', PBX=5.6/
&SLCF QUANTITY='PRESSURE', PBX=5.6/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBX=7.6/

&TAIL /

**Comment by drjfloyd** [comment]
The air that is injected at the supply is injected using the ambient conditions. The air that is removed at the exhaust is done using the conditions in the FDS domain adjacent to the VENT.  The density conditions at the exhaust will not identically equal the density of the ambient air at the supply (the pressure field that develops due to the flow will result in density changes and there is always some numerical error). Since you have fixed volume flow, any differences in density between supply and exhaust will result in slight errors in mass flow and that mass imbalance will manifest itself as a pressure rise or drop. The moment you go to add a fire this will likely even worse as you will be injecting cold dense air and removing hot less dense air.  You should somehow provide a means for FDS to keep the pressure reasonable such as adding leakage or only specifying one of the exhaust and supply and having the other be an HVAC connection to ambient with some small amount of loss assigned to it.
