### ISSUE TITLE
USCARC fails with add/remove OBST

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10357]
@SusanKilian I created another test case for the add/remove OBST that has a non-trivial divergence.  I add a `TMP_FRONT=500` to the `SURF` line.  Here is the case.

[obst_activation_2.fds.txt](https://github.com/firemodels/fds/files/8179532/obst_activation_2.fds.txt)

There are two issues:
1. When run in MPI mode, the case fails at about 5 s.  Note that this case runs fine with the FFT solver (simply comment out the PRES line and try it).
2. The case fails immediately in serial.  I suspect that you have not considered the serial case.  Please double check that the method works in serial (with 4 meshes) once you have 1 sorted out.

**Comment by SusanKilian** [comment]
Hi Randy,

as for the MPI version: At first glance, it doesn't seem to be an issue with obst activation, rather an issue with inseparability.  Here I need to dig deeper.

When I run the same case with INSEPARABLE_POISSON = .FALSE. (current default), then the case runs through to the end. Again, a non-trivial divergence occurs, but I see a very similar increase with the pure FFT version for this case, too.  Can you confirm this?

As for the serial version: it does seem that there is still a bug here, which I will try to fix asap.

Susan

**Comment by rmcdermo** [comment]
Yes, the case has non-zero divergence and we correctly see this with the FFT solver.

**Comment by SusanKilian** [comment]
FYI: It seems that I have found the causes of the errors (instability and failure of serial version). I am still reviewing my other cases and will upload the new version as soon as possible.

**Comment by SusanKilian** [comment]
I hope the new PR will fix the above bugs.

However, there is still one issue that puzzles me and affects the inseparable versions of FFT and USCARC equally.

In order to have a reference plot for UScaRC to compare, I ran the obst_activation_2 case also with the FFT based on the following 'inseparable settings', see attachment:

&PRES VELOCITY_TOLERANCE = 1.0E-10, PRESSURE_TOLERANCE = 1.0E-10, MAX_PRESSURE_ITERATIONS = 50000,                            SUSPEND_PRESSURE_ITERATIONS = .FALSE. /    

Both, the inseparable FFT and UScaRC, show a very similar non-trivial divergence course for this. What confuses me, however, is the behavior of both solvers between Time Step 3900 (T=4.56 s) and 4000 (T=4.66 s). Here the pressure error jumps in both cases from under 10(-9) to above 1.0 and stays more or less at this much bigger level. 

I debugged the pressure errors in detail for both solvers: And for both, it happens in corrector of cycle 3921 at the outflow boundary in mesh 4, starting from cell (16,1,6) which is the cell under the obstruction at the outflow edge. This obstruction is not affected by (de)activation around that time. I am attaching the two out-files for the inseparable FFT (as far as it has currently run) and UScaRC.

I also ran this case without obst activation, i.e. all obstructions were fixed from the beginning, again this effect occurs. 
Is this an expected effect or what do you think about it?

[obst_activation_2_fft_insep.fds.txt](https://github.com/firemodels/fds/files/8215606/obst_activation_2_fft_insep.fds.txt)
[obst_activation_2_fft_insep.out.txt](https://github.com/firemodels/fds/files/8215607/obst_activation_2_fft_insep.out.txt)
[obst_activation_2.fds.txt](https://github.com/firemodels/fds/files/8215608/obst_activation_2.fds.txt)
[obst_activation_2.out.txt](https://github.com/firemodels/fds/files/8215609/obst_activation_2.out.txt)

**Comment by rmcdermo** [comment]
I do not think it is expected.  Please simplify the case and keep trying to pin down the error.  Remove activation from the file, remove multi-mesh (the problem is at the outflow).

**Comment by SusanKilian** [comment]
Yes, I will do that. I actually already tried to reduce the phenomenon to a lower level (e.g. reduce/variate the number of obstructions, turn off the obst activation), but with that I also changed the effects. But I'll continue to dig into it and try to break it down.

**Comment by SusanKilian** [comment]
Okay, I think I have a much smaller case, only one obstruction, the massive increase of pressure error occurs between Time Step 1500 (T=3.6 s) and 1600 (T=3.8 s). For the inseparable FFT this means that the number of pressure iterations explodes from about 30 to 50000. Please see attachment (FFT not finished there, the next iterations obviously also take that long).

[f1.fds.txt](https://github.com/firemodels/fds/files/8216158/f1.fds.txt)
[f1.out.txt](https://github.com/firemodels/fds/files/8216159/f1.out.txt)
[u1.fds.txt](https://github.com/firemodels/fds/files/8216160/u1.fds.txt)
[u1.out.txt](https://github.com/firemodels/fds/files/8216161/u1.out.txt)

**Comment by rmcdermo** [comment]
Looks to me like the issue happens when the flow first starts to reverse at the outflow.

**Comment by SusanKilian** [comment]
Yes, I agree, I had the same impression with the larger case.

**Comment by rmcdermo** [comment]
My bet is that is has something to do with using KRES(IBAR,...) at the boundary when the flow reverses.
```
            CASE(-1)
               IF (UU(IBAR,J,K)>0._EB .OR. INSEPARABLE_POISSON) THEN
                  BXF(J,K) = P_EXTERNAL/ONE_D%RHO_F + KRES(IBAR,J,K)
               ELSE
                  BXF(J,K) = P_EXTERNAL/ONE_D%RHO_F + H0
               ENDIF
```
I suspect that if you check this against the residuals from around line 675 in pres.f90 then this will not be consistent.

If that is not it, then check ONE_D%RHO_F is consistent.

**Comment by SusanKilian** [comment]
Okay, I'll have a detailed look at this

**Comment by SusanKilian** [comment]
I remember stumbling across this part in pres some time ago. In an earlier version for this boundary condition, the part '.OR. INSEPARABLE_POISSON' did not exist. I removed it again as a test but it does not work either, not for FFT nor for UScaRC. And I remember this problem had to do with the correct values of KRES as you suspected. I'll dig deeper right tomorrow morning.

**Comment by SusanKilian** [comment]
It looks like I have found a solution in UScaRC for this special case, for which the pressure error remains small throughout, see attachment. I still have to think about how I can transfer my workaround for this case to general cases or also to the FFT.  This method is not easily transferable to the FFT, because the solution mechanisms in UScaRC are different than in the FFT. 
Unfortunately I have to go to a meeting for today, but will get back to you with it asap.
[u1_new.out.txt](https://github.com/firemodels/fds/files/8223415/u1_new.out.txt)

**Comment by rmcdermo** [comment]
@SusanKilian I now realize this issue is a duplicate of #10271 .  Let's close this one and work from the other.  Thanks
