### ISSUE TITLE
Practice Atrium Project Runtime

### ISSUE THREAD

**Issue by moodyj2000** [firemodels/fds#10384]
I have an atrium project I modeled after a real atrium I dealt with a few years back.  To me it is a simple model but it takes forever to run and crashes almost 100% of the time before reaching 1 minute.  I had originally modeled the project using the localized leak procedure at the doors but have since deleted them in an effort to just see if I can speed the model up.  It is setup as a furniture fire in a two story atrium with smoke vents that engage when a detector is tripped.  Any help would be appreciated.
[Atrium_Practice.txt](https://github.com/firemodels/fds/files/8224364/Atrium_Practice.txt)

**Comment by rmcdermo** [comment]
I'm running the case.  I'll let you know how it goes.

**Comment by moodyj2000** [comment]
Thanks for the help!

**Comment by rmcdermo** [comment]
OK, I've reproduced the problem with the latest code.  Looks like an HVAC velocity bc issue.  I'm going to try a new pressure solver we've been working on to see if that sorts things out.

<img width="1760" alt="Screen Shot 2022-03-11 at 10 10 56 AM" src="https://user-images.githubusercontent.com/4418497/157894480-72d23d41-d529-462d-a89b-24c380a75111.png">

**Comment by drjfloyd** [comment]
The HVAC routines are not being used in this case; the exhausts are being defined using VENT with VOLUME_FLOW on SURF_ID.

**Comment by rmcdermo** [comment]
Sorry, my mistake.

**Comment by moodyj2000** [comment]
Yes, I have approached this problem using several methods to test out FDS capabilities.  I had defined HVAC nodes prior to dropping back to vents.

**Comment by rmcdermo** [comment]
Well, with new pressure solver, we get something odd right off the bat.  This compartment (presumably sealed?) get a very high temperature within a fraction of a second.

<img width="719" alt="Screen Shot 2022-03-11 at 10 33 06 AM" src="https://user-images.githubusercontent.com/4418497/157898294-f38d44a1-2397-4462-a4de-22c8ea7aa1b5.png">

**Comment by rmcdermo** [comment]
OK, I think what I'm seeing in the last post is just related to the fact that the global solvers do not yet deal with activation of OBST per Issue #10271

**Comment by drjfloyd** [comment]
It looks like the issue is the door functions. A control function changes state from the initial state when its inputs evaluate to .TRUE. and keeps its initial state when its inputs evaluate to .FALSE. 

The initial state of invert (the value the control has when its inputs are evaluated as .FALSE.) is .TRUE.  At t=0 invert goes to get the logical state of Door Opening. Door Opening needs tdelay which needs detection. There is no detection which means the delay timer hasn't started which means the state of tdelay is .FALSE. which means Door Opening keeps its initial state of .TRUE.  This .TRUE. is seen by invert and an ALL function with a single .TRUE. input evaluates to .TRUE. The function state is flipped from its initial state to .FALSE. which means the doors are therefore open at the start. When the detectors go off and the time delay expires, the Door Opening function evaluates to .TRUE. and the state changes from the initial state of .TRUE. to .FALSE. The function invert with a single .FALSE. input will evaluated to .FALSE. and its output state will be the initial state of .TRUE. which means the doors close when smoke control activates. With the doors closing when the fans operate a vacuum is drawing in the pressure zone and that leads to an instability.  You are also starting the fans before the doors are open and this is not correct. Smoke controls systems that rely upon automatic door openers do not start the fans until the openers indicate they have functioned. Otherwise the fan draws a vacuum in the building an occupants may not be able to open exit doors which must swing outward.

When working with control functions you should be examining the ctrl.csv output or the devc_ctrl_log.csv output and making sure that your control functions are behaving as you intend. 

You don't need the invert function. Just have the door OBST use Door Opening.

**Comment by moodyj2000** [comment]
Good catch on the controls.  This was a remnant of the older method I was using to deal with doors.  I also never thought to check the control log file which is helpful.  

On another note with this model and FDS in particular is vents and obstructions.  I have used the leakage method in the past with localized leaks and HVAC between them.  The issue I have is you cannot easily adjust the mesh resolution once you set the locations of the vents.  This is also true of the exhaust vents in this model.  I tried to refine the resolution in the fire area and coarsen the resolutions as I moved away.  I worked out the meshes so they aligned but then vents starting giving me errors for not being on obstructions even though the coordinates were in fact on the obstructions.  

Also, when the error, for example, says Vent 55 should be on an obstruction does it literally mean the 55th vent down the list?  I'm hoping so as there is never a vent ID that matches the number it gives.

**Comment by drjfloyd** [comment]
You don't have any IOR specified for your VENTs.  That can help FDS locate the OBST when the VENT and OBST don't line up well with the grid.

Yes, Vent 55 means the 55th &VENT from the start of the input file. FDS doesn't require that all VENTs be given a unique character ID. When there is an error, the ordinal number is all we have that applies to all VENTs.

**Comment by rmcdermo** [comment]
So, is this sorted out now?  Please let me know if there is an instability with the case once the CTRLs are correct.  Thanks

**Comment by moodyj2000** [comment]
I revised this to remove the issues with the controls.  FDS export from Pyrosim does not transfer their wall holes so I am revising the FDS file to account for the door openings.  For the first time I actually was able to get a long run (>60 sec) but it is still taking a very long time. I was 847 seconds into the model this morning with 68 hours of time and an estimated 70 hours to go to get to 1200 seconds. I will upload my modified FDS file when I am finished..

Thank You,
Jason Moody, PE
Mechanical Engineer
RN&M ENGINEERS
94 Main Street, Canton, NC 28716
828-492-0677 ext. 125
mobile 828-400-3198
***@***.******@***.***>

**Comment by rmcdermo** [comment]
Can this be closed?

**Comment by moodyj2000** [comment]
Although I never found a satisfactory solution for that model, attempts to simplify the model resulted in a better outcome.  Lost some resolution and perhaps less realistic results but for what I was looking at all is good.  Yes, it can be closed.

Thank You,
Jason Moody, PE
Mechanical Engineer
RN&M ENGINEERS
94 Main Street, Canton, NC 28716
828-492-0677 ext. 125
mobile 828-400-3198
***@***.******@***.***>

**Comment by rmcdermo** [comment]
Ok, thanks.
