### ISSUE TITLE
Segmentation error in the 2nd restart

### ISSUE THREAD

**Issue by zma22** [firemodels/fds#10388]
Hello,
I am using FDS 6.7.5 for running a model with 1000 meshes with burning simulations. The model has run successfully after 1st restart. After the 2nd restart, it has Segmentation error (forrtl: severe (174). Segmentation fault occurred. I had 'ulimit -s unlimited' in the batch script file in Linux system. It didn't help. I have attached a shortened model file here. If a full model is necessary, please let me know. The error message was 

MPI Process     30 started on r17c13.bullx
 MPI Process     37 started on r17c13.bullx
 MPI Process      3 started on r17c13.bullx

 Reading FDS input file ...

 MPI Process    236 started on r17c19.bullx
 MPI Process    350 started on r17c21.bullx
 MPI Process    296 started on r17c20.bullx
 MPI Process     99 started on r17c15.bullx
 MPI Process    141 started on r17c16.bullx

 Fire Dynamics Simulator

 Current Date     : March 13, 2022  20:26:52
 Revision         : -
 Revision Date    : 
 Compiler         : Intel ifort 19.0.4.243
 Compilation Date : Apr 08, 2021 13:38:50

 MPI Enabled;    Number of MPI Processes:    1000
 OpenMP Enabled; Number of OpenMP Threads:      2

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2018 Update 4 for Linux* OS

 Job TITLE        : Fire Tests by Joint Fire Research Organization
 Job ID string    : JFRO_LD30_RR_NEW_R333W_FULLBURN_LARGE2

Time Step: 345700, Simulation Time:    650.04 s
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
fds_impi_intel_li  000000000855E4C3  Unknown               Unknown  Unknown
libpthread-2.17.s  00007EFFC1B2E630  Unknown               Unknown  Unknown
fds_impi_intel_li  000000000885BC14  Unknown               Unknown  Unknown
fds_impi_intel_li  00000000088592F9  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000008DE1088  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000008DDD0B1  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000008DDCA0A  Unknown               Unknown  Unknown
fds_impi_intel_li  000000000866E458  fds_IP_create_or_        1530  main.f90
fds_impi_intel_li  0000000008634EB7  MAIN__                    750  main.f90
fds_impi_intel_li  0000000000407312  Unknown               Unknown  Unknown
libc-2.17.so       00007EFFC002D555  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  0000000000407229  Unknown               Unknown  Unknown
srun: error: r17c13: task 35: Exited with exit code 174
.......
Best regards,
ZMa

[full_large2_short.txt](https://github.com/firemodels/fds/files/8244829/full_large2_short.txt)

**Comment by rmcdermo** [comment]
The first thing we are going to do is run everything with the current source.  Can you compile the latest and try it on your end?  Thanks

**Comment by zma22** [comment]
It is computationally very expensive. The previous two runs, each takes 3 days and 1000 cpus. Our partition limit is 3 days and 1024 cpus. If you are sure it is a bug and has been fixed, then we have to change the version. So is there any solution before we do it? Do you suspect any problem in the model?
Best regards.

**Comment by rmcdermo** [comment]
I do not know what the problem is, but I need you to first update the input file to run with the latest source.  I see you have a single mesh to describe the domain.  Please just use that and run for a couple time steps on a local machine with 6.7.7, this will make sure the inputs are in reasonable shape.  Then send me that input file.  Do not partition the meshes yourself, I'll do that with MULT.  Just give me an input file that will run on a single process with the latest source.  Thanks

**Comment by zma22** [comment]
I will prepare the model and run a few steps with latest version, then upload here. Thanks.

**Comment by zma22** [comment]
Please find the attached input file for single process. I modified the grid size to 22.5 cm to test the model in single process and it works fine. The actual grid size used in the original model is 2.25 cm and linux cluster may be necessary.

[full_large2_single_process.fds.txt](https://github.com/firemodels/fds/files/8255157/full_large2_single_process.fds.txt)

**Comment by mcgratta** [comment]
If this model works fine, what do you want us to fix? I cannot run your original case because I do not have that many cores on our cluster.

**Comment by zma22** [comment]
I mean the model works fine when running a few steps as you instructed above and there are no input errors. Please see the context. The problem is: 1) I ran the model of burning process for around over 310 seconds. Then the simulation is finished/stopped (timeout) since the Linux cluster has a partition limit of 72 hours for 1000 cpus. 2) then I restart the simulation for running another 350 s (72 hours), then timeout again and simulation stopped at 660s. 3) then I restart the simulation again. This time there is segmentation fault at the starting. Please see the above error message. What is the reason? We don't have the privilege to run large simulation over three days, that's why we have to utilize the restart function of FDS to relay.

**Comment by mcgratta** [comment]
Are there devices or controls that activate and change vents and obstructions? Do you make any changes to the input file between restarts besides adding RESTART=T? If you start the case and run it a few seconds, stop it, start it, stop it, start it, do you have a problem? Have your reproduced the original error?

**Comment by zma22** [comment]
There are no devices or controls that change the vents and obstructions. I only added the RESTART=.TRUE. to MISC line. I will start and restart the case a few times and let you know if the problem is reproduced.

**Comment by zma22** [comment]
It seems that the restart function is vulnerable. I have tried a few cases without success even in the first RESTART. Please find the attached case which use 32 meshes. I have tried to start and stop a few times at the beginning of the simulation (less than 10s) in local window desktop without problem. However in Linux cluster, after I ran 14 days (around 900s), then stop and restart without success in the 1st restart. The same Segmentation Fault error. Why?
[grid_11mm.fds.txt](https://github.com/firemodels/fds/files/8369180/grid_11mm.fds.txt)

**Comment by mcgratta** [comment]
I'll run the case and try to restart it.

**Comment by mcgratta** [comment]
I can stop and restart grid_11mm.fds, but I have not run it for a long time. Looking at your inputs, the only thing that i can see that might cause a problem is `BURN_AWAY`. However, your wood blocks do not reach zero mass because there is a 20% char yield. Just to check, when you run your 14 day case and look at the results in Smokview, do you see obstructions that disappear?

**Comment by zma22** [comment]
No, I didn't see the disappearing obstructions in smokeview at 900s. It looks that all wood sticks keep their shapes.

**Comment by mcgratta** [comment]
I have stopped and restarted your case several times over the past few days. I am using a linux cluster. So far, I have not had any seg faults.

**Comment by zma22** [comment]
I have 'ulimit -s unlimited' in the SBATCH script. Do I need other line in the job submission script?

**Comment by mcgratta** [comment]
No, that is all you need.

**Comment by zma22** [comment]
Now I got cases failed in 1st restart. The analysis was stopped due to TIMEOUT and restart files were produced by &DUMP. I didn't get any success in recent RESTART for a few cases (all cases in recent days if I remember right and they are similar FDS models). Any issues possibly link to the Linux environment for the recent cases?

**Comment by mcgratta** [comment]
I do not understand. Are you running these cases with the latest version of FDS? Are you stopping the cases periodically using DT_RESTART? If the simulation stopped because of a TIMEOUT, there might be something wrong with your network. 

In any case, I cannot reproduce this problem with the latest source code.

**Comment by zma22** [comment]
I am using FDS6.7.5. TIMEOUT means that the Linux allow maximum running time three days. Then stop the analysis. I have succeed the first restart before in the original case. I can't use the latest version since there is a 'Maximum density' error with the latest version and all my analyses were done with 6.7.5 successfully except RESTART.

**Comment by zma22** [comment]
The case with 'Maximum density' error happened in a different FDS model with specified HRRs with the latest version.

**Comment by mcgratta** [comment]
For the case with the "maximum density" error, do you have sealed pockets within the domain. That is, are there regions that are completely surrounded by obstructions?

**Comment by zma22** [comment]
There are steel columns I-section with fire protection boards. I am not sure if it causes problem. Please have a look at the model file.
[full5_6int.fds.txt](https://github.com/firemodels/fds/files/8392249/full5_6int.fds.txt)

**Comment by zma22** [comment]
Does it make sense to restart using the latest version for the results from 6.7.5 for the burning model? I have several models that need a working solution for RESTART.

**Comment by mcgratta** [comment]
No. Restarts can only be done with the exact same version. I am running your full5 case.

**Comment by mcgratta** [comment]
For the case with the steel columns, add these lines to your input file. These lines add a small leak (1 cm^2) to the top of the narrow column. This will relieve the fictitious pressure build-up which causes numerical problems. Let me know if that works for you.
```
&VENT XB= 1.861, 1.989, 1.173, 1.301, 3.0, 3.0, SURF_ID='LEAK' /
&ZONE XYZ=1.91,1.23,1.00, LEAK_AREA(0)=0.0001 /
&SURF ID='LEAK', LEAK_PATH=0,1, COLOR='RED' /
```

**Comment by mcgratta** [comment]
I still get numerical instabilities in my test cases. The lines I added only work for one column. The other hollow column develops instabilities too. I need to work on this more.

**Comment by zma22** [comment]
For the grid_11mm model, could you also check why the burnt weight is much more than the actual total weight of wood sticks (48.4 kg). There are about 9kg equivalent weight from burner (200kw*0.55*0,55/16000*2400s) to be deducted. But still much more burnt wood than the total weight. I have completed the grid size 15mm cases, and the actual burnt mass is 72.8 kg (deduct the burner) and the actual weight of wood is 48.5kg.

**Comment by mcgratta** [comment]
What output quantity are you looking at?

**Comment by zma22** [comment]
I have used the mass loss rate MLR to calculate the total burnt fuel weight.

**Comment by mcgratta** [comment]
This case is too complicated and too long to diagnose this kind of problem.
Create a very simple test case to verify conservation of mass.

**Comment by mcgratta** [comment]
Here's an update on the various issues:

1. I cannot reproduce the restart problem. I have stopped and restarted the case 5 or 6 times over the past week. It has not failed.
2. I cannot verify whether the wood mass loss is consistent. The case is too complicated and too long. I need a simpler test case.
3. I can verify that there is a problem with the case with the hollow steel columns.

To deal with all these issues, you need to first install the latest test bundle:

[https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC)

For the case with the hollow columns, you need to put this (and only this) on the PRES line
```
&PRES SOLVER='ULMAT' /
```
Then you need to make sure that the red objects do not intersect the hollow columns. Part of the problem is that you have added a burning object to the inside of a hollow steel column. The pressure solver will help to maintain the interior of the column to be free of numerical errors that caused the failure.

You can run your other cases with the new versions and if issues arise, start new issues. This current issue is getting complicated. Let me know how things progress.

**Comment by zma22** [comment]
Thank you. I will test the solution. I will also create a simple case to reproduce the excessive mass loss and restart segmentation errors.

**Comment by zma22** [comment]
I attach the grid_15mm model file and the results (processed CHID_hrr.csv) file. The grid_15mm model file is similar to grid_11mm model file (the one you are running for restart problem). The grid is regular to match the cross section of wood sticks, however I got too much mass loss (>150% of the total fuel mass). I hope you can take a look and point out quickly the possible error. 
I will continue to create a simple model to reproduce these errors.
[full5_15mm.fds.txt](https://github.com/firemodels/fds/files/8412819/full5_15mm.fds.txt)
[grid_size_15mm.xlsx](https://github.com/firemodels/fds/files/8412820/grid_size_15mm.xlsx)

**Comment by mcgratta** [comment]
Your wood sticks are 4.5 cm by 4.5 cm. But your have assigned a THICKNESS of 2.25 cm for each of the four faces. This means that each stick is going to generate twice as much fuel vapor. I would expect to generate 48 * 2 * 0.8 = 76.8 kg of fuel vapor.

**Comment by zma22** [comment]
what is the right thickness to assign? or how to make the input so that the right amount of fuel vapor will be generated?

**Comment by mcgratta** [comment]
There is no single "right" way to do this. There are different approaches depending on the objective of your study. But in your case, the most obvious thing to do is to divide your THICKNESS by 2 so that when the wood stick is burned it produces the expected amount of fuel vapor. This will be your model assumption. Whether you realize it or not, you have already made many assumptions, some of which are implicit in the FDS model. When you present the results of this work, you will have to explain these assumptions, and saying that one of the FDS developers told you to do it is not a good explanation.

**Comment by zma22** [comment]
Thanks. I understand the underlining assumptions. I will continue to see if I can produce the RESTART error using a  simpler and faster model. Meanwhile I installed the latest version and see if it solves the problem.

**Comment by mcgratta** [comment]
OK, if new issues arise, start a new issue. This one has become quite complicated. I will close it.
