### ISSUE TITLE
DEVC issue on HVAC LEAK

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#10464]
Following the discussion on:

https://groups.google.com/g/fds-smv/c/LsP9_oqWIDo

FDS file:
[test2.txt](https://github.com/firemodels/fds/files/8489533/test2.txt)

Issue:
This device outputs data:
&DEVC ID='Vol_Flow_E1_total', QUANTITY='VOLUME FLOW WALL', IOR=-2 XB=32.806219,33.6,33.199,33.199,11.7,11.8/

This device yields to zero:
&DEVC ID='Vol_Flow_node1_doorE1_leak_top',  QUANTITY='NORMAL VELOCITY', SPATIAL_STATISTIC='SURFACE INTEGRAL' IOR=-2 XB=32.806219,33.6,33.199,33.199,11.7,11.8 /

**Comment by drjfloyd** [comment]
This is working with the current source but not 6.7.7. There have been some updates to HVAC since 6.7.7 that would have impacted localized leakage. That has probably fixed whatever is wrong in 6.7.7.

You can try the current nightly build of FDS (https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC).  You will need to remove the VOLUME FLOW WALL device as that input has been removed in the current source (now FDS just uses NORMAL VELOCITY with SURFACE INTEGRAL).  Make sure to have IOR on your wall devices.

**Comment by Er9y714** [comment]
I have just tried the shared build. It works indeed. Thank you very much. 
It seems to me that Leak is working properly, only DEVC had issues in the previous FDS versions. 


Do I understand correctly that the nightly build will be available as v6.7.8?

**Comment by drjfloyd** [comment]
It will be in whatever we decide to call the next release: 6.7.8, 6.8, or 7.0
