### ISSUE TITLE
A_DRAG for SURF_CYLINDRICAL

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10514]
In part.f90 where we compute A_DRAG there is this line
```
CASE(SURF_CYLINDRICAL)
    A_DRAG = 2._EB*PI*R_D*SF%LENGTH*LPC%SHAPE_FACTOR
```
Elsewhere in the code, it looks like SHAPE_FACTOR=0.25 and is not changed.  But the shape factor for a cylinder should be 1/pi.

Does anyone have an idea of whether this is intensional or not?

**Comment by mcgratta** [comment]
I'm in favor of just using a SHAPE_FACTOR of 0.25. The orientation of cylinders and plates and random.

**Comment by ericvmueller** [comment]
It looks like the geometry specific `SHAPE_FACTOR` went out in commit 57d1662b68d312b7f213b1b75385e5b0dbd8fdf2
I agree - the previous values (eg 1/pi) are for maximum projected area and don't account for the orientation. The uncertainty in this parameter is sort of lumped into the uncertainty in the drag coefficient ...but I guess another argument for keeping it as 0.25 is that (if I understand correctly) it is the same value used for radiation attenuation irrespective of particle geometry.

**Comment by mcgratta** [comment]
The reason I removed the `SHAPE_FACTOR` from the radiation calculation is that only 0.25 worked for verification cases. I think we should remove `SHAPE_FACTOR` as an input and just hardwire it to 0.25, and also calculate projected areas directly to save on CPU time.

**Comment by ericvmueller** [comment]
If we have a case that demonstrates the need for custom values, then I'm all for allowing it as an input. But until that point, I think it's okay to remove. Especially because it currently can be set for the drag but not radiation, so it's not fully consistent 

...and if it _does_ need to be unique for different particles, then it may also need to be directionally dependent (say there is something like a grass, with particles mostly aligned in one orientation). But again, I'm fine to start simple and build complexity as necessary.

**Comment by rmcdermo** [comment]
I would rather not remove it.  I think we need a vertical cylinder to represent tree trunks that are just barely under resolved, as just one example.  We are far from having a good study of the effect of grid resolution going from well resolved to fully unresolved objects.

In the meantime, I will just add a few comments to the code so that next year I'll remember what is going on with SHAPE_FACTOR.
