### ISSUE TITLE
Question about the values of TMP_G

### ISSUE THREAD

**Issue by StarAlex-Wang** [firemodels/fds#10552]
Dear sirs:
I got a question about the values of TMP_G. In fact, I try to calculate FED_heat using the temperature values. Since TMP_G is in Kelvin in the source code, then the FED_HEAT is calculated as: (HUMAN_GRID(II,JJ)%TMP_G - 273.15_EB)**3.4_EB/5.0E7_EB (Kelvin to Celsius). 
However I got "NaN" in the csv file. When I removed - 273.15_EB, the result in the csv file seems to be OK. It seems that the value (HUMAN_GRID(II,JJ)%TMP_G - 273.15_EB) less than zero caused the "NaN" error. Now that TMP_G is in Kelvin, I believe it is larger than 273.15_EB in fire scene. Then how comes the values (HUMAN_GRID(II,JJ)%TMP_G - 273.15_EB) less than zero? I can't understand this and need your help.
Your comments are much appreciated.

**Comment by gjaeger** [comment]
@StarAlex-Wang Can you share your related feature branch with your change and a small test case?

Which equation are you referring to? Which literature source do you use?

**Comment by StarAlex-Wang** [comment]
> 
Hi Gregor, 
I just want to calculate the FED value caused by heat. By referring to SFPE user guide, I added these codes in evac.f90.
"FED_HEAT =(HUMAN_GRID(II,JJ)%TMP_G - 273.15_EB)**3.4_EB/(50000000_EB * 60.0_EB) + ((HUMAN_GRID(II,JJ)%RADFLUX /1000_EB)**1.33_EB)/(600.0_EB)
HR%INTDOSE_HEAT=DTSP*FED_HEAT + HR%INTDOSE_HEAT"  
(! equations from SFPE user guide to caluculate FED value, the denominator*60 is because minutes are converted to seconds). Attach picture are the equations from SFPE USER GUIDE.
Then question occurs as I get "NaN" in the csv file. When - 273.15_EB is removed, the result in the csv file seems to be OK. It seems the value (HUMAN_GRID(II,JJ)%TMP_G - 273.15_EB) less than zero caused the "NaN" error. But TMP_G is in Kelvin, and it should larger than 273.15_EB in fire scene, right? I can't figure out why. 
Thanks for your kindly help!
![图片1](https://user-images.githubusercontent.com/83077843/166943054-0ec179a8-2540-49ee-8b36-623a134cabf8.png)

**Comment by drjfloyd** [comment]
The 5E7T^-3.4 correlation is based on still air, people at rest, and temperatures above ~50 C.  A best practice for coding this would be to have a MAX statement to not let the correlation be evaluated at temperatures far outside the range it was developed over.

In an FDS simulation it is not impossible for the local temperature to be less than 273 K.  If you were to set TMPA=-10, then at t=0 this would be the case everywhere. Numerical instability or error could also result in this.

**Comment by gjaeger** [comment]
@StarAlex-Wang 
Did you follow the [advice](https://groups.google.com/g/fds-smv/c/NZB89qmOSzE/m/Rkz_UtGLAAAJ) and add some debug to your code? This might help you.

Since [commit 6a1d48a](https://github.com/firemodels/fds/commit/6a1d48aa5ee9485eac41fa27c8a6f771f15a2c48), the FDS+Evac module is no longer part of the code. It seems to me that you are working on an older version. So it will be hard to help you within the scope of this issue tracker.

The variable `HUMAN_GRID` seems to be left in [mesh.f90](https://github.com/firemodels/fds/blob/6d5d42bd5d7d9bc9eea9f5eac7d8af2c61bf99ee/Source/mesh.f90), as well as `HUMAN`, `N_HUMANS`, `N_HUMANS_DIM`. I recommend you to use your [thread](https://groups.google.com/g/fds-smv/c/NZB89qmOSzE) in the discussion group.

I recommend you to close this issue.

**Comment by StarAlex-Wang** [comment]
Well, thank you sirs for your comments. 
I will try it and close the issue.
