### ISSUE TITLE
MPI exchange timed out - FDS stopped

### ISSUE THREAD

**Issue by ghost** [firemodels/fds#10642]
Hello everyone.

During a fire simulation in a car park, in which sprinklers acivate at 272s, I received this error : 

![error289](https://user-images.githubusercontent.com/94290527/170235345-cd4e0680-41cd-4b22-b0fa-9da33ade8da4.png)

First, I ran the simulation twice on my computer, and once on another computer, 14 meshes on 3 cores. The error was occuring at the exact same time (289.25s). Then, I tried to divide these 14 meshes on 6 cores, the simulation went up to 365s and failed again.

![error365](https://user-images.githubusercontent.com/94290527/170237385-e36b38f5-291c-475f-b125-0642c6712f4e.png)

Does anyone have a clue on what's going on ? Is there a limited amount of particle a mesh/core can process ? Or maybe the problem comes from cores sharing particles ?
Thank you for your time.

**Comment by rmcdermo** [comment]
REQ3 is IJK_SIZE exchange.  We would have to see your input file to have a clue of what is happening beyond that.  You need to append .txt to it to post to the Issues page.

**Comment by joktimo** [comment]
I think this is the same issue than https://github.com/firemodels/fds/issues/9951

The solution is to update the Intel MPI Library to the newest version, which is at the moment version 2021.6

**Comment by ghost** [comment]
@rmcdermo here it is, thank for your help
[modele26.txt](https://github.com/firemodels/fds/files/8772261/modele26.txt)

@joktimo I'll check that and come back to you later, thanks !

**Comment by rmcdermo** [comment]
I'm reproducing the error on our system with the latest source.  I am going to kick this one over to Kevin, who will be back next week.

**Comment by mcgratta** [comment]
I am running the case with the latest compilers.

**Comment by mcgratta** [comment]
I am currently running the original case with 6 MPI processes, and I am running the case with 14 processes. Both cases are at about 540 s and still going. I am using the latest source code, which is similar to the latest release. What version are you using?

**Comment by ghost** [comment]
Thanks for the quick answer, I am using the FDS 6.7.8-7 "nightly bundle".

**Comment by mcgratta** [comment]
What is your operating system?

**Comment by ghost** [comment]
Windows but running on Linux (WSL MobaXterm)

**Comment by mcgratta** [comment]
How do you launch the job? Do you use a script or a line command?

**Comment by ghost** [comment]
`mpiexec -np x fds file.fds`, with x the number of cores involved in the simulation.

**Comment by mcgratta** [comment]
Is `fds` the linux executable that you downloaded, or did you compile it yourself?

**Comment by mcgratta** [comment]
This might be a longshot, but try doing this to launch the job
```
mpiexec -np x -genv I_MPI_FABRICS shm fds file.fds
```
This extra option tells the OS to only use the intra-node communicator called `shm`. I assume that you are running this job only on one computer.

**Comment by ghost** [comment]
I downloaded the linux executable. Will do your advice for further simulation and keep you updated, thank you Kevin !

**Comment by ghost** [comment]
Dear Kevin. I tried to process the same simulation with `-genv I_MPI_FABRICS shm` option, but it failed at the exact same time it fails usually.

![image](https://user-images.githubusercontent.com/94290527/172317036-508b06fd-2e56-43c1-965b-aee7faad9c9b.png)
Is there a maximum amount of mesh a core can run ? I also tried to run the simulation on 19 cores instead of 6 and it worked properly.

**Comment by mcgratta** [comment]
I said it was a longshot. There are no limits built into FDS on mesh size, number of meshes, etc. However, you are limited by your computer hardware and software. I suspect that your computer has reached its limit, but I cannot tell you exactly what the problem is. My guess would be that the size of the MPI exchanges is flooding some buffer set up to hold the information before and after it is passed from one process to another. I don't run jobs on a Windows computer or linux emulator. I run jobs on a linux compute cluster that is designed to do these kinds of big calculations. Not that I understand all the specs of this cluster, but I know that RAM, caches, buses, etc, are hardier and more robust than what you have on a single desktop computer. 

I would also guess that the failure occurs after sprinklers have activated, and the MPI exchanges are bigger because of the need to transfer droplet info from one mesh/process to another. Running on 19 cores rather than 6 probably has simplified the exchanges and avoided the bottleneck. Think of it like sending letters from one house to another in a neighborhood, and then introducing a large apartment building with multiple letter senders and receivers. Somehow a clog forms, but I cannot find it on my system, regardless of whether I use 6 or 19 processes.
