### ISSUE TITLE
Leakage vent with material properties and thermal interactions?

### ISSUE THREAD

**Issue by KingCZE** [firemodels/fds#10641]
Good morning,
In relation to my recent FDS forum post ([https://groups.google.com/g/fds-smv/c/t1sB2owRIc4](https://groups.google.com/g/fds-smv/c/t1sB2owRIc4)), I have another issue/question/request. As far as I know, it is not possible to specify material properties for obstructions (surfaces) together with leakage, is that right? This is quite limiting, because some standards require to use leakage for fire non-rated walls (external walls), but then we cannot specify the thermal properties for such a wall, and all the thermal interaction is gone. 

Would it be possible to simply allow to specify the material properties for leakage vents and switch on the thermal interaction (radiation, conduction,... convection might be a bit more theoretical together with the leakage through, but even this could be done, I believe) in the FDS code for these? 

Thank you.

**Comment by drjfloyd** [comment]
You can specify thermal properties for both localized leakage (i.e. HVAC with TYPE_ID='LEAK') and zone leakage (i.e. SURF with LEAK_PATH). They are specified in the normal manner.

**Comment by tmoisand** [comment]
Hello,

I'm sorry to comment on this closed issue, but it seems really familiar with an issue that I am facing myself with FDS V6.7.0.

I am trying to run a script with one sealed compartment (one pressure zone) with a localized leakage at the top and bottom of a door which is on an OBST separating the zone and an area connected to the AMBIENT conditions (via an OPEN SURF).
Everything works fine, until I declare a material with &MATL, without even assigning it to a SURF. The script then won't run and FDS will send the error message "cannot leak and specify flow or pyrolysis at the same time".

When I run this script with FDS V6.6.0, the error doesn't show. I tried to look for some issue fixed in the later than V6.7.0 version of FDS, but I didn't find anything.

Do you have any idea of what could be the origin of the problem?

Thank you very much!

Here is the script if needed:

&HEAD CHID='Leakage'/

&TIME T_END =10/

&MESH IJK = 40,40,30
	  XB = 0.0,4.0,0.0,4.0,0.0,3.0 /
	  
//Limits
&VENT MB= 'XMIN', SURF_ID = 'OPEN' /
&VENT MB= 'XMAX', SURF_ID = 'OPEN' /
&VENT MB= 'YMIN', SURF_ID = 'OPEN' /
&VENT MB= 'YMAX', SURF_ID = 'OPEN' /
&VENT MB= 'ZMAX', SURF_ID = 'OPEN' /

//Walls

&OBST XB = 0.4,3.6,2.0,2.2,0.0,2.5/ 
&HOLE XB = 1.0,1.8,1.99,2.21,0.0,2.0/
&OBST XB = 1.0,1.8,2.0,2.2,0.0,2.0, PERMIT_HOLE =.FALSE., COLOR ='BROWN'/

&OBST XB = 0.4,3.6,0.2,0.4,0.0,2.5, COLOR ='LAVENDER', TRANSPARENCY =0.5/Ymin
&OBST XB = 0.4,3.6,3.6,3.8,0.0,2.6/ Ymax

&OBST XB = 0.4,3.6,0.4,3.8,2.5,2.6/ Plafond
&OBST XB = 0.2,0.4,0.4,3.8,0.0,2.5, COLOR ='LAVENDER', TRANSPARENCY =0.5/ Xmin
&OBST XB = 3.6,3.8,0.4,3.8,0.0,2.5, COLOR ='LAVENDER', TRANSPARENCY =0.5/ Xmax

//Materials

&MATL ID ='Concrete'
          DENSITY =2430
	  CONDUCTIVITY =1.5
	  SPECIFIC_HEAT = 0.736
	  EMISSIVITY =0.7/

//Pressure zone

&ZONE XB = 0.4,3.6,2.2,3.6,0.0,2.5/

&DEVC XB = 0.4,3.6,2.2,3.6,0.0,2.5
            QUANTITY ='PRESSURE'/
	  
&SLCF PBX =1.4
          QUANTITY ='PRESSURE'
	  VECTOR =.TRUE./

//Fire

&VENT XB = 1.0,1.8,2.6,3.4,0.0,0.0, SURF_ID ='FIRE'/
&SURF ID='FIRE'
          COLOR ='RED'
	  HRRPUA =500./
&REAC FUEL ='DODECANE'
            SOOT_YIELD =0.5/

//LEAK

&SURF ID ='Leak'
      COLOR ='BLACK'/

&VENT ID ='Leak_Door_Top_1'
          XB =1.0,1.8,2.0,2.0,1.8,2.0,
	  SURF_ID ='Leak'/ 
&VENT ID ='Leak_Door_Top_2'
           XB =1.0,1.8,2.2,2.2,1.8,2.0,
	  SURF_ID ='Leak'/ 
&HVAC ID ='Leak_Door_Top'
          TYPE_ID ='LEAK'
	  VENT_ID ='Leak_Door_Top_1'
	  VENT2_ID ='Leak_Door_Top_2'
	  AREA =0.000797
	  LEAK_ENTHALPY =.TRUE./
	  
&VENT ID ='Leak_Door_Bottom_1'
          XB =1.0,1.8,2.0,2.0,0.0,0.2,
	  SURF_ID ='Leak'/
&VENT ID ='Leak_Door_Bottom_2'
           XB =1.0,1.8,2.2,2.2,0.0,0.2,
	  SURF_ID ='Leak'/
&HVAC ID ='Leak_Door_Bottom'
          TYPE_ID ='LEAK'
	  VENT_ID ='Leak_Door_Bottom_1'
	  VENT2_ID ='Leak_Door_Bottom_2'
	  AREA =0.003152
	  LEAK_ENTHALPY =.TRUE./

&SLCF PBX =1.4
          QUANTITY ='TEMPERATURE'
	  VECTOR =.TRUE./
	  
&DEVC ID ='Leak flow top 1'
          XB =0.2,1.0,2.0,2.0,1.8,2.0,
	  QUANTITY ='VOLUME FLOW WALL'
	  IOR =-2/
&DEVC ID ='Leak flow top 2'
          XB =0.2,1.0,2.2,2.2,1.8,2.0,
	  QUANTITY ='VOLUME FLOW WALL'
	  IOR =2/

&DEVC ID ='Leak flow bottom 1'
           XB =1.0,1.8,2.0,2.0,0.0,0.2,
	  QUANTITY ='VOLUME FLOW WALL'
	  IOR =-2/
&DEVC ID ='Leak flow bottom 2'
          XB =1.0,1.8,2.2,2.2,0.0,0.2,
	  QUANTITY ='VOLUME FLOW WALL'
	  IOR =2/	 	
	 
&TAIL/

**Comment by rmcdermo** [comment]
If I remove your ZONE line, the case seems to run fine with the last code.  Update to FDS 6.7.9.

**Comment by tmoisand** [comment]
Done, it's fine but the previous problem was something weird for which I didn't find anything on the internet.

Thank you for your help, have a good day!
