### ISSUE TITLE
Unexpected output control functions FDS 6.7.9

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#10836]
Dear,

I'm struggling since a couple of days with some controls, so I made a test case, you find in attachment, to track down the problem.

[input.fds.txt](https://github.com/firemodels/fds/files/9219623/input.fds.txt)

When using the first control from line 20 to 25 instead of getting the F value of the function I get the T value so I don't see the output of my function, but only the input value in my devc file. 

With the second control from line 28 to 36 although I see in the ctrl file that the control changes value nothing happens to the device associated to the control value. 

I am sure that the first control worked in the version 6.7.6 because I have done a test back then, while I don't know about the second one.

I don't know if this is an issue of the input file or I'm missing something out with the new release 6.7.9, but I can't make it work. 

Thank you all for the support.

Matteo

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
This is an output bug and also I think some unclear documentation. The evaluation of the logic is correct for the current inputs.

There are two DEVC outputs for control function: CONTROL and CONTROL VALUE. CONTROL writes the logical state of the function (0 = F and 1 = T) and CONTROL VALUE writes the mathematical value of the function.  For the CUSTOM function we were storing the input value to the RAMP rather than the output value. That was a recently introduced change done when we added the TEMPORAL_STATISTIC of SMOOTHED that should not have been made. That needs to be undone. This was the reason for the odd device output for the first CUSTOM function.

As the file is written now:

For the cycle_RAMP1 function, it should change state at 10 s and in the devc_ctrl_log file this is the case. At 10.04 s the function becomes positive and changes state.

The timer_now1 and timer_now2 functions should change state at 10 and 11 s. In the devc_ctrl_log file we see that this happens at 10.04 and 11.04 s.

The time_control function changes state when either timer_now1 or 2 is true. This should happen when timer_now1 activates and in the devc_ctrl_log file it does change state at 10.04 s when timer_now1 activates.

The device out_ctrl is the numerical value of time_control, but time_control is just a logic function and it doesn't have a numerical value that changes. This means the input to cycle_ramp2 never changes and as a result the second CUSTOM function will not change state.  What you need in this case is to use CONTROL rather than CONTROL VALUE. Then when time_control changes state, the DEVC will go from 0 to 1 and cycle_RAMP2 will change.  In this case however, the DEVC output would only be 0 or 1 and cycle_RAMP2 will just be the same state as time_control.  I should add an error message when CONTROL VALUE is used for a logical only function and make this more clear in the manual.

**Comment by drjfloyd** [comment]
Fixed the output, added an error for CONTROL VALUE being used for a logic only CTRL, and updated the User's Guide.

https://github.com/firemodels/fds/commit/d680e935885412838d224333bc1776a3f18fe4ba

**Comment by mpachera** [comment]
Thank you Jason, for your quick reply and clarification. I fixed the second control and it works as expected. Should I leave the issue open or can I close it?

**Comment by drjfloyd** [comment]
I'll close it. Thanks for the follow up.
