### ISSUE TITLE
MPI issue with overlapping meshes

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#10928]
After 3 hours of debugging my complex model, it turned out the issue was overlapping meshes when using MPI. I never noticed this before because I never use overlapping meshes but this time I had wanted to try. 

Could you please try and see if you can reproduce the issue? After initializing the calculation it gets stuck at the step shown below in the picture.

Thank you for your support.  

```

&HEAD CHID='test'/
&TIME T_END=10.0/ 
&MESH ID='Mesh01', MPI_PROCESS=0    IJK=5,6,5, XB=0.0,1.0,0.0,1.2,0.0,1.0/
&MESH ID='Mesh02', MPI_PROCESS=1    IJK=5,6,5, XB=1.0,2.0,0.0,1.2,0.0,1.0/
&MESH ID='Mesh03', MPI_PROCESS=2    IJK=5,6,5, XB=2.0,3.0,0.0,1.2,0.0,1.0/
&MESH ID='Mesh04', MPI_PROCESS=3    IJK=8,8,10, XB=1.8,2.6,0.2,1.0,0,1.0/



&TAIL /

```

![image](https://user-images.githubusercontent.com/26166281/189374720-2b41bd27-ab70-4817-96d2-18b7e496bd3d.png)

**Comment by rmcdermo** [comment]
OK, thanks.  We'll take a look.

**Comment by mcgratta** [comment]
List the fourth mesh first in the input file and assign it MPI_PROCESS=0. In this case, you do not have to specify MPI_PROCESS at all if you run 4 processes. 

In general, you want to list embedded meshes first because when each mesh looks at the neighboring meshes at its external boundary, it selects the first mesh it finds. You want to find the embedded mesh first. For example, mesh 2 finds mesh 3 at its right side boundary before it finds mesh 4. So a mismatch of sends and receives results in an MPI deadlock. 

All this being said, I have to develop logic to generate an ERROR message before you get the deadlock.

**Comment by mcgratta** [comment]
I implemented a 30 s timeout for cases like this. Some guidance also added to the User's Guide. 

In short, list embedded meshes first in the input file.

**Comment by Er9y714** [comment]
Perfect! Happy to see it was diagnosed. Thank you.

> In short, list embedded meshes first in the input file.

Will do!
