### ISSUE TITLE
Pyrolysis reaction order in TGA simulation

### ISSUE THREAD

**Issue by p-lauer** [firemodels/fds#11000]
Hi!

It seems that I stumbled on a bug trying to simulate pyrolysis with TGA_ANALYSIS=T setting. I haven't checked if it happens anywhere else as well.

I've set up a surface with a 50:50 mixture of two materials with the same density, both undergoing a single pyrolysis reaction. TGA_ANALYSIS=T is set. Now, if I change the reaction order for both materials, it only seems to affect the first material. The second material seems to be always calculated for n_s=1, regardless of what n_s is set to. For FDS 6.7.9, $A$ is adjusted with $\rho(0)^{n-1}$ when changing n_s, but I encountered the same behaviour for FDS 6.7.7 without adjustment. If I plot it, it becomes obvious, here in each run n_s for both materials is the same:

![n](https://user-images.githubusercontent.com/13256462/195398546-cc229bb1-e9b6-4d3d-bb1b-64f7b4eca9f9.png)

FDS files: [n.zip](https://github.com/firemodels/fds/files/9767003/n.zip)

For further investigation I added a third material to the setup described above with a higher peak reaction temperature as the other two materials. I did simulations for each pair (1,2), (1,3), (2,3) for n_s=2 for all materials. Now, the first and third material always produce the same MLR profile. The second material produced a MLR profile that would be expected from n_s=1 when it was the last material reacting and produced a MLR profile that would actuallay be expected from n_s=2 when it was the first material reacting.

![2of3](https://user-images.githubusercontent.com/13256462/195398911-cc878ecf-2d81-4b78-96c7-e0cf34e001bc.png)

FDS files: [2of3.zip](https://github.com/firemodels/fds/files/9767044/2of3.zip)

I hope I'm not missing something but for me it looks like this is not the expected behaviour. This happend in FDS 6.7.9 and FDS 6.7.7. Please let me know if I forgot some information to reproduce the issue.

Best,

Patrick

**Comment by drjfloyd** [comment]
I don't think there is a bug in this case.

Both materials have a density of 500 kg/m3.  At the start there is 250 kg/m3 of each. As the first material pyrolyzes the wall cell shrinks. This means the density of the first material goes down and the density of the second material goes up.  When the first material has completely pyrolyzed all that is left is the second and the wall cell size has shrunk to the point where the density is now 500 kg/m3. When the second material pyrolyzes the cell keeps shrinking and the density stays constant.  The reaction rate is A RHO^N_S exp(-E/RT).  With RHO constant for the second material RHO^N_S is constant. This means there is no change to the width or location of the peak.  For N_S to have an impact the material density in the surface needs to be able to change, i.e. as the material pyrolyzes it creates voids rather than collapsing. In this case you need to set ALLOW_SHRINKING=F.

**Comment by mcgratta** [comment]
Wow, nice detective work. I was buried in print-outs of reaction rates. Nothing seemed amiss.

**Comment by p-lauer** [comment]
Thanks Jason! Great explanation. I already expected that I missed something.
