### ISSUE TITLE
Vegetation properties for CSIRO

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11007]
Kevin,
Please have a look at [this thread](https://groups.google.com/g/fds-smv/c/hw07QszXc-0/m/wF1UyVBPBgAJ?utm_medium=email&utm_source=footer) from the forum.  The Morvan kinetic data is in WUI/Morvan_TGA_2.  Please rerun the CSIRO with these parameters and see if things are working with the latest source.  Thanks

**Comment by mcgratta** [comment]
I ran one of the CSIRO cases with the "current" parameters that are listed in the User's Guide, and the "new" parameters from Morvan_TGA_2
![image](https://user-images.githubusercontent.com/11333911/200938722-46aca05b-682f-44c4-85e1-6280cd3183a4.png)
The front tracking is improved with the new parameters, but I worry about the 50% char yield, which leads to a much lower overall HRR
![image](https://user-images.githubusercontent.com/11333911/200938836-486cf059-8d94-405d-a4a1-17ddab4831af.png)
This makes sense because we are burning less fuel when we increase the char yield.

**Comment by ruddymell** [comment]
I agree, 50% char yield is essentially a factor of 2 larger than what I've seen to be representative of dry vegetation.

**Comment by mcgratta** [comment]
I'm going to close this issue. This question is one of general research into the pyrolysis of vegetation.
