### ISSUE TITLE
The shortcut failed to be created

### ISSUE THREAD

**Issue by LTC53** [firemodels/fds#11020]
Hello, I am a Taiwanese student, so there will be some traditional Chinese in the picture, sorry and sorry. I have a problem with this model. I am using an AMD ryzen9 5900X and Nvidia GEFORCE RTX3080, I downloaded the latest version and installed them as admin, but when I Installing FDS6.7.9-0-gec52dee42 and SMV6.7.21-0-gccbc561da on Windows, it tells me "***error: The shortcut "C:\Users\lotzu\Desktop\CMDfds.lnk" failed to be created".Where is the problem? and how can I fix it?
![1666033770727](https://user-images.githubusercontent.com/116030214/196263686-9d52917a-fbfc-4da2-ba8f-eea013c9a1ed.jpg)
![1666034286848](https://user-images.githubusercontent.com/116030214/196263695-eb7acbad-2fd6-4e6f-bcd7-b8dc887b1cdb.jpg)

**Comment by gforney** [comment]
what version of windows are you using? type winver in a command shell

**Comment by LTC53** [comment]
I am using on windows 10 pro 21H2

**Comment by gforney** [comment]
Not sure what went wrong. That is the same version of windows that i have. Ill have to think about it some more

**Comment by LTC53** [comment]
Ok, thank you very much.

**Comment by gforney** [comment]
type
where fds
where fdsinit

you should see something like
C:\Program Files\firemodels\FDS6\bin\fds.exe
and
C:\Program Files\firemodels\FDS6\bin\fdsinit.bat

Here is a work around.  If you see something like this then open up a regular command shell and type fdsinit

This is all the CMDfds shortcut does (a regular command shell that runs fdsinit when it first opens).  After you type fdsinit, you can then run fds_local as if you were using the CMDfds shortcut.

**Comment by LTC53** [comment]
Thank you very much, I will try it later.

**Comment by ReneRohn** [comment]
Hello, I am German student and I have tried to install the newest version of FDS 6.7.9 and Smokeview 6.7.21 on my computer (windows 11 and AMD Ryzen 5). During my installation I got the following error: The shortcut “C:\Users\rener\Destop\CMDfds.lnk” failed to created.

![Picture 1](https://user-images.githubusercontent.com/128826415/227576058-5e2c2e4c-f84d-4069-a778-df283ffe4eaf.jpg)

After my installation of FDS the CMDfds command shell did not appear at the desktop. Then I have searched for CMD in the taskbar and typed

fds

But this code could not accomplished, because my computer could not find 

impi.dll

![Picture 2](https://user-images.githubusercontent.com/128826415/227576615-0926864b-ce59-445f-b5f9-f450ae050124.jpg)

I rebooted my computer and tried to install FDS again, but it wasn’t also successful.
Then I typed

fdsinit

helpfds

fds_local

![Picture 3](https://user-images.githubusercontent.com/128826415/227576841-0b1d00c0-4813-4c7c-ba81-4be6149891b9.jpg)

Can me help someone? How can I fix the problem? What can I do now?

**Comment by gforney** [comment]
Think this has been fixed in the nightly bundle. Try releases at
GitHub.com/firemodels/test_bundles

**Comment by gforney** [comment]
looks like it wasn't fixed in nightly bundle.  think I know what the problem is .  I am working on it

**Comment by gforney** [comment]
as a work around, try going to the Start menu and opening the FDS6 entry. The CMDfds short cut should appear in the list of FDS6 entries.  Select it and the fds command window should open up.

**Comment by gforney** [comment]
try installing fds posted here and report back if the problem is fixed
https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST

**Comment by ReneRohn** [comment]
I haven't been able to solve the problem yet. I have tried to solve my problem in two ways, but it wasn't successful again. I got the the same error message "The code execution cannot proceed because the impi.dll file cannot be found."



See in the attachment.





1) Picture 1.1 - 1.3

 

2) Picture 2.1 - 2.3

 

 

Gesendet: Samstag, 25. März 2023 um 01:27 Uhr
Von: "gforney" ***@***.***>
An: "firemodels/fds" ***@***.***>
Cc: "ReneRohn" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [firemodels/fds] The shortcut failed to be created (Issue #11020)


 

as a work around, try going to the Start menu and opening the FDS6 entry. The CMDfds short cut should appear in the list of FDS6 entries. Select it and the fds command window should open up.

**Comment by gforney** [comment]
make sure you reboot your pc after installing from here https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST
then run fds by typing 
fds_local casename.fds

**Comment by gforney** [comment]
make sure you reboot your pc after you run the installer.

after you run your case with something like
fds_local casename.fds

you run smokeview in the same directory by typing in a command shell

smokeview casename

to verify that fds and smokeview have been installed properly, type
where fds
where smokeview
you should see something like

where fds
C:\Program Files\firemodels\FDS6\bin\fds.exe

where smokeview
C:\Program Files\firemodels\SMV6\smokeview.exe
