### ISSUE TITLE
Rework EVAP_MODEL namelist inputs

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11063]
Jason,
I just came across this in the user guide.   Similarly to the way we eventually reworked FLUX_LIMITER to use character strings in the input file, I think we should rework the evap model stuff to use characters.  Also, if this parameter only applies to droplets, should we move it to PART?

<img width="957" alt="Screen Shot 2022-10-26 at 1 23 10 PM" src="https://user-images.githubusercontent.com/4418497/198095272-d429b32e-46a3-4261-915a-17198f00102c.png">

**Comment by drjfloyd** [comment]
Good point that it makes more sense to have this be LPC%EVAP_MODEL rather than a global. Strings would be more readable in the input.  What do you think about the two groups of names below?

Verbose name:
RANZ-MARSHALL NO B
RANZ-MARSHALL B
RANZ-MARSHALL B LEWIS
RANZ-MARSHALL FLUX LIMTED B LEWIS

Short name:
R-M NO B
R-M B
R-M B LEWIS
R-M FL B LEWIS

**Comment by rmcdermo** [comment]
For verbose, I'd go ahead and spell out either "BLOWING" or "B-NUMBER".  But, yeah, I'm fine with these.

**Comment by drjfloyd** [comment]
Done and updated release notes.

**Comment by rmcdermo** [comment]
Great.  Thanks!
