### ISSUE TITLE
Wrong output of background species

### ISSUE THREAD

**Issue by herbertTau** [firemodels/fds#11067]
The output of the background species is not displayed correctly (DEVC, SLCF ...)
[devc_test.fds.txt](https://github.com/firemodels/fds/files/9877366/devc_test.fds.txt)

**Comment by drjfloyd** [comment]
This appears to be working. Your two DEVC are only measuring one half of the volume and you have only placed NITROGEN2 in one half of the volume.  At = 0 I would expect the half the volume containing NITROGEN2 to have the same mass of NITROGEN2 and NITROGEN since NITROGEN2 is NITROGEN.  Then over time I would expect NITROGEN2 to decrease as it diffuses to the other side but NITROGEN to stay the same.  This is what happens.
