### ISSUE TITLE
Time Constant for Thermocouples

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11112]
In regard to this [discussion thread](https://mail.google.com/mail/u/0/?tab=wm#inbox/FMfcgzGqRZfCBFBcXsWGjPHnVlNcDxNz), add a parameter to the PROP line that lets one input a "time constant" for a thermocouple. This requires some sort of standard definition of a time constant. FDS would then convert it into an appropriate set of properties for the bead to mimic the constant.

**Comment by drjfloyd** [comment]
Time required to reach 63.2 % of the instantaneous temperature change

https://www.omega.com/en-us/resources/thermocouples-response-time

**Comment by marcosvanella** [comment]
Here is the simple test case I used to estimate the time constant of a TC for the NIST_Backdraft validation cases:

https://github.com/firemodels/fds/blob/master/Validation/NIST_Backdraft/FDS_Input_Files/thermocouple_time_constant.fds

**Comment by mcgratta** [comment]
I added `TIME_CONSTANT` to the `PROP` line so that one can input a time constant which will then be used to compute an effective bead diameter.

**Comment by tgob** [comment]
Thank you all for your contributions.

Attached is a graph of the furnace model output and the experimental results.  This is the full 2.2 kW heating curve of my furnace to 500°C.

My 3 mm diameter MIMS K type thermocouple and instrumentation are certified and calibrated against physical references to within +/-3°C from 0 to 400°C and +/-0.75% to 1,100°C.

A delay function will help, but this won't change the inherent averaging (lack of fine structure in the graph) of the MIMS thermocouple output.  Given the dimensions of kiln (and fire simulations in general) a lumped capacitance model for a MIMS thermocouple is desirable.  A spherical bead shape should be a reasonable approximation to a truncated cylinder for XY plane and -Z orientations.  Perhaps adjusting the diameter, density, specific heat and conductivity will suffice?  I'm working on this, but in slow time due to other pressing commitments.

I've also attached my FDS model and a couple of photographs of the furnace.  The ceramic fibre board (which is quite porous) is sealed in the internal cavity with a Sodium Silicate and Aluminium Oxide refractory cement.  The brown staining on the walls is the binder in the board which has yet to fully burn off.  There are a number of screws in the construction to pin the board while the refractory cement sets (which requires firing).  These are all generously offset in each layer and are at least 18 mm away from inner surface of the fixed inner layer.  They have not been incorporated in the model.

I have a lot more experimentation to complete, perhaps starting with placing a bead thermocouple close to the MIMS tip and seeing how this performs during the heating cycle.

I'll report back shortly.


      
[Heating.pdf](https://github.com/firemodels/fds/files/10020674/Heating.pdf)
![IMGP5214](https://user-images.githubusercontent.com/20181668/202157764-83c73d3b-942a-4e39-b682-31b80c8faf7f.jpg)
![IMGP5241](https://user-images.githubusercontent.com/20181668/202157929-84f09fa8-b94d-4a3e-98ec-9003673faa18.jpg)
[furnace9.txt](https://github.com/firemodels/fds/files/10020809/furnace9.txt)

**Comment by mcgratta** [comment]
The code I pushed up yesterday does this:
```
&PROP ID='MIMS', TIME_CONSTANT=10 /
&DEVC ID='THTR', QUANTITY='THERMOCOUPLE', PROP_ID='MIMS', XYZ=0.315,0.32,0.27/
```
but you can still just do this
```
&PROP ID='MIMS', DIAMETER=0.003 /
```

**Comment by mcgratta** [comment]
This is what a time constant of 10 s looks like
![image](https://user-images.githubusercontent.com/11333911/202262217-86a153fc-9449-4aac-9b2e-8d1546ab0e63.png)

**Comment by tgob** [comment]
That looks very promising Kevin.  Thank you.  I'll try and complete some bead K Type measurements today during a heating cycle.  It will take me a little longer to re-run the model with your modified FDS source.  I'll report back shortly.

**Comment by tgob** [comment]
Dear Kevin,

 

Sorry to bother you, but would you please provide a link to the Windows bundle for your FDS thermocouple commit.  While I can download the commit source code, my Intel compilers and  associated packages are Linux, and I can’t mess with my Linux cluster at the moment.  The most recent Windows bundle I can find is FDS6.7.9-798_SMV6.7.21-604_tst_win.exe but I can’t determine if this includes your commit.

 

With kindest regards,

 

Tim

**Comment by mcgratta** [comment]
I committed my changes yesterday, but this version of FDS has not passed our nightly build tests for various reasons unrelated to my changes. Once we get a clean build, we automatically post new test bundles. 

You can install the Intel oneAPI compilers on your Windows computer. I have done it successfully. It takes a while to download and install, but it might help in future when you need to compile the source directly.

**Comment by tgob** [comment]
Thank you Kevin.  I’ll wait for the next successful Windows build.

 

 

Attached is some more experimental data FYI.

 

This is another heating cycle, but this time with a 1 mm bead K Type thermocouple.

 

There is a difference between the previously reported MIMS experiment and this one that I have attributed to the change in ambient conditions and the tapered gap in the door seal due to the additional thermocouple wiring.  This MIMS reading is 24°C lower than the previous after 210 seconds.  The bead TC is therefore likely to be entirely consistent with the FDS default model (excluding fine structure which is just starting to become apparent).  The MIMS lag remains at about 15 seconds after 300 seconds.

 

I re-checked the element input power.  It is 2.24 kW across the heating cycle which is +2% of the value used in the model.

 

Of course there are lots of other modeling approximations that need refinement, probably the most significant being the thermo-physical properties of the insulation.

 

 

With kindest regards,

 

Tim

**Comment by mcgratta** [comment]
There is a new test bundle for Windows available at the Downloads page.

**Comment by tgob** [comment]
Thanks Kevin.  Bundle downloaded and installed.  Currently re-running my simple furnace model to see how it performs with time constants of 5, 10 and 15 seconds.  I’ll report back when it’s run to completion.

 

t.

**Comment by tgob** [comment]
Hi Kevin.

 

If you have a moment would you please:

 

confirm Equation 21.26 in the FDS User’s Guide.  The reference [70] doesn’t have the integrated incident radiation intensity, U (W/m2) divided by 4.  I can’t see where this factor comes from (the ratio of volume to area of the spherical bead is Deff/6 on the LHS), and view factors are accounted for in the integral.

 

comment of the units for the time constant, Tau in Equation 21.27.  This seems to be in s/m which seems at odds with what one might expect for a time constant. 

 

 

I am continuing with my experiments as time permits and will report back in due course.

 

 

With kindest regards,

 

Tim

**Comment by mcgratta** [comment]
The paper by Welsh and Rubini presents the general idea of a thermocouple correction. I believe at some point we implemented the full ODE for the  heating of the sphere rather than the steady-state approximation by W&R. In any event, U is the radiative intensity, $\sigma T^4/\pi$, averaged over the unit sphere, $4 \pi$. Divide that by 4 to get the $\sigma T^4$.

$\tau=\frac{D \rho c}{6 h}$, so the units are (m kg/m3 kJ/(kg K)) / (kJ/(s m2 K)) = s, if I've done my algebra right.

**Comment by tgob** [comment]
Thank you for making time to reply Kevin.

 

I did struggle with the equation syntax in your email, but I think have sorted out my errors.

 

This is all to do with thermally large thermocouple response.  I am also messing with an iterative numerical solution to the ODE.  I suspect that for thermally large MIMS thermocouples one cannot assume that the average thermocouple junction temperature will instantly match the net heat gain (loss) at the surface, whereas with a small bead this assumption is reasonable.

 

With kindest regards,

 

Tim

**Comment by mcgratta** [comment]
I'm going to close this issue, but open a new one or reopen if something new pops up.
