### ISSUE TITLE
Error in one Beyler Hood validation case

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11256]
This case is different than the others, but I cannot pinpoint exactly what is wrong. This is the only case that threw an error.
```
Beyler_Hood/Current_Results/Beyler_Hood_propane_445_lr.err:ERROR: Problem with REAC 2. Tracked species CARBON DIOXIDE not found. (CHID: Beyler_Hood_propane_445_lr)
```

**Comment by drjfloyd** [comment]
These cases were originally set up with three reactions.  Fuel -> CO, CO-CO2, and CO2-CO.  You changed this in a recent commit (https://github.com/firemodels/fds/commit/95982bb13c8a783f642e3e5c58f8aad7bed96a7e) but for this input file failed to remove R3.  R3 is the reverse reaction for CO2. Since you removed the input &SPEC ID='CARBON DIOXIDE'/ this species is no longer a tracked species and FDS throws an error when you try to use a non-tracked species in a REAC (this erro message predated the recent overhual to SPEC and REAC).

**Comment by mcgratta** [comment]
I must have missed that one file. Thanks.
