### ISSUE TITLE
Check timing of ht3d_ibeam case

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11265]
Case has increased in time from 4 min to 42 min.

fds/Verification/Heat_Transfer/ht3d_ibeam.fds

**Comment by mcgratta** [comment]
[ht3d_ibeam_TS.pdf](https://github.com/firemodels/fds/files/10273142/ht3d_ibeam_TS.pdf)
It works! This is the case with a time step of 1.6 s, which is approximately 5 / 3, the old time step divided by 3. I need to check on some things because it's not as tight as the old case. Might just be an artifact of the time splitting.
