### ISSUE TITLE
Some features of VENT placement

### ISSUE THREAD

**Issue by mst-lyubimov** [firemodels/fds#11262]
Dear colleagues!
We have found several situations when FDS reacts to the VENT, perhaps not in the most correct way. These VENTs are not located entirely on one side of one OBST. These situations were not intentional, but the result was surprising. Previously, we believed that if VENT were not located entirely on one side of OBST, then FDS would report an error.
We work with FDS 6.7.9

First situation:
VENT is located on two OBSTs from different sides. See [test_a.txt](https://github.com/firemodels/fds/files/10266183/test_a.txt)

There is no error message. One part of the VENT burns. Moreover, another part of the VENT is drawn in Smokeview. Not the part that burns!
![image](https://user-images.githubusercontent.com/84854006/208605453-d78504f5-2e4b-414e-a6c2-48fa463be80c.png)

Second situation:
VENT is not entirely located on the OBST. See 
[test_b.txt](https://github.com/firemodels/fds/files/10266190/test_b.txt)

If we place the VENT on top, then no error occurs. Burning is happening, although not over the entire surface of the VENT.
![image](https://user-images.githubusercontent.com/84854006/208605510-e74aa33c-26bc-49ee-82f5-7ae6c762ba1d.png)

But if you place a VENT on the left side of this OBST structure, an error will occur:
VENT 1 must be attached to a solid obstruction

It seems that FDS and SMV response in the cases described is not very consistent.

**Comment by mcgratta** [comment]
These cases should all produce an error. I'll ensure that they do.

**Comment by mcgratta** [comment]
Glenn -- for case test_a, Smokeview only draws a portion of the vent that FDS sends it. What is the logic behind that?

**Comment by mcgratta** [comment]
I may need to rethink this. Currently, FDS is allowing users to get away with specifying vents that are not quite right, and it just ignores those parts of the vent that are not backed by a solid or inverted as you have in test_a. Do we want to stop these jobs with an error? Whenever we do something like this, we get a lot of complaints.

As far as Smokeview is concerned, it only draws the vent that FDS sends it, not a patchwork of vents cut from the original.

**Comment by gforney** [comment]
Off the top of my head smokeview doesnt 2nd guess vent coordinates it draws
except to offset. Ill check code if you still think this is a problem (
wasnt sure about latest comment)

**Comment by gforney** [comment]
smokeview draws the vent as it was defined in the input file.  a portion of it is hidden inside the 2nd blockage.

smokeview offsets a vent a small amount perpendicular to wall or OBST that it is attached to so that there won't be visual artifacts.  the offset causes the vent to be drawn inside the 2nd blockage.  if you draw the blockage as an outline you will see the vent.

this would be hard to address in smokeview as I would have to examine each vent to see if it was attached to 2 or more blockage faces and if so split them and offset  each split vent separately.  I suggest as at work around least for now that you define a separate vent for each OBST that you are attaching it too
![test_a_s0000](https://user-images.githubusercontent.com/12403014/208716946-5d8b1775-d06c-46d8-be92-ff6a4df868b6.png)

**Comment by mcgratta** [comment]
Thanks. That makes sense. So I have to think a bit about whether we want to strictly enforce the placement of VENTs on solid surfaces. My inclination is usually to not allow it, but then I will discover that my own cases no longer run.

**Comment by mcgratta** [comment]
Bryan -- would PyroSim permit these cases? In other words, could a user build these input files using PyroSim?

**Comment by bwklein** [comment]
@mcgratta Yes, you can draw a vent across two faces like this in PyroSim.  We do see the vent on both OBST, because we are not automatically offsetting it from the face of the OBST.  Fire is only coming out of one of the surfaces the vent is placed on and not both, as shown in this screenshot.

![image](https://user-images.githubusercontent.com/12104446/208743806-0ba4c157-504f-4077-a768-772e3ba30695.png)

It is possible, but this is the first time I have seen it done.

**Comment by mst-parkhachev** [comment]
If in example **test_b** the placement of the VENT on top is allowed, then why does the placement of the VENT on the side cause an error?
&VENT XB=53.25,53.25,13,16.25,0,0.5 SURF_ID='1'/  ---- causes an error

Does this happen because the side VENT lies only on one OBST? Is it true that VENTs lying on several obsts are not checked for complete belonging to OBSTs?

**Comment by mcgratta** [comment]
![image](https://user-images.githubusercontent.com/11333911/208750642-74182a2e-1e09-40d5-916c-1fbbb2da0bbc.png)

With the latest source code on a linux computer, test_b runs. I don't think we did anything intentional to make this happen. 

In general, FDS looks for at least one solid cell behind a vent. If it finds it, the vent is given the appropriate orientation (IOR). In the case of test_a, only one orientation is used.

**Comment by mst-parkhachev** [comment]
The picture shows that only the part of the vent that lies on the obst is on fire. Is it really so? Is the amount of fuel emitted really less than if there was an obst everywhere under the vent? Or is it just a visual effect in Smokeview?

**Comment by mst-parkhachev** [comment]
Will such a vent work for LEAKs across its entire surface? I mean HVAC.

**Comment by mcgratta** [comment]
Only the portion of the vent that touches the solid is burning. The reason is that during its initialization phase, FDS assign a SURF_ID to all wall cells. The portion of the vent that touches nothing doesn't apply a SURF_ID to anything. Smokeview draws the vent because FDS gives it the user-defined vent coordinates, but that is all. 

Jason, can you answer the question about HVAC.

**Comment by mst-parkhachev** [comment]
Thank you, Kevin, for detailed explanation.

It seems that it makes sense to show in Smokeview that part of the vent that actually burns (test_a), but not randomly selected. Shift the image of the vent in the correct direction, consistent with FDS choice.

**Comment by mcgratta** [comment]
I prefer to do it this way:
![image](https://user-images.githubusercontent.com/11333911/208760021-65c6efd2-3817-4a88-9726-96d0abc57b81.png)
I use vents sparingly. I prefer to define SURFs, give them a COLOR, and then use SURF_ID, SURF_IDS, or SURF_ID6 on the OBST line to apply boundary conditions.

The reason why we cannot apply a portion of the vent in Smokeview is that when the vent is read in, we do not know exactly what final shape it will have. So Smokeview only gets the 6 XB coordinates and draws that. Same with OBSTs. Smokeview only gets the 6 planes that make up the solid box. It can color those 6 planes according to the SURF_ID. 

If we had to do it all again, we might not adopt this strategy. But to change this now would cause serious pain. We would have to overhaul the way geometry information is transferred from FDS to Smokeview.

**Comment by mst-parkhachev** [comment]
We use vent a lot because of the ability to simulate Radially-Spreading Fire.

**Comment by mcgratta** [comment]
You can use SURFs for that.

**Comment by drjfloyd** [comment]
HVAC uses whatever SURF assigment to wall cells has been done when VENTs are processed in init.f90. In these examples where the VENT is a fire, if it isn't burning when an HRRPUA is being used, then HVAC wouldn't see it

**Comment by mcgratta** [comment]
Good, thanks. So VENTs are really just the means by which the user can specify boundary conditions onto individual wall cells.

**Comment by mst-parkhachev** [comment]
Thanks, very interesting.

It would be nice to include a more detailed explanation of the interaction of VENT and OBST in Manual. I think that explanations like those given by Kevin here would be very interesting and useful for many FDS users.
For example, before these clarifications, I thought that VENT was a separate entity.

**Comment by mcgratta** [comment]
I added some guidance to the User's Guide.

**Comment by AbdelMoumene01** [comment]
im trying to simulate a fire on top of a cylindrical obstacle with HRRPUA=200,
ineed some help pls
&SURF ID='TK_Gasoline_01', COLOR='SKY BLUE'/
&MULT ID='cube array_1', DX=1,DY=1,DZ=1, I_UPPER=16,J_UPPER=16,K_UPPER=8/
&OBST XB= 8,9,12,13,0,8,SURF_ID='HOT',
MULT_ID='cube array_1'
SURF_ID='TK_Gasoline_01'
SHAPE='CYLINDER'
RADIUS=8
HEIGHT=8
XYZ=16,20,0
ORIENTATION=0,0,1/
