### ISSUE TITLE
Stoichiometric imbalance in Purdue cases

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11288]
The Purdue Flame cases do not run. The error is
```
ERROR: Problem with REAC 1. Mass of products,  283.792, does not equal mass of reactants,1974.067 (CHID: 7p1_cm_methane_4mm)
```
I think the problem is that a `SOOT_YIELD` is specified along with a primitive species formulation.

**Comment by mcgratta** [comment]
There is a similar error statement for the NIST Structural Separation cases, but without a specified soot yield. Also, in those cases, do we need to clip the density any more?

**Comment by drjfloyd** [comment]
The issue is the VOLUME_FRACTION, if I shift the decimal place over so the fuel sums to 1 this runs. With all the reorganization my guess is the atom check is now being done before VOLUME_FRACTION is renormalized to 1. I'll figure out the fix.

I wouldn't think we'd need the CLIP line. The default vlaue for CLIP should now be based on the fuel species at 2500 K. 

IF (MINIMUM_DENSITY>0._EB) THEN
   RHOMIN = MINIMUM_DENSITY
ELSE
   RHOMIN = MIN(0.1_EB*RHOA,2._EB*P_INF*MW_MIN/(R0*TMPMAX))
ENDIF

**Comment by mcgratta** [comment]
Thanks, I figured it was something like this. Still, is it appropriate to specify a SOOT_YIELD with primitive species? And yes, let's remove the CLIP line because we'll be running these cases again. It might have been added because of some problem that no longer exists.

**Comment by drjfloyd** [comment]
Yes it is appropriate as you are still using a simple chemistry REAC.

**Comment by drjfloyd** [comment]
Should be working now.

**Comment by rmcdermo** [comment]
Is this issue resolved?

**Comment by mcgratta** [comment]
Yes
