### ISSUE TITLE
Case with ULMAT crashes due to memory issues

### ISSUE THREAD

**Issue by FireResearch-BK** [firemodels/fds#11403]
We have a case in which we are trying to simulate the burning of vehicle components.

With FDS 6.7.9-933 (and the standard 6.7.9 release), the ULMAT solver and a single mesh of approx. 1.1 million cells, the case crashes after 800 seconds with a ```ULMAT_H_MATRIX_LUDCMP PARDISO Num Factor: The following ERROR was detected: -2``` error message.

According to the [Intel PARDISO user guide](https://pardiso-project.org/manual/manual.pdf) (page 12), error code "-2" means not enough memory.

We have restarted the case from a restart file before the crash and noticed that RAM usage for FDS was around 6.4 GB. Our workstation has 64 GB of RAM and a 64 bit OS, so there is more than enough available memory for FDS.

Further investigation determined that Intel's MKL library, of which PARDISO is a part, has two available modes of operation, namely in-core (IC) and out-of-core (OCC)  for the construction and handling of the pressure solver matrix.
FDS uses the default mode, which is IC and, as far as we can tell, limited to a maximum of 2000 MB per core.
We assume that the increasing number of non-zero values in the matrix due to burn-away push the memory usage of the case beyond this limit, leading to a crash.

The PARDISO configuration within [pres.f90](https://github.com/firemodels/fds/blob/e031579b9a4bc091d67235b0d99256f957a738f8/Source/pres.f90) (line 3818 ff) of the FDS source code sets all flags to zero (unless those specifically altered). This also affects the corresponding IC/OCC control flag ([iparm(60) according to the MKL reference manual](http://cali2.unilim.fr/intel-xe/mkl/mklman/index.htm#GUID-7E829836-0FEF-46B2-8943-86A022193462.htm)), which is therefore locked to IC, limiting memory usage.
With ```IPARM(60) = 1```, to our interpretation, it would be possible to switch between the (faster) IC and (slower) OCC mode depending on the values of the ```MKL_PARDISO_OOC_MAX_CORE_SIZE``` and ```MKL_PARDISO_OOC_MAX_SWAP_SIZE``` environment variables. The latter may potentially solve the memory issue with large cases and ULMAT.

Is there a chance to set ```IPARM(60) = 1``` by default in future FDS releases and/or increase the default maximum memory for IC mode (if possible)?

**Comment by rmcdermo** [comment]
Is it possible to give us a case to test?  Even if you can generate the single mesh case that fails, it would help make sure we are on the same page.  Thanks.

**Comment by marcosvanella** [comment]
@FireResearch-BK this is an interesting suggestion. We can try this IPARM[60] as a way to alleviate the maximum memory constraint. Yet, ULMAT is recommended for meshes of up to 50^3 cells (125K pressure unknowns) in the User Guide. Fitting a million cells in a single mesh will make the calculation too slow. You can try splitting your domain in 8 meshes.

**Comment by IFAB-AS** [comment]
We did use ULMAT and a single mesh for this case to get a better understanding why the simulations crash at some point. It is a model with many PRESSURE ZONES that crashes each time with other settings (pressure increases in the zones), for this reason ULMAT was used. We also tested other suggestions:
- decrease PRES VELOCITY_TOLERANCE
- increase PRESSURE ITERATIONS
- THICKEN_OBSTRUCTIONS=T (as we had many thin obstacles and this might generate a problem)
- use only one mesh instead of multiple, if we use multiple meshes ULMAT will not start
- as we get many model data from our customers, it is not possible to close every ZONE (sometimes thousands of zones)
- For this specific case, there are cells in the whole domain that have the BURN_AWAY=TRUE property. From our experience it is not recommended to split the mesh in the fire

The plan for this tests is to obtain a working solution (60 minutes simulated time with many PRESSURE ZONES) for this test case by using only the less problematic parameters such as THICKEN, many pressure iterations, 1 Mesh etc., and change the parameters afterwards for comparision with the ULMAT case (e.g. BACKING=EXPOSED, VOID or using thin obstacles etc.). By this procedure, we hope to get a better undersanding what actually is crashing the simulations and what needs to be changed in advance before starting the model. Or even better how to improve the FDS code.

As the model is under NDA, I think we cannot share this specific case. I restarted the same model using the environment variable `set MKL_PARDISO_OOC_MAX_CORE_SIZE = 6000` before starting the simulation, but I think that this will not have an effect as `IPARM(60)=0` is currenty used and PARDISO might still use the 2000 MB limit. It will take 3-4 days before the crash, so we will give you an update probably next week on this. We can also try to build a model, that we can share.

**Comment by marcosvanella** [comment]
A model similar to what you have would be very handy to test what is going on. You can send it to us directly (nist emails) too.
I'm also interested in the ULMAT not starting with multiple meshes for this case.
Are you using 6.7.9 release?
________________________________

**Comment by rmcdermo** [comment]
Kevin recently added a new feature MINIMUM_ZONE_VOLUME on the MISC line.  This fills void spaces below a certain volume.  Together with the new treatment of normal velocity components at at wall cell, we hope this helps avoid zone-related instabilities without resorting to ULMAT.  Hopefully, you can just set your VELOCITY_TOLERANCE to something reasonable.

This feature is in the latest test bundle available [here](https://github.com/firemodels/fds/wiki/FDS-Test-Bundles).  We are testing on simple cases, but it would be good if you could try this on a real-world example to see if we are indeed improving things.  Thanks

**Comment by IFAB-AS** [comment]
It is currently running with FDS 6.7.9-933 as we had issues with rising pressure in the PRESSURE ZONES, but we also tested the case with FDS 6.7.9. I also managed to start the case with 8 meshes in the morning, it might depend on where the mesh borders are (avoid cutting through the pressure zones), but usually this is not possible due to the amount of ZONES. For this reason we try to make it work with only one mesh and ULMAT, which would make using the imported models much easier.

MINIMUM_ZONE_VOLUME sounds interesting and we will test it the next days. I will also send Marcos the test model with some additional explanation.

**Comment by FireResearch-BK** [comment]
As a sidenote, I've managed to set up the build chain for FDS (the instructions really help once one manages to find them), so we can also patch and compile FDS ourselves to test the initial suggestion (```IPARM(60) = 1```). Getting results may, however, take a while.


P.S: Is there some other way than Google Drive to get a hold of nightly builds of the FDS documentation?
The link posted in Readme.md requires a login and I do not have a Google account, but I'd like to read up on ```MINIMUM_ZONE_VOLUME ```.

**Comment by mcgratta** [comment]
Does it require a login? I thought the link was completely open?

**Comment by FireResearch-BK** [comment]
> Does it require a login? I thought the link was completely open?

It should be open, yes. But clicking on the link sends you to a login window. (Using Firefox on both Windows and Linux.)
This also happens for the Drive hosting the nightly FDS builds, by the way.

IIRC, Google changed the formatting for links and some security settings a few years ago and this may have something to do with it. So it may be worth checking permissions for the Drives and/or generating new share links.

**Comment by mcgratta** [comment]
[https://drive.google.com/drive/folders/0B_wB1pJL2bFQcURod1UyZTJUaEE?resourcekey=0-CW_02fKmi4jxSqW_n9_G7w&usp=sharing](https://drive.google.com/drive/folders/0B_wB1pJL2bFQcURod1UyZTJUaEE?resourcekey=0-CW_02fKmi4jxSqW_n9_G7w&usp=sharing)

Does this work?

**Comment by FireResearch-BK** [comment]
> Does this work?

Yes, that link works just fine.

**Comment by mcgratta** [comment]
Yes, but I think it is old. Let me think about this some more.

**Comment by mcgratta** [comment]
[https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC?usp=sharing](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC?usp=sharing)

Does this work?

**Comment by IFAB-AS** [comment]
@mcgratta Yes, this link works without an acount
@marcosvanella and @rmcdermo I did send a test case that uses ULMAT with multiple meshes to Marcos that crashes during the initialization at the beginning with error code: ``ULMAT_H_MATRIX_LUDCMP PARDISO Sym Factor: The following ERROR was detected: -1`` and ``forrtl: severe (157) Program Exception - access violation``. We had this error code in the last year several times for various models, but I can not share these here at the platform. The -1 indicates ``input inconsistent`` in the PARDISO error table, but the same case is starting when using the standard solver. We tested it in FDS 6.7.9, 6.7.9-933 and the latest 6.7.9-1550 and the -1 error at the start was occurring in all versions for the test case. Other cases run with multiple meshes, so we do not know where the error is.

The other error ``ULMAT_H_MATRIX_LUDCMP PARDISO Num Factor: The following ERROR was detected: -2`` does not occur at the start, but after several days when using ULMAT with 1 Mesh. Marcos has also received our test case for this. This error seems to be related to either burning away of materials and updating the pressure matrix or some internal memory leakage in PARDISO that leads to exceeding the 2000MB limit. Our tests with different FDS versions are still running and will take some time:
- latest build 6.7.9-1550, 1 Mesh (I assume this will crash sometime around 740 s)
- 8 meshes and 6.7.9-933 (this might work and would be a solution for other cases if the -1 error is resolved)
- 1 mesh and FDS 6.7.9-933 using environment variable ``set MKL_PARDISO_OOC_MAX_CORE_SIZE = 6000`` before starting the file (this might change nothing as we think ``iparm(60)=0`` does not use the 6000 MB limit)
- and a self-compiled code with 1 mesh using ``iparm(60)=1`` and ``MKL_PARDISO_OOC_MAX_CORE_SIZE = 6000`` with the latest build 6.7.9-1550 (this was our suggestion in the initial post)

As the simulations are all competing for CPU cycles, you will get an update probably next week. We will test the MINIMUM_ZONE_VOLUME at a later stage as the problem seems to be not related to pressure zone in the specific test case that we did send to Marcos.

**Comment by IFAB-AS** [comment]
All 4 simulations have crashed:
- latest build 6.7.9-1550, 1 Mesh -> ``ULMAT_H_MATRIX_LUDCMP PARDISO Num Factor: The following ERROR was detected:    -2`` after 718 s, everything in SMV looks normal
- 8 meshes and 6.7.9-933 -> ``ULMAT_H_MATRIX_LUDCMP PARDISO Num Factor: The following ERROR was detected:    -2`` after 803 s simulation time, pressure, temperature etc. look normal
- 1 mesh and FDS 6.7.9-933 using environment variable ``set MKL_PARDISO_OOC_MAX_CORE_SIZE = 6000`` before starting the file (this might change nothing as we think ``iparm(60)=0`` does not use the 6000 MB limit) -> crashes after 524 s simulation time with ``forrtl: severe (157): Program Exception - access violation``, everything in the SMV looks normal
- and a self-compiled code with 1 mesh using ``iparm(60)=1`` and ``MKL_PARDISO_OOC_MAX_CORE_SIZE = 6000`` with the latest build 6.7.9-1550 (this was our suggestion in the initial post) -> ``Error: MKL Library compile flag was not defined for ULMAT as pressure solver`` at the beginning of the simulation. Here we might have not the knowledge to compile the file correctly

**Comment by marcosvanella** [comment]
Thank you for the report. The one mesh case is still running here, up to 360s. I have not noted an increase in memory usage (it's about 25% of the node mem, 12GB), but it is possible pressure zone changes have not started yet due to burn away.
We'll also test a case with IPARM[60]=1, to see if it goes further. I reproduced the multiple mesh issue, will look further in the next couple of days. 
About the compile flag, what OS and MPI are you using for compilation? Seems the MKL lib location is not being picked up by the compiler.

**Comment by IFAB-AS** [comment]
I managed to get the compile flag working by using the Intel oneAPI base/HPC toolkit in the meantime with the IPARM(60)=1 code and ULMAT. We used the Intel Fortran compiler and the Intel MPI library before, not the complete toolkits, so this was the problem. I restarted the case with 1 mesh and 8 meshes with ULMAT and iparm(60)=1, our OS is Windows 10.

**Comment by mcgratta** [comment]
We install the base toolkit first, then the HPC toolkit. That seems to be all that is needed to compile all our codes.

**Comment by marcosvanella** [comment]
@IFAB-AS do a repo update and try the cases you sent me. Please run the single mesh case that pardiso was getting out of memory. Try it without changing IPARM[60]. The case is still running here but our cluster is very slow. 
I added code to deallocate pardiso arrays in FDS (we didn't have that).

**Comment by FireResearch-BK** [comment]
@mcgratta The oneAPI base toolkit and HPC toolkit work out just fine to compile FDS on Windows. It would help to make this more clear in the [FDS compilation instructions](https://github.com/firemodels/fds/wiki/FDS-Compilation) because the instructions at the moment imply to pick the separately available Fortran and MPI packages from Intel.

@marcosvanella We are going to try your fix in the next days as we're still testing other attempts at a solution.

**Comment by mcgratta** [comment]
Done, I edited the instruction page.

**Comment by IFAB-AS** [comment]
@marcosvanella 
A few tests have finished, others are still running. All started with ``set MKL_PARDISO_OOC_MAX_CORE_SIZE = 6000`` in command line before starting the FDS file

- FDS 6.7.9-1550 compiled with ``IPARM(60)=1`` and 8 meshes:
Crash after 735 s:  ``ULMAT_SOLVER: The following ERROR was detected:           -2`` (“not enough memory”)
- FDS 6.7.9-1550 compiled with ``IPARM(60)=1`` and 1 mesh:
still running and very slow, will most likely crash
- FDS 6.7.9-1550 compiled with ``IPARM(60)=2`` and 8 meshes:
Crash at start with ``ULMAT_H_MATRIX_LUDCMP PARDISO Num Factor: The following ERROR was detected:   -11`` (“read/write problems with the OOC data file”)
- FDS 6.7.9-1550 compiled with ``IPARM(60)=2`` and 1 mesh:
``ULMAT_SOLVER: The following ERROR was detected:          -11`` at start
- FDS 6.7.9-1550 compiled with ``IPARM(2)=0`` and 1 mesh/ 8 meshes:
Still running, we used ``IPARM(2)`` as there was some entry in the Intel forum about a bug in a previous MKL version with METIS that might be the issue here
- FDS 6.7.9-1591 with 1 / 8 meshes:
Started today, results in a few days.

We will keep you updated.

**Comment by marcosvanella** [comment]
Thank you @IFAB-AS. I'm not surprised about the out of memory crashes, due to not releasing Pardiso arrays memory. 
Did these runs with the -2 error get any further with MKL_PARDISO_OOC_MAX_CORE_SIZE = 6000 than before?
Not sure what the other errors are about, might have to do with permissions to write to the directory the OOC arrays are being dumped.

**Comment by FireResearch-BK** [comment]
Update:

- FDS 6.7.9-1550 compiled with ```IPARM(60)=1``` and 1 mesh:
Crashed after 463 seconds with ```forrtl: severe (157): Program Exception - access violation```
- FDS 6.7.9-1550 compiled with ```IPARM(2)=0``` and 1 mesh:
Still running at 551 seconds.
- FDS 6.7.9-1550 compiled with ```IPARM(2)=0``` and 8 meshes:
Crashed after 702 s with ``` ULMAT_SOLVER: The following ERROR was detected:           -2```
- FDS 6.7.9-1591 with 1 mesh: 
 Crashed after 92 seconds with ``` BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 1700 RUNNING AT [Hostname]
=   EXIT STATUS: -1073741819 (c0000005)```
- FDS 6.7.9-1591 with 8 meshes:   
Still running at 833 seconds.


@mcgratta :
Thanks for the edit. 
Item 2 of the "Preliminaries" section still mentions "Intel oneAPI "classic" Fortran compiler" and "Intel MPI libraries" though.

**Comment by marcosvanella** [comment]
The one mesh case without the Pardiso arrays deallocation (6.7.9-1564) has gone up to 621.79 sec in our cluster. In two solver re-initializations due to burn away, memory in the node jumped from 25% to 37.5%. First burn away event at 618.99 sec, changed the largest pressure zone, 840K unknowns, by one cell.  Last weeks commit was intended to fix this.

_DS 6.7.9-1591 with 1 mesh:
Crashed after 92 seconds with  BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES =   RANK 0 PID 1700 RUNNING AT [Hostname] =   EXIT STATUS: -1073741819 (c0000005)_

I found online that c0000005 in windows might be due to pointer issues. There are no ULMAT restarts due to burn away up to 92 sec, not clear what happened. 
Alex, please rerun this case in your system to confirm its happening all the time. I'm going to run this case here to see what I find.

**Comment by FireResearch-BK** [comment]
> The one mesh case without the Pardiso arrays deallocation (6.7.9-1564) has gone up to 621.79 sec in our cluster. In two solver re-initializations due to burn away, memory in the node jumped from 25% to 37.5%. First burn away event at 618.99 sec, changed the largest pressure zone, 840K unknowns, by one cell. Last weeks commit was intended to fix this.

As "FDS 6.7.9-1591 with 8 meshes" is still running and past peak HRRPUV, the fix may just have worked. Fingers crossed.

> _DS 6.7.9-1591 with 1 mesh: Crashed after 92 seconds with BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES = RANK 0 PID 1700 RUNNING AT [Hostname] = EXIT STATUS: -1073741819 (c0000005)_
> 
> I found online that c0000005 in windows might be due to pointer issues. There are no ULMAT restarts due to burn away up to 92 sec, not clear what happened. Alex, please rerun this case in your system to confirm its happening all the time. I'm going to run this case here to see what I find.

We've already restarted this case as well as the "FDS 6.7.9-1550 compiled with ```IPARM(60)=1``` and 1 mesh" case from a restart point. So far, both continue to run normally.

**Comment by IFAB-AS** [comment]
We stopped the simulations with FDS 6.7.9-1550 compiled with IPARM(60)=1 and compiled with IPARM(2)=0 (both had 1 mesh), due to beeing too slow. The run with FDS 6.7.9-1591 with 8 meshes reached 1091 s and Windows decided it is time to restart ;-. So far, this case seems to work, but we were not able to restart it (``forrtl: severe (157): Program Exception - access violation``).
We also tested another case with 4 Meshes which was crashing at the start (Marcos received this by e-Mail) and this case also starts now with 6.7.9-1591.

**Comment by marcosvanella** [comment]
Hi Alex,
_The run with FDS 6.7.9-1591 with 8 meshes reached 1091 s and Windows decided it is time to restart ;-. So far, this case seems to work, but we were not able to restart it (forrtl: severe (157): Program Exception - access violation)._

Please try two things for this restart.
1. Comment the &PRES line and try restarting. This is to check if we see the exception regardless of the pressure solver.
2. Compile the impi_intel_win_dv  target and run the restart case with ULMAT. This is to see if we get more stderr information on this Access violation.

The single mesh case with latest source has made it to 365sec here.

A point to keep in mind is that every time the domain changes due to a door opening or cells burning away the ULMAT solver needs to be restarted and Poisson matrix factorizations for the new zones need to be performed. This can cost from 10 to 100 times the solve cost. It this is required every time step (say one cell burns away per step) this can make the code very slow.

**Comment by IFAB-AS** [comment]
I tried your 2 suggestions:
1) Restart with &PRES commented: Simulation continues normal
2) Compile the impi_intel_win_dv target: 
![grafik](https://user-images.githubusercontent.com/124035126/219426934-ab5220b0-63e3-4916-aaf6-41cc451d51cf.png)

I also tested to let the case restart with the standard solver until the next restart point is written, stopped the simulation and did continue with ULMAT. This produces a numerical instability after the restart.

**Comment by marcosvanella** [comment]
Ok, this tells me there is something not right with RESTART + ULMAT. The state of PRESSURE_ZONEs when setting up the solver initially (different pressure zones due to compartments and pockets used to compute Poisson matrices) has to be the actual state at the RESTART time point.
I'll look to see if that is what is happening, we might be able to reproduce this with a simple verification case.

**Comment by IFAB-AS** [comment]
The crashing of ULMAT after recalculating the pressure zones seems to be solved now, the only problem remaining is the restart of the ULMAT solver (see also https://github.com/firemodels/fds/issues/11449).
Summary of our tests: The problem with PARDISO error -2 did not occur due to the RAM management in the Intel MKL library as we thought (OOC and IC mode and ``iparm`` parameters), but was related to the garbage collection in FDS, which is fixed in FDS 6.7.9-1591. The ``forrtl`` error did occur when other processes were eating up too much memory and killed an FDS process.
We also tested the same case with 1 and 8 meshes (1 is still running), and we were getting basically the same HRR for this example. This means that cutting through the fire was not an issue in this case.
![grafik](https://user-images.githubusercontent.com/124035126/220135820-41bf45ec-b45e-4cf2-a98b-d8979a6b4f36.png)

**Comment by FireResearch-BK** [comment]
The core issue is solved as of 6.7.9-1591. Note that restarts with ULMAT are still broken; see #11449.
