### ISSUE TITLE
NIST/NRC smoke plots in validation guide

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11448]
Have a look at the nightly build of the validation guide Figs. 9.47 and 9.48.

1. The captions need to be fixed to be consistent with the plots that are shown.
2. What is wrong with Tests 1, 7, 2, 8, 4, 10, 17?  We seem to be no where close the measurements?

**Comment by drjfloyd** [comment]
This has been the case since we first ran these cases with v5. It is why I added all the aerosol stuff.

These are the closed door tests. In these tests we assume 8700 kg/m2 yields the soot density. Who knows if that is still good for soot that has been aging in a compartment. Is suspect it may not be.

There is also likely deposition happening but we dont know the post-flame soot size distribution for these fires. 

Adding deposition (I wrote two papers on this) helps. After many asks over the years for someone to make gravimetric measurements in full-scale tests, I hope to have the opportunity this year to make measurements of deposition, obscuration, and gravimetric gas soot density and soot size distributions in some full-scale compartment fire tests.

**Comment by drjfloyd** [comment]
Here is a slide from my 2014 IAFSS talk.  The 3-bin used a soot size distribution from a small-scale box test burning different fuels but it was at least something.  Just using that with deposition and agglomeration reduced both the bias and error. The 1 and 10-um plot are monodisperse prarticles with deposition but no agglomeration. 10-um made a big improvement in the closed door tests and little impact in the open door. There has been more work in the deposition and agglomeration routines since this time. There are also possible impacts from assuming 8700 kg/m2 applies to the closed door soot and that with the door closed some soot over time gets re-entrained into the fire and might be consumed.

![Clipboard01](https://user-images.githubusercontent.com/12799217/219145717-242a8f08-7b34-4145-bd0f-53011e58f08a.png)

**Comment by rmcdermo** [comment]
Aren't we just using 1 bin in the current FDS input file?  With 1 mu-m?

**Comment by drjfloyd** [comment]
Yes. I was pointing out htere are lots of factors as to why we may not be doing well and they are all things we haven't measured in full-scal;e tests.  Even a multi-bin case with a presumed post-flame soot size distrubtion from a small scale test of a different fuel didn't get the clsoed door to be as good as the open door.  The 10-um results show  that we can turn knobs and get there but that would just be tuning.

**Comment by mcgratta** [comment]
[Pages from FDS_Validation_Guide.pdf](https://github.com/firemodels/fds/files/10796443/Pages.from.FDS_Validation_Guide.pdf)
I changed the intro and captions for these plots.
