### ISSUE TITLE
Fire Propagation, with ERROR: Numerical Instability - FDS stopped (CHID: PVC_CAVI_FIRE).

### ISSUE THREAD

**Issue by tgiacco** [firemodels/fds#11492]
I'm doing a simulation about the pyrolysis of PVC cables arranged on horizontal shelves, triggered by a burner. The problem is that although the information about the pressure and the mesh has been reduced and the cells are very small in size, the simulation continues to give me the following error: ERROR: Numerical Instability - FDS stopped (CHID: PVC_CAVI_FIRE).
I don't know how fix the problem.

[4.FDS.txt](https://github.com/firemodels/fds/files/10859107/4.FDS.txt)

**Comment by mcgratta** [comment]
There are too many errors and bad assumptions in this file. HT3D is inappropriately used. Your stoichiometric coefficients do not add to one. Your burner never ignites because it is associated with a device with no setpoint. 

This is the wrong way to do things. I suggest you first simplify the case. Just focus on developing a reasonable model of the cables. Start with simple properties and work up. Do not try to do a large scale simulation until to verify that your basic model is sound.
