### ISSUE TITLE
Negative velocity from injection point of narrow spray 

### ISSUE THREAD

**Issue by shostikk** [firemodels/fds#11518]
Injecting high-speed (liquid) droplets as a narrow spray causes opposite velocity behind the spray. Negative U-VELOCITY and droplets behind the nozzle, as in the figures. 

If this was fuel, it could cause spurious flaming behind the nozzle. (not sure if visible in the jet flame validation cases).

The droplets are inserted in just few cells (4), and the problem is related to that. Increasing SPRAY_ANGLE takes the problem away. Any other change really doesn't. Did not try super high resolution, though. Question: is there anything in the momentum exchange that could be improved to prevent such spurious flow in wrong direction?

 Current Date     : March 10, 2023  13:08:49
 Revision         : FDS6.7.9-1615-g41c6a36a5-nightly
 Revision Date    : Sun Feb 12 07:45:43 2023 -0500
 Compiler         : 
 Compilation Date : Mon 02/13/2023  08:08 AM

 MPI Enabled;    Number of MPI Processes:       2
 OpenMP Disabled

[two_way_spray.fds.txt](https://github.com/firemodels/fds/files/10941503/two_way_spray.fds.txt)
![two_way_spray_0666](https://user-images.githubusercontent.com/12714528/224304863-281a5959-3cd5-45fc-849c-9a0456168e79.png)
![two_way_spray_0845](https://user-images.githubusercontent.com/12714528/224304867-c51d46e6-a984-47b0-9e79-ce2734dc1c5a.png)

**Comment by mcgratta** [comment]
I'll take a look. Some time ago we discovered a bug in the droplet routine that led to momentum transfer in the wrong direction. I wonder if this is some variant of that.

**Comment by rmcdermo** [comment]
Thought that bug was gravity-related.  This reminds me of the issue Jason and I were working with the HVAC vent.  Not sure it has anything to do with particles.  If you took an OBST and blow air out of it in one direction, I think with the OPEN boundary conditions you see a reverse jet.  I think resolution and bcs ended up being where we landed, but I need to track it down.  Maybe Jason remembers.

**Comment by mcgratta** [comment]
Something obviously wrong here, like an opposite sign somewhere
![image](https://user-images.githubusercontent.com/11333911/224335316-4ad313a5-0c09-4ed4-9b96-43bdbb0bce76.png)

**Comment by rmcdermo** [comment]
See [Issue # 10075](https://github.com/firemodels/fds/issues/10075).   Midway down, you'll see once we started moving the boundary back we noticed these -x velocities.

**Comment by drjfloyd** [comment]
I tried this case by dropping the droplet mass flow and speed two orders of magnitude so there was no significant droplet momentum transfer and then added a VELOCITY PATCH in front of the nozzle. I saw the same backwards flow. 

&PROP ID='nozzle',
      PART_ID='H2O',
      OFFSET=0.12
      PARTICLES_PER_SECOND=10000,
      PARTICLE_VELOCITY=1.00,
      SPRAY_ANGLE=0.0,10.0,
      MASS_FLOW_RATE=0.00004/

&PROP ID='p1',VELOCITY_COMPONENT=1,P0=10/
&DEVC ID='p1',XB=0.9,1.2,0.9,1.1,0.9,1.1,QUANTITY='VELOCITY PATCH',PROP_ID='p1',DEVC_ID='nozzle'/

**Comment by shostikk** [comment]
What do we learn from the PATCH case?

**Comment by mcgratta** [comment]
https://user-images.githubusercontent.com/11333911/224811220-eb650658-7e7a-44a5-b3a6-d6e086b74281.mp4

Set `PARTCILE_CFL=T` on the `MISC` line. This causes the time step to decrease to about 0.0005 s, which makes senses because dt=dx/u=0.05/100=0.0005 s. See the attached movie. Without `PARTICLE_CFL`, the droplets travel multiple grid cells in a time step, and the application of the drag force vector is not good.

**Comment by mcgratta** [comment]
All that being said, I still see some negative velocity. That might be a spatial resolution issue too.

**Comment by shostikk** [comment]
Yes, as I wrote in the input file, PARTICLE_CFL did not fix it.
________________________________

**Comment by mcgratta** [comment]
There might be a better way to interpolate the particle drag onto the mesh. I'll try it.

**Comment by mcgratta** [comment]
There seem to be two issues. First, your nozzle is at the intersection of 4 cells. If you shift the nozzle 2.5 cm in the y and z directions, things improve. This is not a solution, just an observation. Second, currently, FDS deposits the particle drag onto the mesh at the location where the particle is at the end of the time step. That means that the particle might cross several cells, and only the last feels the drag. I changed this and things improve. But there is still some backwash in the original case. I'll keep looking.

**Comment by drjfloyd** [comment]
Some of this might just be grid resolution. 100 micron particles at 100 m/s in a 10 degree cone is going to dump a lot of momentum into a few grid cells. As the flow is entrained radially from around the spray those inward flows collide in the center of the spray cone. That air needs to go somewhere. At the -x edge of the spray cone there is nothing preventing air from escaping in -x. We don;t have the physical sprinkler blocking backwards flow or the solid pre-broken up spray blocking backwards flow. Would this case be helped if the wall cell behind the sprinkler was solid?

**Comment by mcgratta** [comment]
I'll try that.

**Comment by mcgratta** [comment]
https://user-images.githubusercontent.com/11333911/225380400-c7048410-6e56-46c6-8d27-e7ce61805385.mp4

**Comment by drjfloyd** [comment]
That seems to help some. In Simo's image the negative flow spans 5-6 grid cells. In this movie it is more like 2-3.

**Comment by shostikk** [comment]
Can't see the whole spray but it looks quite different downwind
________________________________

**Comment by mcgratta** [comment]
I just pushed up new code that improves the way particle drag is interpolated onto the mesh. It is essentially the inverse of how we interpolate the gas velocity at the location of the particle. This improves the jet structure, but it does not eliminate the "back wash" velocity. I think as we speculated above, this negative velocity is caused by resolution limits and boundary conditions. Aside from putting the jet into a narrow duct, I don't know how to eliminate the negative velocity. 

One thing to consider is the x component of the momentum equation. The particle drag term, $\mathbf{f_b}$, roughly balances with $\partial H/\partial x$ in steady state. Both are defined at cell faces. One cell upstream of the cell where the particles are introduced sees no drag, but it does see the pressure gradient that pushes the gas in the other direction. This strikes me as a resolution thing, where we are "smearing" forces over big grid cells. 

![image](https://user-images.githubusercontent.com/11333911/225760490-fea9ec5c-0d84-4270-ad20-a528d9b02274.png)

**Comment by shostikk** [comment]
To avoid the abrupt .change of momentum source, I tried using 
```
      PRIMARY_BREAKUP_LENGTH = 0.30
      PRIMARY_BREAKUP_DRAG_REDUCTION_FACTOR = 0.01
```

and OFFSET of 0.02, but it did not elimate the problem, just moved it downstream.

**Comment by mcgratta** [comment]
I do not have a good solution for this. I believe it is a result of grid resolution. The best remedy is to put the nozzle at the center of the face of a single grid cell.
