### ISSUE TITLE
PDPA output 'PARTICLE FLUX' is broken

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11540]
[LN02_4_simple.txt](https://github.com/firemodels/fds/files/10971631/LN02_4_simple.txt)
Run this case with the latest source and then dial back to this [commit](https://github.com/firemodels/fds/commit/90265a2fc2036fc63ae00e370772d9b1405ab91b). Something goes wrong in the flux output. Focus on f_40-x and f_40. The numbers change be several orders of magnitude.

**Comment by rmcdermo** [comment]
@shostikk I may need your help to sort this out.  I have found one problem with my overhaul---I was not computing the EXPON correctly.   This has been corrected in PR #11543 .

In this overhaul of the PDPA output, I am trying to make it consistent with the writeup in the user guide, eq. (21.40) and Table 21.2.

What I cannot reconcile is for QUANTITY using f_2, the PY%PDPA_DENOM should always be V per eq. (21.40).  But if you look at the original code in [commit diff](https://github.com/firemodels/fds/commit/90265a2fc2036fc63ae00e370772d9b1405ab91b) that Kevin was pointing to above (that is, look at dump.f90 for [62be431](https://github.com/firemodels/fds/commit/62be4318dd748c5bc7375bb8e692e29b8feb75be)), you will see at line 7523
```
DV%PDPA_DENOM = DV%PDPA_DENOM + FOTHPI*(2._EB*PY%PDPA_RADIUS)**3
```
where you are accumulating the DV%PDPA_DENOM since PY%PDPA_INTEGRATE=T.

I cannot figure out why, yet it seems to give results closer to the flux data for this simple case in this example.  Can you please look at my most recent commit PR #11543 and tell me where I am not being true to the documentation?  Thanks

**Comment by rmcdermo** [comment]
OK, I moved PDPA_DENOM back outside the particle loop, as Kevin suggested (PR #11544).  I'm now rerunning the full resolution VTT_Sprays cases.

**Comment by shostikk** [comment]
Thanks. Side note, VTT sprays inputs for the spray properties have always been kind of backwards engineered to reproduce the droplet size distrributions. Typically, every few years, some adjustment has been necessary. Rad attenuation validation makes sense only after the spray properties align with measured ones.

**Comment by shostikk** [comment]
PDPA algorithm is nowadays much more complex than when I worked with it. Takes me a while to figure out what is going on.

**Comment by mcgratta** [comment]
Things seem to be working. Thanks
