### ISSUE TITLE
FDS issue

### ISSUE THREAD

**Issue by kihila** [firemodels/fds#11601]
Hi,
I need help with my model, every running simulation the results show soot always penetrates the floor above, as shown in the picture
![227733958-468de4fa-48ca-4629-85f8-7f6248ec58bd](https://user-images.githubusercontent.com/127167622/227757643-0fae5392-8a6f-4738-a69b-fd59b6eb3ae3.png)
![227733934-490f3811-92f2-4f3a-8101-bbac60271258](https://user-images.githubusercontent.com/127167622/227757645-5afc9b40-7e47-423b-a4de-6cbe6e4b1e08.png)

how to fix it?

[L1-UJI4_300S.zip](https://github.com/firemodels/fds/files/11070873/L1-UJI4_300S.zip)

thanks!

**Comment by drjfloyd** [comment]
Carefully examine your geometry in Smokeview and look for unintended holes. For example, if I clip the geometry to 3.4 m vertically and move a z plane upwards, it looks like there is a hole between floors at x,y = 4.3,21. The attached image is looking up at the floor at ~3.5 m with the z-plane of grid cells above the floor and you can see the z-plane indicating a hole is present.  This appears to be in the same location as your images.

Another technique is to put slices of the soot mass fraction just above and below the floor and look to see where smoke seems to be passing and then check that area closely for holes.

![L1-UJI4_300S_s0000](https://user-images.githubusercontent.com/12799217/227781233-93537393-3dab-4e6c-b489-5b6cfd91a70f.png)

**Comment by kihila** [comment]
thank you, I will check these points and soon let you know the results

**Comment by kihila** [comment]
I'm sorry, I can't find the hole like the picture you sent, my model doesn't have any gap
please help

**Comment by drjfloyd** [comment]
Did you try running with slice of MASS_FRACTION of SOOT above and below the floor? 
Was the file you attached as a zip file the exact same file you are running?

**Comment by kihila** [comment]
I try running with slice 2D of mass_fraction of soot above and below the floor

**Comment by kihila** [comment]
result slice of MASS_FRACTION of SOOT above show nothing like that
![image](https://user-images.githubusercontent.com/127167622/227789688-fc99dc80-4a76-47b3-a5b8-b0f590ab7579.png)

but in the fact, soot still passing 
![image](https://user-images.githubusercontent.com/127167622/227789803-089bd99b-19a3-4d4b-a8ed-28466a30f259.png)

**Comment by drjfloyd** [comment]
This is the input file you attached being run with the current release of FDS (6.7.9) with a slice file of soot mass fraction at Z=4.2 m viewed from below with domain clipped to 3.5 m using Smokeview. You can see the hole in the floor and soot above the floor at the intersection of the grid planes.

![L1-UJI4_300S_0472](https://user-images.githubusercontent.com/12799217/227790418-d4c58bcb-e9d2-4fc7-870a-9898fc06f852.png)

**Comment by kihila** [comment]
no, this is different from my running results, just for information I use pyrosim to run, but the results show otherwise

**Comment by drjfloyd** [comment]
Make sure you are looking at the geometry as FDS has implemented it and not how you defined it in Pyrosim. If you don't know how to do this, you may want to use Smokeview and not the Pyrosim results viewer.

**Comment by kihila** [comment]
I'm sorry but I don't know how to use FDS and Smokeview. I need to finish this asap because it's related with my final project

**Comment by drjfloyd** [comment]
As the model user, it is your responsibility to know how to use the model. 

This is not an issue with FDS. The issue your input file is resulting in a hole. I have pointed out two paths to finding this hole: using the Pyrosim results viewer in a mode where you view the FDS geometry only or using Smokeview in a mode where you view the FDS geometry only. Both of these are documented in the user documentation.  

Another option is you try running with a uniform grid size at the smallest grid and this might avoid the issue if the root cause is how objects are snapping to the grid.

Since this is not an issue with FDS, I am closing the issue. General discussions on using FDS should be done in the FDS Discussion Forum and issues/questions on Pyrosim should be directed to Thunderhead Engineering technical support.

**Comment by hanasaskia** [comment]
hello, sorry to report. finally I regenerated the model by reducing the size of the mesh boundarie and the same ratio between the model and the size and it went smoothly.

I think if the model follows the existing size it won't be a problem because it will be more accurate, but instead it won't read by FDS

this is an important lesson for me

thanks a lot for helping and checking my model, then I will study FDS and SMV in more detail to reduce errors that occur
