### ISSUE TITLE
Obstacle embedment check breaks case

### ISSUE THREAD

**Issue by FireResearch-BK** [firemodels/fds#11608]
We have a case in which the setup of an electric train set crashes 6.7.9-1935.

The model was imported into Pyrosim from a .dae file.
Since the railway operator's regulations for CFD smoke simulations demand that the platform facing middle set of doors must be open and that all windows must fail sequentially after a set period of time to simulate fire damage, the following measures were undertaken:
- equip all windows that must fail with a hole that is activated by a timed control logic.
- move the middle set of doors on one side outside and away from each other to represent door movement on the actual train.
Furthermore, regulations demand specific material and surface properties.

Model preparation was performed in Pyrosim and then exported for use in FDS.

Since the model is part of a more complex case involving 24 of these train cars, we want to use 6.7.9-1935 (with `MINIMUM_ZONE_VOLUME` parameter) to work around https://github.com/firemodels/fds/issues/11602 in order to avoid having to extend the fine mesh along the entire length of a 12 car train set.

Now when the case is started with 6.7.9-1935, it always crashes immediately with 
`ERROR: [Obstacle name] is embedded within [other obstacle]`.

The case runs only when we completely disable all glass objects, but since this violates regulations, it's not a viable workaround.

We suspect that commit https://github.com/firemodels/fds/commit/7ec0c882efb04ea6d641d307410d2afad988922d might be the root cause.

A simplified test case is attached.

[Test.txt](https://github.com/firemodels/fds/files/11102780/Test.txt)

**Comment by IFAB-AS** [comment]
Since the train model is blocked automatically when starting FDS, I assume some of the OBSTS are created with overlap. The line 9700 in commit https://github.com/firemodels/fds/commit/7ec0c882efb04ea6d641d307410d2afad988922d ``ELSEIF ((DEVC_ID/='null'.OR.CTRL_ID/='null') .AND. (OB2%DEVC_ID/='null'.OR.OB2%CTRL_ID/='null')) THEN`` checks, whether both OBSTS have an CTRL_ID/='null' or DEVC_ID/='null'.
In many cases, these automatically created OBSTS will have the same IDs and will be removed at the same time during the simulation. So it might make sense to add something like ``ELSEIF ((DEVC_ID/='null'.OR.CTRL_ID/='null') .AND. (OB2%DEVC_ID/='null'.OR.OB2%CTRL_ID/='null')) .AND. (CTRL_ID/=OB2/CTRL_ID) THEN`` at the end of the ELSEIF if this does not create new types of errors.

**Comment by drjfloyd** [comment]
I think a better check would that either there is no DEVC/CTRL or that there is the same DEVC/CTRL.  If you had two OBST with the same ID but different DEVC/CTRL, then we would be back to the situation that the commit was addressing. Since no DEVC or CTRL means 'null' we could just have the check be are the DEVC/CTRL identical.

**Comment by mcgratta** [comment]
I could not get the suggested logic to work for all cases. I decided to loosen the criteria for removing embedded obstructions.

**Comment by FireResearch-BK** [comment]
@IFAB-AS tested the original case with 6.8.0 and the error did not occur.
