### ISSUE TITLE
Water pool results seem off

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11731]
Perhaps this has not been run out long enough?

<img width="212" alt="Screen Shot 2023-04-16 at 8 31 03 AM" src="https://user-images.githubusercontent.com/4418497/232310128-cd234b6e-549a-4e50-a192-a3475efc09a1.png">

**Comment by rmcdermo** [comment]
Nothing stands out as obviously wrong with this case.  60 min should long enough run time.  I think it would be good to plot the surface vapor mass or volume fraction to compare that with the expected result.  Hard to tell from just the mass loss rate where the trouble lies.  But I think we should be able to get tighter on this case.

**Comment by drjfloyd** [comment]
I'm taking a look now.

**Comment by drjfloyd** [comment]
Just need to add ADJUST_H = F so the hand calc value for H_R matches the value used by FDS.  This could be speed up by specifying a wall temperature profile rather than taking the time to establish it in the run but RAMP_T_I got removed. I added an issue to put it back; it was a useful freature that I have used on more than on occasion.

**Comment by drjfloyd** [comment]
It is back to the value it had with 6.7.9.
