### ISSUE TITLE
FDS GEOM

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#11868]
Enclose follows a case that work ok with low and medium mesh resolution, but it fails with high mesh resolution.
Error message :
ULMAT_H_MATRIX_LUDCMP PARDISO Num Factor: The following ERROR was detected:    -4
Is this something related to Blender-FDS, or is it FDS ?
FDS revision is in the error message file
[Files.zip](https://github.com/firemodels/fds/files/11624079/Files.zip)

**Comment by emanuelegissi** [comment]
If you discover it is a BlenderFDS problem please open an issue there.
Thanks

Il gio 1 giu 2023, 12:27 fidran ***@***.***> ha scritto:

**Comment by marcosvanella** [comment]
Hi @fidran, thank you for reporting. We'll take a look at this.

**Comment by fidran** [comment]
Something strange here too
![Blender vs FDS](https://github.com/firemodels/fds/assets/40716592/eceadde1-58d4-47c5-afac-66661aa70921)

**Comment by marcosvanella** [comment]
Hi @fidran, after latest changes this case is working on my side. Try it with latest source or tomorrows nightly bundle. 
The issue was related to spurious z location numbers (~1.E-9) defined in the bingeom for the nodes at the bottom of your dome, which were giving issues in the cut-cell computation algorithm. We are sanitizing those cases now.
Thank you for reporting!

**Comment by fidran** [comment]
Works ok - thank you
