### ISSUE TITLE
Flow rate measurements at two different cross sections

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#12019]
There are a few flow measurement devices in the model. One group is on the orifice, other is across the mesh. I see a slight difference in between for both volume flow rate and the mass flow rate. Is that accepted as normal?
 
Thank you

![image](https://github.com/firemodels/fds/assets/26166281/d2b67de2-5287-4a56-82da-b4fea2ac86d9)
![image](https://github.com/firemodels/fds/assets/26166281/3ed9827e-ecae-4168-b29b-43b19a12c697)
[stairs3.zip](https://github.com/firemodels/fds/files/12252563/stairs3.zip)

**Comment by rmcdermo** [comment]
@Er9y714 can you distill this a bit more, I appreciate it.  Otherwise, I have to dive in an take time to study the case.  Is there an obvious issue?  You know well whether the flows should match.  Not all flows will be identical, but the overall mass balance should be.  You need to do the mass balance.  It may not be locally perfectly steady state.  There are examples in the verification guide to follow.  You may need to tighten up penetration errors at solid boundaries or velocity errors at mesh boundaries, etc.  Please check all this... it is what I would have to do.

**Comment by Er9y714** [comment]
Yes of course. Let me spend some time on it. Good to see I did not miss anything obvious.

**Comment by mcgratta** [comment]
I'll run the case.

**Comment by mcgratta** [comment]
This might be a bug related to the integration of the velocity component. Try this. Instead of 
```
&DEVC ID='AOV_VolFlow_01', QUANTITY='W-VELOCITY', SPATIAL_STATISTIC='AREA INTEGRAL', XB=143.6,144.6,32.8,33.8,54.8,54.8/
```
write this instead
```
&DEVC ID='AOV_VolFlow_01', QUANTITY='W-VELOCITY', SPATIAL_STATISTIC='AREA INTEGRAL', XB=143.61,144.59,32.81,33.79,54.8,54.8/
```
FDS is integrating the value over one too many or one too few cells.

**Comment by Er9y714** [comment]
@rmcdermo Since @mcgratta picked up the issue and found a bug, I guess I do not need to distil the issue anymore. 

@mcgratta 
Thank you. It works well now. It appears that the issue is present both at and away (next to OBST) the mesh boundaries. Limiting the bounding box of DEVC prevents the issue. 

This reminds me a similar issue with INIT regions. I will check and report if I can demonstrate. Thank you very much for your help. I will close the issue.
