### ISSUE TITLE
No/Partial Heat Release Rate from Vent when not/partially on an Obstruction

### ISSUE THREAD

**Issue by FireResearch-BK** [firemodels/fds#12044]
This is a simple test case that contains a burner type vent with an area of 0.96 m² at z=0.144m above the floor within a mesh with ~4 cm grid size. There is a ramp made up of multiple points.

Target HRR yields for the ramp are:

|Time (s)|HRR (kW)|
|---|---|
|0|0|
|10|18.76|
|20|75.04|

[Testcase.txt](https://github.com/firemodels/fds/files/12319943/Testcase.txt)

Running the above test case in FDS 6.8.0 (and FDS 6.8.0-512) yields zero HRR.

If an obstruction with equal area (and zero thickness) is placed below the vent, I get a HRR output (not quite according to the target at the corresponding point of the curve above, but I guess this is due to default ramp up times). Test case:

[Testcase_Obst.txt](https://github.com/firemodels/fds/files/12319939/Testcase_Obst.txt)

If said obstruction only covers half the area of the vent, the test case yields half the HRR output of the above:

[Testcase_HalfObst.txt](https://github.com/firemodels/fds/files/12320043/Testcase_HalfObst.txt)

(Sidenote: There is no issue if there is no burner vent and the Zmax surface of the obstacle has the fire surface instead.)

There is a requirement to place vents on top of obstruction, and there used to be an associated warning message/error if there was no such obstruction present, which was removed at some point in preparation for the 6.8.0 release (can't find the associated issue anymore though). 
I have assumed that the warning message was a mere formality and that burner vents work just fine on their own, but this does not seem to be the case.

It would be useful to either reinstate the check and warning message or make vents capable of emitting heat according to their area independent of any underlying obstruction.

**Comment by mcgratta** [comment]
You are right. We wanted to allow a VENT to work properly even if it were only partially backed by an OBST. I guess we went too far. This case should end with an ERROR. My guess is that part of the problem is that the VENT is split across meshes. When the VENT is read by process 0, there is no easy way to know at that point in the simulation whether or not an OBST lies under the VENT in the other mesh.

**Comment by FireResearch-BK** [comment]
Would it be feasible to implement a check for vents near mesh boundaries and check cells of adjacent meshes for parts of the same vent? Once all parts of the vent have been found, the check for (partial) OBST backing would take place.

I figure the reason for OBST backing is to determine the vent orientation from the surface. Now when a vent is not backed by an OBST, it would help if FDS threw an error that could be resolved by placing an OBST underneath the vent or by having to manually specify the vent's orientation. 
In my eyes, a burner type surface on a surface of an OBST with zero thickness is the same as a burner type vent with a specific orientation, so I don't see why both would need to be treated differently.

**Comment by FireResearch-BK** [comment]
Does this mean that even partial backing by an OBST will now yield the entire HRR for the vent?

**Comment by drjfloyd** [comment]
Based on the simple case below, the HRR is based on that fraction of the VENT that is on the OBST.  This example has 50 % of the VENT on the OBST and the HRR is 80 kW instead of 160 kW.

`&HEAD CHID='vp'/

&MESH XB=0,1,0,1,0,1,IJK=10,10,10/

&VENT MB='XMIN',SURF_ID='OPEN'/
&VENT MB='YMIN',SURF_ID='OPEN'/
&VENT MB='XMAX',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/
&VENT MB='ZMAX',SURF_ID='OPEN'/

&TIME T_END=10/

&SURF ID='q',HRRPUA=1000,COLOR='RED'/

&OBST XB=0.3,0.7,0.3,0.7,0.0,0.1/

&VENT XB=0.1,0.5,0.3,0.7,0.1,0.1,SURF_ID='q'/
&REAC `FUEL='PROPANE'/``

**Comment by FireResearch-BK** [comment]
But is this intentional behavior?

If I have a burner vent with a specific area A and specific HRRPUA, I honestly expect it to release HRR = HRRPUA * A, completely independent of the amount of the vent's surface that is backed by an OBST.

**Comment by FireResearch-BK** [comment]
Can the vent behavior for burner surfaces be reconsidered?

While A_obst is the relevant parameter for HRR calculation when A_vent > A_obst, A_obst is not relevant when A_vent < A_obst, A_vent being the limiting factor instead. This is a bit confusing and I think that simply always considering A_vent for HRR would be a much more straightforward solution and eliminating a pitfall in FDS usage.

**Comment by mcgratta** [comment]
Can you present a compelling case for changing the current approach? The reason I ask is that these kinds of changes inevitably result in unforeseen consequences that will prompt someone else to ask that the change be reverted, or that someone's results are no longer the same in version 6.8.1 as they were in 6.7.2 which will lead to a few days worth of source code bisection to figure out why. We spend a substantial amount of time chasing our tails in this way. There is also the functionality of PyroSim and BlenderFDS and other tools to consider. So please send us a case for which it makes sense to crack open the egg on the little end instead of the big.

**Comment by mcgratta** [comment]
Here's a good example of why we are hesitant to change functionality unless there is a compelling reason for doing so:
[https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox/FMfcgzGtwgfNdPxNzHDtRBffqhtbKgjw](https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox/FMfcgzGtwgfNdPxNzHDtRBffqhtbKgjw)
I don't know all the details for this particular case, but it just points out that we must carefully consider changes in functionality.

**Comment by rmcdermo** [comment]
@mcgratta FYI, I could not get to the link you sent.  Looks like it is for one of your email threads.  Probably you meant to point directly to a Google Group discussion post?

**Comment by mcgratta** [comment]
Should work now.

**Comment by mcgratta** [comment]
These examples are very simple, and, sure, we could probably handle them either way. But a more typical example would be a building that is divided up onto multiple meshes of various resolution. A wall may have many holes cut out of it and then a VENT might be laid across its entire extent, spanning multiple meshes. The way the code works now, when we process the OBST lines, we do it mesh by mesh because a given MPI process can only work with its designated mesh or meshes. If we see that the face of an OBST has some part of a VENT attached to it, we assign that OBST face the SURF ID corresponding to the VENT. 

To do what you want, we would have to do this same procedure, but then after it is done, we would have to loop back over the OBSTs and readjust the HRRPUA based on the fraction of the VENT that is actually underpinned by OBSTs. That means we have to exchange OBST info over however many MPI processes the VENT extends. This costs time, memory, and code complexity. It would take several weeks of my time and the code would be hundreds of lines longer and hence more difficult to maintain by the 3 of us who do the bulk of code maintenance. All for a feature that we probably never should have allowed in the first place, or that can be better handled by a graphical user interface like PyroSim. 

So where would you have us spend our time? Is this "feature" really worth it?

**Comment by FireResearch-BK** [comment]
I think we're on completely different continents here.

Frankly, all I'm lobbying for is HRR = HRRPUA * A_vent, in *all* cases (A_obst > A_vent, A_obst < A_vent, A_obst = A_vent).

If this is too complicated or time-consuming to implement, then so be it.

**Comment by mcgratta** [comment]
Yes, I think we are on two continents, literally and figuratively. I do understand exactly what you are asking for. To do what you want, we need to adjust the HRRPUA that is assigned to each underlying OBST so that HRRPUA_adjusted times the area of the underlying OBSTs equals your desired HRR. That requires exchanging information across MPI processes during the early stages of the simulation before much of the exchanges have been set up. To make things work, we would have to overhaul the entire initialization phase of the simulation, which would take much time and could potentially lead to more problems.

**Comment by FireResearch-BK** [comment]
Can the specific relation between burner vents and underlying obstructions and their effect on HRR at least be documented in the user guide? I couldn't find any mention of something like this in chapter 9 and I think this is a large enough pitfall.

I don't know if you've missed it, but case 3 in https://github.com/firemodels/fds/issues/12044#issuecomment-1679101353 produces no HRR at all, despite 25% of the burner vent area being on top of an OBST.

**Comment by mcgratta** [comment]
I can document this. Case 3 works for me with the latest source

![image](https://github.com/firemodels/fds/assets/11333911/356a5ec1-02d6-4038-ae1e-97565712e696)
