### ISSUE TITLE
Jetfan HVAC control deactivation not working

### ISSUE THREAD

**Issue by markkhedher** [firemodels/fds#12064]
[Jetfan_control.txt] (https://github.com/firemodels/fds/files/12353707/Jetfan_control.txt)

I have configured a control to deactivate a HVAC duct fan on activating of sprinklers however it is not shutting down the fan.
The sprinkler head activates and the time delay lapse at 19.69 s, yet the jetfan continues to run at 26 s.
As requested, I have created a simple model with 1 jetfan and uploaded as a txt file to this ticket.

**Comment by drjfloyd** [comment]
thanks for simplifying the file down.  I'll take a look at it.

**Comment by drjfloyd** [comment]
I can reproduce this with the current source. A FAN input with a fixed volume flow fan is treated differently than quadratic or RAMP fans - it sets a duct velocity rather than a fan pressure. I guess all our testing with turning off fans must have been with the pressure fan types as there was a logic error for the volume flow type.  While I fix this as a work around you could change to a quadratic fan. The fan definition below gives 1.25 m3/s and does turn off when the CTRL function operates.

&HVAC ID='Fan01', TYPE_ID='FAN', MAX_FLOW=1.55,MAX_PRESSURE=1000/

**Comment by drjfloyd** [comment]
Should be fixed now. It will be in the next test release of FDS which should be tomorrow assuming firebot passes:
https://github.com/firemodels/test_bundles/releases

**Comment by markkhedher** [comment]
Thank you very much.
