### ISSUE TITLE
HVAC node location E+11 in smv file

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#12081]
Following up on https://groups.google.com/g/fds-smv/c/44EHeDLflpk/m/l-GC1r-9BQAJ

Please see the attached run. I did not simplify the meshes because this issue does not occur with a few meshes only. 

The issue in the attached run generates a smv file with the lines below:

Thank you very much. 

```
HVAC

 NODES

 2

 1 % Inlet08 % Unassigned % 1

 -0.100000E+11-0.100000E+11 0.800000E+00 % NO FILTER % Inlet08                                                     

 2 % Outlet08 % Unassigned % 1

 -0.100000E+11-0.100000E+11 0.800000E+00 % NO FILTER % Outlet08 
```

[v2.zip](https://github.com/firemodels/fds/files/12438581/v2.zip)

**Comment by drjfloyd** [comment]
Thanks. I'll take a look.

**Comment by drjfloyd** [comment]
The issues is in HVAC processing we set the XYZ for a NODE connected to a VENT to the center of the VENT; however, this can only be done in the mesh where the VENT exists. Writing of the HVAC network to the smv file is only done once for the first MPI process. In a single MPI process case, this works fine as all the VENTs exist in that process. In a multiple MPI process case, we need to exchange that data which isn't being done.  This is just an issue for visualization.  For the HVAC solution process there is a more complicated method for setting the NODE location which does have an MPI exchange.  We can't use this method for the smv data since it needs setup details that aren't done for a T_END=0 input.

**Comment by drjfloyd** [comment]
We had code in the hvac processing to check to see if we found any mesh with the VENT named for a NODE. In that same block I added some more MPI calls to get the XYZ from a MESH that had the VENT.  Now the smv file shows the correct XYZ.  Assuming this passes firebot, it will be in the nightly build.

**Comment by Er9y714** [comment]
Great! Thank you very much.
