### ISSUE TITLE
Solid heat transfer with thickness >= cell size in 6.8 (HT1D)

### ISSUE THREAD

**Issue by p-lauer** [firemodels/fds#12101]
Hi!

I encountered some unexpected behaviour in FDS-6.8.0-0-g886e009-release. The setup is as following:

I have two layers of horizontal aluminum panels directly one after the other. Each layer is an individual obstruction. Each obstruction is one cell size thick and spans over the whole domain in the other directions. One side is exposed to a fire, the other side is not. I'm using the HT1D submodel.

![image](https://github.com/firemodels/fds/assets/13256462/67b82743-5e5b-4a48-aa4b-6a2c3420f1eb)

What I would expect is that there would be no heat transfer through the two layers, since the model does not consider heat transfer between two solids that touch each other. I would only expect heat transfer from the fire exposed side of the first obstruction to the other side of the first obstruction.

What I get:

If the solid thickness is < cell size, I see a change in the front and back surface temperature in the obstruction close to the fire and I don't see any temperature change on the surfaces of the obstruction that is not exposed to the fire. This is what I would also expect as a result from my understanding of the model.

Input file: [ht_1d_thin.txt](https://github.com/firemodels/fds/files/12550497/ht_1d_thin.txt)
Results: [ht_1d_thin.zip](https://github.com/firemodels/fds/files/12550479/ht_1d_thin.zip)

If the solid thickness is >= cell size, I also see a change in the temperature of both of the surfaces of the second obstruction. This is a behaviour I would not expect.

Input file: [ht_1d_thick.txt](https://github.com/firemodels/fds/files/12550506/ht_1d_thick.txt)
Results: [ht_1d_thick.zip](https://github.com/firemodels/fds/files/12550487/ht_1d_thick.zip)

I didn't saw this behaviour in version FDS6.7.9-0-gec52dee42-release, so it might be linked to the "1D heat transfer no longer limited to zero or one-cell thick obstructions" change?

**Comment by mcgratta** [comment]
The functionality you describe is in flux at the moment. For FDS 7, we are implementing a feature where the user can stack OBSTs with different MATL properties and FDS will automatically figure out the internal gridding. Rather than compare 6.7.9 and 6.8.0, let's discuss what you want to have happen, and I will see if the latest source code can do that. We issue test bundles every day, so  you may be able to do what you want with a test version.

**Comment by mcgratta** [comment]
Yes, this is confusing, which is why it's being overhauled. Once upon a time, we only allowed conduction through a single cell of a single OBST. Now we're trying to relax these restrictions, but it has led us to some confusing set ups. In your case where you have set THICKNESS=0.045 m, FDS looks at the first OBST and sees that it is 0.05 m thick. If the back of this OBST were not covered by another OBST, FDS would have done heat conduction through that OBST assuming it was 0.045 m thick. But because the OBST is covered, FDS instead is applying the VOID backing condition instead. When the THICKNESS=0.05 m, FDS is searching the next solid cell and applying the back surface condition to the back of the second OBST, even with a THICKNESS of 0.05 m.
