### ISSUE TITLE
Incorrect gas phase mass fraction with user specified ramp with multiple reactions

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12131]
Found an issue when benchmarking spyro and kinetics with the macfp parallel panel case. The amount of reactant being inserted into the gas phase does not align with a user specified ramp when multiple reactions are defined. The attached case demonstrates the issue. If the first &REAC is commented out (corresponding to propane) the correct amount of MMA is generated corresponding to the user defined ramp. However, if the first &REAC is included, the amount of MMA generated is significantly higher. Note that this issue is for all user defined HRRPUA ramps, not related to spyro directly.

I think the issue is related to SF%ADJUST_BURN_RATE in read.f90 assuming that there is only a single &REAC line (see line 8513, hard coded REACTION(1)). In comparison, see how ML%ADJUST_BURN_RATE is set for the kinetics approach (see line 6785, REACTION(NR2)).

[PMMA_simple.txt](https://github.com/firemodels/fds/files/12687014/PMMA_simple.txt)

**Comment by drjfloyd** [comment]
Verified that in the absence of a thermally thick surface things are working. Have PROPANE at 40 MJ/kg and MMA at 20 MJ/kg

Mesh 1: One burner, HRRPUA = 1000, Fuel = PROPANE
Mesh 2: One burner, HRRPUA = 1000, Fuel = MMA
Mesh 3: Two burners, HRRPUA = 500, one with Fuel = PROPANE and one with Fuel = MMA
Mesh 4: One burner, HRRPUA = 1000, 50/50 mass fraction mix of PROPANE and MMA

results are as expected. At least that bit of the logic is doing what it should. I'll start looking at what happens when a MATL gets thrown in the mix.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/27402/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/27402/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Time | P-M1 | M-M1 | P-M2 | M-M2 | P-M3 | M-M3 | P-M4 | M-M4
-- | -- | -- | -- | -- | -- | -- | -- | --
10 | 0.004985 | 0 | 0 | 0.009967 | 0.002492 | 0.004984 | 0.003323 | 0.003323
Hand Calc | 0.005 | 0 | 0 | 0.01 | 0.0025 | 0.005 | 0.003333 | 0.003333



</body>

</html>


[PMMA_test.txt](https://github.com/firemodels/fds/files/12689161/PMMA_test.txt)

**Comment by drjfloyd** [comment]
Added a MATL_ID.  Now have all 4 meshes with one HRRPUA=1000 burner. Mesh 1+2 PROPANE, Mesh 3+4 MMA, Mesh 1+3 no MATL on the SURF, Mesh 2+4 MATL on the SURF.  If everything is working Mesh1 = Mesh2 and 3 = 4. But you can see depending on which FUEL is first only one of the two pairs matches. I think you have the culprit.  Now to fix it without making firebot angry.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/27402/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/27402/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | P-M1 | P-M2 | M-M3 | M-M4 |  
-- | -- | -- | -- | -- | --
10 | 0.004985 | 0.004985 | 0.009967 | 0.039869 | PROPANE 1st
10 | 0.004985 | 0.001246 | 0.009967 | 0.009967 | MMA 1st
  | 0.005 | 0.005 | 0.01 | 0.04 |  



</body>

</html>

**Comment by drjfloyd** [comment]
This could be a bit of a rabbit hole. I had just taken the logic that was there and kept it for mulitple simple REAC without delving too deep.

For a material with solid phase reactions, we do an adjustment in the pryolysis routine that accounts for a wall node having multiple materials with the possiblity of multiple gas species and multiple reactions with different heats of combustion. There I think we are OK.

For MLRPUA or HRRPUA we currently fix the adjustment to the first material in a surface and that is locked to REAC 1. The second part I think would be easy enough to deal with. However, if we have a SURF with multiple layers or multiple materials in a single layer we could have multiple HEAT_OF_COMBUSTION. Right now we aren't accounting for that. Should we? Or for now should we just through an error if this happens when MLRPUA or HRRPUA is used?

**Comment by mcgratta** [comment]
I would not have any heartburn at all if we were to restrict the use of HRRPUA and MLRPUA to one SPEC_ID. That is, if you say HRRPUA, you choose one REAC. Otherwise, you have to use MASS_FLUX etc.

**Comment by drjfloyd** [comment]
I don't think we need to take away capability from FDS to solve this problem. I think we need to think more about what exactly it means when a MATL has a different HEAT_OF_COMBUSTION from the fuel. For example:

&REAC FUEL='MY FUEL', HEAT_OF_COMBUSTION=10000/
&MATL ID='MY MAT',HEAT_OF_COMBUSTION=20000/
&SURF ID='MY SURF 1',HRRPUA=1000,MATL_ID='MY_MAT'/
&SURF ID='MY SURF 2',MLRPUA=0.01,MATL_ID='MY_MAT'/

Right now for both HRRPUA and MLRPUA we are adjusting what gets put in the gas phase. As I think about it, that doesn't make sense with how those inputs are likely obtained.

In this case, an HRRPUA likely means you have something the HRRPUA from a cone test. We should just be putting in the gas needed to get that HRRPUA and not be adjusting it up or down as then we change the HRR.  When we go to account for mass in the wall for burnaway, then we would adjust the solid mass change.

For MLRPUA, here we would likely have a measured mass loss from an item but maybe don't know the fuel gas or are using a surrogate gas. In this case we should adjust the gas to get the right HRR based on the MATL H_O_C*MLRPUA and the mass removal from the wall is just the MLRPUA.

**Comment by drjfloyd** [comment]
We have this processing split up with some in MATL processing and some in SURF processing.  When a MATL has a reaction, then it makes sense to process it all in MATL processing. If you have a pyrolysis reaction, you can't also have an HRRPUA or MLRPUA. This logic is already there and working and it creates the adjustment factors as we have them now that get used in PYROLYSIS.

I think for the case where there is no MATL reaction and the SURF has an HRRPUA or MLRPUA, we should just do that processing in SURF. This will simplify things. There is no point in trying to define all the ML% adjustment arrays since we don't use them for HRRPUA or MLRPUA. There we just use SF% factors. Not splitting the processing of that array will make it a lot cleaner in the SURF processing and I know more or less what is needed to get that done.

**Comment by johodges** [comment]
In principle I agree with the difference there on HRRPUA and MLRPUA. However, it sounds like a headache to me to keep track of and explain in the guide. Agreed with keeping the SURF definition more simple. What would be the disadvantage of not defining all the ML% adjustment arrays? Potential impacts to burn away time?

**Comment by drjfloyd** [comment]
The ML adjustment variables are only used when the ML has a reaction. With HRRPUA or MLRPUA on SURF you cannot have an ML reaciton as that would be overspecifying the mass flux. With HRRPUA or MLRPUA there are SF adjustment variables used.

**Comment by drjfloyd** [comment]
Think I have a fix. I now get the correct burner flow when a MATL is used, no matter what REAC is listed first.  Just need to test the Pyrolysis Verification cases and make sure I didn't break someting.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/27402/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/27402/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | P-M1 | M-M1 | P-M2 | M-M2 |  
-- | -- | -- | -- | -- | --
10 | 0.00498 | 0.00498 | 0.00997 | 0.00997 | PROPANE 1st
10 | 0.00498 | 0.00498 | 0.00997 | 0.00997 | MMA 1st
Hand Calc | 0.00500 | 0.00500 | 0.01000 | 0.01000 |  



</body>

</html>

**Comment by johodges** [comment]
Good news. Thanks for hopping on this!

**Comment by drjfloyd** [comment]
Pushed up the changes. Your simple test case works. Also did the Pyrolysis cases plus the char_oxidation cases WUI. Those all still worked.

**Comment by johodges** [comment]
Thanks, I'll get the macfp case running with the latest.
