### ISSUE TITLE
HVAC duct flow output is zero when run with MPI

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12233]
I started running the cases benchmarking calorimetry and ran into an odd issue with the HVAC outputs. There are two meshes in the attached file. If I run the case without mpi, the outputs all look as expected. However, if I run the case with 2 mpi processes, the duct mass flow device is output as zero. I think this is purely an output issue since the W-Velocity slice still shows exhaust in the case.
[hvac_test.txt](https://github.com/firemodels/fds/files/13367164/hvac_test.txt)

**Comment by mcgratta** [comment]
Jason -- let me know if this involves MPI calls and such, or if it's unique to HVAC.

**Comment by drjfloyd** [comment]
Don't use XYZ for HVAC outputs. The XYZ is setting the DEVC location to the second mesh which is the second MPI process but HVAC data only exists on the first MPI process where the HVAC calculation is done.  We should skip the XYZ mesh lookup for HVAC outputs. I'll fix this. At DELCO today for testing so it may be tonight or first thing tomorrow.

**Comment by johodges** [comment]
Thanks for the update, and I can confirm removing the XYZ from the devices fixes the issue. I'll leave the issue open while Jason makes the update to skip the mesh lookup for the HVAC outputs in the backend.

**Comment by drjfloyd** [comment]
It was difficult to easily untangle mesh assignment from quantity type as mesh assignment was done in a subroutine before quantity lookup. Instead, I added an ERROR when XYZ or XB is used for an HVAC quantity.  Edited the user guide discussion for HVAC outputs as well.  For the ambient O2, rather than trying to define a CONSTNAT you could have lines like below. Just have a DEVC that measure O2 somewhere in the domain and then stop if updating at the start. Now you have the constant value for O2 Amb exactly as it is in FDS.  You could also set OUTPUT=F so you aren't writing a column of constant values to the devc.csv file.

&DEVC ID='AMB O2',XYZ=0,0.3,0,QUANTITY='VOLUME FRACTION',SPEC_ID='OXYGEN',NO_UPDATE_DEVC_ID='STOP'/
&DEVC ID='STOP',XYZ=0,0.3,0,QUANTITY='TIME',SETPOINT=0/
&CTRL ID='O2-DEPLETION-NUM-CTRL', FUNCTION_TYPE='SUBTRACT', INPUT_ID='AMB O2','HOOD-O2'/
