### ISSUE TITLE
Wind goes through the walls.

### ISSUE THREAD

**Issue by PavloNike** [firemodels/fds#12293]
Hi fds community,

I was trying to add wind to my model of the building with multiple natural ventilation wall and roof openings. However, from the modelling results, it looks like wind completely ignores the solid walls, even relatively small wind significantly impacts internal smoke plume. Could you please let me know if I am missing any important setting there. I read article for "Simple Wind in Pyrosim" but it is written more for external or full building fire rather than for smaller internal one.

Also, the simulation time increases dramatically ~100 times slower, I expected more time but this is not realistic to wait so much for me (may take several months..).

Much appreciated.

**Comment by rmcdermo** [comment]
The immersed boundary method, used by default in FDS, admits a "velocity penetration error" that needs to be monitored and corrected if it become significant, which sounds like your situation.  If you have less than 32 meshes, the error will be reported in the .out file.

To fix this, you either need to reduce your VELOCITY_TOLERANCE or use the ULMAT pressure solver.  With ULMAT the error is completely eliminated since you are no longer using immersed boundaries.  Implement ULMAT like this,
```
&PRES SOLVER='ULMAT'/
```

With VELOCITY_TOLERANCE you can do something like this:
```
&PRES VELOCITY_TOLERANCE=1.E-6, MAX_PRESSURE_ITERATIONS=100/
```

**Comment by PavloNike** [comment]
Thanks, @rmcdermo. I will try it tomorrow. Where exactly I need to copy ULMAT into the fds file? 

I have only 9 meshes 300-400k cells per each. Could be split more but have only 20 core PC and try to keep <50% in use. Is it really a problem to use more than 50% of the cores? I get that going with all 20 is pointless but sometimes 1-2 extra cores over 50% allow to split the model a bit better.

**Comment by rmcdermo** [comment]
I usually add the `PRES` line near the top of the input after a `MISC` line, but it does not matter, as long as there is only one `PRES` line.

With ULMAT you will want to keep the mesh size around 32,000 cells (32^3).  And this is in general a good target for efficient MPI scaling.  So try to break up your domain so that each mesh is roughly this size.

**Comment by PavloNike** [comment]
Thanks, @rmcdermo. Do you mean to split current 9 meshes (~3.1 mil cells) into 97 x 32,000 meshes and combine 10 meshes per core via MPI?

**Comment by rmcdermo** [comment]
If you have 3 M cells and you are only going to use 10 cores, you should split the domain into 10 meshes of 300k and you will have to use VELOCITY_TOLERANCE as described above.  ULMAT will probably crash on memory and be too slow if now.

**Comment by PavloNike** [comment]
Thanks again, will give VELOCITY_TOLERANCE a try tomorrow.

**Comment by mcgratta** [comment]
If the case is running "100 times slower", there might be other problems. Post your input file and we'll run it.

**Comment by PavloNike** [comment]
Thanks, @mcgratta. Please see attached input file with wind turned on. I got error after several time steps 0.0X s each. It works pretty well with wind turned off. I haven't had a chance to try VELOCITY_TOLERANCE option advised above as still waiting for 'no wind' model completion. 

I changed extension fds to txt so it can be attached here.

[FS001.txt](https://github.com/firemodels/fds/files/13709208/FS001.txt)

**Comment by mcgratta** [comment]
I am running the case.

**Comment by mcgratta** [comment]
Right away I can see that this case is doomed to fail. You are essentially creating a giant fan blowing at 12 m/s and putting it right up against your building. This is not how wind works. To do a wind simulation you have to create a large (albeit crude) mesh over the entire building(s) and extend that mesh several building diameters and heights. That way, the flow field will develop naturally over the obstructions.

**Comment by PavloNike** [comment]
Thanks for checking, @mcgratta. I am not sure how can I do a large mesh over the entire building that is already split into other smaller meshes. I need to check wind impact on the smoke venting through the building via openings. Based on the FDS mesh calculator, 0.6 is the max size I can have for my 10 MW fire.

@rmcdermo - Unfortunately, VELOCITY_TOLERANCE didn't help, I still got 0.00n s steps and numerical instability after several steps., likely because of giant fan mentioned by mcgratta above.

**Comment by mcgratta** [comment]
I'll try something and let you know.

**Comment by mcgratta** [comment]
I did the following: (1) I added a large, coarse mesh over the entire building complex:
```
&MESH ID='MESH WH5', IJK=40,20,10, XB=-50,350,-50,150,0,100, MPI_PROCESS=9/
```
Make sure that this mesh is added to the input file after all the other meshes. (2) I removed all the `OPEN` `VENT`s and replaced with
```
&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /
```
Then I ran the case with 10 rather than 9 MPI processes. As of this morning, the case has run out 275 s and is still going. The original case died in 2 s. This extra mesh allows a coarse wind field to form over a coarse rendition of your geometry. This coarse flow field serves as a boundary condition for the finer meshes. It serves no other purpose, and whatever is going on inside that coarse mesh is ignored by the fine. The fine meshes only use information from the coarse at their exterior boundaries.

A few other suggestions:
1. To see the flow better, do not use `VECTOR=T` and `CELL_CENTERED=T` on the same `SLCF` line. These two things together are used mostly for detailed diagnostics. They don't present a "natural" looking field. 
2. In Smokeview, hit the "q" button to remove the crude rendering of the building from the coarse mesh.
3. When looking at slices or 3D smoke, remove (via show/hide) the last mesh.

**Comment by PavloNike** [comment]
Thanks a lot @mcgratta and @rmcdermo, I didn't know that mesh within mesh works in FDS. I will try to add your inputs but it will be a learning thing for me as I prepare input files in pyrosim, not writing it myself.

I think I actually resolved the issue. I added pressure slices and noticed that pressure and wind velocity is very high due to L shape of my model. I have changed it keeping 0.5 step for area of fire and main measurements and larger size for other building parts and external areas. It is now 1000s after 2 days of running and interim results look very natural, no wind speed inside the building and stable outside.
![PRS](https://github.com/firemodels/fds/assets/153265370/f6d2386f-41b6-417f-ba65-ceeab6c54914)
![SMV](https://github.com/firemodels/fds/assets/153265370/edf27f56-f711-4722-8842-10b0401a7447)

**Comment by mcgratta** [comment]
Putting a single coarse mesh over the entire scene doesn't always work, and sometimes it can lead to spurious results because FDS still computes everything on the coarse grid as it does on the fine. So you get a very crude rendering of things outside the fine mesh. Your case, on the other hand, is still running using the big, coarse grid approach. But I would go with your approach if you have the computing power. You do not need to worry about the coarse-fine interaction. 

I'll close the issue. Re-open if something new pops up.
