### ISSUE TITLE
ERROR: N_CELLS_MAX should be at least    25 for surface NAPPE

### ISSUE THREAD

**Issue by Carofaj** [firemodels/fds#12463]
**Describe the bug**
I am triying to simulate using "FDS-6.8.0-0-g886e009-release" a diesel fire. The error that I found is :
ERROR: N_CELLS_MAX should be at least    25 for surface NAPPE (MPI Process: 0, CHID: FODR2)
ERROR: FDS was improperly set-up - FDS stopped (CHID: FODR2)
[FODR2_git.txt](https://github.com/firemodels/fds/files/14240441/FODR2_git.txt)

**To Reproduce**

**Expected behavior**
To verify if the code for a diesel fire is well-defined or not and to solve the error problem related to "N_CELLS_MAX"
**Screenshots**

**Desktop (please complete the following information):**
 - Version: [e.g. 22]

**Additional context**

**Comment by Carofaj** [comment]
[FODR2.txt](https://github.com/firemodels/fds/files/14240501/FODR2.txt)

**Comment by rmcdermo** [comment]
What version of the code are you using?  This runs for me after I fix the DUMP line (NFRAMES is an integer).

**Comment by Carofaj** [comment]
I am using "FDS-6.8.0-0-g886e009-release"

**Comment by Carofaj** [comment]
How did you fix the DUMP line ?

**Comment by rmcdermo** [comment]
NFRAMES=90

**Comment by rmcdermo** [comment]
Try the nightly build from [here](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST)

**Comment by drjfloyd** [comment]
Windows lets you get away with a real number in an integer namelist field.  It just does an implict INT().

This died for me at ~ timestep 2200 with the release version with the N_CELLS_MAX error. This error is in wall.f90 as we adjust noding due to mass loss from pyrolysis.  Given the inputs are all constant properties, this shouldn't be happening.

**Comment by Carofaj** [comment]
It is exactly the same output for me. So, What should I do for fix the problem ?

**Comment by Carofaj** [comment]
Thank you for your prompt reply! 
I tried setting STRETCH_FACTOR=1, but then I got a different problem : ERROR: Numerical Instability - FDS stopped (CHID: FODR2). Then, I included the MW as it is mentioned in “12.1.3 User-Defined Gas and Liquid Properties” from the User Guide. 
I'm running it now, but the simulation is taking more time than usual. 

Did you get any results with the nightly build version ?

**Comment by drjfloyd** [comment]
I think the root cause is your REAC. You have a high molecular weight fuel without any properties defined on SPEC. As noted in the User's Guide, the assumptions FDS makes for undefined properties do not work well for high MW species.  I changed your REAC to use FUEL='DODECANE' and removed the C and H.  DODECANE is a predefined species (so it has a full set of properties) that is C12H24. This is a similar molecular weight and a similar C:H ratio. Running with FDS 6.8 without STRETCH_FACTOR=1 and this has made it out over 105 s without errors.
