### ISSUE TITLE
Help understanding error message

### ISSUE THREAD

**Issue by JulietteFranque** [firemodels/fds#12506]
Hi all,
While running a simulation on a Linux cluster (1 node used, 96 mpi processes), after running for a while the simulation failed and the message below was displayed. Could you help me understand if this is an issue with the simulation, or with the computer? (not enough memory? limit imposed somewhere?). 
Thank you.

```[c307-006:1649352:0:1649352] Caught signal 11 (Segmentation fault: address not mapped to object at address 0xfffffffc0ba072c0)
==== backtrace (tid:1649352) ====
 0 0x0000000000012ce0 __funlockfile()  :0
 1 0x0000000006daf580 divgdivergence_part_1_mp_enthalpy_advection_()  ???:0
 2 0x0000000006d9f134 divg_mp_divergence_part_1_()  ???:0
 3 0x0000000006ab5af4 MAIN__()  ???:0
 4 0x000000000040a71d main()  ???:0
 5 0x000000000003acf3 __libc_start_main()  ???:0
 6 0x000000000040a636 _start()  ???:0
=================================
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libpthread-2.28.s  0000154C29476CE0  Unknown               Unknown  Unknown
fds                0000000006DAF580  Unknown               Unknown  Unknown
fds                0000000006D9F134  Unknown               Unknown  Unknown
fds                0000000006AB5AF4  Unknown               Unknown  Unknown
fds                000000000040A71D  Unknown               Unknown  Unknown
libc-2.28.so	   0000154C2722DCF3  __libc_start_main     Unknown  Unknown
fds                000000000040A636  Unknown               Unknown  Unknown


```

**Comment by marcosvanella** [comment]
Hi Juliette, can you post the input file and state at about how many time steps you get this segfault?

**Comment by JulietteFranque** [comment]
Sorry, but I am not allowed to share the input file... would anything else help? I am releasing gas at a high mass flux (9 kg/m2s) intermittently in my simulation, which I thought may be the issue. 
This is when it happens:
`` `Time Step: 222500, Simulation Time:    816.26 s```

**Comment by marcosvanella** [comment]
I can't tell you much without knowing what the problem is about. I would check that velocities are not reaching ridiculous number as the gas is released. I assume you use a ramp, see about making the ramp less pronounced if needed.

**Comment by JulietteFranque** [comment]
Makes sense, sorry about that. Do you suggest using slices to see velocities? Or is there an output somewhere that would give me the maximum velocity in the simulation?
I am actually not using a ramp - it goes from 0 to 9 with TAU_MF=0 (based on a controlled activation). Maybe using a ramp to gradually increase it or having TAU_MF=1 or so could help...?

**Comment by rmcdermo** [comment]
Please do a hand calculation to estimate the velocity of the vent.  Assume an ideal gas at the vent outlet temperature (20 C unless otherwise specified).

**Comment by drjfloyd** [comment]
Large step changes in velocity over a single timestep can cause issues.  Having some short ramp or TAU_MF might resolve the problem.

Another possiblity: Are you using a predefined gas or a SPEC you have defined for the mass flow?  If a predefined gas (or mixture of predefined gases) can you share the gas(es) being used? If so, we can look to make sure we didn't err in defining the properties in the source. If a custom SPEC, have you defined thermophysical properties for it rather than using the default FDS behavior for a non-predefined species?

**Comment by drjfloyd** [comment]
SPEC probably isn't the issue then. Those are commonly used and if one had a problem I suspect we would have seen it by now. But I will check to make sure.

**Comment by johodges** [comment]
Do you have diagnostic information in the out file? If so that will tell you if the pressure or velocity is getting unstable. It will not be output by default with 96 meshes. If you can run the model again some suggestions to help debug:

1. You can set &DUMP SUPPRESS_DIAGNOSTICS=F / to force FDS to output the diagnostic info.
2. Add a boundary output for VELOCITY_ERROR so you can see if you have mesh errors propagating

It sounds like you are trying to simulate a thermal runaway event. We see a lot of crashes modeling these scenarios in FDS mainly due to pressure zone issues relating from importing complex geometries. One way we help troubleshoot these is output a 3-D slice of PRESSURE_ZONE, set DT_SL3D=0.001, and run 1 time step. That way you can check to make sure that all the gas phase cells are in the pressure zone that you expect.

**Comment by drjfloyd** [comment]
nothing looks amiss with the properties FDS is reporting for those species.

**Comment by JulietteFranque** [comment]
Thanks for reporting back and thanks for everyone's input. Sounds like I need to check pressure/velocities.
