### ISSUE TITLE
Some problem to Verification and Validation cases

### ISSUE THREAD

**Issue by lihy213** [firemodels/fds#12578]
Dear contributors,

Recently, I've learned FDS procedure and have run some verification and validation cases, some obstacles encountered to me, for **./Verification/Adaptive_Mesh_Refinement/ns2d_16_emb_1to1_refinement.fds**, in line8 _"&MESH IJK=8,1,8, XB=1.57079632679490,4.71238898038469,-0.05,0.05,1.57079632679490,4.71238898038469, LEVEL =1/"_, the error occurred when I ran it. It seems to be caused by the parameter "LEVEL=1". So what is the reason for that, and how could I solve it?

Kind regards,
Li

**Comment by drjfloyd** [comment]
That is an old case that is not currently part of the active verification suite. It was from a development effort from a decade ago that did not continue.

@rmcdermo should this case be removed from the repo?

**Comment by rmcdermo** [comment]
Good catch.  `LEVEL` is not valid anymore.  We keep these cases around because we have always dreamed of having a clean way to have embedded meshes.  But if you run the two demos (update your repo, LEVEL will be removed, or just delete that parameter) and you will see that the 1:1 refinement case works nicely, whereas the 1:2 case quickly gives garbage for the interior mesh.

The reason I'd like to keep the cases for now, is that I think it would be a simple thing to use a linear interpolation for the boundary pressure for the internal mesh (as opposed to direct injection of the coarse mesh values, which has a discontinuity).

**Comment by lihy213** [comment]
THANKS!I got it!
