### ISSUE TITLE
FDS compile fails if SUNDIALS library is not installed

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#13017]
Let's configure the make file and make_fds.sh scripts to gracefully ignore SUNDIALS if it has not been installed on a user's system.

**Comment by cxp484** [comment]
Marcos and I have added the --DWITH_SUNDIALS directive during compilation. This flag is available if the SUNDIALS_HOME environment variable is set. When available, the code will compile with SUNDIALS support; otherwise, it will not. If the code is compiled without SUNDIALS and the user specifies CVODE as the ODE solver in COMB, they will receive the error message: 'ERROR: requesting CVODE_SOLVER, Sundials not installed.'

I'm keeping this issue open as I've tested the flag on Windows and Linux using Intel compilers. The GNU compilation targets still need to be verified in the Build/makefile, which I'll do before closing the issue.
