### ISSUE TITLE
Obstructed VENT 

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#13010]
FDS sometimes gives error when it can't define the VENT orientation. In some of these cases VENTs are placed in an OBST or obstructed by an OBST on the face. I had a similar case and FDS did not give any error. I noticed the issue when I had unrealistic pressure in the compartment. I post the simplified case below where the VENT is obstructed but FDS does not give any error. 

Would it be possible for FDS to catch these cases?
Thanks.

tested on FDS v6.9.1, windows 11 and Linux. 

```
&HEAD CHID='untitled'/
&TIME T_END=2.0/ 

&MESH ID='MESH_019', IJK=30,16,24, XB=8.1,11.1,49.3,50.9,15.2,17.6,  /
&MESH ID='MESH_022', IJK=22,26,30, XB=8.1,10.3,50.9,53.5,15.2,18.2,  /


&OBST ID='OBST_stairs01_open', XB=8.2,8.3,50.9,51.1,15.2,17.2/ 
&OBST ID='Obstruction', XB=8.1,8.3,50.7,50.9,15.2,17.6/ 
&OBST ID='Obstruction', XB=8.3,9.2,50.7,50.9,15.2,17.6/ 
&OBST ID='Obstruction', XB=9.2,11.1,50.7,50.9,15.2,17.6/ 

&VENT ID='node1', SURF_ID='INERT', XB=8.2,8.3,50.7,50.7,15.3,16.2, COLOR='OLIVE DRAB'/ 
&VENT ID='node2', SURF_ID='INERT', XB=8.2,8.3,50.9,50.9,15.3,16.2, COLOR='OLIVE DRAB'/ 

&HVAC ID='sidelow01', TYPE_ID='LEAK', VENT_ID='node1', VENT2_ID='node2', AREA=2.58199E-4, LEAK_ENTHALPY=.TRUE./


&TAIL /

```

**Comment by mcgratta** [comment]
It is possible to check for hidden `VENT`s but I'd rather not. There are many potential problems with this because `VENT`s are not explicitly parsed by FDS. Rather, exterior and interior surface cells are assigned properties, and if a `VENT` happens to fall on one, that `VENT`'s properties are substituted for the default. But FDS doesn't check to see if the `VENT` is "touched". It doesn't care if a `VENT` is blocked. That is, if a `VENT` is never used, there is nothing that can cause a segmentation fault or array out-of-bounds or similar. 

This seems like something better suited for a graphical user interface like PyroSim. We typically only add `ERROR` statements for inputs that can cause a crash without any understandable error message.

**Comment by Er9y714** [comment]
I understand. Thank you for the evaluation.
