### ISSUE TITLE
Grid alignment problem

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13224]
In `read.f90`, the line below causes a mesh alignment error in the `LNG_Dispersion` `Falcon` cases.
```
   M%CELLSK_LO=-NIPZS
   M%CELLSK_HI=NIPZ+NIPZF
   DO K=M%CELLSK_LO,M%CELLSK_HI
      M%CELLSK(K) = GINV(REAL(K,EB)/M%RDZINT,3,NM)*M%RDZETA
      IF(MOD(K,500)==0) M%CELLSK(K) = REAL(NINT(M%CELLSK(K)),EB)   <--------
      M%CELLSK(K) = MAX(M%CELLSK(K),-0.9_EB)
      M%CELLSK(K) = MIN(M%CELLSK(K),REAL(M%KBAR)+0.9_EB)
   ENDDO
```
I understand the intent of this, but I don't think it works as intended. The physical coordinate z is divided into small uniformly-spaced subdivisions indexed by `K`, but there are differing numbers of subdivisions corresponding to each grid cell, hence the `MOD` function is not going to work to stop small errors in the determination of the index of the grid cell. If you print out the values of `CELLSK` for a `Falcon` case, you will see what I mean. I don't have a way at the moment of ensuring a perfect correspondence between physical and numerical coordinate index. My only thought has been to increase the number of subdivisions.

Jason -- I've assigned this to you, but if you did not add this line, push it back to me. The "blame" function in GitHub does not work with the large `read.f90` file.

**Comment by ericvmueller** [comment]
That was me, if I recall. 

There was an issue with precision errors in comparing `XB` bounds to cell extents for particle insertion (in the `GET_IJK` function). Not a big deal for one or a few `INIT` lines. But when building up voxelized vegetation for the large cases we are running you can end up with significantly more particles than intended because of the many `XB` regions, some of which 'leak' into adjacent cells due to the slight mismatch.

Not sure if that makes sense but perhaps we can discuss if there is a better solution tomorrow.

**Comment by ericvmueller** [comment]
Here's the original demonstration of the issue 
https://github.com/firemodels/fds/issues/12673

I'm considering other ways to deal with it

**Comment by ericvmueller** [comment]
Replacing with something like this catches the mismatches in my example case:

```IF(ABS(M%CELLSI(I)-REAL(NINT(M%CELLSI(I)),EB)) < 1.E-14_EB) M%CELLSI(I) = REAL(NINT(M%CELLSI(I)),EB)```

but I'm not sure how robust that threshold is ...its just based on the deltas I see in that example

**Comment by mcgratta** [comment]
Let me try it on my case.

**Comment by mcgratta** [comment]
OK, that appears to work. Thanks.
