### ISSUE TITLE
Too many MPI processes assigned to this job BUT there isnt too many meshes?

### ISSUE THREAD

**Issue by Mikkelmhfire** [firemodels/fds#13269]
**Describe the bug**
First of all im not even sure if this is a bug, or just me being blind to something. I've have used fds many times for the same purpose but never run into this before.

I have a simpel model with 11 meshes, and therefor i uses fds_local -o 1 -p 11 FILENAME. However when i uses this command it replies errormessage saying that there is too many MPI processes assigned for the job: ERROR(122): Too many MPI processes have been assigned to this job.

Then i just tried with -o 1 -p 8 which apparently works somehow. Im still waiting for results to see if all meshes are calculated. But why does it say this errormessage when i actually have 11 meshes?

**Desktop (please complete the following information):**
64-bit windows 10 pro version 22h2

I cant add the fds file...

**Comment by drjfloyd** [comment]
If you use less processes then meshes, any extra meshes just get assigned
to the last process. Change the file extension to .txt. then you can attach
it. We would need to see your input.

**Comment by Mikkelmhfire** [comment]
Thanks. Here is the file attached.
[Grundmodel_B1.txt.zip](https://github.com/user-attachments/files/16486851/Grundmodel_B1.txt.zip)

**Comment by drjfloyd** [comment]
You have told FDS to only use 8 MPI processes via MPI_PROCESS, so -p 8 will work as the is the number of process you have asked for but -p 11 does not because that is 3 more than what you have told FDS to use.

&MESH ID='MESH01-02-01-02', IJK=96,94,68, XB=207.3,221.7,84.6,98.7,0.0,10.2, MPI_PROCESS=0/
&MESH ID='MESH01-03-01-01', IJK=114,96,34, XB=221.7,255.9,76.5,105.3,7.21645E-16,10.2, MPI_PROCESS=1/
&MESH ID='MESH01-03-01-02-02', IJK=82,96,34, XB=182.7,207.3,76.5,105.3,-2.164935E-15,10.2, MPI_PROCESS=2/
&MESH ID='MESH01-03-02-02', IJK=214,51,17, XB=217.5,345.9,105.3,135.9,-2.164935E-15,10.2, MPI_PROCESS=3/
&MESH ID='MESH01-03-02-01', IJK=200,51,17, XB=97.5,217.5,105.3,135.9,-2.164935E-15,10.2, MPI_PROCESS=4/
&MESH ID='MESH01-02-01-03', IJK=48,22,34, XB=207.3,221.7,98.7,105.3,7.21645E-16,10.2, MPI_PROCESS=5/
&MESH ID='MESH01-01-01-01', IJK=152,48,17, XB=6.9,98.1,76.5,105.3,-7.21645E-16,10.2, MPI_PROCESS=5/
&MESH ID='MESH01-02-01-01', IJK=48,27,34, XB=207.3,221.7,76.5,84.6,7.21645E-16,10.2, MPI_PROCESS=6/
&MESH ID='MESH01-03-01-03-02', IJK=150,48,17, XB=255.9,345.9,76.5,105.3,-1.44329E-15,10.2, MPI_PROCESS=6/
&MESH ID='MESH01-03-01-03-01', IJK=165,16,17, XB=246.9,345.9,66.9,76.5,-1.44329E-15,10.2, MPI_PROCESS=7/
&MESH ID='MESH01-03-01-02-01', IJK=141,48,17, XB=98.1,182.7,76.5,105.3,-2.164935E-15,10.2, MPI_PROCESS=7/

**Comment by Mikkelmhfire** [comment]
Thanks drfloyd. Poor mistake from my side... Im just used to every MPI proces having its own mesh. Any idea why more meshes are given to a singe MPI proces? 

Either way thanks a lot!

**Comment by drjfloyd** [comment]
It is what you asked for when you made your MESH lines. See MPI_PROCESS in the User's Guide

**Comment by Mikkelmhfire** [comment]
Thanks. I just checked Pyrosim and it happens to be the "export scenarios" which automatically gives more meshes a single MPI proces. Im not sure how to avoid this other than export the FDS scenarios one by one.

**Comment by drjfloyd** [comment]
For Pyrosim support contact Thunderhead Engineering
