### ISSUE TITLE
Odd HRR behavior from "NIST_NRC_Transient_Combustibles" validation files.

### ISSUE THREAD

**Issue by donish-getstand** [firemodels/fds#13400]
I am running the [https://github.com/firemodels/fds/blob/dadf911fa65b7ab2aafa225aad6f6aafaeee386c/Validation/NIST_NRC_Transient_Combustibles/FDS_Input_Files/pallet_1x1x2.fds](url) validation file and when I check the intermitten results (see attached plot) I can see that the HRR curve does not match the results published in the FDS Validation guide (fig. 14.24); the HRR peak is ~30kW whereas the published results give ~250kW, and the reaction/combustion reaches a null state at the ~7min mark which is far before the FDS validation guide (~25 mins). I have attached a few of the output files for this simulation. Any ideas on what could be going on here? Thanks in advance!
<img width="886" alt="image" src="https://github.com/user-attachments/assets/9516eaf2-a78a-411e-9968-9db404b15f0c">

[log.txt](https://github.com/user-attachments/files/16901421/log.txt)
[pallet_1x1x2_cat_hrr.csv](https://github.com/user-attachments/files/16901422/pallet_1x1x2_cat_hrr.csv)
[pallet_1x1x2_cat_steps.csv](https://github.com/user-attachments/files/16901423/pallet_1x1x2_cat_steps.csv)

**Comment by mcgratta** [comment]
These cases are fragile, meaning that they are very sensitive to the input values and input assumptions. Between the original results and the latest results, any number of seemingly minor changes in the way pyrolysis, heat conduction, convection, etc, is handled has changed these results. In any case, the original results also did not match the experiment particularly well, which should indicate to the reader that this method is not robust and should be used with caution. We chose to publish all the results, good and bad, to show how well the model is doing, or not doing, in this case. If you are interested, these cases might be something for you to look at and improve. In the meantime, I can look to see what changed between the old results and new, but I recall that modeling these pallets was more challenging than the cribs and boxes because the make up of a pallet is less "regular" or "uniform" than a crib or box filled with crinkle paper. That is, the assumptions that appear to work reasonably well with a crib or filled box do not work as well for a pallet. The big assumption for all of these cases is that these complex combustibles can be approximated with a uniform array of "particles" with a nominal shape, thickness, and material composition. For a crib, this is decent assumption because of its lattice structure. The pallet is more complicated.

**Comment by donish-getstand** [comment]
Thanks for the feedback Kevin! Very interesting notes about the sensitivity to input values and the overall complexity of modeling  the pallets (relative to cribs and boxes). The variability in pallet structure indeed presents a unique challenge that likely complicates the uniform particle approximation. I would be interested in examining these cases further to identify potential improvements and better understand the impact of different assumptions on the results.

**Comment by mcgratta** [comment]
You've got yourself a project ...
