### ISSUE TITLE
Extreme pressure rise/oscillations in a tunnel fire simulation 

### ISSUE THREAD

**Issue by ThijsH24** [firemodels/fds#13473]
When running a simulation of a tunnel fire in FDS, the pressure output shows large oscillating values. These oscillations are caused by the fire inside the tunnel. What is the origin of these pressure oscillations? I don't think they are physical. It seems like the perturbations in pressure/density/temperature close to the fire, transfer immediately across the whole domain of the tunnel (low Mach-number approximation?). All the other quantities seem fine, only the pressure gives strange results. How can I fix these pressure oscillations, and can I assume that the other quantities are not affected by these large oscillations?

I added two graphs.
Pressure profile: pressure measured in devices along the length of the tunnel at a specific time.
Pressure time: pressure measured in a single device (XYZ = 100,8,2) over time.

Case: [FDS_inputfile.txt](https://github.com/user-attachments/files/17130707/FDS_inputfile.txt)
400 m, 14.6 m , 6 m long/wide/high tunnel. 
100 MW fire at 200m. (900 HRRPUA) (Develops linearly from T=5 to T=15)
-3.5 m/s inflow at the inlet. (Develops linearly from T=0 to T=5)
Open boundary at the outlet.
Tunnel preconditioner = True
Device data: &DEVC ID='P-00', XYZ="(0m-400m)",8.0,2.0,TIME_AVERAGED=.FALSE., QUANTITY='PRESSURE' /

![Pressure_profile](https://github.com/user-attachments/assets/892fb091-a477-400b-8c68-af9f6b3a92d7)
![Pressure_time](https://github.com/user-attachments/assets/887f2d44-19f8-49f5-a912-509960259767)
![Tunnel_smv](https://github.com/user-attachments/assets/aafe36a4-5a9b-49d0-ad60-8d9da2b734dd)

**Comment by rmcdermo** [comment]
> What is the origin of these pressure oscillations? I don't think they are physical. It seems like the perturbations in pressure/density/temperature close to the fire, transfer immediately across the whole domain of the tunnel (low Mach-number approximation?)

Yes, this is how a low-Mach flow solver works, pressure perturbations are communicated instantly to every part of the domain.  In your case, if these mini explosions from the fire plume are not physical, then I suspect it is a grid resolution issue with the plume.  You might try SUPPRESSION=F to minimize unburned fuel that then meets pockets of fresh air.  But if that does not work, and if you cannot improve resolution, then you might be in a position where you need to just specify a constant volume of HRRPUV with an INIT line.

**Comment by mcgratta** [comment]
I will run the case with the latest source code.

**Comment by mcgratta** [comment]
This is a bug in the printout. Briefly, when you invoke `TUNNEL_PRECONDITIONER`, the "background" tunnel pressure is taken as a function of x, the coordinate direction along the length of the tunnel. This background pressure is solved for using a 1-D pressure solver. Your output pressure profiles still contain the background pressure field, even though this is not what one would actually measure in the actual tunnel. This background pressure is a result of the low Mach assumption. In a sense, instead of having pressure waves propagate up and down the length of the tunnel, there is this background pressure field that responds to changes in fire HRR, pulsations, etc. Long story short, here is what the pressure field should look like in your case

![image](https://github.com/user-attachments/assets/403ed126-0c4a-4b81-abf2-4d07da629b98)

I'll adjust the output `PRESSURE` to represent only the actual pressure field as one would measure rather than the actual + background.

**Comment by ThijsH24** [comment]
Got it, thank you! The 'actual pressure' is then relative to ambient pressure? Is this problem already solved for in the latest release FDS-6.9.1?

**Comment by mcgratta** [comment]
No not yet. I need to adjust the outputs.

**Comment by mcgratta** [comment]
I am finding it difficult to separate the pressure fields. For now, you should not use `TIME_AVERAGED=F` on the `DEVC` line. FDS will then average the pressure field over `DT_DEVC` seconds. You can also either increase `DT_DEVC` or time-average multiple rows in the `_devc.csv` file. I find that it takes 10s of seconds to get a reasonable time-averaged pressure profile.

**Comment by mcgratta** [comment]
This is your pressure profile averaged over 50 s, from 20 to 70 s. I suggest that you try various time intervals to ensure that the averaged profiles do not change.

![image](https://github.com/user-attachments/assets/5726a7be-67d3-4ac6-b8ea-35a56f6be435)

**Comment by ThijsH24** [comment]
Thanks a lot!
