### ISSUE TITLE
PDPA only samples the very small droplets

### ISSUE THREAD

**Issue by bphusted** [firemodels/fds#13577]
**Describe the bug**
I have defined a spray using the Rosin-Rammler-lognormal distribution, where the droplet size varies between 1µm to about 400µm.
Turning the particle diameter on in smokeview shows that the droplet varies from about 0.2µm to about 220µm, which is expected.

My PDPA device using D30 (M=3, N=0, mean volume droplet diameter) shows that the only droplets recorded are around 10µm. No droplets above 25µm are recorded, although I can see the droplets passing through the measurement volume in Smokeview.

**To Reproduce**
1. Run the attached file:  
[single_nozzle_turbulent_dis.zip](https://github.com/user-attachments/files/17362907/single_nozzle_turbulent_dis.zip)
2. Open smokeview, load particles - > show/hide/particles/particle diameter. This will produce a similar figure as below, showing a relatively large variation in droplet size 
![single_nozzle_turbulent_dis_0000](https://github.com/user-attachments/assets/dae18c10-d16f-4dd6-a510-0d9057a13cc2)
4. Open the hist.csv file
[single_nozzle_turbulent_dis_hist.csv](https://github.com/user-attachments/files/17362931/single_nozzle_turbulent_dis_hist.csv)

**Expected behavior**
I would have expected that the droplet size would vary from 1µm to 300µm, but only droplets around 10µm are recorded.

**Screenshots**
![image](https://github.com/user-attachments/assets/222f9f3a-8cb6-4315-bca6-f978cced785d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: [FDS 6.9.1]  also tried it with earlier versions, down to 6.7.3, but got the same result.

**Additional context**

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
I assume you want a distribution of the droplet mass or volume, which is why you have specified `PDPA_M=3`. There are two problems:
1. The `HISTOGRAM_LIMITS` are expressed as D, not D^3, and the values of D^3 fall only into the first bin.
2. Even if you were to express the `HISTOGRAM_LIMITS` as the lower and upper diameter to the power of 3, FDS automatically multiplies these numbers by 1E6 to convert the value in micrometers to meters. More importantly, the new range of D^3 would be evenly divided by 30 to given you very skewed bin sizes. 
I notice that we have no examples where `PDPA_M` is a value other than one. I'll put something together. For the moment, I think you can only get a distribution of D, not D^3.

**Comment by mcgratta** [comment]
I think you need this
```
&PROP ID='ROSIN-RAMMLER-LOGNORMAL_D30',
	PART_ID='water-drops_wm-7.1_9.9',
	QUANTITY='DIAMETER',
	PDPA_RADIUS=0.2,
	PDPA_START=3.0,
	PDPA_M=1,
	PDPA_N=3,
	HISTOGRAM=T,
	HISTOGRAM_NBINS=30,
	HISTOGRAM_CUMULATIVE=.FALSE.,
	HISTOGRAM_NORMALIZE=.TRUE.,
	HISTOGRAM_LIMITS=1.0E-6,500.0E-6 /
```
Note that `PDPA_M=1` and `PDPA_N=3`. The User's Guide mentions this, but it is not too clear. I'll try to make it cleare.

**Comment by mcgratta** [comment]
Did my answer solve the problem?

**Comment by bphusted** [comment]
Thanks. I am still working on it.

**Comment by mcgratta** [comment]
I'll assume that this is fixed. If not, reopen the issue or start a new one.
