### ISSUE TITLE
Wall temperature colors missing on several surfaces

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#13602]
In the enclosed case I would like to trace the wall temperature with the instruction &BNDF QUANTITY='WALL TEMPERATURE' /. All surfaces are colored if I use Mesh 1 and 2. With 4 meshes there are several faces with no colors. Is this a bug or am I doing something wrong ? 

FDS-6.9.1-1028-g111b7fa-nightly
[Eger.txt](https://github.com/user-attachments/files/17451704/Eger.txt)
![BNDF colors](https://github.com/user-attachments/assets/309095f1-a63b-4d72-9f19-06ad462b0eb3)

**Comment by mcgratta** [comment]
We noticed this as well last week. We should have a fix posted this week.

**Comment by gforney** [comment]
I"m taking a look.  thanks for the test case

**Comment by mcgratta** [comment]
One of your meshes connects its top surface to both another mesh and the outside.  This wouldn't be a problem except fds sends the entire patch for this top surface to the output file. In order to draw this properly, smokeview would have to check every grid cell in the patch to determine whether it is connected to the outside or another mesh because we want to draw part of the patch connected to the outside but not draw the part that is connected to another mesh.  This would be very expensive for large cases.  

I think the right solution would be to either: 

1.  Split problem mesh so top surface of one mesh is connected to outside and top surface of other is connected to the other mesh.  This would require no programming changes in fds or smokeview.
2.  Change fds so that patches that are sent to smokeview are either connected to the outside or to a mesh - not both

I'll look into option 2.

**Comment by fidran** [comment]
This configuration gives me the same result
&MESH ID='Mesh-01', IJK=20,10,100, XB= 0.0,10.0,  0.0,5.0,  0.0,25.0, MPI_PROCESS=0 / 
&MESH ID='Mesh-03', IJK=12,10,12,  XB=-3.0, 0.0,  0.0,5.0,  0.0, 6.0, MPI_PROCESS=1 /
&MESH ID='Mesh-04', IJK= 8, 6,12,  XB= 6.0,10.0,  5.0,8.0,  0.0, 6.0, MPI_PROCESS=2 /

**Comment by mcgratta** [comment]
OK. I think there is a bug in smokeview. We'll fix it.

**Comment by mcgratta** [comment]
Glenn, try this new version of FDS. Each patch in the BNDF file should have an obstruction number and the mesh where that obstruction lives. These parameters are already passed in the preamble of the `BNDF` file, but we may not have been using them.

**Comment by gforney** [comment]
thanks - am taking a look

**Comment by mcgratta** [comment]
This should now be working in the nightly build of FDS/SMV. Try it and let us know if it works for you.

**Comment by fidran** [comment]
Almost perfect, but it did not like my roof with a smoke hatch

Revision : FDS-6.9.1-1101-gfe97f2c-nightly
![BNDF(2) colors](https://github.com/user-attachments/assets/8c59ecde-3e08-4647-a6d7-15fdcd1693ea)
[Eger(2).txt](https://github.com/user-attachments/files/17544554/Eger.2.txt)

**Comment by gforney** [comment]
I just pushed up some changes.  update your smv repo,  rebuild smokeview and see if the problem is still there

**Comment by fidran** [comment]
It is ok if I expand mesh 01 from 25.00 to 25.25m with revision : FDS-6.9.1-1101-gfe97f2c-nightly

**Comment by mcgratta** [comment]
Glenn -- is FDS output BNDF files that have the proper patches in this case?
