### ISSUE TITLE
SPREAD_RATE issue with T_BEGIN

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#13729]
I'm trying to use  a`SURF` that has a `SPREAD_RATE` but also a custom `RAMP` for hrr/mass. But it seems like the ramp ends up  using time relative to `T_BEGIN` rather than absolute.

As an example, I modified the `circular_burner.fds` case:
```
&TIME T_BEGIN=-2,T_END=20. /

&SURF ID='BURNER', MASS_FLUX(1)=0.02, SPEC_ID(1)='PROPANE', RAMP_MF='rmf' /

&RAMP ID='rmf', T=  2, F=    0.0 /
&RAMP ID='rmf', T= 2.1, F=  1.0 /
```

The burner activates at a different times if I set `T_BEGIN`. I would expect it to start at T=2 regardless.

![image](https://github.com/user-attachments/assets/46483fa3-36cb-4d9b-8e1d-c28baa006af6)

[circular_burner.txt](https://github.com/user-attachments/files/17682300/circular_burner.txt)

**Comment by rmcdermo** [comment]
This seems to be the relevant section in the user guide, though, it still does not make things crystal clear to me: "When a time-base RAMP is evaluated, the time used for the RAMP is the time since the item (e.g., VENT,
OBST, DEVC) using the RAMP became active. This means RAMPs use the **actual time** if the activation time of
the item using the RAMP is the same as T_BEGIN".  I am not sure what "actual time" is supposed to mean here.  Apparently, it means time since activation, which I guess is T_BEGIN for your case.  But "actual time" for me would mean the absolute value of T in the simulation.  Perhaps some rewording of this section is needed.

At any rate, we went round and round with thinking about modifying the ramp inputs in Issue #13234  and the accepted answer seems to be to use CTRLs to do anything that is different from what is coded up.

**Comment by ericvmueller** [comment]
Okay, I guess my confusion came from the exact meaning of the vent being 'active', but its just a lack of familiarity since I'm used to using RAMPs in the context of wind where things are absolute.

**Comment by drjfloyd** [comment]
I think I wrote that text back when devices were first added. This is what it is trying to say:

&SURF ID='MY SURF',HRRPUA=1000,RAMP_Q='MY RAMP'/
&RAMP ID='MY RAMP',T=0,F=0/
&RAMP ID='MY RAMP',T=10,F=10/

This vent is active at the start of the simulation (there is no CTRL_ID or DEVC_ID). T in the RAMP will be the simulation time.
&VENT XB=0,1,0,1,0,0,SURF_ID='MY SURF'/

This vent is not active until 10 s. T in the RAMP will be the current simulation time - 10.
&VENT XB=0,1,0,1,0,0,SURF_ID='MY SURF',DEVC_ID='MY DEVC'/
&DEVC ID='MY DEVC',QUANTITY='TIME',SETPOINT=10,XYZ=0,0,0/

**Comment by rmcdermo** [comment]
So I think in the guide we could say something like (instead of "actual time") we could say "the T in the time ramp is evaluated as the current simulation time minus the activation time" and somewhere add "unless otherwise controlled, a VENT will activate at T_BEGIN".  Do I have this right?

**Comment by drjfloyd** [comment]
That sounds right.
