### ISSUE TITLE
Mesh Misalignment when degrading resolution

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#13833]
**Describe the bug**
I am trying to implement mesh resolution degradation in both horizontal and vertical directions. I am getting mesh misalignment between meshes that are far from each other. I understand that the boundaries are not along a line, but my source must be placed along a boundary to avoid any influence of vortices around obstacles.

**To Reproduce**
[test.txt](https://github.com/user-attachments/files/18005945/test.txt)
This is the FDS file to reproduce the problem. I get mesh misalignment between the ones that are not next each other.  

**Expected behavior**
I only expected mesh misalignment to happen only to adjacent grid cells

**Desktop (please complete the following information):**
 - OS: iOS
 - Version: Sequoia

Could you please tell me how to get rid of this mesh misalignment.

Thanks in advance

**Comment by drjfloyd** [comment]
@kevin, this case has PERIODIC FLOW ONLY for the top of the domain but GROUND for the bottom.  While that isn't a correct input (not having it periodic on both faces) do we require that periodic vents have the same resolution? If so that isn't mentioned in the guide.  Also should we throw an error if one face is defined as PERIODIC but the opposite face is not?

**Comment by rmcdermo** [comment]
I think we can have different resolutions on PERIODIC boundaries because we treat these like any other INTERPOLATED bc.  We have a hook in the code called FISHPAK_BC=0 that will set true periodic boundaries for a single mesh case (uses a periodic matrix).  In that case the grid resolution should be the same at both ends.

The reason we did not throw an error for not having both ends being PERIODIC is that we had designed on making arbitrary VENT be periodic (recycling)... but like many things we have not gotten around to that.  I am fine with throwing an error.

**Comment by rakyuv** [comment]
Thank you @drjfloyd and @rmcdermo  for your inputs. My apologies. It is not supposed to be periodic at the top of the domain. I'll change it

**Comment by rakyuv** [comment]
When I change the boundary condition to OPEN for ZMAX, I don't have the error anymore.

**Comment by mcgratta** [comment]
I have never tested this. Given that a `PERIODIC` boundary is treated much like a boundary between meshes, and these meshes can have different resolutions,, I would expect your case to work. Try it for a simple scenario and let me know.

**Comment by rakyuv** [comment]
Thank you @mcgratta for your answer. As I mentioned previously, the corrected input '.fds' runs without any problem when I corrected ZMAX to OPEN. This is the latest corrected file
[test.txt](https://github.com/user-attachments/files/18010359/test.txt)

However it reaches Numerical Instablitiy quite fast (within 8 seconds of simulation). 

I understand that it is a large file and the error could come from multiple problems. At the moment, I'm starting with a simple file and increasing the complexity to see at what point it crashes. I will keep you posted about where it crashes exactly in a while.

**Comment by mcgratta** [comment]
I'll close this issue. If you can't solve the instability problem, start a new issue.
