### ISSUE TITLE
Error in visualization of 'fog' from WATER VAPOR_COND species.

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#13840]
**Describe the bug**

Following up from an earlier discussion about visualization of 'fog' or condensed WATER VAPOR in Smokeview.
There seems to be a rendering issue with the '3D Smoke' data when the max condensation level is reached.  The view goes to a transparent state in the center of the volume instead of staying opaque.

See part of this video starting at 4:28 https://youtu.be/x08sxhVE95U?feature=shared&t=268

**To Reproduce**

1. Run attached FDS file.
2. Open results in Smokeview
3. Load 3D Smoke > 'WATER VAPOR_COND DENSITY'

**Expected behavior**

View should stay at max level of opacity after the peak is reached until the end of the results data.

**Screenshots**

See Video above for example.

**Desktop (please complete the following information):**

 - OS: Windows
 - Version: 11

**Additional context**

[condensation.zip](https://github.com/user-attachments/files/18017971/condensation.zip)

For @gforney to take a look at and let me know if there is anything I can do differently to render this more accurately.

**Comment by gforney** [comment]
Ill take a look

**Comment by mcgratta** [comment]
Glenn -- do you think this an FDS or Smokeview issue?

**Comment by gforney** [comment]
should be fixed in smokeview posted here

https://github.com/gforney/test_bundles/releases/tag/SMOKEVIEW_TEST

or you can update your smv repo and build smokeview or you can download the nightly bundle at

https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST

after the next firebot pass .  

this was a smokeview not a oneapi problem.  an array used to map smoke opacities was not defined for the last position.  the bug only showed up for grid cells that were completely opaque - ie smoke alpha values of 255

@bwklein thanks for catching this.

**Comment by gforney** [comment]
bryan, I'm closing this.  If you still see a problem open it back up
