### ISSUE TITLE
Mesh out of alignment for meshes that is not adjacent to each other

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#13935]
**Describe the bug**
I have a simulation with multiple meshes containing multiple resolutions. I have a problem of mesh misalignment between meshes that aren't adjacent to each other. This happens when the lateral boundary conditions are "periodic flow only". However the moment, I change the lateral boundary conditions to "open", there is no problem of mesh misalignment. 

I have had similar problem in the past, and at that time I made a mistake of having the top of the domain to be "periodic flow only", which is not a realistic boundary condition given that the bottom of the domain is GROUND. Presently, I have "Periodic flow only" only in the lateral boundary conditions. 

**To Reproduce**
This is the [FDS input file](https://github.com/user-attachments/files/18218824/fdsMultiresolution.txt), that I used to run the simulation

**Expected behavior**
I would expect the mesh to be all aligned irrespective of whether the lateral boundaru condition is periodic or open

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: HPC

Any help would be greatly appreciated
Thanks in advance

**Comment by Er9y714** [comment]
A SURF with an ID of "PERIODIC FLOW ONLY"  is not defined. 

Also note that when you apply DB=XMIN, FDS will apply this to XMIN boundary of all meshes. Instead I would recommend applying VENTs manually (XB).

**Comment by rakyuv** [comment]
Thank you @Er9y714 for your answer. 

I wanted to have a periodic boundary conditions for wind field in the lateral direction without affecting the Methane getting recycled in the domain, therefore I used "PERIODIC FLOW ONLY" boundary conditions from Section 16.6 in FDS User guide. I have attached the screenshot which shows this boundary condition:

![Capture d’écran 2024-12-25 à 16 58 31](https://github.com/user-attachments/assets/645e6fde-9751-41bc-b840-9a9c9041cc16)

As for DB=XMIN, XMAX, YMIN, YMAX, I wanted the PERIODIC BOUNDARY FLOW only to all over the lateral boundaries. For particular vents to release methane, I am using XB for the VENT with SURF_ID='METHANE BLOWER'

I'd be happy to know what I could do to make the simulation work

Thanks in advance

**Comment by Er9y714** [comment]
Try creating VENTs at boundary locations where you would like to have Periodic. Build those VENTs with XB instead of DB.

**Comment by mcgratta** [comment]
The error message says that Mesh 38 is not aligned with Mesh 3. These two meshes do not "touch", but when you ask for periodic boundary, FDS is not going to make Mesh 38 and Mesh 3 exchange information. Look at the domain in Smokeview, position the scene so that you are looking in the minus z direction; that is, looking down. Hit "g" and "z" to see the mesh. Hit "Alt v" to render the projection isometric. Follow the plane x=x_min on Mesh 3 towards Mesh 38. You will see that the meshing violates the rule that says that a single grid cell of one mesh must not connect with more than one other mesh. That is, a single cell of Mesh 38 communicates with cells in Mesh 3 and Mesh 1.
