### ISSUE TITLE
agents avoiding flames

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#1475]
```
Please complete the following lines...

Application Version:5.5.3
SVN Revision Number:7031
Compile Date:Sept 2011
Operating System:Windows XP


in Evacuation, agents cross the "flames" area.
Would it be possible to add a feature/control variable focused at having the agents
avoid "flames" in FDS+Evac?



```

Original issue reported on code.google.com by `fabriziomagugliani@yahoo.com` on 2011-10-14 13:52:33

**Comment by gforney** [comment]
```
Timo will take a look at this.
```

Original issue reported on code.google.com by `mcgratta` on 2011-10-14 14:01:57

**Comment by gforney** [comment]
```
Well, at the present only the smoke is used to
change the target exit door of the agents. The
agents do not avoid "high smoke areas" or hot
areas. They just try to choose a door, where 
is no smoke or where is less smoke than in
some other door.

If you want that the agents do not walk in your
fire, add OBST with EVACUATION=.TRUE. so the 
agent do not walk on top of the fire. This is
at present the only option.

The feature that the agents avoid hot places is
on my to do list. So, I'll change this issue
as "Enhancement" type.

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2011-10-17 08:02:47
- **Labels added**: Type-Enhancement
- **Labels removed**: Type-Defect

**Comment by gforney** [comment]
```
Well, I have had no time to do anything for this enhancement yet, but this enhancement
should be added at some point, so I keep it open at the Issue Tracker.

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2012-08-15 07:51:49

**Comment by godisreal** [comment]
Excuse me, may I give some input regarding this issue?  I am trying to implement a model in evac.f90.  In the model hazards such as smoke or radiation will generate a kind of repulsion to evacuees so that evacuees will not easily go through the harzardous areas.  If the magtitude of repulsion is sufficiently large, it turns out that evacuees will avoid having contact with hazards like flames and it may actually provide a solution to this problem.  BTW, are flames equivalent to heat radiation?  In evac.f90 radiation is read in.

**Comment by tkorhon1** [comment]
Well, flames are easiest to model using radiation information. If radiation is too large in some evacuation grid cell, then the agent should not go there. One could try to change the motive force direction using the radiation information. So, if the guiding flow field towards the exit door is going toward a high radiation grid cell, see, if there is less radiation in some neighboring cell and turn the motive force to that direction. Or something like this. If there are not good directions towrads this door (say, in the front 180 degree section) => make the door choice algorithm once again, but without the current door (too much radiation) => see, if a better door is found.

When going towards a door, it might happen that an agent ends up in a dead end due to the fact that radiation blocks some grid cells (too much radiation). One should, perhaps, categorize the radiation cells in different categories, one should be: the agent can not use that grid cell (= there is a flame here and/or the radiation level is really high, say more than 25 kW/m2 so that clothes start to burn quite quickly).

One can not recalculate the guiding flow fields towards the exit doors easily during the simulation. These flow fields are calculated in the initialization phase and afterwards they can not be recalculated. So, there is no radiation information at the initialization phase. So, the change of the route should be dealt in some other means.

**Comment by godisreal** [comment]
Hi, Timo, Thank you for your comments.  
FYI. I tested the smoke repulsion, and it works out the problem roughly.  When smoke (SOOT_DENS) becomes thick, the replusion keeps agents away from the hazardous area.  If the smoke spreads faster than the movement speed of agents, it seems that agents are incapaciated.  In brief, more tests are needed, and I think this method is promising to be extended to heat radiation in the future.  
I agree with you that v0 and motive force should be recalculated with hazardous condition, and this issue is critially related to the door selection algorithm.  Your function See_door() does consider the smoke level, but sometimes agents still go to the doors with smoke.  This is unexpectedly useful in test of smoke repulsion, but how to integrate smoke or heat radiation into the door selection algorithm is of much importance.  Your guidance and suggestion are much appreciated.

**Comment by tkorhon1** [comment]
Well, the agents do not know how much there is some in the building elswhere. They just know what they see. 

One way to make the door selction better, when there is smoke:

"Visible doors" (= without smoke there is a line-of-sight): More or less like now, see how much there is smoke and choose the best one. If this is "too bad", check the non-visible doors (no line-of-sight), if there is a better direction found.

"Non-visible doors": See the direction of the guiding flow field towards this door at the current agent position. Go forward in this direction until you find an OBST (hit a wall). calculate the average smoke density along this path. Do the same for other non-visible doors. Pick the "less average smoke" non-visible door. Then, compare this to the best visible door to decide, which one to use.

Problems: An agent is in a corner => the flow field direction is leading to a wall very soon. Well, this is not a problem, the agent (if it picks this direction) will follow this flow field some time and it will not be in a corner anymore => next time the door selection is not this door anymore, because now the "follow the flow field direction" is not hitting a wall right away anymore => some more smoke is found if this direction is a bad direction (too much smoke).

**Comment by godisreal** [comment]
I tried to read SUBROUTINE Change_Target_Door(), and I am confused by PP_see_door.  
Sometimes it is computed by See_each_other() and sometimes it is computed by See_door().  See_door() takes smoke into account while See_each_other() does not.  So... what is your idea here?  I suppose that agents will change target door when they see smoke on the route.

**Comment by tkorhon1** [comment]
Well, these routines are badly named. I use the subroutine See_each_other to check a pair of points (x,y) if there is a bee-line connecting them. This is done without any smoke information, if I remember correctly. This was first used to see, if an agent can see another agent. So, I used it, for example, in the social force calculation to check if there is an OBST between the agents or not.

And the see_door is using smoke information. 

And one thing to note is that there are two meshes: One is for movement and one is for seeing.
So, you should always check, that which mesh information you are passing to the subroutines.
Well, this probably just is an issue for see_each_other. The see_door is, probably, always using
the visibility mesh. (I am not remembering now and I did not check the source code right now.)

TimoK

**Comment by godisreal** [comment]
Hi, Timo.  So the mesh for seeing contains the information about obstruction and smoke.  Is that right?  Also what is the mesh for movement?  I suppose agents move in a continuous 2D plane, and HR%X and HR%Y are not directly attached to any mesh.

**Comment by tkorhon1** [comment]
Yes, the agents have continuous (x,y).

The agents move in the mesh that is given in the .fds file: MESH with EVACUATION=.TRUE. etc.
The OBSTs that are in this mesh are obstacles for movement. See the FDS+Evac UG:
"Figure 34. A 2D evacuation mesh."

There the orange mesh is the one that is given on the evacuation MESH line. The light blue mesh is the visibility mesh that is automatically generated for this movement evacuation mesh. 

The UG (pages 72-73):

In addition to the user defined meshes, there is automatically generated visibility
meshes for each “main” evacuation mesh defined by the user. These meshes are
located horizontally exactly at the same place as the main evacuation mesh, but
the z range is different. The mid z level is at the position defined by the keyword
HUMAN_SMOKE_HEIGHT on (some) PERS namelist, the default is 1.6 m above
the floor level. And the keyword EVAC_DELTA_SEE also given on (some) PERS
namelist defines how much higher and lower are the zmax and zmin. The default
value is 0.29 m. By choosing “cleverly” the z-coordinates of the obstacles (and
holes) one is able to make these objects to show up in both the visibility and movement
(the “main evacuation meshes”) meshes or in one or in the other. These visibility
evacuation meshes have their ID set automatically and they are “Emesh_”ID,
where ID is the ID of the “main evacuation mesh”. So, one can also use the keyword
MESH_ID on the OBST and HOLE namelist to force the objects to go into
some specific mesh.

TimoK

**Comment by godisreal** [comment]
Hi, Timo, 
This is a pic of my testing result.  I add a kind of smoke force there so that agents cannot go through the area in thick smoke.  
![ex2018test-smokefed_0087](https://user-images.githubusercontent.com/13465534/52051109-872cfe00-258d-11e9-8a50-26fcc2674a4b.png)

**Comment by godisreal** [comment]
[color4Test.zip](https://github.com/firemodels/fds/files/2825259/color4Test.zip)

Hi, Timo, 
This is the render output.  Any commets?  Some TPRE features are also modified.  
I haven't extended the model to heat radiation.  I only use SOOT_DENS to calculate the force.  
FED file is directly read in, and it is only effective for the first 80 sec.  
Best Regards, 
Peng WANG

**Comment by godisreal** [comment]
Hi, Timo, do you have time to take a look at the programming code that I modified?  If so, I am glad to give a pull request to your repo first.

**Comment by tkorhon1** [comment]
Hi Peng,

I was two weeks away from the officel. I and my kids were ill (a common flu and some ear infections).
So, I did not have time to check your programming code. 

Actually, I did not find you programmin code. I checked the evac.f90 file from the firemodels/fds
and also tkorhon1/fds. Where did you put it?

Timo

**Comment by godisreal** [comment]
Hi, Timo.  Please keep fit and have a good rest.  I did not merge my coding work to firemodels/fds.  If you would like, maybe we can merge it in the future.  
Best Regards

**Comment by godisreal** [comment]
[EvacSOOT2019.pdf](https://github.com/firemodels/fds/files/3087758/EvacSOOT2019.pdf)

Hi, Timo.  Please read the document as attached.  The algorithm is presented and the code has been revised and tested.  Your comments are much welcome.

**Comment by tkorhon1** [comment]
Thanks! I just printed the pdf file and I'll have a look.

TimoK

**Comment by godisreal** [comment]
Hi, Timo, 
The smoke resistence consists of two components.  One is obtained from the gradient of SOOT_DENS, and the other one is a damping force that slows down agents in any directions in smoke areas.  In the testing results, it seems that the damping force is more effective in a general sense.  

This method can also be applied to TMP_G (Gas Temperature).  Previously I plan to use RADFLUX, but I am not sure about the physics meaning of RADFLUX in evac.f90.  So TMP_G is clear to me to characerize the heat effect on evacuees.  

I also think about how to incorperate hazard information into your door selection algorithm, and that's another important issue.  However, there are many test model in the code.  Your suggestions are much appreciated.

**Comment by tkorhon1** [comment]
Yes, the gas temperature (at head height about) is a clear quantity to use. The integrated radiant intensity would tell more or less the same information. It is high, when the temperature is high.

TimoK

**Comment by godisreal** [comment]
Hi, Timo, 
A major difference between smoke and gas temperature is that smoke is visible while gas temperature is not.  Agents may detect smoke far away and change their target doors before they get there.  In contrast the gas is not visible and agents cannot feel the temperature unless they get there.  
So I think that smoke gets involved with the visiability mesh while gas temperature does not.  
Your comments are much appreciated.

**Comment by tkorhon1** [comment]
Well, I save the fire information (co, soot, radflus, gas temp) at the visibility mesh z level. I think that the most important temperature is at the head height. You have just plain skin at your face and your face skin is sensitive to heat. You other body parts are covered with clothes (mostly). And you breath the air at your head level.

And you are right, that the gas temperature is a "local variable", so the agents just feels it at the current location. And the agent also remembers, so is the temperature is increasing or decreasing along the route that the agent has walked.

**Comment by gjaeger** [comment]
@tkorhon1 With PR #10089 we should/can close this issue.
