### ISSUE TITLE
Smokeview will not display model. 

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#1605]
```
Please complete the following lines...

Application Version: 5.6 & test version
SVN Revision Number:
Compile Date: 10.05.12
Operating System: Windows 7 64bit

Describe details of the issue below:
I have FDS and Pyrosim installed onto a desktop and laptop. On the desktop everything
runs fine but on my laptop Smokeview will not display the model. The labels can all
be seen and I can rotate the labels in the usual 3d motion but where you would expect
the model to be is a blank white screen. The timer for the model is in the corner of
the screen. I have also tried the new test version of SMV and the results are the same.

I have a fairly new laptop with an Nividia 520mx GPU alongside integrated graphics.


Paul Blake
```

Original issue reported on code.google.com by `pbaltorfire` on 2012-05-10 22:34:10

**Comment by gforney** [comment]
```
upload your .smv file and I'll take a look at it.
```

Original issue reported on code.google.com by `gforney` on 2012-05-11 12:41:52

**Comment by gforney** [comment]
```
can't debug without a .smv file that illustrates problem.  If you upload it I'll take
a look at it.
```

Original issue reported on code.google.com by `gforney` on 2012-06-02 03:04:17

**Comment by gforney** [comment]
```
I have exactly the same problem and i don't think that the problem takes place in the
.smv file.I tried to run the examples included in the FDS  and the same problem appears
.
operating system: windows 7 64bit
graphics: NVidia GeForce 630M

dimosthenis90@gmail.com
```

Original issue reported on code.google.com by `dimosthenis90` on 2012-11-05 19:16:35

**Comment by obscureed** [comment]
I experienced the issue of smokeview loading a model but showing only a white screen. The issues I had were about setting up graphics to display on a Windows machine, from applications running in Windows Subsystem for Linux (WSL2). (In my case, this is an Ubuntu installation, using the bash shell.) The issues I experienced are not relevant as FDS/SMV issues, but I thought it might be worth sharing some hints. This closed issue shows up on a Google search, so it seems as good a place as any to add these hints, without reopening the issue.

First, you need to make sure that WSL2 applications can display graphics.
• It is easier to troubleshoot this with a simple application, rather than smokeview. Try xeyes (after "sudo apt install x11-apps -y"), or install ImageMagick ("sudo apt install imagemagick") and display an image file.
• There is some talk of Windows running WSL2 Linux applications with native graphics; I have not pursued this far enough to make it work.
• I think you need to install on Windows an X-windows server service, such as Xming or VcXsrv. I went with VcXsrv.
• When it is running properly, you will set it going once. (You need to remember to restart it when Windows is rebooted.)
• When you are troubleshooting, you might find it useful to cancel the current service and restart a new one. To do this, run the command "taskkill /f /im vcxsrv.exe" in a Powershell terminal window.
• When you launch either Xming or VcXsrv, there are some important settings to adjust, in both cases from an application called Xlaunch: first "start no client", then untick "Native opengl" and tick "Disable access control". (As a mnemonic, I reverse *all* the default settings in that dialogue window.)
• You need to set the DISPLAY variable in bash. When everything is working, this will be a command in your .bashrc file. You might be familiar with a command such as "export DISPLAY=:0", but the consensus is that this is not enough for WSL2. You need something like "export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0" (or google for alternatives).
• The last remaining hurdle is that your firewall may stop the traffic between your Linux applications and your screen. If you have problems, try disabling your firewall for 15 minutes to see if this is the case. If so, obviously do not leave your firewall off; instead, create an exception that allows that specific traffic. My firewall is non-standard, so do a web search for advice on this.

OK, so now you can display a static image from your Linux terminal. Now you need to get the graphics card involved.
• You can probably run smokeview, but it will complain about not being able to use the graphics card -- something about CUDA version etc. (My experience is with an Nvidia graphics card; if your card is different, expect your experience to be different.) I think it would be a mistake at this stage to research, install and update CUDA versions.
• Again, do not use smokeview to troubleshoot your graphics card. Instead, install something like glxgears ("sudo apt install mesa-utils"). Run this from the Linux terminal window: you should see three cogs appear, they should rotate, and you get a FPS message in the terminal.
• You should probably update all your graphics drivers. (You have several -- who knew?) This sent me down a rabbit-hole of near-malware from a motherboard manufacturer, so it can be painful. It might be necessary.
• In a new Linux terminal, check you can still display static images. Run the command "export LIBGL_ALWAYS_INDIRECT=0" -- this will also end up in your ~/.bashrc. Try running glxgears.
• I encountered one issue with my machine, which (like the OP's) has both integrated graphics and a graphics card. You need to direct the setup to use your graphics card. The default behaviour is unlikely to be helpful. I think symptoms of a problem are that glxgears will run, and report a moderate framerate, but show either no image or a static image. You can see whether the graphics card is being used with "glxinfo | grep -i Device" -- you want to see the name of the card, not Intel UHD graphics, and not llvm. (See https://github.com/microsoft/wslg/wiki/GPU-selection-in-WSLg) Here is another command that I put in ~/.bashrc: "export MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA". (This is clearly advice for an Nvidia graphics card.)
• When you can display static images, and you can run glxgears, with the cogs rotating at a decent rate, then try smokeview. For me, it worked.
• I hope this helps. Unfortunately, I am not an expert in this and cannot help you if this advice does not work.

Now I have it working, FDS and smokeview in WSL2 is a good choice for me -- better than running either as a Windows application. For example, parallel execution with mpiexec works, and scripts that I have written for Linux machines work. Good luck!
