### ISSUE TITLE
Segmentation fault with pyrolysis and sprinkler

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2352]
```
SVN Revision Number: 22107

The attached case throws a segmentation fault at around 300 seconds. Running the same
case in debug mode yields a division by zero error at 199 s.

fds_intel_linux_6  0000000001ED9E06  wall_routinesspec        1005  wall.f90
fds_intel_linux_6  0000000001EC7FB5  wall_routines_mp_         841  wall.f90
fds_intel_linux_6  0000000001E6F895  wall_routines_mp_          46  wall.f90
fds_intel_linux_6  000000000251F175  MAIN__                    872  main.f90

```

Original issue reported on code.google.com by `jmvaari` on 2015-03-30 11:38:42

<hr>
- _Attachment: [SegFault.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2394/comment-0/SegFault.fds)_

**Comment by gforney** [comment]
```
Caveat that I haven't run the case yet but looking at the line with the error this means
the wall temperature has gone to zero.  In this case we have a low density and low
conductivity foam.  The droplet cooling is completely decoupled from the wall temperature
solution. I have a feeling the value we compute for droplet cooling, given the very
small thermal capacity of the first wall node, is removing too much heat. We probably
need to check for this in the droplet update.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-03-30 12:40:50

**Comment by gforney** [comment]
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `mcgratta` on 2015-03-30 12:47:03

**Comment by gforney** [comment]
```
Any clue as to why the debug crashes at a different time? Can we be sure it is the same
bug?
```

Original issue reported on code.google.com by `jmvaari` on 2015-03-30 13:42:44

**Comment by gforney** [comment]
```
Release and debug treat variable initialization and math error handling somewhat differently.
Debug also avoids inlining of functions and other optimization which can result in
slight changes values. In the case of a div by zero error it could be something as
simple as at t=199 release is getting the wall temperature to be 0.000000000001 but
debug is 0.0000000000000. No guarantee it is the same bug, but pretty good odds it
is.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-03-30 13:56:25

**Comment by gforney** [comment]
```
Issue 2467 has been merged into this issue.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-06-15 17:41:01

**Comment by gforney** [comment]
```
changing to accepted.  Comment #1 appears to be the issue.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-06-15 17:41:43

**Comment by gforney** [comment]
```
Appears to be a couple of possible issues:

We only compute reaction rates at the start of PYROLYSIS.  In this case the surface
temperature drops quickly over the time step due to cooling which should greatly limit
the energy lost to pyrolysis, but this isn't captured and the heat of pyrolysis is
continously removed as if the surface stayed at a high temperature.

TMP_F in one timestep goes from 510 to 290 so we invoke the sub timestep routine. 
However, this has TMP_F drop 510 to 413 to 293 to 189 - the sub timestep drops below
the single timestep.  There might be something amiss with that logic.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-06-18 15:18:11

**Comment by juanjobh** [comment]
After posting it to forum (https://groups.google.com/forum/#!topic/fds-smv/kz1zhPjsU40), I attach an example of unphysical results when water droplets cooling of a surface. 

Just to check if this issue is related and solve this as well. 

Thanks

`&HEAD CHID='MYsprinkler_test', TITLE='Particle flux test case' /
Water at 1ºC cooling a low density vertical fabric

&MESH IJK=20,20,20, XB=0.0,0.5,0.0,1.0,0.0,1.0 /

&TIME T_END=10. /

&MISC PARTICLE_CFL=.TRUE. /

RADI RADIATION=.FALSE.

&MATL ID='Textile',
      SPECIFIC_HEAT=1.32,
      CONDUCTIVITY=0.04,
      DENSITY=65.0/

&SURF ID='Curtain',
      RGB=51,204,255,
      MATL_ID='Textile',
      THICKNESS=0.02/

&SPEC ID='WATER VAPOR'/
&PART ID='water drops', SPEC_ID='WATER VAPOR', DIAMETER=1000., SAMPLING_FACTOR=1, INITIAL_TEMPERATURE=1 /

&SURF ID='SPRAY', PART_ID='water drops', VEL=-1.0, PARTICLE_MASS_FLUX=0.1, COLOR='BLUE', NPPC=5, DT_INSERT=0.01 /

&OBST XB=0.10,0.15,0.45,0.55,0.90,0.95, SURF_ID6='INERT','SPRAY','INERT','INERT','INERT','INERT', DEVC_ID='clock' /
&OBST XB=0.10,0.15,0.15,0.25,0.90,0.95, SURF_ID6='INERT','SPRAY','INERT','INERT','INERT','INERT', DEVC_ID='clock' /
&OBST XB=0.10,0.15,0.75,0.85,0.90,0.95, SURF_ID6='INERT','SPRAY','INERT','INERT','INERT','INERT', DEVC_ID='clock' /

&OBST XB=0.40,0.45,0.0,0.95,0,0.95, SURF_ID='Curtain'/

&DEVC ID='clock', XYZ=0,0,0, QUANTITY='TIME', INITIAL_STATE=.TRUE., SETPOINT=55. /

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /

&DUMP DT_DEVC=0.1 /

&DEVC XB=0.0,0.4,0.0,1.0,0.5,0.5, ID='flux', QUANTITY='PARTICLE FLUX Z', STATISTICS='AREA INTEGRAL'  /
&DEVC XB=0.40,0.40,0.0,1,0.0,1.0, ID='flux', QUANTITY='PARTICLE FLUX X', STATISTICS='AREA INTEGRAL'  /
&DEVC XB=0.40,0.40,0.0,1,0.0,1.0, ID='total', QUANTITY='AMPUA', PART_ID='water drops', STATISTICS='SURFACE INTEGRAL'  /
&DEVC XB=0.40,0.40,0.0,1,0.0,1.0, ID='total', QUANTITY='CPUA', PART_ID='water drops', STATISTICS='SURFACE INTEGRAL'  /

&SLCF PBZ=0.4, QUANTITY='PARTICLE FLUX Z' /
&SLCF PBX=0.4, QUANTITY='PARTICLE FLUX X' /

&DEVC XB = 0.40, 0.40, 0.0, 1, 0.0, 1.0, QUANTITY='WALL TEMPERATURE', STATISTICS = 'MEAN', ID = 'WALL_TEMPERATURE' /
&BNDF QUANTITY = 'WALL TEMPERATURE' /

&TAIL /
`

**Comment by drjfloyd** [comment]
Thanks for posting your input.  Running with the current source it finishes and the resulting wall temperature is attached.  Looks like the new routine will solve this problem. 

![mysprinkler_test_0492](https://cloud.githubusercontent.com/assets/12799217/20066206/c32ddb36-a4de-11e6-9528-20aafa6ac6f7.png)

**Comment by mcgratta** [comment]
Set `CELL_CENTERED=.TRUE.` on the `BNDF` line, and then set the color bar range to show the absolute max and min values.

**Comment by rmcdermo** [comment]
Isn't it time that we make these default settings?

**Comment by mcgratta** [comment]
I think most users like the continuous contours, at least in the gas phase. Might be worth considering for solid boundaries.

**Comment by oriolrios** [comment]
Ohh! That's perfect. 

Indeed it somehow resembles the solution I posted in the forum of same case but with high (normal) density material. 
I take the chance to ask you if you know of any cooling_surface validation check? 
Could not find any in the Validation Guide. 

Looking forward new release! 

Thanks again, 

PS: juanjobh username was previously used by mistake.

**Comment by drjfloyd** [comment]
I don't think user's would be happy for CELL_CENTERED to be the default especially in the gas phase.
