### ISSUE TITLE
MAX_FLOW exceeded

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2427]
```
FDS Version: 6.2.0
SVN Revision Number: 22343
Compile Date: Sat, 11 Apr 2015
Smokeview Version/Revision: 6.2.3
Operating System: Ubuntu 14.04.2 x86_64 

Describe details of the issue below:
I use pressure zones and HVAC to extract from an area. The MAX_FLOW is set a 2m3/sec.
The pressure does not drop below the specified MAX_PRESSURE but the flow exceeds the
2m3/sec specified by MAX_FLOW.

I have cut down an example as much as I can.

```

Original issue reported on code.google.com by `ciandavis` on 2015-06-18 16:08:19

<hr>
- _Attachment: [fecctd.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2469/comment-0/fecctd.fds)_

**Comment by gforney** [comment]
```
MAX_FLOW is the flow at zero back pressure on the fan.  It is not the maximum flow that
can occur in the system. MAX_FLOW and MAX_PRESSURE merely defines a quadratic fan curve
that goes through the points MAX_FLOW at zero back pressure and 0 flow at MAX_PRESSURE.
 If your run starts to put pressure on the upstream side of the fan, then you can exceed
the max flow.  Add a DEVC for the pressure across the fan and see if this is the case
for your run.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-06-18 16:46:23

**Comment by gforney** [comment]
```
Yes, my OUT is at a pressure of approximately 400 Pa below my in.

I suspect it's down to my possibly erroneous understanding of the height parameter
- I have set the XYZ of the OUT node as 0,0,40 to simulate the outlet vent being on
the roof of the building and to include the effect of the fan having to pump the air
up 40m. I've obviously misunderstood how this is supposed to work. 
```

Original issue reported on code.google.com by `ciandavis` on 2015-06-19 15:07:52

**Comment by gforney** [comment]
```
I have run a number of "real-world" cases over the weekend with a reduced bouyancy head
(XYZ=0,0,2 on the outlet node). Unfortuantely, they have all failed with numerical
instabilities. The fan doesn't seem to ramp up - just goes full on immediately. The
DP goes to 97Pa immediately with an extract of 21m3/sec. 

It does make me look at the results for the test case again and wonder if the 400Pa
pressure difference reported on the DEVC is just the bouyancy head - which on it's
own won't drive flow. The fan will have to overcome the bouyancy head. 

I am now running two versions of the test case I posted - both with the XYZ of the
node at 0,0,2. One of them with TAU_FAN at the same -20 and the other at 20. Will post
the DEVC in the morning.

Regards,
Cian

```

Original issue reported on code.google.com by `ciandavis` on 2015-06-22 16:46:09

**Comment by drjfloyd** [comment]
Had some time to look into detail at your first case.
At t=0 the fan is on and the hallway is closed tight.  The fan flow is ~0.8 m^3/s which is reasonable given make-up is via leakage.

At t=50 the fan turns OFF and a door is opened to the stairwell.  You do not have any flow losses in your ducts. At a minimum you would have entrance losses and exit losses at the inlet and outlet plus some friction loss over the 40 m duct length. The quadratic fan model attempts to balance the pressure loss over the duct with the flow through the fan, without any flow losses there is nothing to dampen the acceleration of air in the duct due to pressure changes at its inlet and outlet. This is likely the cause of the instabilities you are seeing.

At t=80 the door opens to the fire room which adds positive pressure to the duct inlet.  With no flow losses, flow can keep accelerating as there is nothing to attenuate the pressure. At this point the fan is off. The flow > MAX_FLOW is not due to the fan model.
