### ISSUE TITLE
Confusing Device Output Values

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2431]
```
Please complete the following lines...

FDS Version: 6.2.0
SVN Revision Number: 22352
Compile Date: 12 June 2015
Smokeview Version/Revision: 6.2.1
Operating System: MS Windows

Describe details of the issue below:

I've been trying to use devices to measure the radiative heat flux that hits a surface
at specific points in the domain. However, no matter where I locate the devices, they
output the exact same values of radiative heat flux for each device, even though the
boundary file on the surface clearly shows that each device should have a different
value than all the others.

In fact, I ran the simulation again with just one device and it still gave the exact
same values. What do those values represent? The average radiative heat flux over the
entire surface?

Is there a way to make each device tell me the radiative heat flux exactly at each
individual location for each time step?
```

Original issue reported on code.google.com by `devinck4` on 2015-06-23 19:15:42

<hr>
- _Attachment: [Try Me_4.txt](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2474/comment-0/Try Me_4.txt)_

**Comment by gforney** [comment]
```
I'll take a look.
```

Original issue reported on code.google.com by `mcgratta` on 2015-06-23 19:37:30

**Comment by mcgratta** [comment]
You are using XYZ and STATISTICS at the same time. You should use XB instead of XYZ to describe a volume or area over which to perform the statistical function.

**Comment by saschagottfried** [comment]
I reviewed and fixed the attached input file according to your recommendations. I tried to capture the intention of the person starting this issue. I added single point devices tracking quantity at each time step. I fixed the devices measuring spatially-integrated outputs to match the area of the solid surface (using XB).

Device output visualization now clearly shows the quantity 'radiative heat flux' is dependent on the location. Tracking the maximum value is helpful since the 4 single point devices are not near the location with the peak value. [Saved the input file as a Gist for any reference](https://gist.github.com/saschagottfried/614250a6779a470a1260) 

![chart 6](https://cloud.githubusercontent.com/assets/1422627/9006565/1b9a4490-3789-11e5-9b50-8d0cbf6cbe5c.png)

**Comment by saschagottfried** [comment]
The results were computed with FDS 6.2.0 

```
 Fire Dynamics Simulator

 Compilation Date : Sat, 11 Apr 2015
 Current Date     : July  2, 2015  14:09:14
 Version          : FDS 6.2.0
 SVN Revision No. : 22343

 MPI Enabled; Number of MPI Processes:     1
 OpenMP Enabled; Number of OpenMP Threads:   4

 Job TITLE        : Compare DEVC output to spatially-integrated values
 Job ID string    : Try Me_4_statistics
```

**Comment by mcgratta** [comment]
I'll take a look at this.

**Comment by mcgratta** [comment]
Sascha -- do you mean that there is not a problem with FDS when you fixed the input parameters?

**Comment by saschagottfried** [comment]
Yes, FDS 6.2.0 is working as expected as long as users setup single point devices properly and follow guidelines outlined in FDS Users Guide to setup devices for spatially-integrated output. 

You may investigate further if FDS should require devices capturing spatially-integrated output to specify an area or volume, since running these devices with XYZ may lead to confusion.

**Comment by mcgratta** [comment]
Good, thanks for checking this. I'll close the issue.
