### ISSUE TITLE
v5 and v6 visibility comparison

### ISSUE THREAD

**Issue by bcasterline** [firemodels/fds#3112]
We have made quite a few visibility comparisons between v5 and v6 and wonder why the visibility is consistently lower with v6.
Kevin, a co-worker asked you about this at the recent Conference and you said post it to the issue tracker. 

thanks,

Brad

[mk-032-v5.txt](https://github.com/firemodels/fds-smv/files/33101/mk-032-v5.txt)
[mk-032-v6-smag.txt](https://github.com/firemodels/fds-smv/files/33102/mk-032-v6-smag.txt)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
I'm not sure that this case indicates that there is a significant difference between 5 and 6. It is a very coarse grid which might lead to spurious conclusions. Take, for example, the following images:

![mk-032-v5_1000](https://cloud.githubusercontent.com/assets/11333911/11130265/1e128fc8-8952-11e5-9ffa-74edebef5cf2.png)

![mk-032-v6-smag_1000](https://cloud.githubusercontent.com/assets/11333911/11130269/265f3b5e-8952-11e5-83c3-f0670a0f8b4b.png)

Going from FDS 5 to 6, we made improvements to the velocity boundary conditions. Notice in the FDS 5 figure that the left most velocity component is more or less zero, whereas it is positive in the FDS 6 figure. That is due to subtle changes in how we handle the boundary layer, especially near OPEN boundaries and edges. 
![vdot](https://cloud.githubusercontent.com/assets/11333911/11130575/bd75c0ca-8953-11e5-8170-bfe9c2a8b8fa.png)
I added a printout of 'VOLUME FLOW' through the ceiling vent, and noticed that in FDS 5 you are a losing a bit more smoke to the outside. Not a huge difference, but your hole is only covered by 4 grid cells, so it's hard to say if FDS 5 or 6 is more accurate. In any case, your VISIBILITY is based on the exponential of smoke concentration, and your smoke concentration is different in FDS 5 and 6 for various reasons. In this case, those reasons appear to be due more to the crude grid than any substantial change in physics. 

Looking over the entire case, there are a number of places where subtle changes in BCs can affect things. The connections of multiple meshes, for example. We improved that functionality going into FDS 6. 

Can you run this case at higher resolution and record VOLUME FLOW through the various openings. It could be that a big more smoke is escaping in the FDS 5 case which would explain the increased visibility at the end of the hall. Focus your attention more on MASS FRACTION than VISIBILITY, and try to figure out where the smoke is going.

**Comment by bcasterline** [comment]
Thanks Kevin. Yes, I will do as you suggest. I will say we have also run
comparisons with '(chid...)-refined' where the cell size is .25 instead of
.5. The visibility is a little better with both versions but it is
proportionally better.
Thanks again.

Brad

**Comment by bcasterline** [comment]
Kevin,
The first thing I did is remove the vent in both cases and the visibility
matched within .2m! (taking the average of the average visibility of the
two devices.
I 'learned' during v6 beta that OPEN vents on a mesh boundry is a NO-NO,
however I used the current v6 example 'energy_budget_adiabatic_two_fuels'
as a starting point. If this were a real case I would extend the mesh
several cells +Z and use an obstruction with a hole for the ceiling.

Thank you very much,

Brad

**Comment by mcgratta** [comment]
I wouldn't say it's a no-no in all cases. Sometimes it's convenient to create an door or window with an OPEN vent, but in your case you need to be concerned about the total mass of soot particulate accumulating in that upper plenum. The thing about an OPEN vent is that we assume the pressure at the interface is ambient, but in reality the pressure is a continuous function across.

**Comment by rmcdermo** [comment]
It's a no-no for two-way flow.  And it's a no-no if your case depends
heavily on the ventilation rate and you are not resolving the vena contra
of the "orifice" even if it is just one-way flow.

**Comment by drjfloyd** [comment]
To follow up on Kevin's comment.  The OPEN boundary condition will introduce errors in natural flows in or out of an opening if there isn't some extension beyond the opening. In the case of a naturally vented compartment this can be significant. There are cases though where errors might not matter - for example if you are just using the opening for makeup air in a simulation of smoke control where you specify the exhaust.

**Comment by bcasterline** [comment]
Thanks Docs!
You guys are the best.
