### ISSUE TITLE
Problem in mesh union

### ISSUE THREAD

**Issue by guipesa** [firemodels/fds#3125]
Hi,

I have some problems looking species slices in mesh unions in a tight enclosure when the pressure is high. As Randy wrote me in https://groups.google.com/forum/?fromgroups#!topic/fds-smv/C2klZIz0vXQ I build a simple 2-mesh compartment that shows the same problem.

I attach it and an image that shows the problem.

Thanks,

Guillem,

![mesh union problem](https://cloud.githubusercontent.com/assets/14068673/11210187/77883440-8d26-11e5-8694-d43c95481a5e.png)
[Pressure.txt](https://github.com/firemodels/fds-smv/files/36591/Pressure.txt)

**Comment by rmcdermo** [comment]
Well done.  Thanks.  I'll take a look.

**Comment by rmcdermo** [comment]
Good news is that this is just an image rendering problem.  If you set CELL_CENTERED=T on your slice files you will not see this.  So that is the short term fix.  We will fix the ghost cell data on the next maintenance release.

![pressure_0509](https://cloud.githubusercontent.com/assets/4418497/11213079/0ad86766-8d08-11e5-9a4d-e7570342aa92.png)

For this case, you should also add SECOND_ORDER_INTERPOLATED_BOUNDARY=.TRUE. on MISC, since no OBST abut a mesh boundary.

[Pressure_new.txt](https://github.com/firemodels/fds-smv/files/36725/Pressure_new.txt)

**Comment by rmcdermo** [comment]
I think the problem is actually the assignment of RSUM at interpolated boundaries.  Mass fractions look fine.

**Comment by mcgratta** [comment]
Fixed. Please check to confirm.

**Comment by rmcdermo** [comment]
Yep. Working.
