### ISSUE TITLE
Multiple Meshes and Suppression Calculations

### ISSUE THREAD

**Issue by sreihani** [firemodels/fds#3380]
Hi there,
I am running current version of FDS compiled with Intel, for a case with multiple mesh regions and suppression set to TRUE. The hrr results are reported all zero for the time interval of interest that is not anticipated. I wonder if FDS can handle computational domains with multiple meshes and an existing suppression system.  As a fact, by setting the suppression to FALSE, it works properly and reported results are correct.

Thanks for any comment and suggestion.

SR

**Comment by rmcdermo** [comment]
The extinction model is telling you that you will not burn under your current conditions.  We cannot diagnose this without an input file.  Simplify you case to the point where you have a simple box with the same stoichiometric conditions.  Take out EVERYTHING that is not essential to the "bug" you are reporting (do you think this is a multi-mesh problem? probably not, use a single mesh).  If you still have not solved the problem, then post the simplified input file.  Thanks.

**Comment by sreihani** [comment]
As I said FDS works fine with SUPPRESSION = .FALSE.. I think it means that burning happens under the current conditions. Input file is a variant of input files in Appendix D and Appendix H by NRC.

I guess you have access to those files.

SR

**Comment by rmcdermo** [comment]
No, that is not what it means.  With SUPPRESSION=F you are bypassing the extinction model.  Please simplify your case and send me your input file.

**Comment by mcgratta** [comment]
The cases in the Appendix of NUREG-1934 need SUPPRESSION=.FALSE. because they use a specified HEAT_OF_COMBUSTION which is not consistent with the stoichiometry of the fuel molecule. The reason is that it is not one fuel molecule that is created when the polymer offgases. There are many, but the models can only track one. So the "effective" fuel molecule is not consistent with the HoC. Try removing the HoC from the input file and let FDS use 13,100 kJ/kg O2 to calculate the HoC based on the assumed fuel stoichiometry.

**Comment by drjfloyd** [comment]
The problem is with the HoC itself.  The HoC is based on the integral of the heat release rate divided by the initial cable mass and does not account for residual material. A substantial fraction of a cable's weight is non-combustible. If you are just doing a scoping calc this is fine. Quickly multiple total cable weight by the HoC and you can get the total energy released. For CFD, this value is not good. It would be better to use an HoC that represents the polymer for the cable jacket.

**Comment by sreihani** [comment]
Kevin,

Thank you for your suggestion. I removed the HoC line and did let FDS
calculate it using EPUMO2. Now ​combustion and suppression are occurring
concurrently.

SR
