### ISSUE TITLE
Flame Extinction and Suppression

### ISSUE THREAD

**Issue by sreihani** [firemodels/fds#3417]
Hi Kevin,

I wonder if two parameters "SUPPRESSION=.TRUE." and "CRITICAL_FLAME_TEMPERATURE = -273.15" are compatible. I have run FDS for a case with these two parameters. Temperatures are lower than the same case with SUPPRESION=.FALSE., which make sense. However, in the case with suppression, at some point along the temperature trajectory, temperatures starts to increase, but still much lower than the case without suppression. I suspect this anomaly comes from unburned fuel gas that have found enough oxygen in the field. Would you agree? I noticed manual suggest the parameter "AUTO_IGNITION_TEMPERATURE" be used along with a form of heat/ignition source. Would HRR curve be enough for the source?

Also, FDS does not make any change in HRR curve with suppression which looks to me questionable. I would appreciate your thoughts on this point.

Regards,

SR

**Comment by drjfloyd** [comment]
SUPPRESSION = .FALSE. and SUPPRESSION=.TRUE.,CRITICAL_FLAME_TEMPERATURE=-273.15 should give the same results as in both cases there should not be any extinction occurring.  

Do you have a simple case you can provide?

**Comment by sreihani** [comment]
But sprinklers were activated in the second case and temperatures were lower.  My understanding was that suppressant should absorb part of heat generated. Would you agree?

**Comment by drjfloyd** [comment]
SUPPRESSION refers to the extinction model, not to sprinklers.  For two otherwise identical cases SUPPRESSION = .FALSE. and SUPPRESSION=.TRUE., CRITICAL_FLAME_TEMPERATURE=-273.15 should give the same results. In both cases water droplets will remove heat and any generated water vapor will act as a diluent in the flame.  However, with CFT=-273.15, any time fuel and oxygen meet, combustion should be allowed since post combustion temperature will always be greater than or equal to the CFT.

If you have two identical cases except for SUPPRESSION and are seeing different results, please post a simple file that demonstrates your problem.

**Comment by sreihani** [comment]
Just to understand your point, are you saying that temperature of any target in the field should be the same in both cases?

**Comment by rmcdermo** [comment]
This is not an Issue.  Please move to the discussion forum.

**Comment by drjfloyd** [comment]
SUPPRESSION=.FALSE. means FDS will not use any extinction submodel and that any time fuel and oxygen meet, they will burn.

SUPPRESSION=.TRUE., CRITICAL_FLAME_TEMPERATURE = -273.15 means FDS will use the extinction model, and that FDS will only allow combustion if the resulting flame temperature is greater than or equal to -273.15 C.  Since this will happen everywhere, given otherwise identical cases, results should be the same as SUPPRESSION=.FALSE.

**Comment by sreihani** [comment]
Yes,  that means heat generated by combustion will possibly be the same in both cases. I guess my point is how that amount of energy is distributed in the field. If there is a sprinkler defined in the second case, temperatures should be different in these two cases. Probably there are some limitations in applying FDS to cases with suppression.

**Comment by drjfloyd** [comment]
If you have a sprinkler in one case but not the other, then you should expect differences in both the instantaneous heat release rate and the temperature (mixing from the water spray plus the addition of water vapor means you will have changed the fuel and oxygen present in the domain). They are no longer the same case.  That, however, is not a bug and further discussion should be in the forum.
