### ISSUE TITLE
Validation case issue VTT

### ISSUE THREAD

**Issue by szakalboss** [firemodels/fds#3517]
I was trying to run VTT validation test case. There are 3 cases, let's consider the first one only here. 
I have already tried with version 5.5.3 reported by some Windows users as the most stable one, also latest version from development, as well as version taged as Git-r7 (I guess 6.4.0). Each of these are failing for this test case. 

I am using openmpi-1.5.5 with gcc-5.3.0 on a Linux cluster. This test case uses 5 processors. 
The problem starts when I use optimized executable (from -O1 up to -O3), for -O0 it works somehow.
I tried to debug the issue with sanitizer and it finds a line affected. I attach a log from my run.
The line affected is : IF (OB%PROP_ID /= 'null') THEN

[VTT_01.txt](https://github.com/firemodels/fds-smv/files/136942/VTT_01.txt)

BTW: In part.f90 for all the calls of SHUTDOWN, there is probably a 'return' statement missing afterwards. For one verification test case it was creating an infinite loop, leading to huge err file created.

**Comment by mcgratta** [comment]
We run with Open MPI 1.8.4 and the Intel 16 compiler. We use -O2 optimization because sometimes -O3 gives spurious results. 

I just noticed the problem with part.f90 and I am fixing it. 

When you say the cases are failing, what do you mean? Numerical Instability?

**Comment by szakalboss** [comment]
I also tested with ifort, version 12.1.3 . But there were issues with numerical instability created for this test case after roughly 25s of fire propagation. The input files however were read properly.
Then I decided to use gcc/gfortran since it has better dubugging in my opinion, especially new version with sanitizer. 

With gcc, the case is failing and I mean it crashes with all the versions since 5.5.3 up to 6.4.0 during input file reading, in the line that I mentioned. Try to run it with -O1, -O2 or -O3 and gfortran with openmpi using 5 procs...
I tried to print out the structure M%OBSTRUCTION(N) pointed by OB in PROC_OBST routine, for each processor involved (5 in total). I attach the outputs below. There you can see one file is empty, and I guess some mismatches are also visible.  BTW I use the latest git version with some fixes that I mentioned before.

[output.zip](https://github.com/firemodels/fds-smv/files/137070/output.zip)

**Comment by mcgratta** [comment]
Post the input file. I will try to run it on my machine.

**Comment by szakalboss** [comment]
This is original input from your git. Replace extension to fds.
[VTT_01.txt](https://github.com/firemodels/fds-smv/files/138089/VTT_01.txt)

**Comment by szakalboss** [comment]
BTW if I compile read.f90 file with -O0 flag and all the rest part with -O2 or -O3 the code runs and does not crash. I was able to run all Verification tests and lot of Validation with such settings. So you may suppose the problm comes from optimization and data communication between the processors.

**Comment by mcgratta** [comment]
FDS is a complex program that uses fairly new Fortran data structures. With almost every version Fortran compiler we have used, we find bugs in the optimization settings. That is why we use -O2 instead of -O3. The latter is dangerous, and the compiler developers themselves warn us that it may not significantly speed up the code. I just ran the VTT cases a few days ago in preparation for a minor release. The output files are on GitHub. The git hash is `Git-r6-590-g0e39913`.

If you want to compile FDS yourself, I suggest you use the latest versions of the Intel compiler and Open MPI. Several times a year I post bug reports to both and they are fairly responsive in fixing them. I do not have enough experience with gfortran to say if it is better or worse. Obviously, the Intel compiler is expensive, but we have found it to be well-supported and faster than the others. 

So, the only way we can help you is if you use the most up-to-date versions of the compilers, preferably Intel. If you want to use gfortran, we can try to compile that too. But if you find that the code runs with -O0 and not -O2, we're not going to be able to fix that. That is clearly a compiler bug.

**Comment by szakalboss** [comment]
For sure you have a memory issue there which prevents from normal run under optimized code. 
This is however suppressed by Intel compiler as you said, but contrary Intel was failing for me with numerical instability issue for this test. This however seems to work at the moment with -O0 flag set only for read.f90 file...

**Comment by mcgratta** [comment]
But you are using an old version of the Intel compiler. If you update the compiler to the latest version, do you still have trouble? We do not.

**Comment by szakalboss** [comment]
This I cannot do :(

**Comment by mcgratta** [comment]
That's a problem, because if we complain to Intel about a compiler bug, they will tell us to buy the latest version. They cannot possibly support version 12.

**Comment by rmcdermo** [comment]
Marcos,
You have been using gfortran to compile lately.  Can you please have a look at this case and see if the compiler bug is still present in the version of gfortran we use?
Thanks.

**Comment by marcosvanella** [comment]
Hi, I just find out I've been assigned to this.

I compiled on a Mac the last version of the firemodels repo, using OpenMPI 1.8.6 and gcc 5.2.0 (from homebrew). My flags are:

mpifort -c -O2 -ggdb -fbacktrace -m64 -cpp -DGITHASH_PP=\"Git-r8-177-g5ac3c20-dirty\" -DGITDATE_PP=\""Tue Mar 8 08:45:34 2016 -0700\"" -DBUILDDATE_PP=\""Mar 08, 2016  16:31:54\"" -fopenmp ../../FDS_Source/main.f90

The problem VTT_01.fds doesn't seem to crash at startup, see fig: 

![screen shot 2016-03-08 at 4 58 39 pm](https://cloud.githubusercontent.com/assets/7450069/13617922/2d8e6806-e54f-11e5-9dc1-e0a940b767d0.png)

What you gave as output for the OBSTRUCTION(N) data structure is not unusual, look in type.f90 the type OBSTRUCTION_TYPE. It has different types of data as fields (char, int, real, logical). If you did a 

write(0,*) M%OBSTRUCTION(N)

in the source, you will get all of those fields written one after the other. That is what you see on output_0.dat, for example. I assume that one of your output files has nothing on it because there is no obstructions on that mesh.
Looking at smokeview the calculation seems to be running fine. 

![screen shot 2016-03-08 at 5 03 38 pm](https://cloud.githubusercontent.com/assets/7450069/13618013/be1a529a-e54f-11e5-9801-ae07bd780ef8.png)

Hope this helps.

**Comment by rmcdermo** [comment]
No comments from user.  Closing.
