### ISSUE TITLE
File keywords inconsistency about Isosurface

### ISSUE THREAD

**Issue by zrui** [firemodels/fds#3534]
![image](https://cloud.githubusercontent.com/assets/3052535/13226729/a8b4249c-d958-11e5-91f5-009a0dc74a29.png)

SMV_user_guide sixth edition use the ISOF as the keyword, but I got ISOG in the .smv output file.

**Comment by gforney** [comment]
ISOF was the keyword used when FDS called C routines to generate isosurfaces.  These C routines were converted to Fortran so that FDS is now 100% Fortran.  In order to not confuse smokeview (and more importantly to keep smokeview from crashing) the keyword for specifying isosufraces is now ISOG.  I will update the guide to reflect this.
