### ISSUE TITLE
energy_budget_adiabatic_walls

### ISSUE THREAD

**Issue by boris-stock** [firemodels/fds#3708]
FDS 6.3.2
Windows 7 x64

I have a question concerning the verification case [energy_budget_adiabatic_walls.fds](https://github.com/firemodels/fds-smv/blob/development/Verification/Energy_Budget/energy_budget_adiabatic_walls.fds)
The verification case shows a good energy balance, but does not take radiation in account. So convective losses equal hrr, no radiative losses and nearly no conductive losses.

Changing your verification case in 3 lines (file attached)
1. &RADI RADIATION=.FALSE. / -> &RADI RADIATION=._TRUE_. /
2. &SURF ID='FIRE', HRRPUA=300, HEAT_TRANSFER_COEFFICIENT=0. / -> &SURF ID='FIRE', HRRPUA=300, _ADIABATIC=.TRUE._ / and
3. &REAC FUEL='PROPANE',RADIATIVE_FRACTION=0.0/ -> &REAC FUEL='PROPANE',_RADIATIVE_FRACTION=0.35_/

includes radiation.

As far as I understood, there should be radiative losses through the open vents, decreased convective losses and still no conductive losses.
In fact it seams like hrr (+) equals conv (-) , and rad (-) roughly equals cond (+) (please mind the attached diagram).
Could someone give me a hint where I am wrong here, please?

Your help is appreciated.

Thanks 
Boris

[energy.zip](https://github.com/firemodels/fds-smv/files/185015/energy.zip)

**Comment by rmcdermo** [comment]
Boris,

ADIABATIC=T will automatically make radiation equal and opposite of conduction.  That leaves the convective flow in and out to still be equivalent to the total heat release rate.

Randy

**Comment by boris-stock** [comment]
Randy,

thanks for your very fast help.

What I would have expected ist something like hrr 1200 kW - rad 200 kW - conv 1000 kW - cond 0 kW = 0 kW
8.2.3 FDS User Guide says "there is no net heat transfer (radiative and convective) from the gas to the solid". If I am understanding the energy balance right, it says that all of my hrr convects out and there are conductive energy wins?

**Comment by rmcdermo** [comment]
This is a bit confusing because of what "cond" means in the context of the _hrr file.  The key is to look at Eq. (16.3) of the FDS User Guide.  When you say ADIABATIC=T, this means that the "conduction" term at the wall (-k grad T) is balanced by the net radiative flux at the wall so that the net heat transfer through the wall is zero (perfect insulation).  For this problem, ignore the _b terms in Eq. (16.3), because there are no Lagrangian particles.  By definition, with ADIABATIC=T the Q_COND term will balance the Q_RADI term.  Q_DIFF is small and Q_PART is zero.  We are at steady state, so Q_ENTH is close to zero.  So, you are left with Q_CONV balancing Q_HRR.  The radiation that is lost by the flame (the radiative fraction) is eventually absorbed by the gas phase species and transported out of the domain.

**Comment by boris-stock** [comment]
O.k., I have to confess I did not know this. Thanks for your explanation.

One last question: as far as I understand this, if I want to measure the radiative losses through the opening, I have to measure it directly at the opening. There is no chance to calculate the radiative losses by the values in the _hrr-file, because here, the radi-term always balances the cond-term. The last one is positive, because the wall-cells are assigned to the same temperature as the referring gas-cell?

Boris

**Comment by mcgratta** [comment]
Correct. Q_RADI is the volume integral of the divergence of the radiation heat flux vector, q_r. By the Divergence Theorem, this volume integral is equivalent to the surface integral of q_r over all boundaries, both open and solid. In physical terms, the divergence of q_r is the net radiation loss/gain by each grid cell. When you sum these all up, you get the net loss/gain for the whole domain.

**Comment by mcgratta** [comment]
I will create a simple test case to make sure what I am saying is right.
