### ISSUE TITLE
To change wind direction

### ISSUE THREAD

**Issue by Edward101** [firemodels/fds#3745]
Is it possible to change the wind direction with time at the inlet vent?
I find TAU_V can change the wind speed (in normal direction) with time. If the wind speed in the tagential directions (VEL_T)  can also change with time (both components of VEL_T need change individually), then we can model changing wind direction.

**Comment by rmcdermo** [comment]
If you are trying to simulate variable wind direction, you should consider
the approach used by Kuldeep Prasad to couple FDS with down-scaled data
from WRF.  This option is not yet written up in the released FDS User Guide
because it is still in development.  But it is better than using VEL vents
and OPEN outflow vents for wind.  An example of how to do this is given
here:

https://github.com/firemodels/fds-smv/blob/development/Verification/WRF/wrf_time_ramp.fds

**Comment by rmcdermo** [comment]
I did not realize this was an issue.
