### ISSUE TITLE
Smokeview: HRR Label

### ISSUE THREAD

**Issue by guipesa** [firemodels/fds#3812]
Dear all,

In my simulations I like to see the HRR label instead of the frame label that appears by default, but sometimes the HRR Label option dissapear when I load some slices and I cannot choose it.

Also I found that even I save the .ini file with this option activated it is not recorded. I cannot find the line in the .ini. For example, I know that ShowFrameLabel shows the frame but i cannot see which lines gives the HRR label to activate it.

SHOWFRAMELABEL
 0  -> deactivated

Thanks,
Guillem,

![smokeview_hrr](https://cloud.githubusercontent.com/assets/14068673/14892420/fdf4a49a-0d6a-11e6-83f5-0b3e6cebbd94.png)

**Comment by gforney** [comment]
The hrr label should only appear when you are displaying 3d hrr/smoke
files. Start an issue with a simple example illustrating the problem.
Indicate what you were expecting to see.
Thanks,
Glenn
On Apr 28, 2016 12:08 PM, "guipesa" notifications@github.com wrote:

Dear all,

In my simulations I like to see the HRR label instead of the frame label
that appears by default, but sometimes the HRR Label option dissapear when
I load some slices and I cannot choose it.

Also I found that even I save the .ini file with this option activated it
is not recorded. I cannot find the line in the .ini. For example, I know
that ShowFrameLabel shows the frame but i cannot see which lines gives the
HRR label to activate it.

SHOWFRAMELABEL
0 -> deactivated

Thanks,
Guillem,

[image: smokeview_hrr]
https://cloud.githubusercontent.com/assets/14068673/14892420/fdf4a49a-0d6a-11e6-83f5-0b3e6cebbd94.png

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/firemodels/fds-smv/issues/3812

**Comment by guipesa** [comment]
I have a short program which obtain all the images I need. Sometimes i don't show the HRR or Soot, only slices of visibility or temperature and in this cases I still want to see the HRR label because I think it gives a better idea to understand the simulation.
What I do in the program is to change the .ini through the program to show but I want. For example if I want to show the frame label in the images I change SHOWFRAMELABEL from 0 to 1. In the case of HRR label there is no option. Then what i would like would be:

1) Possibility to choose HRR Label in all cases even if Smoke or HRR are not displayed.
2) Possibility to save the configuration. In the .ini a line SHOWHRRLABEL for example, and if it is activated, everytime you start smokeview the HRR label is shown.

If it could be implemented I will really appreciate,
Thank you in advance,
Guillem,

**Comment by gforney** [comment]
I'll take a look

**Comment by guipesa** [comment]
Thanks!

**Comment by gforney** [comment]
Take a look at smokeview located here
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

first time load your hrr label.  then save an .ini file.  The next time you load your case the hrr label should appear.  The ini keyword is SHOWHRRLABEL

**Comment by guipesa** [comment]
Thanks Gleen!

I have tried it, and it works. Thanks!
Only one detail, I find a little bug when you unload the slice and load another slice. Then the HRR label dissapear and there is not option to load it again. I attach an image.

Thanks,
Guillem,

![hrr_image](https://cloud.githubusercontent.com/assets/14068673/15110885/de047c10-15e3-11e6-8f57-58274d325a72.png)

**Comment by gforney** [comment]
I'll take look

**Comment by JakeOShannessy** [comment]
I'm interested in this too as there was trouble with this when creating a script function for this. You might have already fixed this, but in case you haven't this is the simplest way I went about it.

 This menu item is only shown when the struct `hrrinfo` is present, which contains a summary of all the HRR related info. This struct is populated when reading the .smv file (i.e. the only `readhrr` call with the `LOAD` flag is under the `readsmv` function). As it is part of the automatic .smv file read, I would suggest that dropping this information when the user selects "Unload All" is not the right thing, particularly as there is no way to load this data from the load menu. The `readhrr` is called with the `UNLOAD` flag under the "Unload All" menu item. Removing this call from the `LoadUnloadMenu` worked perfectly for me (with minimal code changes).

**Comment by gforney** [comment]
I fixed this. See previous comment in this issue for smokeview location
with fix.

**Comment by JakeOShannessy** [comment]
I've tested the smokeview versions linked above and HRR label option remains unavailable after using unload all. Perhaps it should be in a different issue, but that is what I'm referring to, not the .ini config option.

**Comment by sbenkorichi** [comment]
@gforney Glenn, if the issue is fixed can you get it close please.

**Comment by gforney** [comment]
If this is still an issue, start a new issue under the smv repo
