### ISSUE TITLE
Sprinklers combined with localized leak causes crash

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#3910]
I've been working on a scenario where there is a fire, a HVAC pathway (nodes, duct, no fan) to the exterior of the room, a sprinkler, and a localized leak path under the door.  For whatever reason, If I include both the sprinkler and the localized leak path then it crashes. There is a significant velocity error at the leak path localization.

Adding &PRES VELOCITY_TOLERANCE=0.001, MAX_PRESSURE_ITERATIONS=200 / is of no value.

A simplified file is attached (with a .txt ending). It crashes in ~14 s. However, if either the sprinkler or the leak path is disabled, then it runs.

My example is somewhat similar to the door_crack example. I added a sprinkler and replaced the zone leak with a localized leak path. It runs fine; I could not reproduce the problem.

A few related questions.
1. Is, "&PRES VELOCITY_TOLERANCE=0.001, MAX_PRESSURE_ITERATIONS=200 /" of any value to a single mesh, or is it just effective at the boundary between multiple meshes?
2. Is there a difference between a Numerical Instability, and the error message,  "forrtl: severe (157): Program Exception - access violation"

Thanks

Dave

[HVAC_leak_10_MW.fds.txt](https://github.com/firemodels/fds-smv/files/297771/HVAC_leak_10_MW.fds.txt)

Is

**Comment by rmcdermo** [comment]
Hi Dave,
This will be a good one for Ben Ralph to cut his teeth on.  We'll have a look.

**Comment by Dave-McGill** [comment]
Thanks Kevin

Ooops, I mean thanks Randy

**Comment by bmralph** [comment]
Hi Dave, looking in to this now. I'll try running it on the latest development version of the code also.

In the short term, re your questions:
1: VELOCITY_TOLERANCE and MAX_PRESSURE_ITERATIONS also apply to solid boundaries. They relate to the non-zero normal velocity error at mesh boundaries and solid boundaries. By specifying these values (as lower and higher respectively) you are driving down this normal velocity error.

2: Yes. Numerical instabilities are created when the time step decreases and decreases; due to very high velocities (time step and velocity are related via the CFL constraint). Whereas forrtl: severe (157): Program Exception - access violation is typically generated when the code is trying to retrieve a piece of stored information which is outside of an acceptable/existing range; e.g. trying to retrieve column 101 of a matrix which only has 100. This can occur due to spurious (very high or very low) values of variables (e.g. temperature).

I'll let you know once I get answers regarding your case.

**Comment by bmralph** [comment]
Hi Dave; believe I've found the problem with your case. Running a version of the case now and it's reached over 150 seconds.

Your pressure zones were set up incorrectly - the room of fire origin wasn't a separate pressure zone. This meant that the RFO was not able to develop it's own background pressure. This means that the velocity divergence in the RFO due to the fire and HVAC system was not correctly calculated. No background pressure increase in the RFO means that the local density is not correctly calculated using the equation of state (density change only due to temperature change and species concentration accounted for).

Try fixing your pressure zone definition and re-running your case. Let me know if this fixes your problem and I'll close the issue.

**Comment by Dave-McGill** [comment]
Hi Ben,

Can you provide the file you are running so I can see what you've done differently?

Thanks

Dave

**Comment by bmralph** [comment]
See below. Only changes should be &ZONE line on line 28 and removal of &PRES line tolerances.

[HVAC_leak_10_MW.fds.txt](https://github.com/firemodels/fds-smv/files/305103/HVAC_leak_10_MW.fds.txt)

**Comment by Dave-McGill** [comment]
Ben,

The original file had a zone in the room of origin. if filled almost the entire room. (see attached). The modified file has a much smaller zone in the same room. My understanding of zones is that they expand until they hit an obstruction, in which case both zones should have the same effect.

As an aside, zones are required for sealed rooms. I was unsure if a room with both an HVAC connection and a localized leak path would be considered "sealed" and require a zone.

Dave

![original pressure zone](https://cloud.githubusercontent.com/assets/13259079/15900343/325974a0-2d6d-11e6-90ce-5de18004f6ab.png)

**Comment by bmralph** [comment]
In the input file you attached, your zone extended beyond the wall of the closed RFO (to y=102.5 but the outer wall terminates at around y=101). At least in the input file you sent over, the &ZONE extends into the "outside".

I can see from your screengrab though that it doesn't appear to - perhaps it might be a snap problem in outputting from Pyrosim to FDS input file?

You're correct that a &ZONE will expand to fill a OBST enclosed volume. I personally like to input a geometrically small &ZONE definition which I definitely know is within my pressure zone (e.g. directly in the middle of the room XYZ); then allow FDS to expand as required. I've found this to be safer.

When you're using HVAC (and leakage, which uses the HVAC module) definitely use &ZONE to specify pressure zones for each enclosure separated by OBSTs. Fluid flow within the FDS domain is driven by the perturbation pressure whereas the HVAC solver calculates flow based on the background pressure; if you're not allowing background pressure to vary from room to room correctly (no mass/density effect) then flow will be incorrectly computed.

Let me know how you go.

**Comment by Dave-McGill** [comment]
Ben,

That is odd. Here are the relevant lines from the original file.

&ZONE ID='inner zone', XB=66.4,70.6,95.7,100.7,0.0,3.8/

&OBST ID='wall', XB=63.4,65.8,101.1,101.3,0.0,3.8, THICKEN=.TRUE., SURF_ID='concrete'/ 

There should be 0.4 m clearance between the outer edge of the zone and the inner edge of wall. I haven't got the original PyroSim file with me at the moment, but I'll check it when I get home.                                                                                                                              |'ll use a conspicuously smaller zone, run it tonight, and report back.

Thanks for the help.

Dave

**Comment by Dave-McGill** [comment]
Hi Ben,

The file you sent is still crashing for me using,

sion          : FDS 6.4.0
 Revision         : Git-r10-48-g5996289
 Revision Date    : Thu Apr 7 11:24:39 2016 -0400
 Compilation Date : Thu 04/07/2016  11:28 AM

I also reduced the size of the zone in my original file and it also crashed.

Can you run it with 6.4.0 and see what happens?

Thanks

Dave

Dave

**Comment by bmralph** [comment]
Hi Dave - okay. I'll start case running tonight on Git-r10-48-g5996289 and be in touch tomorrow. Speak soon, BMR

**Comment by bmralph** [comment]
Hi Dave. The case does fail for me with a forrtl: severe (157) on the current release of the bundle (Git-r10-48-g5996289). It is running on the latest compiled source code from the development branch of the firemodels repo.

You can either compile yourself or we are pushing out a new bundled release soon (next couple of weeks as I understand) which should run your case. Kevin has made some changes to the iteration of the baroclinic torque term when solving the Poisson equation - this may have an effect on your case. The latest source code now iterates on the baroclinic torque term - which is calculated using the perturbation pressure from the previous time step.

**Comment by rmcdermo** [comment]
Dave,
I'll close for now.  But let us know if you see problems with next release.  Thanks!

**Comment by Dave-McGill** [comment]
Thanks Guys

**Comment by Dave-McGill** [comment]
Ben and Randy,

This runs with 6.5.0.

**Comment by mcgratta** [comment]
Great, thanks for letting us know.
