### ISSUE TITLE
Smokeview bug?

### ISSUE THREAD

**Issue by rednasss** [firemodels/fds#3958]
I posted this already here: https://groups.google.com/forum/#!topic/fds-smv/jxhfuimeTRY

I am having this problem:
I am using FDS and smokeview. After the simulation with FDS I view the results in Smokeview, but I found out something strange.
When I am viewing the results I always go forward and backward with - and +, so when I reach the end it starts over again. However, when I go through the time by clicking and dragging on the time bar there is always 1 frame EXTRA after the last frame. But the time below the slice does not change!
A wild guess would be that all the slices are shifted 1 timestep forward, which is quite inconvenient.

I am unable to add the zip file here  because of an error but I put it somewhere else: http://www.filedropper.com/slice-test

This includes the fds file and also the results. I also checked the results with TecPlot and I can see there is a difference between the results!

**Comment by gforney** [comment]
I'll take a look at it. Just upload your input file .  If upload doesn't work change extension to .txt

**Comment by rednasss** [comment]
Thanks, here it is:
[slice-test.zip.txt](https://github.com/firemodels/fds-smv/files/313720/slice-test.zip.txt)

**Comment by rednasss** [comment]
Something else which supports this is that the FIRST timestep always has the initial field:
![knipsel](https://cloud.githubusercontent.com/assets/3071416/16041519/1455b36a-3236-11e6-9942-becad01b4b5c.PNG)
In this case the slice time step was 2s, but the same shows at 1s when you choose a 1s slice time step. So all slices are shifted 1 time step.

**Comment by rmcdermo** [comment]
Glenn,
I confirm that this happens with latest FDS.  Might be an FDS problem.
I'll have a look.

**Comment by rednasss** [comment]
Might be, but I don't think so as Tecplot shows the results correctly. So, not a blank field at the first time step for example.

**Comment by rmcdermo** [comment]
Looks to me like the first time step is off.  It is a replicate of the
initial state, then jumps to the second time step.  Glenn, I will leave
this with you.

**Comment by rednasss** [comment]
No, all time steps are 1 time step shifted..

**Comment by drjfloyd** [comment]
I am seeing the same thing.

The _1000 image is what happens when smokeview hits the last frame while time stepping (I actually obtained this by dragging the timebar to near the end and then hit the space bar to get to the last frame).
The _dragtimebar image is what happens if I use to mouse to drag to the last frame.

It is only happening to one of the two slice files loaded. It does not matter what order I load them in.

This seems to happen at any point in time. That is if I load a slice file for a simulation that is running, I see this for whatever the last frame is at that point in time.

![porous_media_dragtimebar](https://cloud.githubusercontent.com/assets/12799217/16052863/2f5cab20-3234-11e6-8e2d-3edaaa82594d.png)
![porous_media_1000](https://cloud.githubusercontent.com/assets/12799217/16052864/2f65721e-3234-11e6-8a81-d86a38dea553.png)

**Comment by gforney** [comment]
So 2nd image is correct?

**Comment by drjfloyd** [comment]
oops file names get stripped from what is shown. Yes the second is correct and the image with the 100 % blue slice is incorrect.

**Comment by gforney** [comment]
Probably an indexing problem. I'll check it out

**Comment by gforney** [comment]
when checking for times in an interval needed a '<=' test rather than '<' 

try test smokeview located here
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

the logic for deciding which frame to display is trickier than you would think so let me know if you see any other problems

**Comment by rednasss** [comment]
I installed it and I can confirm that it works!
The first slice is correct now and when dragging through time, there isn't a slice appearing anymore like I had before.
Thanks! Can you let me know when the update is available?

**Comment by gforney** [comment]
thanks for reporting back.  I'll close the issue.  report back if you see any other problems.

**Comment by gforney** [comment]
fyi: the update is available in smokeview 6.3.8 at:
https://pages.nist.gov/fds-smv/downloads.html
