### ISSUE TITLE
  The problem of asymmetry

### ISSUE THREAD

**Issue by dy944533118** [firemodels/fds#3998]
Weird !The size of my model is 380 \* 9.5 \* 6.765 m , and it is a long straight tunnel. There is a 50 mw heat source in the tunnel middle, and the tunnel has 12 symmetrical vents. Completely symmetrical model, the result of the FDS simulation is asymmetrical. Please correct me for the strange phenomenon. Thank you very much in advance.
[results.zip](https://github.com/firemodels/fds-smv/files/320330/results.zip)

**Comment by rmcdermo** [comment]
First, FDS is an LES code, not RANS.  Any small perturbations can lead to a fluidic switch that propagates in a long tunnel.  But to minimize these possibilities, make sure that when you hit "q" in Smokeview your geometric model does not move.  That is, ensure there is no snapping going on that could be causing an asymmetry.  And, as always, use the latest code.  (There is no need to post an exe of FDS 5.)

**Comment by dy944533118** [comment]
Hello, thank you very much for your reply. There is almost a month since I found this problem. During the time I tried all kinds of adjustment, but each calculation results are completely same: asymmetry. I guarantee that the geometric model is symmetrical and I also did not move or change. So could you please have a look at my somkeview results and the code in the FDS file ? I really feel this is the FDS BUG.Thank you very much.

**Comment by rmcdermo** [comment]
Please set the problem up and run with the latest code.  If you still see something you do not expect, then we will look at it.

**Comment by dy944533118** [comment]
Ok,I will set the problem up and run with the latest code.If I find this problem again according to your method, I'll tell you.Thank you very much sincerely.

**Comment by dy944533118** [comment]
Hello rmcdermo, I didn't download to FDS 6 for some reasons. I think I could not solve the problem with FDS5, then this problem should not be solved with FDS6. I also calculated the model through proysim, And the results did not change : asymmetric. So I beg you to spare some time to help me check my code and model, I think it must be a defect of FDS. If Conditions allow, you can also send me a latest version of FDS, my mailbox is 15730116086@163. com. Thank you very much sincerely again.

**Comment by rmcdermo** [comment]
I need a case to debug, and we do not support FDS 5.  Please post an input file that runs with FDS 6.4.0 and I will take a look.

**Comment by dy944533118** [comment]
Hello rmcdermo, the code is in my first file that is named “results.zip”.You can use Notepad to open and edit the file.Thank you very much for your help.

**Comment by drjfloyd** [comment]
The price we charge for providing you with free software and free support
is that you must provide us an input file that runs with the current
version of the software.

**Comment by dy944533118** [comment]
Hello. For the problem of asymmetric (there happens this problem about 600 seconds), I use FDS6 to calculate, but there is also a new problem. The program will break down automatically. I really don't know what's wrong, so could you help me to look at my code, thank you very much!
[fds6.zip](https://github.com/firemodels/fds-smv/files/325321/fds6.zip)

**Comment by drjfloyd** [comment]
You must convert your file to work with FDS6. As a start see table 1.1 in the User's Guide. For example that table says that CO_PRODUCTION on MISC is no longer an available input, so specifying it will result in an error.  Check your inputs against Table 1.1 and the list of available inputs given in Chapter 17.

**Comment by dy944533118** [comment]
The program I sent to you is no problem. This code can run in FDS6, but there happens break down in 580 seconds. Could you help me to check my code? It won't take up too much of your time, and please give me advice after you read my code. Thank you very much.
[fds6.zip](https://github.com/firemodels/fds-smv/files/326031/fds6.zip)

**Comment by mcgratta** [comment]
I cannot edit your file. It has many non-ASCII characters, tab stops, hidden characters, etc. You also have too many MISC lines. There can only be one MISC line. Check the User's Guide about others. Reduce the size of the file. Get rid of all comments lines. Get rid of all non-standard text. Remove all unnecessary output. I want the smallest possible file that still demonstrates the problem.

**Comment by drjfloyd** [comment]
Running the case shows an anomaly by one of the exhaust vents.  Run it for ~10 s and load the upper z temperature slice. One of the exhaust vents is hot.

**Comment by dy944533118** [comment]
Ok, I'll revise the code carefully, If there is still the problem I will communicate with you. Thank you very much sincerely .

**Comment by dy944533118** [comment]
Hello, I have revised the code carefully, but unfortunately this case still exists the problem of asymmetric. And it is also not stable, always automatical interrupts. So I have to ask for your help. Please help me have a look at what's the problem. I also want to consult you a few small problems in the word, looking forward to your reply. Thank you very much. 
[fds6 2016.6.29.zip](https://github.com/firemodels/fds-smv/files/337573/fds6.2016.6.29.zip)

**Comment by mcgratta** [comment]
I am running the case.

**Comment by dy944533118** [comment]
Thank you very much, I am waiting for your good news.

**Comment by mcgratta** [comment]
The case is still running. I am at 633 s. The flow field is more or less symmetric but I will not be surprised if the flow transitions. Just because a calculation has symmetric boundary conditions does not guarantee symmetric results. FDS adds a small amount of noise (random velocity fluctuations) to the flow field at the start of the calculation to trip any unnatural symmetries. Consider just a simple fire plume calculation. Why does the plume move somewhat randomly about the axis of symmetry? If you put a fire in the bottom of a vertical shaft, you will see the fire and smoke lean to one side or the other, randomly. In your case, you have very large fans drawing air from the tunnel at a large rate. If these were real fans, pressure changes in the tunnel would affect the flow rates and I could easily imagine that the flow would become asymmetric. I have witnessed many fire experiments in our lab and others, and I've never seen a perfectly symmetric fire scenario. Small changes in air pressure usually trip an asymmetry.

**Comment by drjfloyd** [comment]
Kevin are you seeing this in the upper Z temperature slice? It is a symmetric hot spot at the two extraction points closest to each tunnel end. (image just shows the right half of the tunnel)

![sz7_0002](https://cloud.githubusercontent.com/assets/12799217/16452877/b3a3f01e-3dd8-11e6-9dcc-1bf2bb861ac4.png)

**Comment by mcgratta** [comment]
Yes, I see it. It goes away on the left side at about 9 s, but lingers on the right for about 200 s.

**Comment by dy944533118** [comment]
Hello, I understand your interpretation of this asymmetry. There is not perfect symmetry. But I think it is unreasonable like this large asymmetry (image shows). It appears in about 600-800 seconds and sustains all the time.
There is another problem, which is automatic interrupted. I do not know whether you encounter the problem when you run this example, but I meet with the unstable problem really. In addition, my last word I sent to you shows a few small questions. I will be appreciate it if you can answer me. Thank you very much.
![image](https://cloud.githubusercontent.com/assets/19992906/16459934/8cf34120-3e57-11e6-9e8a-52ba44f1e21f.png)

**Comment by dy944533118** [comment]
There is this tip in out file:  STOP: Numerical Instability (CHID: SZ7). I think this tip is the reason for  automatic interrupte. And now , I can not restart this code form the time I stop.
[7.zip](https://github.com/firemodels/fds-smv/files/339787/7.zip)

**Comment by mcgratta** [comment]
I am running the case with FDS 6.5. This is the HRR:
[hrr.PDF](https://github.com/firemodels/fds-smv/files/341557/hrr.PDF)
I do see the asymmetry, but I do not believe that this is a bug in FDS. You are pulling air from the tunnel at a very high rate, and I am not surprised that the flow does not remain symmetric. If this were a real tunnel and these were real fans, I suspect the asymmetry would be even more noticeable because the fan flows would be dependent on local pressure gradients, which I suspect would not be the same.

```
DUMP DT_RESTART=...
```

does not work because there is no `&` in front of `DUMP'.

Yes, by default, FDS assumes a single step combustion reaction.

If you are not using FDS 6.5, I suggest you try it and report if your case develops a numerical instability.

**Comment by dy944533118** [comment]
Hello, I don't know the reason that you did not meet with automatic interruption but I did. I will continue to try to solve this problem. And now I want to ask you another question. You said that FDS assumes a single step combustion reaction, and this is my code about the reaction mechanism:
&REAC FUEL = 'PROPANE'
SOOT_YIELD = 0.01
CO_YIELD=0.04
HEAT_OF_COMBUSTION = 46460.
IDEAL=. TRUE./
So, for the 50MW fire (definition in my file), the mass flux of CO should be: 50000*0.04/46460=0.043kg/s. But I detect that the mass flux of CO is only about 0.02kg/s. I don't know what's reason of this problem, and I am sure the value I tested is correct. Can you help me have a look at what's the problem? Thank you sincerely.

**Comment by mcgratta** [comment]
What version of FDS are you using?

**Comment by mcgratta** [comment]
How did you calculate the mass flux of CO?

**Comment by dy944533118** [comment]
The version of FDS is 6.4. I calculate the the mass flux of CO in this way :50000*0.04/46460=0.043kg/s and I detect it by this means: &DEVC ID='CO_flow', XB=106.5,113.5,1.75,7.75,6,6, QUANTITY='MASS FLUX Z',SPEC_ID='CARBON MONOXIDE', STATISTICS='AREA INTEGRAL' /
The detection place is above the fire source. The location of fire is XB=108.5,111.5,3.75,5.75,1.5,1.5. 
The position of fire and  detection plane is showed in the below diagram:
![location of fire and detection plane](https://cloud.githubusercontent.com/assets/19992906/16494917/cbacdf36-3f1d-11e6-9480-f1b1c60f41f0.png)

**Comment by mcgratta** [comment]
Your detection plane is in the fire. The CO is generated as fuel is consumed. At the height of the plane, the fuel has not all been consumed, which is why you are seeing a lower mass flux of CO.

**Comment by dy944533118** [comment]
Hello, CO mass flux is 0.043 kg/s in theory. Now I'm testing net outflows of CO from my model, which is 12 exhaust ports and two openings on both ends. In the 600 s to 700 s (under stable conditions), the sum of them is only 85% ~ 90% of CO yield. I think it should be the problem of detection, so could you tell me whether this error is due to the accuracy of detection? Will the surface of detection move because of coarse grid? Thank you very much.

**Comment by mcgratta** [comment]
I would attribute this to numerical error. The method for calculating `MASS FLUX` only considers convective flux, and it calculates this using a central difference approximation, which is different than the more complicated flux limiting scheme used in the transport algorithm.

**Comment by dy944533118** [comment]
Dear mcgratta, thanks for your reply on the weekend. And there are still two unsolved problems, you know, 1: asymmetry which start in  600-800 seconds , 2: CO is imbalance between yield of fire and detective yield. My current example is a 380 meters long tunnel.  I ran the two examples that are two 220 meters long tunnels a few days ago, and there was not any problems. So I think it is FDS BUG. Why there is a problem sometimes and there is no problem at the other time? Could You answer me these two questions definitively? I don't think they are the errors, and such a big error is impossible in my opinion. It may be a superexcellent opportunity for the improvement of FDS. Thank you very much.

**Comment by mcgratta** [comment]
I'll address question 2 first. Here is a plot of the CO mass flux from the simulation of your case that I performed with FDS 6.5. In summing up the various channels of data, you must be careful to account for the sign. `MASS FLUX X`, for example, refers to the mass flux in the positive x direction. When I sum up all the `DEVC` columns reporting a mass flux of CO, except the first one, which reports the mass flux within the fire itself, I get this result:
[CO_plot.PDF](https://github.com/firemodels/fds-smv/files/346418/CO_plot.PDF)

Next, question 1. The boundary conditions at an `OPEN` boundary are based on the assumption that the computational domain opens up to an infinitely large volume at ambient pressure. Flow may enter or leave the domain through an `OPEN` boundary, depending on the nature of the flow field within the computational domain. The asymmetric flow pattern that you see is not necessarily a bug. It is a legitimate solution of the discretized Navier-Stokes equations solved by FDS. Your specified exhaust fans in the middle of the tunnel create relatively low pressures that draw fresh air in from both ends of the tunnel. Initially, the air is drawn more or less evenly from both ends of the tunnel. But eventually the air is drawn predominantly from one side because the initial flow field is intentionally made to be asymmetric. The fact that you get different solutions for different initial conditions is not surprising. Many phenomena in nature are like this -- weather patterns being a perfect example.

**Comment by dy944533118** [comment]
Dear mcgratta, thanks for your reply sincerely. Now, I know the asymmetry is a normal phenomenon. The imbalance of CO at the time of 600-800 seconds is just a stage, after more than 1000 seconds this problem becomes nothing. But I want to invite you to confirm a problem. I had many similar examples. Some occurred the asymmetric phenomenon but others did not. Some had the imbalance of CO at the time of 600-800 seconds and others did not in 600-800 seconds. Do you think this is normal? In other words, for the same example (the difference between two numerical examples is very small), there is a big difference in results. Do you think this is normal? Thank you very much.
[Desktop.zip](https://github.com/firemodels/fds-smv/files/350296/Desktop.zip)

**Comment by mcgratta** [comment]
Yes, instability is a common phenomenon in fluid mechanics.

**Comment by dy944533118** [comment]
Thank you very much. Are there the two problems in the example you calculated ? If it is true, I think the calculation result of FDS is incredible.

**Comment by mcgratta** [comment]
I attached the plot of the mass flux of CO above. This is not a problem. The asymmetry is also not a problem, in my opinion. If you think it is, conduct a full-scale experiment that proves otherwise.

**Comment by dy944533118** [comment]
Hello, I want to ask whether I can set up the mesh like this picture?

![mesh](https://cloud.githubusercontent.com/assets/19992906/16901877/3fd67c02-4c82-11e6-8e9c-58be4aaf5a78.png)

 One side of the mesh is intensive, the adjacent side is sparse. I drew the mesh in PyroSim and the export code of PyroSim is like this picture. 

![code](https://cloud.githubusercontent.com/assets/19992906/16901881/57ffd42c-4c82-11e6-95cd-caecef37b86d.png)

Then,I write the program “&MESH IJK=760,20,27,XB=-80,300,0.5,9.5,0,6.765/ 
&MESH IJK=760,4,27,XB=-80,300,-0.5,0.5,0,6.765/” in FDS. But the software  can't run.  
In addition, I have another small problem.The program “&DUMP DT_RESTART=100.0” in FDS can not achieve the function of automatic save. Could You answer me these two questions? Looking forward to your reply, thank you very much sincerely.

**Comment by mcgratta** [comment]
Start a new Issue. I am closing the existing issue.

**Comment by dy944533118** [comment]
OK, anyhow, thank you very much for your reply sincerely.
