### ISSUE TITLE
Error for thermally thick obstructions that span two meshes

### ISSUE THREAD

**Issue by pimvanrede** [firemodels/fds#4070]
Can someone help me with this error (see attachment). I'm trying to make a simple simulation using multiple meshes. The same model with just one mesh runs just fine. I've attached my inputfile as well. Thanks in advance!

![error](https://cloud.githubusercontent.com/assets/20352807/16681690/91648566-44f6-11e6-8381-91388e7597d0.PNG)
[Inputfile_oefening2a_FSEFSM_MPI.txt](https://github.com/firemodels/fds-smv/files/353780/Inputfile_oefening2a_FSEFSM_MPI.txt)

**Comment by foolstone** [comment]
Your meshes are overlapping each other. FDS didn't detect it and can't allocate some variables properly. You need to adjust your meshes to make it work.

**Comment by rmcdermo** [comment]
Actually, FDS allows overlapping meshes (in prep for someday doing two-way embedded meshes methods).  The problem here is related to the backside wall temp.

Kevin, run this case in debug and you will quickly see where it fails.  Probably some logic that needs to be tightened up or else, as foolstone suggests, trap this setup as being in error.

**Comment by rmcdermo** [comment]
BTW, mcgratta is out for a week, so it will be some time before this gets fixed.  In the mean time, as foolstone suggests, you might want to reorganize your meshes.

**Comment by pimvanrede** [comment]
Thanks guys. I'll try reorganizing the meshes.

**Comment by mcgratta** [comment]
This problem is more difficult than I first thought. I need some time to fix it. Here is a work-around. Set 

```
BACKING='VOID'
```

on each `SURF` line. This will stop FDS from trying to calculate the heat transfer from the front to back face of each obstruction. Your problem is caused by the exchange of heat conduction information within an obstruction that is touched by two meshes.

**Comment by pimvanrede** [comment]
Thanks!

**Comment by mcgratta** [comment]
I fixed the bug, commit #4120. This will be effective in the next maintenance release.

**Comment by mcgratta** [comment]
There is still a problem with the original case. I'll look at it.

**Comment by mcgratta** [comment]
Fixed. #4121.
