### ISSUE TITLE
Issue/Solution for VTT Validation using PARTICLES_PER_SECOND = 5000 

### ISSUE THREAD

**Issue by ChangminCao** [firemodels/fds#4122]
**Issue Description:**
The FDS default PARTICLES_PER_SECOND = 5000 does not generate a droplet size distribution that is specified in the input file. 
Figure 1 shows plot that were created from running the VTT Water Spray Validation input file LN02_1.fds with the PARTICLES_PER_SECOND = 5000 (see bottom plot). 
![default model results](https://cloud.githubusercontent.com/assets/20332448/17167010/16c5355a-540d-11e6-9a96-5f353d9184bd.png)

The reason for this issue is that the particle insert number per time step is too small to generate the desired droplet size distributions.

**Solution:**
One proposed method to solve the issue is to increase the number of particles inserted per time step by setting a minimum N_INSERT limit (by defining a new variable MIN_N_INSERT) in the particle injection process. For example when MIN_N_INSERT =7, particles will not be injected into the domain until the number of particles inserted per time (N_INSERT) reaches 7, which occurs after two or three time steps.  
Below plot is droplet size distributions using modified spray injection model.
 ![modified model](https://cloud.githubusercontent.com/assets/20332448/17167026/31342f72-540d-11e6-8602-056c68d96c66.png)

You may find the detailed information about the issue description, results discussion, solution and improved results in [FDS spray injection model issues.pdf](https://github.com/firemodels/fds-smv/files/385465/FDS.spray.injection.model.issues.pdf)

In order to use the new approach, the user should modify the following three files, read.f90, part.f90, devc.f90. See detailed information in [FDS source code modification.pdf](https://github.com/firemodels/fds-smv/files/385468/FDS.source.code.modification.pdf)

**Comment by rmcdermo** [comment]
Changmin,

Thank you for submitting this.  This looks like a reasonable solution to me.

@mcgratta @drjfloyd Please confirm and I will implement.  Thanks.

**Comment by drjfloyd** [comment]
Whether we insert 1 particle per step or 1,000,000 particles per step, over a sufficiently long period of time the mass distribution of the particles at the moment they are inserted should converge to the correct size distribution.  If that is not happening, doesn't that suggest we are doing something wrong in picking from the distribution?

**Comment by mcgratta** [comment]
Could you post the input file that you are using to generate the distributions above.

**Comment by rmcdermo** [comment]
@ChangminCao,
We have the input file.  But it would be good if you could show us exactly how you obtained the output.  Presumably the PDPA devices in our input file are not what you used.  Didn't you put special output in the code to get the distributions?

@shostikk @tstopi 
Kevin mentioned that there is a special binning process (default is 7 bins he says, probably not coincidentally) so that we do not over sample small droplets.  Should the fix involve reworking how this sampling is done?

**Comment by rmcdermo** [comment]
@ChangminCao 
OK, my apologies.  I see now in your writeup where you discuss how you coded up the output.  I will try to implement this as well.

**Comment by rmcdermo** [comment]
@ChangminCao 

There may be something wrong with your analysis.  I am not seeing the poor sampling that you report.  For 5000 PPS using the attached input file with my modified code (which I will point you to in a moment) I get the following results:

[LN02_1_cdf.pdf](https://github.com/firemodels/fds-smv/files/387060/LN02_1_cdf.pdf)

Here is the input file I used (note: I have reduced the gas phase resolution to make it run fast).

[LN02_1.fds.txt](https://github.com/firemodels/fds-smv/files/387063/LN02_1.fds.txt)

The source code I used has been pushed up to my fork on GitHub.  See the following commit:

350e042 FDS Source: implement particle sampling for Changmin (rmcdermo)

Here is a link to my fork:

https://github.com/rmcdermo/fds-smv

Here is the Python script I used to process the output and generate the plot.

[plot_cdf.py.txt](https://github.com/firemodels/fds-smv/files/387072/plot_cdf.py.txt)

I will consider this closed for now.  If you find that I have made a mistake let me know and I'll reopen.  Thanks.

**Comment by rmcdermo** [comment]
If it helps, here are the _cdf and _cdf_actual files I used to generate the plot.

[LN02_1_water drops_cdf_actual.csv.txt](https://github.com/firemodels/fds-smv/files/387099/LN02_1_water.drops_cdf_actual.csv.txt)

[LN02_1_water drops_cdf.csv.txt](https://github.com/firemodels/fds-smv/files/387100/LN02_1_water.drops_cdf.csv.txt)

![ln02_1_cdf](https://cloud.githubusercontent.com/assets/4418497/17191166/bf115db6-5416-11e6-9ab0-a602ab04f689.png)

**Comment by rmcdermo** [comment]
Minor error in my python script (that you would not notice).  Here is a fix.

[plot_cdf.py.txt](https://github.com/firemodels/fds-smv/files/387148/plot_cdf.py.txt)

**Comment by rmcdermo** [comment]
@ChangminCao 
OK, I see your point that we want to test the case with N_INSERT=1 particle per time step.  With the above input file, instead of running at higher resolution, you can run with fewer particles to test this.  So I ran with 1/10th the particles (500 PPS) and increased the time to 50 s to get the same number of total particles.  You are right, the distribution changes drastically.  See below.

![ln02_1_cdf](https://cloud.githubusercontent.com/assets/4418497/17216957/b444d1f2-54b0-11e6-934c-505f29cd75e2.png)

@mcgratta 
I think this points to the issue you were mentioning about sampling from the first bin at the start of every time step.  Let's look at this when I get in and see if we can fix it without adding a new parameter to PART.

**Comment by rmcdermo** [comment]
@ChangminCao 
I think I have this sorted out.  The problem was in the way PWT0 was being computed.  With 1 droplet per time step, we were effectively double counting the weights.  To fix this, I compute a true global weighting factor from the sprinkler input parameters.  I have modified the code in my fork [branch issue_4122](https://github.com/rmcdermo/fds-smv/tree/issue_4122).  Here are the results with 1 droplet per time step.

![ln02_1_cdf](https://cloud.githubusercontent.com/assets/4418497/17263383/cfa7d080-55ae-11e6-9899-298dee0fa199.png)

I also checked total volume flow rate and PPS.  Here are results:

0.34881883013  L/min
499.96  droplets per second

And I checked for different values of N_STRATA and the above source works.

We need to think about whether this same idea needs to be applied to other droplet insert subroutines.

All: please test and provide feedback.  Thanks.

**Comment by rmcdermo** [comment]
Just pushed up changes to the code to address this issue.  See pull request #4146.  The test cases are given in [droplet_distributions_2.fds](https://github.com/firemodels/fds-smv/blob/development/Verification/Sprinklers_and_Sprays/droplet_distributions_2.fds).

I'll let firebot chew on this tonight.  @ChangminCao please see if you can compile and test these changes.  Thanks.

**Comment by shostikk** [comment]
@rmcdermo 
When talking about "same idea", do you mean adding the stratified sampling, or ensuring correct PWT0 when N_INSERT < N_STRATA?

**Comment by rmcdermo** [comment]
I meant correcting PWT0.  But given last night's firebot warnings I am clearly not out of the woods on this.  I am only starting to understand all the code.  It's quite complex.

**Comment by rmcdermo** [comment]
I reverted the new weighting until I get the other verification cases sorted out.

**Comment by rmcdermo** [comment]
I believe this is sorted out now.  At least the verification cases in the FDS User Guide are happy.  @ChangminCao let us know if you see any problems with the current code.  I'll close for now.

**Comment by rmcdermo** [comment]
OK, but I *did* make a modification to the code to address your issue.  Please run the latest code against your specific test cases and let me know if you see problems.
