### ISSUE TITLE
High velocities caused by TMP_EXTERIOR on SURF_ID='OPEN'

### ISSUE THREAD

**Issue by Emmanuelfireengineer** [firemodels/fds#4156]
Dear all,

I’d like to understand how the parameter TMP_EXTERIOR on SURF_ID=’OPEN’ works. What I want to simulate is a building with a specific temperature inside which is different from outside.
-   Inside temperature : 24°C, set with &INIT XB=… /
-   Outside temperature : 40°C, set with &SURF_ID=’OPEN’, TMP_EXTERIOR=40/

The issue that I’m facing with is that air is supplied from the boundary at high velocities, around 4 m/s. In addition, it appears that the air is supplied from the lower part of the vent whereas I would expect it to come from the entire surface of the vent. At the end, this parameter simulates  wind/flow coming from the vent whereas I want to simulate a stationary temperature without any movement. What is surprising is that I only specify the temperature with TMP_EXTERIOR, there’s no velocity specified anywhere in the input file.

I tried to solve it by adding an &init region between the building and the boundary of mesh. Slice temperature shows a uniform temperature at the beginning of the simulation but there’s still some air supplied at high velocities from the vents.

An easy way to solve that would be to set up TMPA = 40 and an init region of 24°C for the area inside the building, but if I do that the obstruction, which is INERT, will be at 40°C also.
You’ll find attached an input file with the small case.

Thank you in advance to any one who may be able to give me some ideas.
[tmp_exterior.txt](https://github.com/firemodels/fds-smv/files/401819/tmp_exterior.txt)

**Comment by drjfloyd** [comment]
Per the User's Guide the INERT boundary condition is no species input and a temperature fixed at TMPA.

At the bottom of the domain you have rho_exterior and rho_interior determined by P_INF and TMP_EXTERIOR and TMPA.  At the top of the domain you have a new pressure (see 3.1 in the Tech Guide) based on stratification using TMPA.  The result is the exterior density gradient based on TMPA isn't matching what would really be there had the pressure lapse been based on 40 C. 

This is the same underlying issue as https://github.com/firemodels/fds/issues/2255

**Comment by herbertTau** [comment]
Concerning this issue I had the same problem with high velocities caused by TMP_EXTERIOR at open vents.

The attached example shows an area divided by a wall in the centre. All vents are open. The condition of the left part is that of TMPA (20°C) and the right part is different to TMPA. The temperature (TMP_EXTERIOR, INIT..., wall) is set to 0°C.

The velocity at the right part of the area is very high (see figure 1). The air is flowing from the top to bottom, allthough there should no airflow.

Another inconsistency as seen in fig. 2 is the temperature in the corners of the right part of the area (marked with circles).

Figure 3 shows the temperature profile from 0 to 0.04°C.

![figure1](https://cloud.githubusercontent.com/assets/27724706/25132638/7dce8c0c-244a-11e7-9cfd-e3f458e4a09f.jpg)
![figure2](https://cloud.githubusercontent.com/assets/27724706/25132639/7dd3648e-244a-11e7-9908-e37903b80b6d.jpg)
![figure3](https://cloud.githubusercontent.com/assets/27724706/25132640/7df09342-244a-11e7-90c9-d5c0951c8e41.jpg)

**Comment by mcgratta** [comment]
On the `SLCF` line set
```
&SLCF ..., CELL_CENTERED=.TRUE. /
```
This will color each cell with its `QUANTITY`, with no interpolation. What you see are artifacts of the interpolation routine.

**Comment by herbertTau** [comment]
Enclosed you will find my input parameters.

&MESH IJK= 40, 1, 40, XB= -1.0, 1.0, -0.01, 0.01, 0.0, 2.0 /
&INIT XB= 0.0, 1.0, -0.01, 0.01, 0.0, 2.0, TEMPERATURE=0 /
&TIME T_END=10.0 /
&OBST XB= -0.05, 0.05, -0.01, 0.01, 0.0, 2.0, SURF_ID6=,'wall_out' /
&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN', TMP_EXTERIOR=0 /
&VENT XB=0.0, 1.0,  -0.01, 0.01, 2.0, 2.0, SURF_ID='OPEN', TMP_EXTERIOR=0 /
&VENT XB=0.0, 1.0,  -0.01, 0.01, 0.0, 0.0, SURF_ID='OPEN', TMP_EXTERIOR=0 /
&VENT XB=0.0, 0.0,  -0.01, 0.01, 2.0, 2.0, SURF_ID='OPEN' /
&VENT XB=0.0, 0.0,  -0.01, 0.01, 0.0, 0.0, SURF_ID='OPEN' /
&SURF ID='wall_out',TMP_FRONT=0, TAU_T=0, COLOR='BLUE' /
&SLCF PBY=0.0, QUANTITY='VELOCITY', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.0, QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /

Right, the problem as seen in fig.2 has nothing to do with TMP_EXTERIOR.
