### ISSUE TITLE
Enhancement request: Radial spread from the edge of a circular vent

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#4404]
Here's one for the wish list. 

It's possible to create a square vent representing a burner and use "XYZ= ?,?,?" and "SPREAD_RATE" to start the fire at the edge of the burner and have it spread radially from the point over the square vent. (see attached)

However, I don't think it can be done with a circular vent, as "XYZ= ?,?,?" indicates the center of the circular vent. A radially spreading fire starts at the center. I can't figure out a way to start it at the edge, which I think is where a pool fire is more likely to start.

Thanks

[pool_fire.fds.txt](https://github.com/firemodels/fds/files/516408/pool_fire.fds.txt)

**Comment by mcgratta** [comment]
We're already overloading the parameters. We "borrowed" `XYZ` to designate the center of the circle, assuming that we'd only have spread from the center of the circle too. Have you thought about this:

> If you desire that the fire spread over an area that is not confined to a flat plane, specify XYZ and
> SPREAD_RATE on the SURF line directly and then apply that SURF line to the obstructions or particles over
> which you want the fire to spread. This technique can be useful for simulating the spread of fire through
> a cluttered space when the detailed properties of the materials are unknown, or when the uncertainties
> associated with modeling the pyrolysis of the solid fuels directly are too great.

**Comment by Dave-McGill** [comment]
Nope, but I'll give it a shot, and report back.

Thanks

**Comment by rmcdermo** [comment]
Dave,
Option B is this... VENTS can overlap and the the first one in the input file takes precedence.  So, if you so something like this:

&VENT ID='cover pool', XB=2.0,2.5,2.25,2.75,0.0,0.0, SURF_ID='INERT'/

&VENT ID='pool fire', SURF_ID='burner', XB=1.0,2.5,1.5,2.75,0.0,0.0, SPREAD_RATE=0.1, XYZ=1.7,1.6,0.0/

You get output like this:

![pool_fire_0182](https://cloud.githubusercontent.com/assets/4418497/19195343/3b1384e8-8c7f-11e6-85b1-316c58f9a7a0.png)

Since you are using Pyrosim (looks like) then perhaps this would be a good feature for them to add.

**Comment by Dave-McGill** [comment]
Kevin,

That worked.

Thanks

**Comment by Dave-McGill** [comment]
Randy,

I can't reconcile the input lines with the image. Can you send the file you used?

Thanks

**Comment by rmcdermo** [comment]
[pool_fire_2.fds.txt](https://github.com/firemodels/fds/files/516621/pool_fire_2.fds.txt)

**Comment by Dave-McGill** [comment]
Thanks
