### ISSUE TITLE
Check that PART and OBST give the same HRR for nominally the same problem

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4653]
Kevin,
This case comes from the discussion forum:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fds-smv/F7KByFgVMAU/IJr0I2lLAQAJ

The test case is given here:
[part_obst.fds.txt](https://github.com/firemodels/fds/files/716818/part_obst.fds.txt)

I have not looked at this closely, but I think the idea of getting nominally the same HRR for an OBST and PART would be a good verification case.  We might need to think about the limits where this should be true.  For example, in a large domain a single cell OBST should be nearly identical to a particle split with 6 IORs.

**Comment by mcgratta** [comment]
This input file demonstrates that a 0.1 m by 0.1 m by 0.1 m "plate" burning on top and bottom releases the same amount of heat as a solid obstruction with the same dimensions burning on top and bottom. But the peak HRR is different, as is the time to burn-out. The reason is that the radiative and convective heat flux above the specified 50 kW/m2 is going to be different because the particle occupies no volume in the FDS flow calculation. These Lagrangian particles are not designed to be the same size as a grid cell. They are purely sub-grid. I don't want to put the case in FDS Verification Guide because there are now many examples of mass conservation for burning particles and obstructions, including plates.
```
&HEAD CHID='part_obst', TITLE='Comparison of burning particle and obstruction' /

&TIME T_END=200. /

&MESH IJK=10,10,10, XB=0,1,0,1,0,1 /
&MESH IJK=10,10,10, XB=2,3,0,1,0,1 /

&REAC FUEL='PYROLYZATE', C=6, H=10, O=5, SOOT_YIELD=0.01 /

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMIN', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /

&SURF ID='SAMPLE_P'
      LAYER_DIVIDE=0.025,
      EXTERNAL_FLUX = 50,
      LENGTH=0.1, WIDTH=0.1,
      THICKNESS = 0.05
      BACKING='INSULATED'
      MATL_ID='WOOD' /

&MATL ID    = 'WOOD'
      EMISSIVITY  = 0.9
      DENSITY      = 400
      CONDUCTIVITY = 0.2
      SPECIFIC_HEAT = 1.0
      N_REACTIONS  = 1
      REFERENCE_TEMPERATURE = 395
      PYROLYSIS_RANGE      = 190
      NU_SPEC       = 0.75
      SPEC_ID       = 'PYROLYZATE'
      NU_MATL       = 0.25
      MATL_ID       = 'CHAR'
      HEAT_OF_REACTION     = -500. /

&MATL ID             = 'CHAR'
      DENSITY        = 100
      EMISSIVITY     = 1
      CONDUCTIVITY   = 0.2
      SPECIFIC_HEAT  = 1.0 /

&OBST  XB=0.5,0.6,0.5,0.6,0.2,0.3, SURF_ID6='INERT','INERT','INERT','INERT','SAMPLE_P','SAMPLE_P' /

&PART ID='wood', SURF_ID='SAMPLE_P', STATIC=.TRUE., ORIENTATION(1:3,1)= 0,0,1, ORIENTATION(1:3,2)= 0,0,-1 /

&INIT ID='FL1', PART_ID='wood', XYZ=2.5,0.5,0.3, N_PARTICLES=1, CELL_CENTERED=.TRUE. /

&DEVC ID='HRRP', QUANTITY='HRR', XB=0,1,0,1,0,1  /
&DEVC ID='HRRO', QUANTITY='HRR', XB=2,3,0,1,0,1  /

&TAIL /
```
