### ISSUE TITLE
simple burn away example

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4727]
I tried to follow the user guide and set up a simple burn away case.  I would expect the input file below to quit issuing fuel at 10 s.
[simple_burn_away.fds.txt](https://github.com/firemodels/fds/files/774919/simple_burn_away.fds.txt)

**Comment by mcgratta** [comment]
Add `BURN_AWAY=.TRUE.` to the `SURF` line and only put `SURF_ID='my surface'` on the `OBST` line. Also, no need for `BULK_DENSITY` in this case. When talking about `BURN_AWAY`, the User's Guide says:

If BURN_AWAY is prescribed, the SURF should be applied to the entire object, not just a face of the object
because it is unclear how to handle edges of solid obstructions that have different SURF_IDs on different
faces.

All this being said, I think the code should work without `BURN_AWAY` to just stop the burning. Most people just do this with a `RAMP`. I'll see if it can be done.

**Comment by mcgratta** [comment]
I checked the User's Guide again and it says that when one specifies the HRR or MLR, one needs to use a ramp to turn off the fuel. I added some more explanation to this to make it clearer.
