### ISSUE TITLE
Running on windows but not on linux

### ISSUE THREAD

**Issue by RakeshRanga** [firemodels/fds#4780]
Hello !!

I am trying to run the following code. It is running in windows but not in linux.
It is giving the error
forrtl: severe (174): SIGSEGV, segmentation fault occured
In both the windows and linux, i am using FDS 6.5.3.

[pmma_downward.pdf](https://github.com/firemodels/fds/files/814785/pmma_downward.pdf)

**Comment by sbenkorichi** [comment]
Hi RakeshRanga,
I believe your issue lies with the non matching of your meshs of your two first lines with the rest. (i.e. with the Z one). You are using 5mm for that, however for the first two lines it's different that's why you might result in that issue. I've changed the two lines to 5 mm, and it works fine. Try to replace your two lines with these:
&MESH IJK=52,6,30,XB=0.014,0.066,0.005,0.0065,0,0.150 /
&MESH IJK=26,6,20,XB=0.014,0.066,0.005,0.0065,0.150,0.250/

Kind regards,
Salah
