### ISSUE TITLE
Add parameters/namelists to FDS to provide an API for simulation of fire in vegetation

### ISSUE THREAD

**Issue by tmilac** [firemodels/fds#4790]
We would like to extend the FDS API (Namelists) to accommodate parameter specification customarily used by the wild land fire community.

FDS specifies:
a) Material fractions (MATL_MASS_FRACTION in SURF)
b) MASS_PER_VOLUME (in INIT): the net mass of *wet fuel* per volume

In the wild land fire community, the material parameters are specified differently.  

WFDS specifies:
a) moisture fraction (MOISTURE)
(mass before drying - mass after drying) / (mass after drying)
The moisture fraction is specified for each dry fuel component separately.
b) Bulk density (BULK_DENSITY): net mass of *dry fuel* per volume

The mapping from WFDS -> FDS terms is as follows.

MASS_PER_VOLUME           = MOISTURE * BULK_DENSITY + BULK_DENSITY
material fraction of water    = MOISTURE * BULK_DENSITY / MASS_PER_VOLUME
material fraction of dry fuel = BULK_DENSITY / MASS_PER_VOLUME 

In addition to these new parameters, certain defaults must be (re)set to correctly simulate fire in vegetation.

a) ALLOW_SHRINKING=.FALSE.
b) ALLOW_SWELLING=.FALSE.
c) N_PARTICLES_PER_CELL=1
d) CELL_CENTERED=.TRUE. (this may already be the default)

**Comment by rmcdermo** [comment]
Thanks, Tom.  Looking into read.f90, it looks like there is no longer a VEGE namelist.  But there are several VEGETATION_ parameters on SURF.  There is a LOGICAL parameter VEGETATION.  If T, you can make all these conversions above.  Do you want to give this a go and send us a pull request?

**Comment by tmilac** [comment]
Hello Randy,
I can certainly do that.  Along with the code changes, I will
document the reassignment of defaults etc in a separate
chapter of the Users Guide dedicated to vegetation.

Thanks,
Tom

**Comment by mcgratta** [comment]
I suggest we start with the User's Guide chapter on vegetation. In this chapter, we would explain how to create a tree, for example, using the existing FDS namelist groups. We do this for most things. For example, a sprinkler is 
```
&PROP ID='K-11', QUANTITY='SPRINKLER LINK TEMPERATURE', RTI=148., C_FACTOR=0.7,
ACTIVATION_TEMPERATURE=74., OFFSET=0.10,PART_ID='water drops', FLOW_RATE=189.3,
PARTICLE_VELOCITY=10., SPRAY_ANGLE=30.,80. /
&DEVC ID='Spr_60', XYZ=22.88,19.76,7.46, PROP_ID='K-11' /
&PART ID='water drops' ... /
&SPEC ID='WATER VAPOR' /
```
A tree would be described in a similar way. Once we write down how to specify these objects using the current parameters, we can talk about useful shortcuts to define moisture and dry/wet mass per volume. In some cases, it might be easiest to just write the conversion formulae in the User's Guide, like how to convert moisture fraction into a material mass fraction for water. 

In older versions of FDS, we used to have namelist groups for sprinklers, heat detectors, different kinds of fire protection devices, cables, trees, and so on. With each new project we took on, or new area of interest, we'd add more namelist groups. The problem was that many of these items were closely related, and yet required duplicate code to parse the different namelist groups. So we decided to work with more "primitive" namelist groups and create the various things in the model from the basic components. 

Also, there is a company, Thunderhead Engineering, that makes a GUI for FDS. We have left it up to them to develop the additional layer of logic to help users assemble things. Thus, if one were to use their product, PyroSim, one would just specify a sprinkler with properties X,Y,Z and PyroSim would write out the appropriate FDS input lines. 

So let's write the chapter on vegetation first, and then decide what shortcuts to introduce directly into read.f90 and what conversions can be done by the user.
