### ISSUE TITLE
Unintended pressure leak between ZONEs

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#4796]
Hi, I modelled a tunnel with two compartments. The big one has dynamic pressure from one end to other (both OPEN). 
The narrow and adjacent tunnel has no opening to the big tunnel. 

However, you can see (pressure slice file) within a minute the pressure in the narrow tunnel is being affected by the pressure in the big tunnel. 

These two compartments have two ZONEs assigned. 

The issue #3002 seemed related yet I posted this to show a simpler case. 

Please let me know if I am using the ZONE feature in a wrong way. (Initial aim was to see the pressure profiles when I open some doors between two tunnels. )

Thank you for your help. 
[tunnel.txt](https://github.com/firemodels/fds/files/824861/tunnel.txt)

 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-598-geb56ed1

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
Add this line to your input file
```
&PRES MAX_PRESSURE_ITERATIONS=50, VELOCITY_TOLERANCE=0.01 /
```
Also, remove the `ZONE` lines. Pressure zones are not necessary when the domain is `OPEN` to the exterior, because that automatically makes the background pressure go to ambient. The `PRES` lines will tighten up the pressure solver. The way FDS solves the pressure, the flow is not exactly zero at solid surfaces. However, this line forces the error to be less than the default. Try increasing the `PRESSURE_ITERATIONS` and decreasing the `VELOCITY_TOLERANCE` until the spurious velocity is tolerable. Of course, this will increase the CPU time, so experiment with a few different values. There's more discussion of these parameters in the User's Guide. Let me know if this works for you.

**Comment by Er9y714** [comment]
Thank you for your answer.  I tried your suggestion, it did not work. Then I reduced the tolerance and increased the iteration number. Also I decreased the time step from 0.3 to 0.01 s. That also did not work.  I still measure pressure differences and fluctuations which is synchronised with the other compartment. 

I also added DEVC to measure, in case smokeview shows the wrong values. But the devices are also showing the same result. 

Do you have any other suggestions?

**Comment by mcgratta** [comment]
This will not eliminate the velocity in the second tunnel. It should reduce it. Does it?

**Comment by Er9y714** [comment]
I had focused on pressure. I realised it does not have a big impact on velocity indeed. 
Tightening the tolerances also helps it. 

Thank you for your time and help. I have a better insight now.

**Comment by mcgratta** [comment]
Thanks for letting me know. The pressure solver and tight tolerances are a particular problem for tunnels that have no leakage. We are working on improving the pressure solver for these kinds of cases, but for the moment, you just have to tighten the tolerance yourself.
