### ISSUE TITLE
Documentation for HVAC_PRES_RELAX

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4832]
Jason,
I did not find this in the user guide.  If this is solving problems, then perhaps we should set it as a default?  I think instabilities are more problematic then 10% time hit.

**Comment by drjfloyd** [comment]
I'll add it to the guide, thanks for catching that I hadn't done so yet.

I don't think we want the value I had suggested for that particular case as the default.  This parameter dictates how the node pressure used as the boundary condition for the HVAC solver evolves from time step n to n+1 based upon the pressure in the FDS domain at the HVAC inlet/outlet (P_fds):  

P_node(n+1) = P_node(n)*HVP + P_fds(1-HVP).   

We do want the HVAC flows to be able to quickly respond to pressure changes due to a fire.  In order to avoid having the HVAC system lag too much, we generally don't want HVAC_PRESS_RELAX to be very close to 1.  For a typical HVAC system the inlet/outlet area is very small compared to the size of the compartment (a 10 ft x 10 ft x 10 ft office with one 2x2 inlet and one 2x2 outlet has HVAC vent areas that are ~1 % of the wall area). This means having a rapid change in the duct velocity should not cause an instability as the total volume flow should be small compared to compartment volume and not result in a large change in the bulk pressure.

For the case that this issue is referring to, the vent sizes are relatively large compared to the size of the compartment. The HVAC pressure solution is not directly coupled to the FDS pressure solution. With the very large vent area, a rapid change in the HVAC solution results in large change in the bulk pressure in FDS which then feeds back into another rapid change in HVAC and ultimately results in an instability.

**Comment by rmcdermo** [comment]
I notice now that the default is HVAC_PRES_RELAX=0.5.  Do I understand correctly that setting a lower value would slow the HVAC response to FDS compartment pressures, but might also help stability?

**Comment by drjfloyd** [comment]
The cases where this issues seems to arise are cases where people are defining inputs that do not comport to typical commercial or residential HVAC systems (like trying to use HVAC to represent full faces of tunnels).

Slowing the HVAC response in itself can result in instabilities, and that has been observed in prior issues.  If we get a large compartment pressure rise in a small space that isn't vented rapidly due to HVAC lagging, then we wind up overshooting the duct velocity and we drive the compartment pressure below ambient.

**Comment by rmcdermo** [comment]
I probably sound like  broken record... but I wonder if the relaxation trick could be used here.  Algorithm would be:

1. Compute steady-state duct flows (EQ)
2. Formulate ODEs as relaxation models
3. Take time constant from small FE step
4. Take DT_HVAC in a relaxation step toward EQ.

Maybe a thought for extreme cases.

**Comment by drjfloyd** [comment]
Should I prioritize developing a new HVAC solver over extinction?

**Comment by rmcdermo** [comment]
No, I would just keep this on the shelf if we feel like HVAC instabilities are becoming too much of a problem.  Always in the hunt for a more stable code.

**Comment by rmcdermo** [comment]
Closing for now.
