### ISSUE TITLE
Mock furnace temp curve with HT3D

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4857]
From user forum:

I have performed several simulations with multi layers and it works well when I used a hot vent to heat the solid (like the ibeam validation case).
 
 However, my goal is to use a gas temperature profile (ISO-834) to heat the material (like in a furnace), so I used ASSUMED_GAS_TEMPERATURE to pilot the gas temperature but the material temperature does not increase at all. I also tried to initialize the gas temperature (INIT = 1000°C) close   to the obstruction but it does not work.
 
Have you an idea to heat the solid obstruction with a hot gas ?
[Test_cond.fds.txt](https://github.com/firemodels/fds/files/863113/Test_cond.fds.txt)

**Comment by rmcdermo** [comment]
We do not have a direct way to implement ISO 834 in FDS.  So, I've played a trick by applying the time-temperature curve on an OBST that is made up of GAS.  I applied gas properties to this gap and specified the CONDUCTIVITY to be h*dx.  The input file and image are shown below.  This is 2D for now.  Will this work for your purposes?

[test_2d.fds.txt](https://github.com/firemodels/fds/files/865422/test_2d.fds.txt)

![test_2d_0137](https://cloud.githubusercontent.com/assets/4418497/24258340/d57724b4-0fc3-11e7-9c96-02654095cfef.png)

**Comment by sbenkorichi** [comment]
Hi Randy,
Thanks for this work, for somehow, I test the file attached by you, but I still get only 5 c as temperature. 
Please have a look at the attached image.

![temp](https://cloud.githubusercontent.com/assets/20113030/24259625/56f141f8-0fe9-11e7-8207-fc11f33e8149.PNG)

**Comment by sbenkorichi** [comment]
I've just had to enable it from the dialogue box to show its value.
Sorry for that, now it's showing the data.

![temp](https://cloud.githubusercontent.com/assets/20113030/24260861/13206388-0fed-11e7-9441-8e1da8b6cd37.PNG)

**Comment by rmcdermo** [comment]
Salah,

The shortcut for this is Alt-r, which toggles between the default and "research" mode (show full range of whatever quantity).

Part of the problem with HT3D cases is that since we are still in development we have not set up Smokeview to consider the values inside the OBST when it computes its bounds.  This will eventually change.

**Comment by sbenkorichi** [comment]
Thanks for the info Randy.

**Comment by tkorhon1** [comment]
Hi!

I have modelled ISO oven like:

&ZONE XB= 0.0,1.250, -0.15,0.00,  0.0,0.2, LEAK_AREA(0)=0.1 /

&SURF ID=        'OVEN_ISO',
      COLOR=     'RED',
      TMP_FRONT= 1049.039569,
      RAMP_T=    'ISO',
      HEAT_TRANSFER_COEFFICIENT=10000.0,
      LEAK_PATH=1,0,
      DEFAULT=.TRUE. / 

&RAMP ID='ISO', T= 	0	 , F= 	0.019065	 / 	20
&RAMP ID='ISO', T= 	10	 , F= 	0.140082	 / 	146.9519909
and so on for the ramp...

Sometimes, I have put a "burner" as a VENT that blows ISO temperature
gas to the oven (and somewhere exhaust tubes without the leak path):

&SURF ID='OVEN_ISO_VEL', COLOR='CYAN',
      VEL=        -5.0,      RAMP_V='Burner_vel',
      TMP_FRONT=1049.039569, RAMP_T='ISO' / 
 
&RAMP ID='Burner_vel', T=   0.0, F=0.0 /
&RAMP ID='Burner_vel', T=   1.0, F=1.0 /
&RAMP ID='Burner_vel', T=7200.0, F=1.0 /

These simple models are missing the effect of the burner flame, i.e, the
radiation from the flame. The actual (plate thermometer) exposure in real
oven might be higher at the start of the test. If you model plates in the
model furnace, they heat up rather slowly, i.e., they lag the ISO curve.
If you model gas phase thermocouples, they react much faster in the
simple FDS model, i.e., you get ISO hot gas using this simple model.

TimoK

**Comment by sbenkorichi** [comment]
Timok,
Aren't the plate thermometers modelled using AST ?

**Comment by tkorhon1** [comment]
Well, the plates have some inertia. T_AST is not what is inside the metal of the plate. The metal
sheet has mass. I have made some furnace models, where I have about one metre of air in
front of the sample (vertical partition as a test specimen) and place thin OBSTs (one grid cell
face size) in front of the test specimen at some distance. The SURF of the thin OBST has the
real plate metal properties and below the insulation (if it is on the other side of the plate).
It was a couple of years ago, I do not remember right now, what kind of things the plates
really are...

I have also measured in the simple model the T_AST at the test specimen surface and using
my inputs, the T_AST at the specimen surface follows quite nicely the ISO temperature curve.
The furnace surfaces are following the ISO curve => radiation to the specimen from the furnace
walls follows ISO temperatures. Also the gas temperature (I have also measured it) follows quite
well ISO curve (a small lag, but not much, the high heat transfer coefficient of the furnace
walls heat the air quite fast. And in a "big model" I have some HVAC stirrers that move the
air around. (In some cases I just blow ISO hot air and have somewhere outflow hole, i.e.,
exhaust duct.)

But, as I said, it seems that the real furnace experiment exposure within the first couple
minutes is probably higher than the exposure in my model that gives the T_AST that is following
the ISO curve. The plates are heating up faster in the real experiment than in the model. After a couple
of minutes the ISO curve is not rising so fast and the time lag is much less.

I did not experiment too much different options for the first minutes. But it might be that
the burner flames have some effect. The flames are radiating. So, it might be that in the
start of the furnace experiment, the radiation field inside the furnace is not the field of
ISO temperature furnace. I.e., the flames emit more energy as radiation than the ISO
temperature walls would.

TimoK

**Comment by sbenkorichi** [comment]
Hi TimoK,
If you have access to IAFSS documents, there is a good paper by ULF WICKSTRÖM, who discuss it. Check his explanation under Fig. 8
http://www.iafss.org/publications/fss/9/1227/view/fss_9-1227.pdf

Regards,
Salah

**Comment by bmralph** [comment]
Timo, is your furnace modelling work documented/published anywhere?

I've always been interested in the differing thermal exposure (which is
meant to be standard) for different furnaces with different wall materials
and different dimensions - hence different radiation, convective
coefficient. Did you trial different geometries? Why did you adopt this hc?


On 28 Mar 2017 08:32, "Salah Benkorichi" <notifications@github.com> wrote:

Hi TimoK,
If you have access to IAFSS documents, there is a good paper by ULF
WICKSTRÖM, who discuss it. Check his explanation under Fig. 8
http://www.iafss.org/publications/fss/9/1227/view/fss_9-1227.pdf

Regards,
Salah

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/firemodels/fds/issues/4857#issuecomment-289687471>, or mute
the thread

**Comment by tkorhon1** [comment]
Thanks for the paper link. 

I have not published the furnace model anywhere. It was done in a EU funded
project FIRE-RESIST some years ago. The project is finished, so its final report should
be somewhere in the net, well Google says: http://www.fire-resist.eu/FireResist/index.xhtml

I did not want to model a real furnace. I just wanted ISO temperature oven model. I.e.,
a furnace that:

 1) wall temperature is the ISO temp. curve
 2) gas temperature is the ISO temp. curve

So, this should generate a T_AST that is following the ISO curve. And it did.
Here T_AST means for flat specimen. If the specimen had non-flat geometry,
then the view factors makes the specimen to see itself, of course, and the
T_AST is lower than the ISO curve. (Specimen is colder than the ISO curve.)

Well, I added some "stirrers" or blowers and outflow ducts. Why? I wanted that the
air moves inside the furnace model (note: the real large furnace was not modelled
completely, the air space was quite small for CPUs reasons, of course). Moving
air => the heat transfer coefficient might be better at the specimen, because in 
the real furnace the air is moving due to the burners.

Wbr,
TimoK

**Comment by bmralph** [comment]
Thanks for the link and information Timo :)

On 29 Mar 2017 09:29, "TimoK" <notifications@github.com> wrote:

Thanks for the paper link.

I have not published the furnace model anywhere. It was done in a EU funded
project FIRE-RESIST some years ago. The project is finished, so its final
report should
be somewhere in the net, well Google says: http://www.fire-resist.eu/
FireResist/index.xhtml

I did not want to model a real furnace. I just wanted ISO temperature oven
model. I.e.,
a furnace that:

   1. wall temperature is the ISO temp. curve
   2. gas temperature is the ISO temp. curve

So, this should generate a T_AST that is following the ISO curve. And it
did.
Here T_AST means for flat specimen. If the specimen had non-flat geometry,
then the view factors makes the specimen to see itself, of course, and the
T_AST is lower than the ISO curve. (Specimen is colder than the ISO curve.)

Well, I added some "stirrers" or blowers and outflow ducts. Why? I wanted
that the
air moves inside the furnace model (note: the real large furnace was not
modelled
completely, the air space was quite small for CPUs reasons, of course).
Moving
air => the heat transfer coefficient might be better at the specimen,
because in
the real furnace the air is moving due to the burners.

Wbr,
TimoK

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/firemodels/fds/issues/4857#issuecomment-290020414>, or mute
the thread

**Comment by sbenkorichi** [comment]
Timo,
Recently ULFWICKSTRÖM has shared another work on it, you might find it interesting.
You can check it out here : 
https://www.researchgate.net/publication/315790513_Measuring_Incident_Heat_Flux_and_Adiabatic_Surface_Temperature_with_Plate_Thermometers_in_Ambient_and_High_Temperatures

**Comment by sbenkorichi** [comment]
The user doesn't come back. I believe this should be closed. If he needs more info, he/she can request it.

**Comment by Benkorichi** [comment]
Mdr
