### ISSUE TITLE
Problem with a simulation of a fire in air tigh building.

### ISSUE THREAD

**Issue by ChristianMebus** [firemodels/fds#5003]
Hi Everyone

I’m writing my master thesis where the scope is to investigate if smoke propagation through the ventilation system in an air tight compartment where the window will stay intact.

The building is a 10 storey building where the simulated room is 5 x 5 x 3 m with a grid size of 0.10 x 0.10 m. The grid size is not important because it is the pressure rise in the room that matter.

The ventilation system in the building is made with the HVAC module and is a duct system that has connection to every floor with an exhaust fan on the top of the building. All connection to the floors that are not simulated are ambient and for the compartment to a VENT. There is no problem with the ventilation system, this part of the simulation has been is working well.

The fire that are simulation is a 1 m2 square placed on the floor in the middle of the room. It is a small fire with a HRRPUA of only 196 kW with a TAU_Q of 60 sec. This is because that the only the room has a constant extraction of air and smoke through the ventilation system, and due to pressure rise the volume flow of the exhaust if only increasing with the fire. The only intake of air to the room is the through a small OPEN VENT in a finer mesh located on the wall of the compartment.

[inputfile1.txt](https://github.com/firemodels/fds/files/955377/inputfile1.txt)

The problem is that the simulation is crashing when reaching about 40 sec. I have theory but I’m not sure if it is correct. The pressure rise the air is flowing out of the room both through the exhaust system and the intake OPEN hole. This causes to low oxygen level in the room for the fire to burn. But im not sure if this causes the simulation to have an error?

 I’m not sure yet if it is okay for me to share my files, but please ask if there are more information that are needed. I will link a picture of the SMV view of the room.

I Hope that one of you could help me on this matter or maybe discuss the subject more with me here! 😊

Kind Regards

Christian Laustsen

**Comment by rmcdermo** [comment]
I'm looking at it.  But it is taking me time to clean up the file.

**Comment by ChristianMebus** [comment]
Thank you! :)

And I'm sorry for the messy input file.

**Comment by rmcdermo** [comment]
Jason,
I've reproduced the instability with the latest code.  Can you have a look at the input file and see if you see any obvious problems.  Thanks.

[room.fds.txt](https://github.com/firemodels/fds/files/956050/room.fds.txt)

![screen shot 2017-04-25 at 1 57 56 pm](https://cloud.githubusercontent.com/assets/4418497/25400064/72e0fad0-29bf-11e7-8c65-363205909b29.png)

**Comment by drjfloyd** [comment]
You have a very oddly shaped fan curve:
1) No stall pressure (e.g T=0 at some pressure F > 300).
2) At a pressure of 150 Pa across the fan your curve states the flow is all values between 0.28 and 0.42 m^3/s.  Either the 150 at 0.28 needs to be larger or the 150 at 0.42 needs to be smaller.
3) From no pressure across the fan to 120 Pa you only show a change in flow rate of 0.001 m^3. 

Are your duct lengths correct?  A 10-story building is going to be around 40 m tall but you are showing duct lengths of 120 - 200 m.

Your infiltration is an OPEN vent that has a hole that is a single cell into the compartment.  This means the compartment is directly connected to an OPEN vent and you don't have a separate pressure zone.  You might want to define the entire infiltration area as leakage. This would have the advantage that you could make the grid size the same as the room and your run time would be faster.

You don't have any way for flow to get into the ventilation shaft since you are modeling that flow with HVAC ducts. The pressure solver is still trying to solve for pressure in that shaft which should stay at ambient. The pressure in the room however is negative from the HVAC system.  So you have a sizable gradient forming at the wall to the shaft.  Since you don't have flow, you can reduce velocity errors across that wall by just filling in the shaft.

I made some changes to reflect some of my comments above and restarted.  After 134 s it is still going strong and not showing any issues with strange pressure or flow behavior.

[room_2.fds.txt](https://github.com/firemodels/fds/files/956797/room_2.fds.txt)

**Comment by ChristianMebus** [comment]
Thank for the help to both of you! :)
I will take a look at it, abd maybe return with some more questions :)

**Comment by ChristianMebus** [comment]
Hi Drjfloyd

The reason why the duct length are varying, are because that I could not regulated the ventilation system with the function LOSS. So instead I used that the program calculated to friction loss from the area and the length.

The new code also worked for me. My problem is that the LEAK_AREA=0.04 is way too high for the air tight building I’m simulating. I will have LEAK_AREA that ranges between 0.0013 and 0.0027 m2.

So when I insert this the simulation crashes again at around 30 sec. I also remove the DYNAMIC_PRESSURE to ensure that this is not causing the problem.

Do you know if these small LEAK_AREA could cause the simulation to crash?

**Comment by drjfloyd** [comment]
If I take the file I uploaded and change the AREA on the leakage duct from 0.04 to 0.002, it seems to run fine. It is out to over 50 s with no signs of issues.  Are you running the current version of FDS?

**Comment by sbenkorichi** [comment]
Jason,
I think this should be closed. The user can comment back if he has more to add.

**Comment by sbenkorichi** [comment]
Thanks !
