### ISSUE TITLE
Slice blockage in SMV

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5091]
Glenn,
Could you please take a look at this case. 
When I load the x direction of tmp I can see the evolution of it inside the solid, whereas in the y and the z direction I have to go through show/hide and then use the show slices in blockage. 
Why does the x direction show what's inside and not y and z? 

The input file submitted by Randy can be found here. 
https://github.com/firemodels/fds/pull/5089/commits/aeb8624286658a537d527fbb7a1c1c196d2d3f43

**Comment by gforney** [comment]
I"ll take a look at it

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

note the problem was that smokeview was displaying slices inside a blockage (for the x slice) when it shouldn't have.  smokeview by default does not display slices in blockages.  I added a keyboard shortcut, 'I' that toggles the visibility of slices in blockages

**Comment by sbenkorichi** [comment]
Thanks Glenn !

**Comment by sbenkorichi** [comment]
I've tested the Linux dist and it no longer shows it.

**Comment by gforney** [comment]
are you saying it works or does not work on linux?

**Comment by sbenkorichi** [comment]
I meant it's fixed now. That's why I've closed it. It shouldn't show what's inside the solid as you said, that's why I had to report it.
