### ISSUE TITLE
PR_GAS on SPEC line does nothing

### ISSUE THREAD

**Issue by tstopi** [firemodels/fds#5100]
Two issues:

First: Setting PR_GAS on SPEC line does not affect the thermal conductivity 

So setting 
&SPEC ID='METHANOL', PR_GAS=0.93/
Gives the same thermal conductivity of the gas as
&SPEC ID='METHANOL'/

Second: PR_GAS for METHANOL in data.f90 seems to be excessively large (9.5). For other gasses PR < 1.  I don't have access to the book where this value is from, nor do I know what the value should be but perhaps this is PR for a liquid and not gas ?

**Comment by drjfloyd** [comment]
I'll take a look at the conductivity issue.  On the 9.5, this is probably a typo (9.5 v .95).

**Comment by rmcdermo** [comment]
I take it this means I need to kill the methanol cases I have running for MaCFP?

**Comment by rmcdermo** [comment]
Topi,
If you have modifications you need to make to the Waterloo input files, please so so asap.  Thanks.

**Comment by tstopi** [comment]
The thermal conductivity of the gas will be off with the current code not
sure how big the difference.

Changing the input files won't help as PR_GAS does nothing. I guess I could
make a RAMP , but I don't really have data for thermal conductivity of
methanol.

**Comment by rmcdermo** [comment]
OK, I'll wait for Jason to investigate.

**Comment by drjfloyd** [comment]
The 9.5 was a typo.  It should be 0.95. I will push this up after this comment. 

The logic for PR_GAS was coded to let one define PR for an unknown species, it isn't replacing the PR for a known species.  This is why it didn't have any effect.  Do we want it to override a known species?

The values of conductivity computed using PR_GAS , SIGMA, and EPSOK are only used in transport if the mode is DNS or RESEARCH, otherwise it is MU*CPOPR where CPOPR is based on the background CP and the PR set on MISC.  The computed values are used for surface heat transfer and droplet evaporation.  Since you are using research mode you would be using incorrect conductivity numbers; however, the net impact may not be large since the error would be proportional to the methanol vapor concentration which is likely not large in most locations in the domain.

**Comment by tstopi** [comment]
Thanks. I don't know if user should be able to change the PR_GAS psrameter.
However the usrer guide seemed to imply so.

The difference in results will probably not be huge for the reasons you
mentioned.  At lesst not with prescribed burning rates.

It could hsbe some effect on predicting the burning rates. However initial
testing suggests otherwise.

**Comment by rmcdermo** [comment]
Jason,
For now, let's just clarify the user guide.

Topi,
I will rerun Waterloo with new source.  Are you running the cases too?  Am I duplicating work?

**Comment by tstopi** [comment]
I am running the cases up to 0p25 mm

**Comment by rmcdermo** [comment]
OK, thanks.  Make sure you double check the global radiant fraction output.  Plot Q_RADI/HRR and make sure it gives you what you input.  We have been having problems with this.

I'll see if I can get the 1.25 mm cases finished, but I am not optimistic.
