### ISSUE TITLE
getting forrtl: severe (174): SIGSEGV, segmentation fault occurred 

### ISSUE THREAD

**Issue by zladicolor** [firemodels/fds#5117]
[test7.docx](https://github.com/firemodels/fds/files/1026048/test7.docx)

Hello, i'm getting the error at t= 45s and i'm using now the FDS version 6.5.3

Thanks very much

**Comment by mcgratta** [comment]
I have reproduced the error. It has to do with HVAC. I am going to rerun with the latest version of FDS to see if the problem has been fixed. 

Jason, FYI, the code seg faults at the line
```
IF (PROCESS(1)==MYID) CALL HVAC_CALC(T,DT,FIRST_PASS)
```
I don't have a specific line within the HVAC routine.

**Comment by mcgratta** [comment]
You have not specified a `LOSS` or a `ROUGHNESS` for the `DUCT`s. This can lead to numerical instabilities within the `HVAC` routine. Add either loss or roughness to your ducts. Let me know if that fixes the problem.

**Comment by drjfloyd** [comment]
Running with the current source it is dying in GET_AVERAGE_SPECIFIC_HEAT being called from HVAC_UPDATE.  This likely means either the temperature or species solution in the HVAC solver has gone bad, e.g. an instability developed either in the HVAC model or in the FDS domain that is impacting the boundary conditions for the HVAC model.  If you want to predict HVAC flows using fan curves and get a meaningful solution, you need to specify, to the best of your ability, the duct and fitting losses in your HVAC network. Otherwise, you should just specify fixed flows using VOLUME_FLOW or MASS_FLOW.

**Comment by zladicolor** [comment]
Hello sir,
Thanks very much for your answers.
I've tried to add Loss in Duct and it worked. But now i meet a new problem, the O2 concentration reduced always and means the no air from outside into the computational domain. I think that because of the wrong pressures in rooms, which can influence the quadratic fans. That means, i should correct the duct loss? And where some reference  losses can be found?

**Comment by drjfloyd** [comment]
Duct losses should represent the as-built / as-designed system. Specifying these in order to predict flow rates (vs. specifying MASS_FLOW or VOLUME_FLOW at all inlets and outlets) requires detailed knowledge of the duct type, duct diameters, and fittings (tees, elbows, expansion/contraction, etc.). If you have that information, the ASHRAE handbook is one source for loss data. In the absence of detailed design data, if you know the design supply and exhaust rates at each inlet and outlet and have the correct fan curves, then you could run a simulation without a fire and adjust losses to obtain the correct flow rates.

**Comment by mcgratta** [comment]
Let me second that thought -- run your simulation with no fire first. Make sure that the HVAC system is working as designed. Then add the fire.

**Comment by zladicolor** [comment]
Thank you, sirs .Now I'm testing the HVAC system. And i have some other questions that a fan curve shows the relationship between the flowrate at Inlet or outlet  and the room's relative pressure? My HVAC system is a little complex that there're 2 inlets and 2 outlets with quadratic fans in the domain. But the inlet 1 and outlet 1 with flowrate 1 m3/s and the others (inlet 2 and outlet 2) only with 0.5 m3/s. Should i set RAMP_LOSS in the duct for the both?

**Comment by zladicolor** [comment]
Hello sirs,
I've tested the hvac system without fire and the output seems good. Then i set the new hvac system in my simulation but at t=600s is  Numerical Instability because of a sudden hrr's increasing. I've set then MAX_PRESSURE_ITERATIONS, the problem is solved but the jump is still there. The hrr curve which i hoped should be fast constant after t=200s. Can you check the new codes and maybe give me some advices? Thank you :)

[test8.docx](https://github.com/firemodels/fds/files/1040834/test8.docx)
![snip20170531_5](https://cloud.githubusercontent.com/assets/28928013/26624680/e72516c6-45f1-11e7-99a6-11882562684c.png)
