### ISSUE TITLE
Line width in the validation script

### ISSUE THREAD

**Issue by rkj15** [firemodels/fds#5123]
Hello, 

I was trying to change the line width of the plots produced by the validation script by changing the Line_Width parameter in the plot_style.m script but it didn’t work. The Line_Width property does not affect the plots produced.  I asked Simo about it and he suggested that I add:

" set(K, 'LineWidth', Line_Width) "  after both d1 and d2 datasets have been plotted, and the curve handles are stored in K –vector. This around line 437 of dataplot.m. 

Adding the additional line applies the Line_Width parameter specified in plot_style.m for the plots. 
![foa_t01_pressure](https://cloud.githubusercontent.com/assets/9218382/26575718/0991d9f6-452f-11e7-81d8-adf2fde9e640.png)
![foa_t1_pressure_nolinewidth](https://cloud.githubusercontent.com/assets/9218382/26575875/a5daf00e-452f-11e7-9d19-120b50cacffd.PNG)

Could you please verify it again and add it to the repository files?

Thank you,
Rahul

**Comment by mcgratta** [comment]
We'll take a look at it. Matlab is tricky -- with each new versions, our plots change in some way.

**Comment by rmcdermo** [comment]
Nothing tricky here.  We just had never added linewidth to dataplot.

I've made short-term fix.  You can now change linewidth from plot_style and get a different line width in dataplot.  I'd like to eventually add a column to the dataplot_inputs files, though, so that we can have different widths for different lines on the same plot.
