### ISSUE TITLE
Volume flow and dynamic pressure don't give the same results

### ISSUE THREAD

**Issue by elmadrab** [firemodels/fds#5252]
Hello,

I'm trying to use dynamic pressure as a boundary conditions. I already ask a question in FDS & SMV discussions group here is the link : 

https://groups.google.com/forum/#!topic/fds-smv/I9BQqUkMXOE

In the first case I used a dynamic pressure and in the second one I used a volume flow condition.

The volume flow in the second case was calculated from the first case.

I noticed the following differences with : 

-  the smoke transport, smoke moves differently

- the velocity profile, in the first case the velocity profile seems to be more realistic.

Here are the the simple cases :

[two_simple_cases.zip](https://github.com/firemodels/fds/files/1159761/two_simple_cases.zip)

Thank you.

Best regards.

**Comment by drjfloyd** [comment]
Volume flow imposes a fixed flow over the entire boundary no matter what the fire conditions are.

Dynamic pressure imposes a fixed pressure on the boundary.  The flow into the domain then depends on the sum of the external pressure plus interior pressure rise due to the fire (this is computed on a per grid cell basis).

I would not expect these two to be the same.

**Comment by elmadrab** [comment]
Thank you Jason.

So the dynamic pressure gives more accurate results right ?

Is there any simple correlation between the dynamic pressure and the volume
flow at the boundary condition ? In many real cases I know only the volume
flow.

----------------------------------

mail : mohamed.elmadrab@gmail.com

**Comment by Er9y714** [comment]
(I assume) It may be found by Bernoulli equation. If you assume the the height terms are equal, then you only have the third and fourth terms on the right side of the equation. Only variables are pressure and velocity. For a given pressure difference, you can find the velocity. By multiplying velocity and area, you can obtain volume flow. 

![image](https://user-images.githubusercontent.com/26166281/28523423-a2a6f108-707c-11e7-9a7e-b5b5e99e156e.png)

**Comment by drjfloyd** [comment]
That form of Bernoulli's equation is appropriate for inviscid flow.  Depending on the tunnel length and cross sectional area, there could be significant pressure loss due to wall friction.  Friction losses can be found using Darcy's equation:

f L/D v^2 /2

where f is a friction factor (can get this from a Moody Diagram), L is the length, D is the diameter, and v is the velocity in the tunnel.

**Comment by elmadrab** [comment]
Thank you guys for your answers.

Just for a matter of comprehension, I learned fluids mechanics in French. I can't make a difference between total pressure, dynamic pressure and static pressure ( those are the name of the different pressure in French).

In FDS, the total pressure is the head H ?

In the equation of Bernoulli, the third term is it the static pressure ? and the fourth one is it the dynamic pressure ?

Sorry to bother you.

**Comment by mcgratta** [comment]
H is the stagnation pressure divided by the density. The stagnation pressure is

p_stag = 0.5*rho*v^2 + p_static
