### ISSUE TITLE
Seg faults in complex geometry cases

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5327]
Running the latest version of the code, I get
```
Complex_Geometry/sphere_helium_3meshes.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
Complex_Geometry/sphere_helium_3meshes.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
Complex_Geometry/sphere_helium_3meshes.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
```

**Comment by marcosvanella** [comment]
Thank you Kevin. This should be fixed by pull request #5328.
- Seems I forgot to test a modification on the use of GLMAT solver for pressure in whole domain (including solid cells) when &GEOMs are present. I made these changes to test tripping to turbulence the heated_channel cases using OBSTS as trip wires. 
- I added a flag to the Complex_Geometry cases to use the Poisson solver as was previously the default (building the L matrix only for gas cells).
Lets leave the issue open, I'll close it when I have fixed the problem I have apparently, when solving with GLMAT on whole domain divided in different meshes and having &GEOMS.
