### ISSUE TITLE
mass flow rate problem

### ISSUE THREAD

**Issue by guoxiangzhao** [firemodels/fds#5365]
Hello,

I run a simple case as can be seen infigure 1. 

- It is a case where an enclosure with an single opening on the wall. 

- There is a constant wind, blowing towards the enclosure from the boundary. wind speed  0 m/s, 0.1 
    m/s,......2 m/s, 4 m/s, 6 m/s, 8 m/s are considered.
- Use  devices "mass flow +" and "mass flow -" cover the entire opening to measure the mass flow rate. 
- Steady-state state results should read this:  Mass outflow =Mass inflow + mass of the fuel

Normally, the difference between the mass outflow rate and the mass inflow rate should be the same value for different wind speed(equal to the fuel mass flow rate from the burner). However, we find it is not this case.

The difference between the mass outflow rate and the mass inflow rate increases when increasing the wind speed (see picture 2). 

Can you explain this?  The FDS code can be found in the attachment.

Cheers,
Gzhao

![1](https://user-images.githubusercontent.com/13900156/29843652-ec8d92c0-8d0c-11e7-8c71-09ac07ef8b48.jpg)
![2](https://user-images.githubusercontent.com/13900156/29843656-f13c3c90-8d0c-11e7-86c3-6ed46e8cccdf.jpg)
[1.zip](https://github.com/firemodels/fds/files/1261724/1.zip)

**Comment by mcgratta** [comment]
Tighten your pressure tolerance. Add this line
```
&PRES VELOCITY_TOLERANCE=0.001, MAX_PRESSURE_ITERATIONS=100 /
```
See if that helps.

**Comment by rmcdermo** [comment]
You also probably need to use MASS FLOW WALL.  The other "flows" do not give exact results.  See sec. 18.10.12 of user guide.

**Comment by guoxiangzhao** [comment]
@mcgratta Thanks! But, I have already tried that. It doesn't help.

**Comment by guoxiangzhao** [comment]
@rmcdermo Thanks Randy, but I didn't find section 18.10.12 in the user guide, you probably mean 17.10.12. what you suggest is to replace the ' QUANTITY='MASS FLOW ' with 'MASS FLOW WALL'? 
But, I don't see the point why we need to do this. Here, we are trying to get the mass flow rate through a hole (shown in figure 1).
is that possible to use the device 'MASS FLOW WALL' at a hole in FDS?

**Comment by rmcdermo** [comment]
No.  But you need to integrate first along all the domain boundaries, not internal boundaries.  There will be velocity errors along the surfaces that can easily account for the discrepancies you are seeing.  Try adding a BNDF of VELOCITY ERROR and you will see what I mean.

**Comment by mcgratta** [comment]
I don't think that the issue is the pressure solver. I ran the case with a tight pressure iteration tolerance and the results did not significantly change. It appears that the mass flow out of the compartment is 0.004 kg/s greater than the mass flow in. The fuel added to the compartment is about 0.0013 kg/s, so that does not explain all of the difference. I think that the difference is due to the fact that when we compute the `MASS FLOW` for output, we use a simple central difference scheme, but in the actual simulation, we use a more complicated flux limiting scheme.

**Comment by marcosvanella** [comment]
Hi Kevin, we have the advective and diffusive flux containers defined on the EXTERNAL_WALL_TYPE type:

```
TYPE EXTERNAL_WALL_TYPE
   INTEGER :: NOM,NIC_MIN,NIC_MAX,IIO_MIN,IIO_MAX,JJO_MIN,JJO_MAX,KKO_MIN,KKO_MAX
   REAL(EB) :: AREA_RATIO
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: FVN, FVNS ! species advective flux at E-wall -> flxint(rho*Y_alpha)*U
   ! where flxint(rho*Y_alpha) is the corresponding flux limited interpolation of rho*Y_alpha being used
   ! in the code and U is the normal velocity. FVN -> based on variables at time level n, FVNS based on
   ! predicted variables for step n -> n+1.
   REAL(EB), ALLOCATABLE, DIMENSION(:) :: RHO_D_DZDN, RHO_D_DZDNS ! species diffusive flux at E-wall, as computed in divg.f90.
END TYPE EXTERNAL_WALL_TYPE
```

I currently load these in calls from density and divergence_part_1 when the misc flag for mass conservation is set (CHECK_MASS_CONSERVE) in &MISC. I actually use this in my mass conservation tests around the sphere. The routines in geom.f90 that load these fluxes are SET_DOMAINADVFLX_3D, and SET_DOMAINDIFFLX_3D. 

The mass conservation test does the time integration of fluxes (SSPRK2 for consistency), but we might be able to use these directly instead of using centered evaluations.

**Comment by rmcdermo** [comment]
Yes, this all has to be done with boundary values.  The internal "flow" devices are not precise enough for tight conservation tests.

**Comment by marcosvanella** [comment]
I can work on rewriting it with your guidance. Should be a good way to get this from hack mode to &DEVC utility. It will also be good to add this as a CompGeom verification test.

**Comment by guoxiangzhao** [comment]
@mcgratta Thanks Kevin for your explanation. In practice, what can we do to eliminate this post-processing error? To use finer grid cell size? or to Tighten your pressure tolerance?

**Comment by mcgratta** [comment]
At the moment, nothing. It would be too costly to recompute mass flux quantities just for output purposes.
