### ISSUE TITLE
FDS crashes when a hole crosses an open boundary

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#5479]
Dear developers,
I'm facing a strange instability when I run a simple case with a hole crossing an external boundary. The calculation gives back a segmentation fault and stops, I tried to delete the hole and the simulations runs smoothly, but I can't figure out the origin of the problem. I attach a simplified version of my model.
Thanks in advance for your support
[input_fds.txt](https://github.com/firemodels/fds/files/1313574/input_fds.txt)

**Comment by sbenkorichi** [comment]
Ok, I will take a look.

**Comment by sbenkorichi** [comment]
From User Guide section 7.2.6 Creating Holes in Obstructions

Note that a HOLE has no effect on a VENT or a mesh boundary. It only applies to OBSTructions. 

In your file, you have holes with no OBST, where are your OBST?

Which operating system are you using Windows or Linux?

**Comment by mpachera** [comment]
I created a simpler version with no obstacles, but I will upload one version also with obstacles. I'm using Linux (lubuntu) to run the model, while the geometry was created in Pyrosim.
[input_fds_complete.txt](https://github.com/firemodels/fds/files/1313681/input_fds_complete.txt)

**Comment by sbenkorichi** [comment]
As I thought, the segmentation is due to the lack of memory, do this on terminal: `ulimit -a` 
And past the result here.

**Comment by mpachera** [comment]
I tried but I still get the same error, I don't think it is a lack of memory because if I delete the two lines with the hole command the case runs smoothly. Were you able to run the case with holes in it?

**Comment by sbenkorichi** [comment]
The case works fine for me with the up to date version. However, it's giving an error with 6.5.3. In the simplified example, whether I comment the hole or not, it doesn't work with 6.5.3. But, works fine with the latest compiled one on my syst. That's why I said it could be due to the memory limitations. I need to look deep into this.

**Comment by sbenkorichi** [comment]
There you go, now I cornered the issue. I remember we had this earlier on, it's due to the Z coordinates are negative which gave us an error. Kevin has fixed this issue, that's why I didn't have an issue with the latest version. Now, this issue wont appear in the latest release from now on. But, for now, you can avoid using negative values for Z. 
See the corrected input file,
the issue has nothing to do with the hole. 


[input.fds.txt](https://github.com/firemodels/fds/files/1313798/input.fds.txt)

Test it and report back.

**Comment by mpachera** [comment]
Perfect I didn't realise that, I will move my model up in order to have only positive z coordinate. 
Thanks a lot Salah

**Comment by sbenkorichi** [comment]
You're welcome
