### ISSUE TITLE
Smokeview dies when loading a SLCF and then a BNDF.

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5497]
Run this case
```
&HEAD CHID='ray_effect_example', TITLE='Demonstrate ray effect'/

&MESH XB=0.0,1.0,0.0,1.0,0.0,1.0, IJK=100,100,100 /

&RADI NUMBER_RADIATION_ANGLES=100
      TIME_STEP_INCREMENT = 1
      ANGLE_INCREMENT = 1 /

&TIME T_END=0.1, DT = 0.1  /

&SURF ID='HOT'  TMP_FRONT=100, TAU_T=0., EMISSIVITY=1., HEAT_TRANSFER_COEFFICIENT=0., COLOR='RED'  /
&SURF ID='COLD' TMP_FRONT=20., TAU_T=0., EMISSIVITY=1., HEAT_TRANSFER_COEFFICIENT=0., COLOR='BLUE' /

&VENT MB='XMIN',SURF_ID='HOT' /
&VENT MB='XMAX',SURF_ID='COLD' /
&VENT MB='YMIN',SURF_ID='COLD' /
&VENT MB='YMAX',SURF_ID='COLD' /
&VENT MB='ZMIN',SURF_ID='COLD' /
&VENT MB='ZMAX',SURF_ID='COLD' /

&SLCF PBY=0.5, QUANTITY='INTEGRATED INTENSITY' /

&BNDF QUANTITY='GAUGE HEAT FLUX', CELL_CENTERED=.TRUE. /

&TAIL /
```
and then in Smokeview load the slice file and then the boundary file. I have the Windows Sept 11 build, and this causes Smokeview to shut down.

**Comment by rmcdermo** [comment]
Glenn,
I confirm the fault with this build:
```
dante:Issue_5497 rmcdermo$ smv ray_effect_example

Smokeview  Test(SMV6.5.4-104-g183f81d17) - Sep 11 2017 - 14:30:48

Version          : Test
Revision         : SMV6.5.4-104-g183f81d17
Revision Date    : Mon Sep 11 14:28:00 2017 -0400
Compilation Date : Sep 11 2017 14:30:48
Compiler         : Intel C/C++ 17.0.4
Checksum(SHA1)   : eb662600e6b09727764fe2edbb331594ca4b7dc6
Platform         : OSX64

Smokeview        : /Applications/SMV6.5.4-104-g183f81d_osx64/bin/smokeview
Texture directory: /Applications/SMV6.5.4-104-g183f81d_osx64/bin/textures
Scratch directory: /Users/rmcdermo/.smokeview/
```
Here is the error:
```
Determining GAUGE HEAT FLUX(cell centered) percentile and global data bounds
  Examining ray_effect_example_01.bf
boundary time=0.00
boundary time=0.10
computing boundary color levels 
 0.5 MB loaded in 0.02 s - rate: 245.1 Mb/s (overhead: 0.05 s)
Segmentation fault: 11
```

**Comment by gforney** [comment]
this is the definition of insanity.  your case crashed for me too but not every time.  there are only 2 time steps in the data files.  could you try running the case for longer say 1.0 s and see if it still crashes.

**Comment by gforney** [comment]
ps:  reason for asking want to know if smokeview is having trouble dealing with a small number of time steps in the data files.

**Comment by rmcdermo** [comment]
If I run the case to 1 s, then it works.

**Comment by rmcdermo** [comment]
You can find the case in:
/home4/rmcdermo/Issues/Issue_5497/test.fds

**Comment by firemist** [comment]
At the risk of barely providing any additional information, I have had problems at times this year with consistently loading boundary files. Smokeview would crash during the load. These are very large boundary files, so definitely not the < 1 s problem. There are 23 meshes.

I never posted an issue on this because I could not consistently reproduce it, although I tried a number of times to narrow it down. (It's also a large problem that does not lend itself to easy simplification.) Based upon my analysis, I'm pretty sure that it had nothing to do with CPU, memory, disk space, etc. I would then restart Smokeview and load the boundary file and it would work.

I believe I was running SMV 6.4.4 most of the time (although I think I did some periodic upgrades), so I'm not sure if the problem is still there and that's why I'm just adding to this issue. I'm running 6.5.5 now, so I'll let you know if it reappears.

Thank you.

**Comment by gforney** [comment]
I fixed a pointer that is NULL sometimes.  try smokeview here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by sbenkorichi** [comment]
Running the example case shared by Kevin with smv in the link, it works under Linux. No shutdown noticed.

**Comment by gforney** [comment]
is this still a problem?
here is the latest test smokeview
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by mcgratta** [comment]
This issue is resolved. I just double-checked.
