### ISSUE TITLE
Heat Flux Boundary for solid 3D heat transfer domain: HT3D

### ISSUE THREAD

**Issue by dpkPrasadPaudel** [firemodels/fds#5519]
Dear All,

For 1-d wall models it was possible to implement "External_HF" via surf line to define surface heat flux. With ht3d, "External_HF" doesn't seems to effect the heat diffusion inside the 3D solid domain. May I ask how can I implement external heat flux for "ht3d" simulations  or is this feature yet to be added ?

Here is a simple HT3D model that I tried to run using the latest repo version of fds. 

>

&HEAD CHID='cube_hf', TITLE='compare 3D heat transfer with COMSOL'/
&MESH IJK=32,32,32, XB = -0.16,0.16,-0.16,0.16,-0.16,0.16/
&TIME T_END = 1500, DT=5 /
&DUMP DT_DEVC = 10 /
&MISC TMPA = 20., SOLID_PHASE_ONLY=T, BNDF_DEFAULT=F/
&RADI RADIATION = F/
&OBST XB = -0.15, 0.15, -0.15, 0.15, -0.15, 0.15, MATL_ID = 'STEEL', HT3D=T, SURF_ID='ADIABATIC_SURF', BNDF_OBST=T /
&SURF ID = 'ADIABATIC_SURF', COLOR='GRAY', ADIABATIC=T/
&SURF ID = 'HOT_SURFACE', COLOR='RED', EXTERNAL_FLUX=56./
&MATL ID = 'STEEL'
      SPECIFIC_HEAT = 0.6
      CONDUCTIVITY  = 45.
      DENSITY       = 7850. /
&VENT XB = -0.15,-0.15,-0.15,0,-0.15,0, SURF_ID = 'HOT_SURFACE' /
&SLCF PBX=-0.075, QUANTITY='TEMPERATURE', CELL_CENTERED=T/
&SLCF PBX=0.075, QUANTITY='TEMPERATURE', CELL_CENTERED=T/
&DEVC XYZ = 0.1425, 0.1425, 0.1425, QUANTITY = 'TEMPERATURE', ID = 'T1'/
&DEVC XYZ = 0.1425, 0.1425, -0.1425, QUANTITY = 'TEMPERATURE', ID = 'T2'/
&TAIL /

>

Thanks

Deepak

**Comment by sbenkorichi** [comment]
I will also try to take a look, in the main while, your &OBST is missing / at the end.

**Comment by dpkPrasadPaudel** [comment]
thanks, I have now corrected the typo !

**Comment by sbenkorichi** [comment]
I think we don't have yet the external heat flux linked to the ht3d,
You can use for now TM_FRONT as alternative until Randy adds it up to the code.
 &SURF ID = 'HOT_SURFACE', COLOR='RED', TMP_FRONT=900./

**Comment by rmcdermo** [comment]
I asked Deepak to submit this as an Issue.  I'll add EXT_FLUX to HT3D from here.

**Comment by rmcdermo** [comment]
For the moment, you need to use NET_HEAT_FLUX.  I will see if I can hook up EXTERNAL_FLUX.

&SURF ID = 'HOT_SURFACE', COLOR='RED', NET_HEAT_FLUX=-56./

![cube_hf_0299](https://user-images.githubusercontent.com/4418497/30977516-b885ae0e-a445-11e7-9c38-5d0815e1dc07.png)

**Comment by rmcdermo** [comment]
@DpakPaudel I think your concept of EXTERNAL_FLUX is not right.  EF requires RADIATION=T, because it effectively is a shortcut for setting WC%RADIN.  But RADOUT and convection to the gas are still computed.  Therefore, it is also not physically reasonable to set SOLID_PHASE_ONLY=T with EXTERNAL_FLUX.  The correct BC for your verification case is NET_HEAT_FLUX.

However, EF works if you set HT3D=T on the SURF line.  This is discussed in the user guide, actually.  I had to read it to check.  It is somewhat buried, but it is there.  Here is an input file example:
[cube_external_flux.fds.txt](https://github.com/firemodels/fds/files/1341701/cube_external_flux.fds.txt)

![cube_external_flux](https://user-images.githubusercontent.com/4418497/30979783-bf6c30d8-a44c-11e7-9328-573c1467b086.png)

**Comment by dpkPrasadPaudel** [comment]
Thank you for the solutions. I was always looking at pre-compiled version of user guide, hence thought as an issue. I will try to benchmark/compare the results with other tools !!

**Comment by rmcdermo** [comment]
OK, please note that your verification case is very similar to the ht3d_ibeam.fds case, where we compared the solution against ANSYS for a constant temperature patch.  So, please follow this example when setting up the case.  When you are done, please compile the guide and send me a pdf before you send a pull request.  Thanks.
