### ISSUE TITLE
Duplicate multi-slice files issue. 

### ISSUE THREAD

**Issue by WLau1** [firemodels/fds#5591]
Hi there,

I am currently having issues loading multi-slices where certain slices would have duplicates e.g. z=0 would have 6 duplicates but when I select one of these slices it would load a random slice in the x/y/z not related to z=0m.

I've checked my mesh alignment and there is no issue. I've also tried to load single slice files however have the same issue e.g. z=0m mesh 01 would have 3 duplicates and would load a random slice file. 

We are also currently running the latest version of FDS 6.5.3 and Smokeview 6.5.5. This issue only appeared after the model completed and I have not moved the file. 

Any help would be appreciated. 

Cheers, thanks

Regards,
Will

![image](https://user-images.githubusercontent.com/32921871/31756656-da20a558-b4f0-11e7-963c-36338acc1a84.png)

**Comment by sbenkorichi** [comment]
Simplify your input file and upload it as .txt not .fds so it can be uploaded, to see what you're doing and how you're outpuing the slices.

**Comment by WLau1** [comment]
I've tried to simply the file as possible, removing obstructions and only keeping the mesh and slice files. I have also rerun the model and it seems fine at the moment. 

As I test, I copied the entire folder onto another computer and the slices are all random. Could this just be a hard-drive issue?

[TEST.txt](https://github.com/firemodels/fds/files/1397606/TEST.txt)

**Comment by sbenkorichi** [comment]
I'm testing it, I don't see what you're talking about.
Multi-slice ----> soot visibility ----> Then which Mesh did you select that causes the issue?
I don't see you outputing slice at Z=0.

2. What do you mean by slices are all random?

**Comment by WLau1** [comment]
Apologies if my post was not clear.

In my first comment, there is a screenshot of the FDS model after it has completed its 1800s duration. If you can see from the multi-slice ----> soot visibility ----> z = 0m there are 6 duplicates. From my FDS input file, I haven't assigned z=0m as a slice file. The lowest z slice i have assigned is at 2m and I have the meshes at 0.5m z-axis intervals. 

When I click on the z=0 slice file, smokeview will show me random slices in either x/y/z plane which does not correlate with z=0m. Furthermore if you look at the y slice files from the above screenshot, you see these really large values. 

I am only getting this error after the model has completed. It is fine when the model is running the simulation (say 200s) and I can actually select z=2m.  

When i copied the files onto a different computer and try to load the soot visibility, rather than get 6 duplicates of z=0m i might get 3 with the same issue.  

I wasn't sure whether this could be a hard-drive issue or a bug.

**Comment by sbenkorichi** [comment]
Now I understand. No, smokeview shouldn't output non outputed slices. 
I didn't see it since the run didn't complete.
You are outputing close to 300 slices which is big number for smokeview --theoretically smokeview should handle it.
We need the help of Glenn for this. However, let's try these two experiments:
1. Download smokeview from here: 
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA
Test it on the case after its finished -- Does it give same issue?

2. Download previous old smokeview version from here: 
https://github.com/firemodels/fds/releases/tag/Git-r20
Does it also give the same issue or not?

**Comment by Er9y714** [comment]
Can you try running smv file once again, after deleting .info file in the folder?

**Comment by WLau1** [comment]
Thank you for the pointers. 

I will let you guys know how it goes tomorrow ( I currently don't have access to the FDS model at the moment).

**Comment by gforney** [comment]
As a workaround to your problem, I suggest you replace all your &SLCF
entries with one 3D slice file

**Comment by gforney** [comment]
your example TEST case is not a proper FDS input file.  I'm getting the error ERROR: SPEC_ID SOOT is not explicitly specified for QUANTITY VISIBILITY (CHID: TEST) .  I am getting this error with both the latest official release and the fds built from the repo.  If you fix this I"ll take a look at it.

**Comment by sbenkorichi** [comment]
Yes Glenn, 
Here is a fix for it.
[TEST.txt](https://github.com/firemodels/fds/files/1398224/TEST.txt)

**Comment by gforney** [comment]
I am not able to reproduce the problem .  It is working for me.
 Download a test smokeview here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

Also, all of  you 1D &SLCF entries can be replaced by the following three 3D &SLCF entries.  You only need to specify VECTOR=.TRUE. once, otherwise you'll get duplicate slice files for the U, V and W components of velocity.  Remember to specify DT_SLC3D on the &DUMP line

&SLCF XB=9.0,104.,-59.0,34.5,0.0,35.0,QUANTITY='VISIBILITY', VECTOR=.TRUE./
&SLCF XB=9.0,104.,-59.0,34.5,0.0,35.0,QUANTITY='TEMPERATURE'/
&SLCF XB=9.0,104.,-59.0,34.5,0.0,35.0,QUANTITY='VELOCITY'/



![issue5591_sliceload](https://user-images.githubusercontent.com/12403014/31771186-265a3274-b4a9-11e7-9f2b-d41628b29727.png)

**Comment by sbenkorichi** [comment]
This is an example to what Glenn suggested.

[TEST.txt](https://github.com/firemodels/fds/files/1398410/TEST.txt)

**Comment by WLau1** [comment]
I have tried the methods above and using the older version of Smokeview 6.3.12 resolved the issue.

![image](https://user-images.githubusercontent.com/32921871/31797822-14f9a8b0-b57c-11e7-9897-330e0ef36cc1.png)

Using Smokeview 6.5.5 had the same issue where smokeview will display multiple z=0m slices. I also will avoid the use of 1D slice files in the future and use one 3D slice file.    

Thank you all for the help!

**Comment by sbenkorichi** [comment]
Glenn,
What's the status of this? IMO, it should be closed since it's not possible from your end to be reproduced it.

**Comment by sbenkorichi** [comment]
Thanks
