### ISSUE TITLE
SMV - offset window

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5613]
When the function is enabled (Show/Hide > offset window), the timeline cannot be shifted by mouse by clicking on it anymore. In fact, it still works but only by clicking on an empty area below the timeline.
 
SMV 6.5.5 -2-gf88f65e

Thank you.

**Comment by sbenkorichi** [comment]
It works fine from my end. Just grab it from the bottom and it would be fine. -- I can't reproduce the issue you're talking about.
The reason in your case is not, it may be due to the image size is a bit larger, and it passes behind the timeline, so that's why you can't grab the timeline instead you would grab the scene. --Solution would be simply approach it from the bottom and grab the timeline, this should do the trick.

**Comment by Er9y714** [comment]
Do you mean grabbing timeline or outside?

**Comment by sbenkorichi** [comment]
Just hover around the black spot, you should be to grab the timeline with the mouse.
![smv](https://user-images.githubusercontent.com/20113030/31936288-0fd67f40-b8a9-11e7-9967-ea5e78724f3c.png)

**Comment by Er9y714** [comment]
Thanks for the figure. I do grab the timeline with mouse on the black spot, but this zone is outside of the timeline. 

So it works, but outside of the zone. That was my point.

**Comment by sbenkorichi** [comment]
Well, simply you can't grab it because the scene is at its level. Either you just do what I suggested, or maybe Glenn could put some space in between so they wont overlap.

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
should be fixed in smokeview that will be released shortly

**Comment by Er9y714** [comment]
Thank you Glenn
