### ISSUE TITLE
Segmentation fault when using non-uniform meshes

### ISSUE THREAD

**Issue by mrgcfraga** [firemodels/fds#5709]
I am trying to run a simulation with a non-uniform mesh using the &TRNX and &TRNY parameters. However, although the case runs without problems for a uniform mesh, if this parameters are set (even for a mesh with very little alteration in the grid cell size), I receive the error message "forrtl: severe (174): SIGSEGV, segmentation fault occurred" as soon as the simulation starts.

An example file where I've noticed this behavior is:

&HEAD CHID = 'test'/

&MESH ID = '1', IJK = 150,150,100, XB = -0.2,0.2,-0.2,0.2,0.0,0.5/

&TRNX CC=-0.025, PC=-0.02, MESH_NUMBER=0/
&TRNX CC= 0.025, PC= 0.02, MESH_NUMBER=0/

&TRNY CC=-0.025, PC=-0.02, MESH_NUMBER=0/
&TRNY CC= 0.025, PC= 0.02, MESH_NUMBER=0/

&TIME T_END = 20 /

&VENT XB = -0.025,0.025,-0.025,0.025,0,0 SURF_ID = 'INTAKE'/ 
&VENT PBX=-0.2, SURF_ID = 'OPEN'/
&VENT PBX= 0.2, SURF_ID = 'OPEN'/
&VENT PBY=-0.2, SURF_ID = 'OPEN'/
&VENT PBY= 0.2, SURF_ID = 'OPEN'/
&VENT PBZ= 0.5, SURF_ID = 'OPEN'/

&SURF ID = 'INTAKE',
      MASS_FRACTION(1) = 1.0,
      SPEC_ID(1) = 'METHANE',
      VEL = -5, 
      TMP_FRONT = 20,
      TAU_V = 0.2, 
      TAU_T = 0.0, 
      COLOR = 'RED'/

&REAC FUEL = 'METHANE'/

&TAIL /

**Comment by drjfloyd** [comment]
we'll take a look.

**Comment by drjfloyd** [comment]
@mcgratta @rmcdermo The error in this case is occurring in the FISHPAK solver. It runs with FDS 6.3 (it may run with later versions, I just had 6.3 readily available). Are there changes to initializing the pressure solver either of you can think of offhand that might have caused  this?

**Comment by rmcdermo** [comment]
I think there were changes related to fixing warnings with Gnu compiler.  Kevin, please check.

**Comment by mcgratta** [comment]
Yes, I might have accidentally broken something. Will fix.

**Comment by mcgratta** [comment]
Doh! This bug goes back a year. Must have had too much turkey.
```
[mcgratta@burn fds]$ git bisect bad
e12dd7db1df5a8400cbd365a087790bd48413ecd is the first bad commit
commit e12dd7db1df5a8400cbd365a087790bd48413ecd
Author: mcgratta <mcgratta@gmail.com>
Date:   Thu Dec 1 10:46:25 2016 -0500

    FDS Source: Add option to do a grid transformation in all meshes.
```

**Comment by mcgratta** [comment]
Actually, this bug goes back even further. The change on Dec 1, 2016, forced the transformation to be done when `MESH_NUMBER=0`, but before that, a bug in the logic would skip out of the transform, which is why the case appeared to work. However, the real problem is that a grid of 150,150,100 causes a floating point overflow in the calculation of various coefficients used to solve the pressure (Poisson) equation. The transformation forces the use of a slightly different solver than the one normally used. In any event, I have no remedy for the overflow because it occurs in code (Crayfishpak) that we did not write and it is not clear what this coefficient does. Everything works fine with a grid of 100,100,100, so I suggest you do not use larger meshes and this transformation at the same time. In fact, we use grid transformations less and less in favor of multiple meshes and MPI processing.

I'll keep the case open for now in case I have an idea, but I suggest you use multiple, smaller, meshes.

**Comment by sbenkorichi** [comment]
When using single mesh, I don't think it's necessary to use MESH_NUMBER, maybe we can explain this in the UG.

**Comment by mcgratta** [comment]
You don't have to, but it is allowed. It just means to apply the given transform to all meshes.

**Comment by mcgratta** [comment]
I added a warning to the User's Guide not to use more than 1 million cells when stretching in two directions.
