### ISSUE TITLE
GLMAT solver not working

### ISSUE THREAD

**Issue by Joshuaklein98** [firemodels/fds#5716]
[18BIE - copia.txt](https://github.com/firemodels/fds/files/1487535/18BIE.-.copia.txt)
[19BIE - copia.txt](https://github.com/firemodels/fds/files/1487536/19BIE.-.copia.txt)

I have tried to use the GLMAT solver in a case of study abour a tunnel, but it gives me this error:

Using GLMAT as pressure solver. List of H unknown numbers per proc:
MYID=0, NUNKH_LOCAL=410031
GET_H_MATRIX_LUDCMP CLUSTER_SOLVER Num Factor: The following ERROR was detected: -4
MPI process 0 has completed

STOP: FDS was improperly set up (CHID: 18BIE)

[18BIEtxt.txt](https://github.com/firemodels/fds/files/1486148/18BIEtxt.txt)

**Comment by sbenkorichi** [comment]
Thanks @marcosvanella will take a look.

**Comment by marcosvanella** [comment]
Thanks Salah. 
Hi Joshua, thank you for reporting. I'll look at the case you posted. Can you tell us if you are using the bundle or compiling the code yourself, and also which Operating System you are using?
Also, what are the "- copia" cases you have posted?

**Comment by Joshuaklein98** [comment]
Hello Marcos,

Initially yesterday I submitted the 18BIEtxt.txt
<https://github.com/firemodels/fds/files/1486148/18BIEtxt.txt> file, where
I had the problem that the GLMAT solver didn't work.

Today I have realized that two jet fans were out of the domain, which may
cause some trouble. That's why I have created the 18BIE - copia.txt
<https://github.com/firemodels/fds/files/1487535/18BIE.-.copia.txt> and 19BIE
- copia.txt
<https://github.com/firemodels/fds/files/1487536/19BIE.-.copia.txt> files
(18BIE-copia.txt is the original case withdrawing the jet fans and
19BIE-copia.txt is equal to 18BIE-copia.txt, but with two meshes instead of
a single mesh).

I am using the software Pyrosim to create the model, and , after that, I
add to the fds file the lines concerning the Pressure solver. I am working
on Windows 10.

Thank you for your aid, cheers.


2017-11-20 15:32 GMT+01:00 marcosvanella <notifications@github.com>:

**Comment by mcgratta** [comment]
The basic problem of tunnels is demonstrated by this case:
```
&HEAD CHID='klein_tunnel'/
&TIME T_END=1200.0/
&MISC GVEC=-0.06869,0.0,-9.8098/

&MESH IJK=1800,24,16, XB=0.0,900.0,-6.0,6.0,-0.5,7.5/

&REAC FUEL='N-HEPTANE', SOOT_YIELD=0.037 /

&SURF ID='Boca C', RGB=26,204,26, VEL=-1.86 /
&SURF ID='Fire', COLOR='RED', HRRPUA=909., TAU_Q=100. /

&VENT SURF_ID='OPEN', XB=0.0,0.0,-6.0,6.0,-0.5,7.0 /
&VENT SURF_ID='Boca C', XB=900.0,900.0,-6.0,6.0,-0.5,7.0 /

&OBST XB=550.0,558.0,-3.0,-2.5,3.0,3.5, SURF_ID6='INERT','INERT','Fire','INERT','INERT','INERT'/
&OBST XB=550.0,558.0,-1.0,-0.5,3.0,3.5, SURF_ID6='INERT','INERT','INERT','Fire','INERT','INERT'/
&OBST XB=550.0,558.0,-3.0,-0.5,3.5,4.0, SURF_IDS='Fire','INERT','INERT'/
&OBST XB=558.0,560.0,-3.0,-0.5,3.5,4.0, SURF_IDS='Fire','INERT','INERT'/

&DUMP VELOCITY_ERROR_FILE=.TRUE. /

&SLCF QUANTITY='TEMPERATURE', PBY=0.0, VECTOR=.TRUE. /
&SLCF QUANTITY='PRESSURE', PBY=0.0  /
&SLCF QUANTITY='H', PBY=0.0  /

&TAIL /
```

**Comment by marcosvanella** [comment]
Hi Joshua, the culprit of why GLMAT is failing is related to the fact that you have a set of gas cells inside the truck, that are surrounded by solid boundaries and disconnected from the rest of the domain. 
So, essentially you have two discretization regions in the mesh, having two different sets of pressure boundary conditions (inside the truck all Neumann BCs for pressure, whereas outside in the tunnel Neumann-Dirichlet due to the open boundary). 
The logic used building the discretization matrix is such that one single matrix is built for the total set of pressure unknowns and the "Neumann-Dirichlet" character of the matrix is input to the linear system solver (in algebra terms we say this matrix is positive definite). I reality the matrix is not, due to the second all Neumann BC set of unknowns, and the matrix factorization stops when a zero pivot is found.
We will have to come up with a strategy to make FDS aware of these different topologies, as GLMAT is essentially an unstructured mesh solver. 

For the time being, comment the OBST line:
`
&OBST XB=550.0,550.5,-2.5,-1.0,0.5,3.5,SURF_ID6='Camion','INERT','INERT','INERT','INERT','INERT'/ Obstruction`

To make the back door of your truck open, and try the case.

Note that this pressure solver uses the same decomposition of the pressure terms as the default solver, only that it does so only on gas cells. Issues related to instability in large tunnels (specially in single mesh cases like the one you posted) for the model are expected to still be present.

I'll leave the case open, to remind us of thinking about how to go about defining correctly the topology in cases of isolated sealed compartments defined by internal boundaries.
For the time being I'll add a warning about this possibility when a zero pivot failure in the matrix factorization phase is found.

**Comment by drjfloyd** [comment]
For real-world applications (buildings with multiple rooms), being able to handle multiple sealed compartments will be important. Until this is resolved, we should note this limitation in the User's Guide.

**Comment by marcosvanella** [comment]
Good point, I'll add discussion on the User Guide for the time being. 
Eventually, I think we want to be able to build pressure discretization matrices and invoke the solver by pressure zones.

**Comment by Joshuaklein98** [comment]
Thank you very much, Marcos and Jason. I am glad that this case has helped
to improve the practice of FDS.

Best regards.

2017-11-20 21:30 GMT+01:00 marcosvanella <notifications@github.com>:

**Comment by Joshuaklein98** [comment]
Thank you to all of you, I will re run the case to see the results, best
regards.

2017-11-21 8:38 GMT+01:00 Joshua Klein <kleinjoshua98@gmail.com>:

**Comment by marcosvanella** [comment]
I'm closing this for now, Joshua let us know if things worked out for you.
