### ISSUE TITLE
SMV -  overlapped surfaces of OBST on the Boundary not shown properly

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5849]
When clipping the model in the x axis, the surfaces on the boundary are not shown appropriately. `Dialogs > Display > Hide overlaps` does not help.

Thank you.

SMV.6.6.1 -69-gb280623 - Jan 3
 
![image](https://user-images.githubusercontent.com/26166281/34567278-e8343c38-f161-11e7-8a15-e102a1638dfd.png)

```
 &HEAD CHID='untitled'/
&DUMP RENDER_FILE='untitled.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0, DT_SL3D=0.25/

&MESH ID='Mesh01', IJK=10,4,12, XB=0.0,2.5,0.0,1.0,0.0,3.0/


&OBST ID='Obstruction', XB=0.0,2.82705437923682,0.0,0.7500000000000004,0.0,3.0, RGB=0,51,204, SURF_ID='INERT'/ 


&TAIL /
```

**Comment by gforney** [comment]
you are placing an OBST drawn with one color at the same location as your mesh boundary which is drawn with a different color (since the mesh boundary is not open).  If you want to get rid of the visual artifacts you will need to either hide the OBST or hide the boundary.  To hide the boundary select Show/Hide>Geometry>Surfaces>Hide All

**Comment by Er9y714** [comment]
That solves it!
Thank you.
