### ISSUE TITLE
[request] Radiation shield feature in porous screens

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5865]
Continuing from the discussion >> [here](https://groups.google.com/d/msg/fds-smv/zE_DWkvFllc/3cGWap-LEgAJ)

Porous surfaces are currently possible to be modelled as mesh screens with static particles in INIT region. Since particles already have their own calculation routine for radiation, is it possible to model radiation screens (perforated heat shields e.g. that are used in oil rigs) with the same way we model porous screens? 

Thank you.

**Comment by mcgratta** [comment]
Create a simple verification case using the latest version of FDS to demonstrate what you want to do.

**Comment by Er9y714** [comment]
[Radiation_shield.fds.txt](https://github.com/firemodels/fds/files/1615728/Radiation_shield.fds.txt)
I hope the file is consistent with what I explain here. 

I aimed to halve the incident heat flux on the +x wall by using a 50% perforated metal sheet (FREE_AREA_FRACTION=0.5).  It currently reduces but not 50%. Is it because I modelled in a wrong way or the application is not suitable to the purpose? If the latter, is it possible to have this as a new feature?

**Comment by drjfloyd** [comment]
The screen data model is intended for window screens -- metal meshes rather than perforated metal sheets. You will probably not get the pressure drop through the perforated metal.  You could get the screen drag model to get the correct pressure drop by playing with the porosity, but this would impact the area for attenuating radiation which is important in your application. Having the correct metal area plus the correct drag means you will need to use the POROUS media inputs and calibrate the two drag constants to get the correct drag as a function of flow through the perforated metal.  You should be able to located this data online as perforated metals are often used to cover HVAC openings or are used as coarse screens in industrial ventilation systems.

I don't think we have at this point the ability to have porous media attenuate radiation. I think we have a lot of the pieces needed for that present. I think this is doable.

**Comment by Er9y714** [comment]
I understand.  I noted and will follow the recommendation for calibrating the media as you stated. It is a good starting point. Thank you.
