### ISSUE TITLE
Numerical instability GLMAT in tunnel

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#5917]
Dear developers,

First, I want to thank you and especially Marcos Vanella for the development of the new solver. Last week, I encountered a numerical problem while I was simulating one tunnel with the new solver GLMAT. 

I was performing a mesh independence study and I ran two cases with regular grids of 0.10 m and 0.05 m size. For the coarse mesh the simulation ran smoothly till the end, but for the finer mesh the simulation stopped after 45 s. I'm now rerunning the case with finer mesh with the normal solver and it is going well, I already simulated 90 s. However, the GLMAT is much faster and I would like to exploit this capability.

I attach a simplified version of the input file with coarse and fine grids.
[input_tunnel_coarse.txt](https://github.com/firemodels/fds/files/1645663/input_tunnel_coarse.txt)
[input_tunnel_fine.txt](https://github.com/firemodels/fds/files/1645664/input_tunnel_fine.txt)

I also report some results from the q files before the simulation stops, the temperature looks good but the HRRPUV and the velocity show really high values.
![u-velocity](https://user-images.githubusercontent.com/15084725/35140057-1c2c6728-fcf6-11e7-808d-db3a194a8341.png)
![hrrpuv](https://user-images.githubusercontent.com/15084725/35140058-1c4d406a-fcf6-11e7-9fc5-9b9f27218e82.png)
![temperature](https://user-images.githubusercontent.com/15084725/35140059-1c681fc0-fcf6-11e7-9445-0ab5e1aa31dc.png)
I also checked the pressure during the simulation but it doesn't show really high values, it is usually in the range between -20 and +10 Pa.

Thanks for your help 

Matteo

**Comment by rmcdermo** [comment]
@mpachera Thanks for the report.  We will take a look.  So that I understand, the first priority here is to get GLMAT to complete the "fine" case, correct?

**Comment by mpachera** [comment]
Yes, that would be my wish, for tunnel I often need a lot of iterations to avoid numerical problems and with the GLMAT solver the computational time drops.

**Comment by marcosvanella** [comment]
Hi Matteo, I'll take a look at your case.

**Comment by marcosvanella** [comment]
Matteo, I haven't forgotten about you. I run the coarse case and that run fine up to 60+ sec. I'm still running the fine case to see if I can reproduce the instability.

**Comment by marcosvanella** [comment]
Hi Matteo, I finally got a numerical instability for the fine grid. Interestingly, it happened at 56 sec of simulation time, instead of 45 sec as you reported. At this point, it is hard to pinpoint if the culprit of the instability is the GLMAT solver itself, given that the calculation run without issues for 11540 time steps. I submitted two more calculations with the fine mesh, one reducing the CFL number to 0.85, and the other suppressing the baroclinic term (BAROCLINIC=.FALSE. in &MISC line).
I'll let you know what I find.

**Comment by mpachera** [comment]
Thanks Marcos for your help, do you expect the BAROCLINIC=.FALSE. to change is somehow the results of the simulation?

**Comment by rmcdermo** [comment]
While I understand the idea of trying this (BARO=F) for the sake of debugging, we must be careful not to allow this to become lore should the case happen to run successfully.  We spent years getting BARO back working.  All the validation for flame heights, plume correlations, etc., depend on it.

**Comment by marcosvanella** [comment]
Hi Matteo, Randy is correct in his note. 
Scrapping the baroclinic term on momentum is not advisable, as it will potentially reduce the fidelity of the model. On top of that, all validation work currently done on FDS uses the baroclinic term, and you want to have that reassurance. 
My test is more related to understanding if the inclusion of the term and the treatment of it done in FDS has to do with the instability. Note that GLMAT solves the Poisson equation for H once per timestep, so there are no iterations to convergence on this term for the timestep, as done with the default Poisson solver. 
I noted that reducing CFL_MAX to 0.85 made the simulation run up to 94 sec (vs. 56 sec for the default CFL_MAX=1), stopping with a numerical instability. 

So your options at this point are:

- You might want try another test setting CFL_MAX=0.7 to see if it finishes completely. That will give you a 30% hit in computation cost. I can't do that at this point, because our cluster is going to be shut down in a couple of hours.

- Use the default Poisson solver with pressure subiterations.

The fact that we use a previous step Pressure on the term for momentum, gives us the impression there is a stability time step constraint on this term, which at this point we don't know. This is something we are going to explore, and may potentially lead to stable calculations. So let's keep the issue open to remind us of looking into that.

**Comment by mcgratta** [comment]
What's the status of this issue? I'm running the original fine case to see where we are.

**Comment by marcosvanella** [comment]
This should be more stable with the added baroclinic iteration in glmat. Lets see.

**Comment by mcgratta** [comment]
The case is running, but it seems slow. It has run 26 s of simulation, 6600 time steps, in 20 h. That's about 10 s per time step.

**Comment by marcosvanella** [comment]
Kevin, how many pressure subiterations is it doing? This is probably the source of the low speed.

**Comment by mcgratta** [comment]
Between 7 and 10. 10 is the max allowed.

**Comment by marcosvanella** [comment]
Well, for one solve GLMAT is much slower than the FFT solver, but gives no velocity error in mesh boundaries. Makes sense that it will be very slow running it ~10 times to reduce the pressure error. Lets see if the stability issue is addressed, and we can try reducing the maximum pressure iterations.

**Comment by SusanKilian** [comment]
I calculated the input_tunnel_coarse case from Matteo's first post with both GLMAT and ScaRC (structured variant) using 

PRESSURE_TOLERANCE=100, MAX_PRESSURE_ITERATIONS=50 /

each. For a first comparison the maximum computing time was limited to 8 hours each (on the Lunarc cluster in Lund).  I didn't decrease the VELOCITY_TOLERANCE for ScaRC yet, but it seems to produce reasonable results and times. Enclosed are the corresponding results. 

Could you please also test the finer case from input_tunnel_fine with ScaRC on your cluster, beyond the original instability time? I leave the setting of a possible VELOCITY_TOLERANCE to your assessment.

Many thanks and greetings, Susanne

[model_tunnel_00_glmat_steps.csv.txt](https://github.com/firemodels/fds/files/4448890/model_tunnel_00_glmat_steps.csv.txt)
[model_tunnel_00_glmat.fds.txt](https://github.com/firemodels/fds/files/4448891/model_tunnel_00_glmat.fds.txt)
[model_tunnel_00_glmat.out.txt](https://github.com/firemodels/fds/files/4448892/model_tunnel_00_glmat.out.txt)
[model_tunnel_00_scarc_steps.csv.txt](https://github.com/firemodels/fds/files/4448893/model_tunnel_00_scarc_steps.csv.txt)
[model_tunnel_00_scarc.fds.txt](https://github.com/firemodels/fds/files/4448894/model_tunnel_00_scarc.fds.txt)
[model_tunnel_00_scarc.out.txt](https://github.com/firemodels/fds/files/4448895/model_tunnel_00_scarc.out.txt)

**Comment by SusanKilian** [comment]
Still as a supplement to the previous post: As you know, the structured ScaRC has NO velocity error along inner mesh boundaries. The velocity-error shown in the out-file only refers to the inner obstructions and I'm not sure if this really matters in this case. I just started the structured ScaRC with a finer velocity tolerance to see the runtime differences (to default) and additionally the unstructured UScaRC, which also eliminates the obstruction errors.

**Comment by mcgratta** [comment]
The original fine case (model_tunnel_00.fds) with 5 cm grid resolution and GLMAT solver ran out of memory. This is a problem that we have identified with GLMAT, and it has been fixed with the Intel 20 update 1 compiler and MPI. I forgot about that. I am now going to run the case with the SCARC solver.

**Comment by SusanKilian** [comment]
I suppose you use the baroclinic pressure iterations? How did you set the values for the pressure (and velocity?) tolerance and the max number of pressure iterations?
And is the use of an unstructured variant of the pressure solver even considered for this case?

**Comment by marcosvanella** [comment]
Hi Susanne, we are running the case in our older cluster (blaze) for both UGLMAT and USCARC and intel 2020 update 1. The issue with memory in MKL/MPI is fixed (from other tests we have done) on this version. We are having issues porting update 1 to burn.
The cases are running with default pressure solution values (I only changed SOLVER).
UGLMAT is taking 9 seconds here per time step (~1 subiteration) and USCARC is taking 10 minutes (iterating ~180 times to default convergence). Please advise if you want to try changing any scarc parameters.

**Comment by SusanKilian** [comment]
This is much too bad, it seems that there is something wrong with my Pardiso preconditioning for the unstructured variant. The times of the structured version (with FFT preconditioning) seemed to be much better. I will have a look.

Overall, the data-parallel global CG method simply has a much too bad convergence rate for problems of this size. Therefore I am currently implementing a Smoothed Aggregation Algebraic Multigrid method (still stuck in parallelisation), which has comprehensively better convergence rates and works especially for arbitrary numbers of cells (i.e. without the divisibility condition by 2). I hope that this will bring improvement here.

**Comment by marcosvanella** [comment]
Should I resubmit with SOLVER='SCARC' then?

**Comment by mcgratta** [comment]
I started the fine case from above with SOLVER='SCARC'. The case ran for the past 24 hours. It completed 3700 time steps, or 23 s per step. I stopped the job.

**Comment by SusanKilian** [comment]
Okay, thanks a lot for the tests. Even though the FFT preconditioning (ScaRC) is noticeably faster than the PARDISO preconditioning (UScaRC), the convergence rate of the CG method deteriorates with increasing mesh count and seems to be too bad overall. I continue to work on the algebraic multigrid method, which has the advantage of using global information.

**Comment by marcosvanella** [comment]
I'm running the fine case on blaze with UGLMAT, with 1, 2 and 4 OMP threads. Times vary from 17 down to 14 sec per step for 3 max pressure iterations. So it is going very slow. I'll keep the runs to see if the pressure error reduction helps with the instability (Mateos query), and also to check that the IMPI/MKL memory issue is resolved. I submitted also a case with the default solver and 2 OMP threads to compare timings. Susan, let me know (here or email) if you want me to do any other tests with ScaRC.

**Comment by marcosvanella** [comment]
An update on this, in blaze UGLMAT takes about 8.3 sec per step (single pressure iteration, 2 OMP threads per MPI proc), whereas default FFT is taking 6.3 seconds per step in same situation.

**Comment by SusanKilian** [comment]
The convergence rate of the pure CG method (whether for structured or unstructured discretization) with pure blockwise preconditioning does not seem to me to be further improvable, so that I am currently not planning any further tests for this case. It is in the nature of the method that it deteriorates for increasing numbers of meshes. Of course the efficiency of the solvers (FFT/Pardiso) used for local preconditioning plays a big role here and we have already observed for several cases that FFT in the structured case performs much better here. Nevertheless, I still believe that additional global structures are needed for preconditioning, which I would like to provide using the algebraic multigrid method (still working on). I will get back to you by mail in this regard.

**Comment by marcosvanella** [comment]
All tests (1, 2 , 4 OMP threads) using UGLMAT with 3 pressure sub-iterations have run over 200 sec of simulation time (35K+ time steps). Calculations are stable and memory is bounded with Intel 2020 update 1 suite. So, looks like subiteration addresses the instability seen by Mateo on his original post.  
In terms of timings UGLMAT is much more expensive than FFT per subiteration, so a small number of MAX_PRESSURE_ITERATIONS should be used. UGLMAT with 2 OMP threads and 3 subiterations takes 16.8 sec per time step (0.85E5 max pressure error, 1e-15 max vel error), whereas FFT with default settings (10 subiterations, 0.70E4 max pressure error, 0.46 max velocity error) takes 12.2 sec. FFT is running stable on this case.

**Comment by marcosvanella** [comment]
Old and stale. There have been several changes in Poisson solvers including a tunnel preconditioner.
