### ISSUE TITLE
SMV 6.6.1 - Display dialog shortcut

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5945]
**Display** dialog shortcut does not work with lowercase "d". It works with "D". (I suppose it should work with lowercase)

Thank you

![image](https://user-images.githubusercontent.com/26166281/35379287-e949110c-01b5-11e8-97a6-ac973dd430c8.png)

**Comment by gforney** [comment]
should be fixed in the smokeview posted here.  Note, the ALT d short cut is not available on the mac.  The mac uses the d and f keys for CTRL and ALT respectively. (ALT D can be used on the mac to open the display dialog box) 
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
It works in Windows. Thank you!
