### ISSUE TITLE
Remove Version from FDS and SMV, keep Revision number

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5952]
Glenn,
Please remove the Version string from FDS and SMV.  Now that we tag with Git describe we have the version string we want in the Git tag and having a redundant number just leads to errors, as we saw in the post this morning.  Thanks.

Along the same lines, I think we need to slightly modify the bundle process so that you do not bundle directly from the repo, but rather physically download the .zip from the GitHub Releases Tag (as our user did) and build the bundle from that.  This will ensure that future users will be able to easily build the same version that we release.  I understand that the bundle scripts will have to change for this.  I think the first step is to figure out where or how to download that tag .zip from the command line.

**Comment by gforney** [comment]
I disagree on the the second point.  This would be very difficult and more importantly not consistent with how we normally build our apps. Think it much better to make clear how to build our apps to be consistent with what we release by checking out appropriate revision.

**Comment by rmcdermo** [comment]
You're right.  The download step is not important.  But I think the process should checkout via the tag to ensure what gets bundled is the same as what would get built by a user who does download the tag.

**Comment by gforney** [comment]
Given that we often realize we need to make changes after we tag but before
we bundle lets document how we move a tag from one revision to a few
revisions later. This process is not clear to me now and i think is what is
needed. Don't think changing scripts to checkout a tag would be hard.

**Comment by gforney** [comment]
just to make sure we are on the same page , you would like to change
 Fire Dynamics Simulator

 Current Date     : January 26, 2018  10:06:26
 Version          : FDS 6.6.0
 Revision         : FDS6.6.0-131-g88ae75a-HEAD
 Revision Date    : Wed Nov 1 16:03:29 2017 -0400
 Compiler         : Intel ifort 17.0.4
 Compilation Date : Nov 01, 2017 21:03:34

to

 Fire Dynamics Simulator

 Current Date     : January 26, 2018  10:06:26
 Revision         : FDS6.6.0-131-g88ae75a-HEAD
 Revision Date    : Wed Nov 1 16:03:29 2017 -0400
 Compiler         : Intel ifort 17.0.4
 Compilation Date : Nov 01, 2017 21:03:34

(note: ':' don't line up in this message because of fonts that git uses)

**Comment by rmcdermo** [comment]
Correct.  Though, HEAD should be master in the final version.

**Comment by gforney** [comment]
I pushed up my changes.  this is what is generated now

 Fire Dynamics Simulator

 Current Date     : January 26, 2018  10:25:34
 Revision         : FDS6.6.0-798-g18a59ac-master
 Revision Date    : Fri Jan 26 10:18:52 2018 -0500
 Compiler         : Intel ifort 17.0.4
 Compilation Date : Jan 26, 2018 10:24:15

**Comment by rmcdermo** [comment]
Works great.  Thanks.
