### ISSUE TITLE
Minor problems with wind example

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#5991]
I have been running the wind_example.fds example described in section 10.1.2 of the FDS User Guide and have two relatively minor comments:

1. The wind does not go through a complete 360 deg revolution. The vector plot at 0 sec shows the vectors aligned in the +X direction, but at 60 sec, they are not quite aligned.

2. Not all obstruction sextuplets are sorted min to max. This is not required, but it makes things a bit nicer. In addition, there are two duplicate obstructions and two obstructions that are outside the mesh. These are indicated in the highlighted_changes image. I have also attached a modified fds file with these changes.

Hope this is useful,
Dan

![vector plot at 0 sec z 20](https://user-images.githubusercontent.com/13338306/35884558-b6064a04-0b50-11e8-9745-ec96002909d3.png)

![vector plot at 60 sec z 20](https://user-images.githubusercontent.com/13338306/35884590-cbe54924-0b50-11e8-9379-4c4e5ea44ad2.png)

![highlighted changes](https://user-images.githubusercontent.com/13338306/35884598-d1e45be4-0b50-11e8-8123-2788d37c2ab1.png)

[wind_example_fixed.fds.txt](https://github.com/firemodels/fds/files/1700820/wind_example_fixed.fds.txt)

**Comment by mcgratta** [comment]
I'll take a look. Someone else generated this file once upon a time.

**Comment by mcgratta** [comment]
I cleaned up the input file and committed it. As for the alignment, I added another 60 s of simulation time so that you can see the wind come fully back to its original direction. You will not see perfect alignment because the boundary conditions are `PERIODIC`, meaning that the turbulence induced by the buildings is reintroduced into the simulation upstream. It's as if this set of buildings is mirrored in all directions, as in a suburban setting. 

I'll close the issue unless there are other problems, in which case just reopen.
