### ISSUE TITLE
HVAC device doesn't work as control logic input

### ISSUE THREAD

**Issue by rjokonski** [firemodels/fds#6102]
In the attached model, I've added a duct with a basic fan. I also created a device to measure DUCT VOLUME FLOW (one of the HVAC quantities) and put a setpoint on the device record. I then have an obstruction that uses the device as its control logic.  

I found that instead of the obstruction turning on when the device reaches the setpoint value, which happens at ~2.5 s, the obstruction is always on instead.

[flow_control.txt](https://github.com/firemodels/fds/files/1772529/flow_control.txt)

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
I think I know what the problem is. The default TRIP_DIRECTION is +1.  This means, if the  value of a DEVC is  above the SETPOINT, it will change state from the initial state (which is FALSE by default).  Your SETPOINT is -2 and the starting value of the DEVC is 0.   0 > -2, so the DEVC  trips.  Try setting TRIP_DIRECTION to -1.

**Comment by rjokonski** [comment]
That seemed to do it. Thanks!
