### ISSUE TITLE
smv running .ssf from cmd error

### ISSUE THREAD

**Issue by deanmadoo** [firemodels/fds#6172]
Hi All,

I am trying to automate the rendering of results in smv. I have written a .ssf file which goes through all of my slices, loads them, clips the geometry and renders an image. 

The script works well if loaded within smv i.e. right click>load/unload>scripts>NAME.ssf 
All the slice images were rendered correctly and dumped into the folder.
![xslice_55 0_soot visibility_f_0100](https://user-images.githubusercontent.com/37524001/37737707-bf8e8828-2da8-11e8-8a59-549e6d69393e.png)

However, if I run the script from within cmd i.e. "smokeview NAME -script NAME.ssf", the script runs but the images are incorrect, not all mesh slices are loaded and some are missing. This only happens in smv 6.6.0, when smv 6.4.4 is used to run, everything runs perfectly. Also, smv 6.6.3 breaks my script altogether, and does not produce any images at all. 
![xslice_55 0_soot visibility_f_0100](https://user-images.githubusercontent.com/37524001/37737700-b78b7762-2da8-11e8-84db-282882409746.png)

Based on the fact that the script runs fine from within smokeview, I don't think it is an issue with the .ssf file but rather an issue with how smokeview runs it. 

Attached is my .ssf script, does anybody have any ideas?

`RENDERDIR
.
LOADINIFILE
NSWLib-SCF3-A9.ini

LOADSLICE
TEMPERATURE
1 55.0
CBARNORMAL

SETVIEWPOINT
worldcentreyz

XSCENECLIP
1 54.0 0 0
YSCENECLIP
0 0 0
ZSCENECLIP
0 0 0
SCENECLIP
1

RENDERALL
50
Xslice_55.0_TEMPERATURE_f
UNLOADALL

LOADSLICE
SOOT VISIBILITY
1 55.0
CBARNORMAL

SETVIEWPOINT
worldcentreyz

XSCENECLIP
1 54.0 0 0
YSCENECLIP
0 0 0
ZSCENECLIP
0 0 0
SCENECLIP
1

RENDERALL
50
Xslice_55.0_SOOT VISIBILITY_f
UNLOADALL

`

**Comment by gforney** [comment]
try running
smokeview -runscript NAME

**Comment by deanmadoo** [comment]
Hi Glen,

"smokeview -runscript NAME" didnt work for smv 6.6.0. 
The script runs but the images are still wrong with missing slices.

"smokeview NAME -runscript NAME" also dint work.

**Comment by gforney** [comment]
Upload your .fds, .ini and .ssf files and I'll take a look at it

**Comment by deanmadoo** [comment]
[Test4.zip](https://github.com/firemodels/fds/files/1835604/Test4.zip)

**Comment by deanmadoo** [comment]
[Test4.zip](https://github.com/firemodels/fds/files/1835608/Test4.zip)

**Comment by saschagottfried** [comment]
Hi @deanmadoo,

please make sure your issue is not related to a known issue #5969. If you use both Smokeview 6.4.4 and Smokeview 6.6.0 in the same working directory, an existing file `chid_slice.info` generated by Smokeview 6.4.4 might affect loading slice informations in Smokeview 6.6.0.

Until this is fixed in next official version, you can might be fix this behaviour on your machine by deleting the file `chid_slice.info` in FDS working directory. Do not worry, this is only a cache file that is regenerated during next run of Smokeview.

Please add console output of Smokeview scripting and an existing `chid_slice.info` as well as it might support ongoing debugging purposes.

**Comment by mcgratta** [comment]
I'm going to close this issue. If this is still a problem, open a new issue.
