### ISSUE TITLE
 Extinction models

### ISSUE THREAD

**Issue by LahnaACH** [firemodels/fds#6195]
I want to test different extinction model (EXTINCTION 1, 2 and 3) for  propane free pool fire .
for EXTINCTION 2 I have an error message: # ERROR: The default EXTINCTION MODEL is designed for 1 reaction. See Tech Guide (CHID: propane)

**Comment by LahnaACH** [comment]
This is the code:

[propane.txt](https://github.com/firemodels/fds/files/1847209/propane.txt)

**Comment by rmcdermo** [comment]
As the error message says, you cannot use E2 with more than one reaction.
You have 3.

**Comment by mcgratta** [comment]
Since the release of FDS 6.6.0, we have done a significant amount of work on the combustion and extinction routines. If you are working towards a degree, or if this is a research effort of some sort, I suggest that you compile the code from source using the latest build. Also, recompile the guides, in particular the FDS Tech Guide, which will provide more information about what we are doing. Let me know if you need help doing these things.
