### ISSUE TITLE
Developing radiation for GEOMs

### ISSUE THREAD

**Issue by emanuelegissi** [firemodels/fds#6330]
As requested, I just submitted a pull request adding 3 new verification cases to FDS in Verification/Radiation:
- plate_view_factor_2D_100_GEOM.fds
- plate_view_factor_2D_30_GEOM.fds
- plate_view_factor_2D_60_GEOM.fds

These could be the starting base for developing radiation for GEOMs.

**Comment by marcosvanella** [comment]
All right, we'll get to this.

**Comment by mcgratta** [comment]
I added the necessary hooks for radiation. There are two test cases that I have added as well. I will write these up as verification cases.

Simo -- could you look over what I have done. It appears from the test cases that things are working properly.

**Comment by mcgratta** [comment]
Marcos and I are working on the GEOM versions of the plate_view_factor test cases.

**Comment by mcgratta** [comment]
I changed the GEOM cases to be 3D only, and added the results to the Verification Guide, section on Radiation View Factors.

**Comment by mcgratta** [comment]
Marcos -- the `plate_view_factor` test case for GEOM appears to be working well, predicting a heat flux of 81.96 instead of the exact 81.8. Should we close this issue, or I can create some more test cases?

**Comment by marcosvanella** [comment]
Lets close it an talk off line. I have an idea on automating the generation of input files with the plates at arbitrary orientations.
________________________________
De: Kevin McGrattan <notifications@github.com>
Enviado: miércoles, 10 de octubre de 2018 01:41 p. m.
Para: firemodels/fds
CC: marcosvanella; Assign
Asunto: Re: [firemodels/fds] Developing radiation for GEOMs (#6330)


Marcos -- the plate_view_factor test case for GEOM appears to be working well, predicting a heat flux of 81.96 instead of the exact 81.8. Should we close this issue, or I can create some more test cases?
