### ISSUE TITLE
Maximum Pressure Error

### ISSUE THREAD

**Issue by ghost** [firemodels/fds#6347]
Hi,

I have set up a very simple case with an inlet into a domain. I have two models, one with uniform velocity at the inlet and another one employing the Synthetic Eddy Method. What I have discovered is that without the SEM, the maximum pressure error at the end of the simulation is 0.19E+02 and when with the SEM, the maximum pressure error is 0.10E+04.

May I know how this happens, and that how the terms Maximum Pressure Error and Maximum Velocity Error in the .out files are defined?

Thanks.

Edmond

[max_pressure_error.zip](https://github.com/firemodels/fds/files/1962421/max_pressure_error.zip)

**Comment by mcgratta** [comment]
Search the User's Guide for "velocity error" and/or "pressure error".

**Comment by drjfloyd** [comment]
Should we define that e^k in eq 6.17 is the pressure error?

maybe in the sentence before change to "maximum value of e^k, the pressure error, in the following expression" ?

The guide doesn't seem to have a specific definition for the velocity error.  A pdf search shows four occurrences and none are a definition or equation.

**Comment by mcgratta** [comment]
I'll add some more explanation to the User's Guide.

Edmond, do the following, and then I'll explain what's going on:

1. Do not use more than one `DUMP` line in your input file.
2. Add this line to your input file
```
&PRES PRESSURE_TOLERANCE=100. /
```
3. Add `VELOCITY_ERROR_FILE=.TRUE.` to the `DUMP` line.
4. Run the "with turbulence" case.
5. Open the `_pressit.csv` file and plot column 3 `Total` vs column 13 `Pressure Error`. Look at about 50 rows of data. This shows the pressure error, as defined in the User's Guide. You will see that this error goes from about 1000+ down to less than 100 in a few iterations. In your original case, even through the pressure error was larger in the turbulent case, it was still below the tolerance of 20/dx^2. By adding a tighter tolerance, you are reducing the error, but adding a few extra pressure solves to each time step. 

So why is this happening? As you can see from the User's Guide, FDS solves the pressure equation multiple times to reduce errors in the velocity at solid and mesh boundaries, and errors related to the decomposition of the pressure gradient term in the momentum equation. In your case, the velocity error is essentially zero, because you only have one mesh, and you are applying velocity boundary conditions at the external boundary of the mesh, for which the velocity solver we use handles exactly. The pressure error is greater in the turbulent case because the SEM method "stirs up" the flow field each time step, which increases the difference between the old and new values of the pressure, requiring more iterations to get them to converge. 

Since you are within tolerance in both pressure and velocity, you are probably OK in ignoring this, but if you want to tighten the pressure tolerance, you can do so. It doesn't seem to cost much in this case.

**Comment by ghost** [comment]
Thanks Kevin for your detailed explanation.
Is there a reason for the default setting of the pressure tolerance to be such a high value? (20/dx^2) means dx=5mm would give a maximum 8E+5 of pressure error. Is the epsilon^k in Eq. 6.18 of the User's Guide the pressure error? Thanks.

**Comment by mcgratta** [comment]
Units are 1/s^2, not Pa. I cannot think of a better way to express the error. Yes, it's eps^k
