### ISSUE TITLE
HVAC system

### ISSUE THREAD

**Issue by alexismano** [firemodels/fds#6390]
I have a problem with my hvac system.My hvac system has 1 inlet in the corridor and 8 outlets in the rooms ,i use 1 fan and i get a numerical instability error.
[boat.txt](https://github.com/firemodels/fds/files/1988294/boat.txt)

**Comment by drjfloyd** [comment]
You have only specified a fixed volume flow for the fan and are asking FDS to predict flows in all the other ducts, but you haven't specified any losses in your HVAC system.  Without this any predictions made will not reflect the true behavior of the HVAC system and you increase your risk of instabilities. The system will have flow losses in any tees, elbows, reduction or expansion fittings, balancing louvers, etc.  If you do not have sufficient design detail to be able to determine these losses, then I suggest you just specify the design flows at each duct connected to a VENT and not have the fan.

Note, your material properties are 'Completely Made Up'.  It could be the case that the instability is not due to the HVAC model but due to made up material properties.

**Comment by alexismano** [comment]
In the case i have below i followed the same steps with this and the simulation worked just fine.I used the same details for the fan and the fan was used in the ducts of the internal nodes.I did not use any more details.
[boat1.txt](https://github.com/firemodels/fds/files/1988385/boat1.txt)

**Comment by drjfloyd** [comment]
Like your earlier issue, boat.txt  has no leakage.  This may be the cause of an instability.

If you want to have the model to correctly predict the behavior of an HVAC system in response to a fire, you must specify losses that reflect the HVAC design.  Without appropriate losses your duct flows will not be correct. Also, without losses you run a significantly higher risk on instabilities.  

boat1.txt has a node connecting to AMBIENT which appears to be providing pressure relief from the fire
boat1.txt appears to fully specify the flows which avoids the issue of have no losses in the system.
boat1.txt is not an equivalent case to boat.txt

**Comment by alexismano** [comment]
I tried to run the simulation with no fan as you suggested (because i do not know about the losses in ducts).I put 200sec simulation but now it stops at 60sec approximately again with a numerical instability error.
[Text Document.txt](https://github.com/firemodels/fds/files/1996107/Text.Document.txt)

**Comment by mcgratta** [comment]
Three things. First, you need to create a pressure `ZONE` for each room. FDS needs to know that these rooms are all sealed so that it can compute a separate background pressure for each. Second, include a horizontal (z-plane) slice of pressure and make sure that it makes sense. Third, run your HVAC network without the fire to make sure it makes sense. Then add the fire.

**Comment by drjfloyd** [comment]
If you want FDS to solve for the flows in ducts (i.e. you are not specifying the flow everywhere), then you need to provide losses.  If you are unable to determine or estimate reasonable losses, then you are better off just specifying the flow at all the inlets and outlets to the system.

Right now you are still asking FDS to solve for flows in the ducts based upon the pressures resulting from the fire. With essentially zero losses in the system, there is nothing to prevent very large accelerations of flow in the ducts with small changes in pressure in the FDS domain.

Each of your compartments is sealed with a single duct going to them. How is the air that you want to supply to the compartments going to get back into the hallway to be recirculated in the compartments where the door is closed? There is likely a louvered opening on the door or wall to allow air to return back to the hallway that you are not capturing in your model.

You should specify XYZ(3) for the tee nodes.

Right around the time you are reporting the crash, the compartment is flashing over. That pressure pulse combined with a non-physical HVAC system (predicted duct flow but no flow loss) is likely that cause of the crash.

Why have you set BACKING='VOID' for your steel bulkheads?  Steel bulkheads will transfer a significant amount of heat to adjacent spaces and can serve as a means for spreading fire to adjacent spaces.

I took your file, added holes to the compartments to allow for return air flow (this should really be done with localized leakage and specifying pressure ZONEs for each room), put the 2 m^3/s volume flow back at the air intake point, and added some notional losses to the HVAC system (I am not claiming these losses are correct, just to illustrate). Also, is this the correct flow? It is over 10 air changes per hour which is fairly high for a non-hazardous space. The file is attached.  It is now out to over 100 s and still running.

[new_boat2.txt](https://github.com/firemodels/fds/files/1996432/new_boat2.txt)

**Comment by alexismano** [comment]
Ok i see.Thanks a lot!
