### ISSUE TITLE
Problem with rendering every X number of frames

### ISSUE THREAD

**Issue by adnannweilati** [firemodels/fds#6435]
Hi, 

Im using the latest version of Smokeview (SMV6.6.4-0-g7331116). Although the RENDERALL is working now with this version, Im unable to render images at any certain number of frames (example: every 5th, every 10th).

**Comment by rmcdermo** [comment]
![screen shot 2018-05-22 at 7 01 22 am](https://user-images.githubusercontent.com/4418497/40358656-f9d3ffb2-5d8d-11e8-898e-2fdca739bcbd.png)

This is what I get with latest test version of Smokeview.  Try the version posted [here](https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA) and see if this solves your problem.  Please report back.

**Comment by gforney** [comment]
I'm not able to reproduce your problems using the menu as randy suggested or with the smokeview smokeview script command RENDERALL .  If you are still having a problem,  detail exactly what you did.  thanks.

**Comment by adnannweilati** [comment]
Im loading the slice and choosing Every 10th in the frame selection menu as shown in the screenshot
![image](https://user-images.githubusercontent.com/38315126/40360893-7556c97c-5dbf-11e8-8117-042ab678ea37.png)

When I press 'Render normal', it starts to render all the frames in my simulation and disregard my frame settings.

**Comment by gforney** [comment]
sorry, I'm still not able to reproduce the problem.  upload your test case (or create a simpler one if you can't) and I'll take a look to see if there is something special about your case

![issue_6435](https://user-images.githubusercontent.com/12403014/40364551-a356aabe-5da0-11e8-8dbe-b08c0f205f9b.png)

**Comment by adnannweilati** [comment]
In response to Randy's suggestion of using the test version of Smokeview, I tried it and it did not make any difference. Im still unable to render images at any certain number of frames.

My problem is not related to a specific case. Its occurring with all the smokeview cases I have on my computer or on our HPC cluster. So I dont think providing a test case will enable you to reproduce this problem.

**Comment by gforney** [comment]
I am not able to reproduce  the problem.  so that we are dealing with the same case.  upload a simple test case that fails for you.  you say you are using a HPC cluster.  Is the case located on the same pc that is running smokeview?  if not try running a case on your "smokeview" pc to see if the problem still occurs

**Comment by sbenkorichi** [comment]
Glenn,
Nothing of rush, but you can work on this when you have time later on.
I found a way to reproduce this issue (under Linux --latest release).

1. Run the attached example. Then load temperature slice.
2. Dialogues/Motion ---> Render : Select : every 20th or 10th. Then hit start rendering. You will notice that 20th or 10th will switch to "all frames".  
However, if you from the beginning choose every 2nd, or 3rd or 4th or 5th. They will all work. And after if you try 10th or 20th, they will work also. 
The problem seems to do start rendering from the beginning with the 20th or 10th frames option.

[test.fds.txt](https://github.com/firemodels/fds/files/2129364/test.fds.txt)

**Comment by gforney** [comment]
I"ll have to wait until monday to try the linux smokeview.  not able to reproduce the problem using your steps with windows or osx smokeview

**Comment by sbenkorichi** [comment]
Yes, no rush.
Thanks !

**Comment by gforney** [comment]
I was finally able to reproduce the problem.

should be fixed in smokeview posted here.  let me know if there is still a problem
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by sbenkorichi** [comment]
Like a boss indeed !
Well done Glenn, fixed on Linux platform. Hats off to you and your hard work.

Close the issue please if there is nothing to be done.
Thanks
