### ISSUE TITLE
SMV 6.6.4 - few bugs

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#6446]
Thank you for the new release, I noticed few small issues. Please let me know if I need to share a fds file to reproduce the errors. 

Thank you.

1. 3D smoke > tick `Use Gpu `
this appear on top left corner:
![image](https://user-images.githubusercontent.com/26166281/40476044-5b246e3a-5f43-11e8-8142-3267826bc1ad.png)

2. When `Show `option is selected, clicking `slice `button on the right toggles the slices (show/hide)
`Hide `button does not work.
![image](https://user-images.githubusercontent.com/26166281/40476219-c7fc1198-5f43-11e8-9562-f8c0338d7a65.png)

3.File/Bounds>Data>Boundary> Output data
(This is not a new feature but) I could not work it out to get an output file. I also did not see any instructions in user guide. Could you please guide me?

4.File/Bounds>Time
After setting Min time and Max time, simulation starts with min time but ends with (Max_time-1). Is this intentional?

5.Clipping
when `center of clipping planes` is ticked, 
changing bounds of clipping (x,y or z) resets the view angle of the model. Is it possible to hold the view during changing these values?

6.Not a bug or request but a question; 
Is the reason of setting CELL_CENTERED on fds file prior to a calculation that storing data becomes  different? If not, is it possible to toggle view (regular/cell centered) after calculation?

**Comment by gforney** [comment]
Thanks for the feedback. I'll take a look

**Comment by gforney** [comment]
1.  this is a bug in the library I used to display dialog boxes (or a bug in how I call one of these dialog box routines.  I've been looking for this bug for a while but have not found it.
4.  not intentional
6.  yes .  fds collects and stored different data for cell centered and node centered slice fifles.  so it is not possible to toggle this view after the calculation
am looking at other items in your list

**Comment by sbenkorichi** [comment]
4. Isn't this related somehow to the issue reported here https://github.com/firemodels/fds/issues/4608

**Comment by gforney** [comment]
Could be. I'll check

**Comment by gforney** [comment]
4.  think if you check the actual times put in the data files by fds you will find that they are not exact multiples of 1 second.  so the time may be 30.04 rather than 30.  so if you put a max of 30 in smokeview , smokeview will not load the 30.04 time step but stop at the one before.  just add a small amount to the max time value in the smokeview time bounds dialog box

**Comment by mcgratta** [comment]
Question 6: Yes, when `CELL_CENTERED=T`, the data value for each cell is different.

**Comment by gforney** [comment]
Think the problems are fixed or explained.  I'm closing this issue.  If any of the problems are still unresolved open another issue - thanks.
