### ISSUE TITLE
Problem with MPI

### ISSUE THREAD

**Issue by zhaopengswjtu** [firemodels/fds#6465]
My FDS is 6.5.4(Windows), When I want to use the MPI, I follow the order of the FDS Guide :mpiexec -n 4 fds jobname.fds, The screen display: Credentials for DESKTOP-515I198\Dr.Zhao rejected connecting to DESKTOP-515I198, But  Pyrosim2016 can use MPI, Could you give me some advise?

**Comment by Er9y714** [comment]
I did not look into a permanent solution for this issue but I bypass this by adding` -localonly` parameter to the cmd line.

**Comment by mcgratta** [comment]
You should talk to your network administrator. In order to use the MPI functionality of FDS under Windows, your computer(s) should be on a Windows Domain Network where all users have common credentials (name, password) on all machines. If your credentials are rejected, it sounds like (a) you are not on a Windows domain network, or (b) there are security requirements that the FDS installation has no control over.
