### ISSUE TITLE
Development of BNDF for Complex Geometry

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6596]
Glenn,
To start, this case is not working with current BNDF, BNDE capabilities with `Test(SMV6.7.1-45-g90f18d223)`.  If you try to load the boundary files, the geometry disappears and nothing shows up at the boundary.

Next, we need to start working toward getting the output parameters for GEOM to be fairly seamless .  This means we need to get rid of things like BNDE, FACE_CENTERED, etc., and do whatever needs to be done either internally in FDS or Smokeview.

**Comment by rmcdermo** [comment]
Oops... forgot the case.  It is

`fds/Verification/Complex_Geometry/sphere_propane_demo.fds`

**Comment by gforney** [comment]
This is a settings problem.  The short term solution is to

1. select Dialogs/Data bounds menu item
2. select Geometry settings
3. select solid radio button, then shaded (and/or outline, points) checkbox

The problem is that these settings effect both geometry slice files and geometry boundary files.  Currently these settings were customized for geometry slice files (show only in gas and cutcell region, not solid region)  If I were to change the settings to draw this boundary file correctly then the geometry slice files won't be drawn correctly.

The long term solution then is to have one set of settings for geometry boundary files and another set of settings for geometry slice files

Also, when you do make the solid region visible you will note that you only see data drawn for the bottom of the sphere.  marcos and I have noticed this before.  I think this is an fds problem

**Comment by gforney** [comment]
I'm implemented a "medium" term solution .  geometry boundary files should now be visible without having to use the settings dialog box in mentioned in previous comment.  still need to have separate settings dialog boxes for geometry slice and geometry boundary files unless we decide that line/points visibility settings should be the same for geometry slice and geometry boundary files.

I'll post smokeview's to test tomorrow

**Comment by gforney** [comment]
smokeview posted here should draw faces not volumes by default (assuming you didn't save an ini file with volume drawing set)

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by rmcdermo** [comment]
Works, thanks!

**Comment by rmcdermo** [comment]
Glenn,
It looks like to me that Cut Cells are always drawn, even if "solid" is checked.  I cannot find a setting that draws the original triangles that get created by the sphere geometry.  (I'm expecting to be able to see the equilateral triangles used to build the sphere.)

![screen shot 2018-07-06 at 12 45 22 pm](https://user-images.githubusercontent.com/4418497/42390658-a494c79c-811a-11e8-9535-fb86755c3124.png)

**Comment by rmcdermo** [comment]
OK, I spoke too soon when I said things work.  Here is what I get for the sphere_propane_demo case.

I know I am coming to this after some time... but I am really lost.

![screen shot 2018-07-06 at 1 04 38 pm](https://user-images.githubusercontent.com/4418497/42391406-43d321b2-811d-11e8-81c0-3101c6e53aee.png)

**Comment by gforney** [comment]
(didn't see your last two comments until after we talked)
sphere comments:
you won't see the original sphere geometry when you are viewing the geometry boundary file - you see the geometry generated for the boundary file which will have nodes from the original geometry plus nodes at intersections of the original geometry and the fds grid (marcos correct me here if I mistated something)

I realized that my fix to allow one to see the geometry boundary file (which was hidden yesterday) is preventing me to show only the outline ie I can't hide the solid surface

Hemisphere comments:
1. drawing only half a sphere is a bug in fds in how the data gets generated
2. the bound data dialog box is really meant for geometry slices but should work for geometry boundary files with the caveat that geometry boundary files are always in the solid so gas and cut cell shouldn't have an effect.  If you click on solid you should be able to check/uncheck shaded, outline and points to show/hide these features.

**Comment by gforney** [comment]
randy, can you tell me again what files and in what order you loaded them that was causing the problem with temperature scale.  It was the ccibm_sphere_heat_flux case ?

**Comment by gforney** [comment]
never mind - I reproduced the problem

**Comment by gforney** [comment]
from our last conversation this is my recollection of the smokeview problems that need to be addressed. 

1.  geometry boundary files have an extraneous z=x.yyy appended to the its menu item
2.  parameters controlling shaded, outline and points display affect geometry boundary and geometry slice files in the same way
3.  colors/values for boundary slice files are not consistent when displayed along with regular slice files

I've fixed 1 and 2.  I'm working on 3 - this will take some time as it is not a simple bug that can be fixed but more of a "design" problem (geometry slice and geometry boundary files were being treated the same in smokeview - though I had "separated" these constructs somewhat in smokeview I have more work to do). 

I may need some help in modifying my test case (I copied ccibm_sphere_heatflux.fds over to the smv repo ) to generate data with known values so I know whether smokeview is working.  We can talk when I get back.

**Comment by rmcdermo** [comment]
@gforney From SMV point of view, do we need DUMP_BNDC and DUMP_BNDE routines in FDS?  Looks like these write up .bc and .be files, respectively.  I suspect they are very stale and can be purged, but wanted to see if you are by chance using them for anything.

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
we can get rid of DUMP_BNDC and DUMP_BNDE.  Need to keep DUMP_GEOM .  We can get rid of "under constructdion" comment in DUMP_GEOM.  This routine is pretty stable now.

**Comment by gforney** [comment]
I'm making progress with smokeview being able to visualize geometry slice files with the corrected color bar labels.  I've got a couple of test cases (derived from ccibm_sphere_heat_flux.fds in the fds repo)  in smv/vistest/geometry .  In sphere_test2.fds I'm initializing various regions to specific temperatures. The idea is that when I load slice files both structured and unstructured I want to know what colorbar temperature labels to expect.

@rmcdermo  think you told me how to do this before  but can't remember what case I put it in.  can you tell me how to turn off flow so that the temperatures stay constant in time .

**Comment by rmcdermo** [comment]
FREEZE_VELOCITY=T on MISC turns off the momentum solver.  You can initialize the TMP field to something with an INIT line.

&INIT XB=..., TEMPERATURE=.../

**Comment by gforney** [comment]
Take a look at smokeview here.  
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

This should fix these 3 problems: 
1. geometry boundary files have an extraneous z=x.yyy appended to the its menu item
2. parameters controlling shaded, outline and points display affect geometry boundary and geometry slice files in the same way
3. colors/values for boundary slice files are not consistent when displayed along with regular slice files

I made a lot of changes so there may still be bug lurking.

Also look at the sphere_test1.fds test case located at smv/vistest/geometry (see attached image drawn at t=0).  It is divided into 3 meshes.  3 meshes are initialized to 100, 200, 300C and 3 sphere and obst they sit on are initialized to 400, 600 and 800 C.  You can draw boundary or slice files to verify that they are colored correctly.

randy - is it possible to put a device on a solid surface to record its temperature the way I use devices for the gas?

I changed the image to be at 10 seconds instead of 0.0
![sphere_test1_0127](https://user-images.githubusercontent.com/12403014/43226440-e117c552-9029-11e8-9dc4-af0c663611b8.png)

**Comment by rmcdermo** [comment]
Yes, you use something like this (for OBST):

`&DEVC XYZ=..., QUANTITY='WALL TEMPERATURE', IOR=... (+1 for surface pointing to the right) /`

I do not know the status of DEVC for CFACES.

**Comment by mcgratta** [comment]
I'm going to close this issue. Let's open a new one if new issues with BNDF and IBM arise.
