### ISSUE TITLE
Velocity Vector for Gas Release from a Particle

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#6928]
I see the option of using a velocity patch to help the gas flow in a certain direction from the particle location.  What I am suggesting is that you can set a velocity vector for that cell and the velocity values at cell faces will be nudged by this amount.  Allowing a simplified gas release direction from a certain point in the domain.

**Comment by rmcdermo** [comment]
@bwklein Sorry, but I am not a fan of this idea.  The reason is that at the resolution on which you can alter a velocity component, you might as well put an OBST in the cell with a VENT specifying the velocity components.  If you are trying to mimic the field from a point source of momentum, then you need a field, not a single vector.  The VELOCITY PATCH gives you the flexibility to specify that field.  I don't see a good reason to change it.
