### ISSUE TITLE
Wind velocity change near inlet open vent

### ISSUE THREAD

**Issue by dlucioist** [firemodels/fds#7014]
[wind_profile_A2B9_1.txt](https://github.com/firemodels/fds/files/2634446/wind_profile_A2B9_1.txt)
Hello there,

I'm having trouble with the open boundaries. I define the wind velocity and temperature profiles with ramps and put a heat source in the middle of the 2D domain. The problem is that the wind velocity changes after the inlet and somehow generates vertical velocities.
I've tried increase the sponge cells and to reduce the dt_mean_forcing, but it didn't make any difference.
Can you help me?

Thank you

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
No, I cannot help you. You are not using a conventional atmospheric wind profile. You have stretched the grid cells far more than we recommend. You are using various parameters that I would not recommend for such a simulation. 

I would guess that you are doing one of two things. Either you are trying to replicate a known analytical solution to the 2D equations of an atmospheric boundary layer, or you are trying to simulate a line fire. If I were you, I would start with a coarsely gridded 3D simulation in order to establish appropriate boundary conditions. Then refine the grid without overly stretching the cells more than 2 to 1.

**Comment by dlucioist** [comment]
Yes, I'm trying to compare results. Thank you for your answer
