### ISSUE TITLE
PARTICLE FLUX X varies around mesh boundary

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#7147]
I aimed to measure particle flux at a cross section (e.g. tunnel). Design nozzle releases 0.2 l/s flow rate. 

The attached first file has one mesh, the second has two meshes. The location of the nozzle and devices are the same. The output varies between calculations. Also the first few devices do not measure correct flow rate.

Nozzle is located at 9.75 m (x) in +x direction horizontally. Devices are located between 8.9 m and 11.4 m at every 5 cm. 
Grid size is 20 cm.

Thank you.

 
![capture](https://user-images.githubusercontent.com/26166281/52286773-19a41780-2969-11e9-98cd-1195211a66ce.JPG)

[one mesh.txt](https://github.com/firemodels/fds/files/2832863/one.mesh.txt)
[two meshes.txt](https://github.com/firemodels/fds/files/2832864/two.meshes.txt)

**Comment by mcgratta** [comment]
I have found one bug, which you can work around. 

The way `'PARTICLE FLUX X'` works is by summing the particles over a one cell thick slice through the domain. But because of a bug, the slice in the first cell of the second mesh is being set to 0 instead of 1. To work around, put your slices (and you only need one per cell in the x direction) in the right side of the grid cell. That is, make sure that x is, say, 0.75 of the width of the cell.

Next, set your time step to, say, 0.005. The big droplets are crossing nearly the entire cell in one time step, which is OK, but not good for statistics.

**Comment by Er9y714** [comment]
- I have placed devices to 75% of the right side of each following cell after the nozzle. I received this output:
![image](https://user-images.githubusercontent.com/26166281/52328196-020f7200-29ef-11e9-8c04-a8c033d650c8.png)

Did I implement your suggestion correctly? 



- As  for the time step:

Nozzle dia is 0.004 m
Flow rate is 12 kg/min = 0.2 kg/s = 0.0002 m3/s
Velocity at the nozzle is 15.9 m/s
cell size is 0.2 m
particles travel a cell in 0.01256 s
the output of the file shows the time step is 0.0019 s

I think time step is sufficient because of `PARTICLE_CFL=.TRUE.`

**Comment by Er9y714** [comment]
Additionally, I noticed that even in one mesh calculation, PARTICLE  FLUX device has to be at least 1,5 cells away from the mesh boundary.

**Comment by mcgratta** [comment]
I fixed two bugs. The first one I mentioned above. The second bug was related to the mesh boundary. When the particles crossed the boundary at x=10, the x,y,z coords were transferred but the i,j,k was not. The i,j,k indices are updated in the next time step. The particle mass flux is calculated using the particle indices, thus, there was missing information.

If you could recompile and check, that would be great. Otherwise, follow the work-around above and avoid measuring particle flux near mesh boundaries.

**Comment by Er9y714** [comment]
Thank you for your time. 
I am not able to compile, therefore I will use the suggested method. 

As an update: halving the DT (time step) improves the measurement accuracy compared to only using **`PARTICLE_CFL=.TRUE.`**
