### ISSUE TITLE
Possible problem with Smokeview coloring particles

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#7169]
Run this simple case, and in Smokeview load the particles, show them as TUBES, and at the same time show their temperature. I recall being able to do this in the past.
```
&HEAD CHID='junk' /

&MESH IJK=10,10,10, XB=0.0,1.0,0.0,1.0,0.0,1.0 /

&TIME T_END=30. /

&MATL ID='cable material'
      DENSITY=2000.
      CONDUCTIVITY=0.2
      SPECIFIC_HEAT=1.5 /

&SURF ID='cable surface'
      THICKNESS=0.00725
      LENGTH=0.1
      MATL_ID='cable material'
      GEOMETRY='CYLINDRICAL' /

&PART ID='cable segment', SURF_ID='cable surface', STATIC=.TRUE., PROP_ID='cable picture', QUANTITIES='PARTICLE TEMPERATURE' /
&PROP ID='cable picture', SMOKEVIEW_ID='TUBE', SMOKEVIEW_PARAMETERS='L=0.1','D=0.0145','DIRY=1','R=255','G=0','B=0' /
&INIT ID='cable tray A', XB=0.41,0.59,0.41,0.59,0.41,0.59, N_PARTICLES_PER_CELL=4, CELL_CENTERED=.FALSE., PART_ID='cable segment' /

&SURF ID='HOT', TMP_FRONT=500. /
&VENT MB='ZMIN', SURF_ID='HOT' /

&TAIL /
```

**Comment by gforney** [comment]
I've reproduced the problem.  I"ll try to figure out what is going on

**Comment by gforney** [comment]
try smokeview posted here.  the problem was that the R=255,G=0,B=0 line in the input file was overwriting the particle file color (if you removed R=255... it would work with your smokeview) I changed logic so that the colors on property line should only be used if Uniform is selected in the Show menu.  The logic is kind of complicated so hopefully we won't be playing whacka mole - let me know if this works for you and if there are any unintedned side effects

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by mcgratta** [comment]
Works! Thanks.
