### ISSUE TITLE
Relative humidity results not correct

### ISSUE THREAD

**Issue by pankajadgjmp** [firemodels/fds#7473]
Hi all,

I was trying to model an air conditioned cooling case using fds and applied the water vapour mass fraction to the supply at 86.5% RH. while viewing the RH results the maximum relative humidity reaches 150% at the inlet. What is the cause of this problem? why don,t I see the RH specified 86.5%? 

Can anyone help ?

Thank You
[RH_1.txt](https://github.com/firemodels/fds/files/3370955/RH_1.txt)

**Comment by drjfloyd** [comment]
The default air species has 40 % RH (at TMPA). So your AC inlet is 99.2 % AIR with 40 % RH at 20 C plus 0.8 % WATER VAPOR.  FDS does not currently have a condensation model so the two humidity values just add up. 40 % RH at 20 C is 66 % more than 40 % RH at 13.8 C so instead of seeing a humidity that is  86.5 + 40 = 126 % you are seeing 86.5 + 40 * 1.66 = 153 %

**Comment by pankajadgjmp** [comment]
Hi Dr J Floyd. Thanks for the response. Can you please suggest how to replicate the same case with the correct value?

Thanks

**Comment by drjfloyd** [comment]
Adjust the MASS FRACTION of WATER VAPOR on your SURF so when it is added to the existing ambient humidity you get the correct total mass fraction for your inlet boundary condition.

**Comment by pankajadgjmp** [comment]
Thank jason.
