### ISSUE TITLE
Deardorff viscosity at mesh boundaries with velo initialization

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7537]
The attached case has an initial WIND.  With NOISE there is a discontinuity in the turbulent viscosity at the mesh boundaries.  This probably has something to do with initialization and/or mesh exchange for M%U_GHOST(IW) values, which are needed in the Deardorff eddy viscosity routine for test filtering.  If it is not a huge effort, it would be nice to get rid of these discontinuities.

[test.fds.txt](https://github.com/firemodels/fds/files/3525674/test.fds.txt)

![Screen Shot 2019-08-21 at 9 58 45 AM](https://user-images.githubusercontent.com/4418497/63438450-4c3fca00-c3fa-11e9-9e94-92f8a645eca1.png)

**Comment by mcgratta** [comment]
The problem was that calls made to `COMPUTE_VISCOSITY`, `VISCOSITY_BC`, and other `velo.f90` routines during the `INITIALIZATION` rely on the setting of `PREDICTOR` and `CORRECTOR` to determine whether to use `U, V, W` or `US, VS, WS`. These parameters are not well-defined before time stepping begins. Now, you will see on several of these subroutine calls the parameter `APPLY_TO_ESTIMATED_VARIABLES` which if T points to `US` and F to `U`. This makes it more clear in `main.f90` what is being done.

Try your case again and make sure that things are working as you expect.

**Comment by rmcdermo** [comment]
@mcgratta Thanks.  The normal-direction mesh boundaries now look correct.

Next step would be to fix mesh corners.  With NOISE=F, you will see the following for the velocity magnitude at a mesh interface in SMV.

It might be possible to use FILL_EDGES (in module TURBULENCE, this avoids a mesh exchange by doing an extrapolation to the edges and corners).  But you might come up with a better solution.

[test2.fds.txt](https://github.com/firemodels/fds/files/3550882/test2.fds.txt)

![Screen Shot 2019-08-28 at 8 32 05 AM](https://user-images.githubusercontent.com/4418497/63856184-0ab99c80-c96f-11e9-91f0-8ef15223fc5d.png)

**Comment by rmcdermo** [comment]
Simply mirroring KRES to edges and corners (analogous to MU) seems to solve the problem. #7557
