### ISSUE TITLE
WARNING messages should be logged to file

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#7570]
There are occasions where FDS issues warning messages to screen. One example is:
`WARNING: DEVC outflow is not within any mesh.`
(in version 6.7.1, at least, now that this has been downgraded from a fatal error).

I believe that all warnings should also be logged to an output file, but I think this is currently not done. (Are there any settings for verbosity? I can't find them in the User Guide.) The '.out' file is the obvious destination. Logging to file is beneficial because the messages on screen can be difficult to find, or lost altogether. It is also good to have proof when there were no warnings.

Another enhancement request: I would also prefer to be warned at the end of a run if any warning messages have been issued during the run: so the message "FDS completed successfully" should become "FDS completed successfully with warnings". (This would be a very frustrating message if the warnings were no longer visible.)

By the way, other users might want to be warned that the workaround of using `tee` needs extra care:
`mpiexec -n 32 fds run1.fds | tee run1__FAIL.log`
produces an empty file. Presumably the messages (both routine and warnings) that appear on screen are not directed to stdout. The following works for me on Linux/bash (see https://stackoverflow.com/questions/363223):
`mpiexec -n 32 fds run1.fds |& tee run1.log`

**Comment by rmcdermo** [comment]
Do you not see the warnings in the .err file?

**Comment by drjfloyd** [comment]
You can redirect the screen dump to a file using > or >& depending on your OS.  See the User's Guide Chapter 3 Running FDS

**Comment by obscureed** [comment]
@rmcdermo and @drjfloyd -- thanks for your responses.
You are both correct in spotting that I did not follow the instructions to redirect the output to run1.err -- because it is useful/essential for me to see the output as the program runs. So effectively, I have rediscovered this idea, but using `|& tee` instead of `>&`, and naming it `.log` instead of `.err`.

I guess my point is that it would be better for FDS to automatically produce a copy of the screen dump, with a name to match all the other output files, rather than obliging the user to redirect and keep track of names. This would make the command to launch FDS cleaner and less variable by OS. (There is also the request of mentioning if there were warning messages at the end of the run.) I admit these are only small improvements, but they apply to every FDS run.

**Comment by rmcdermo** [comment]
@mcgratta Please see if these warnings can be easily incorporated.  Thanks.

**Comment by mcgratta** [comment]
There is a long history of Fortran output syntax, back to punch card days. Fortran reserves logical unit 0 for "standard error", which is what FDS either dumps to the screen or redirects to the `.err` file. LU 5 is "standard in" which FDS assigns to the input file, and LU 6 is "standard out" which FDS assigns to the `.out` file. It would be nice if there were some way to write "standard error" to both the screen and a file simultaneously, but I don't know a way to do this on all three OS we support without just adding a second `WRITE` statement for each write to standard error. If there is a clean and proper way to do this, let me know. Otherwise, I'd rather not break something that seems to be working reasonably well.

**Comment by firemist** [comment]
For my uses, I am fine with the way things log into the various files. Even with that being the case, I think a slight, helpful extension of the code may better flag a potential issue. It would have two steps, although I'm not attempting to minimize the potential work.

1. When a warning is encountered, set a flag that a warning exists.
2. At the end of the run, however that comes about, write a line to the output file saying something like, "Run completed with warnings." That would provide notice to the user that they should definitely go and carefully review their output logging files. I admit that this should be done in any event, but having wrapup information that indicates a potential problem would be helpful. Another logical place to write this to the output file may be at the wrapup of initialization. Then, it would be seen earlier in the .out file.

Having flags in the output file is helpful to "single source" that potential problems exist.

As for alternative approaches, I usually have a few windows open watching the output and error files. Instead of doing this with a tee, I usually do it with a tail -f. Since I'm running nohup to ensure my job doesn't go away with an accidental session or connection closure, I find this is an easier way to watch the text file outputs for my jobs. I also have a number of awk scripts that dump pertinent information from output files, typically the csv's, that allow a quick status overview.

**Comment by rmcdermo** [comment]
I'm not trying to be a smart *** here, but would it not work to just grep WARNING in the .err file?

**Comment by firemist** [comment]
As I attempted to represent at the end of my comment, I am very comfortable with unix/linux tools as I've been using them for more than 30 years.

My comment was aimed at something different and related to documentation. There's a beneficial value to having important information in a single file. That's all I was suggesting because sometimes when you receive materials, not everyone redirects output (STDOUT/STDERR) as recommended, but the .out file is always written. Therefore, you would automatically know that something happened along the way that, as a reviewer, you should know about. Similarly, as a reviewer, it takes longer to develop the familiarity with the model as the original developer of that model (I'm using developer in this case related to the modeler, not your work in mathematical modeling and coding).

As always, I expect the FDS development team to decide whether something has enough value to implement. I was just trying to give some additional thoughts for consideration.

**Comment by rmcdermo** [comment]
I appreciate that.  I was certainly not trying to insult your linux expertise, which I'm sure is way beyond mine.  I just wanted to be sure we were not overlooking an obvious and simple work around.  I looked at all the WARNINGs in the code and what we are proposing, as you stated, is not as trivial as it sounds.  The warnings are sort of hacked in here and there.  Doing this right would probably mean some time to overhaul and standardize how the warning are presented.

**Comment by mcgratta** [comment]
I've decided not to take action on this. Over the years we have tweaked the messages and input/output syntax, and usually we create more problems than we solve.
