### ISSUE TITLE
DEVC could report percentage area found; features not found should generate warnings

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#7571]
When a DEVC monitor is defined as a rectangle, but not all this rectangle is found within the model, then this should be reported as a warning. Similar warnings should apply to VENTs and all other features that are outside the mesh.

We currently have a warning:
`WARNING: DEVC outflow is not within any mesh.`
(which used to be a fatal error). There are other times when a `DEVC` is only partially found -- and sometimes this is not the user's intention (either by user error, or user/code mismatch as in  https://github.com/firemodels/fds/issues/7565). So it would be helpful to have a warning message such as:
`WARNING: The percentage of DEVC outflow within the model is 70.0%.`
If that is what the user expected, then the warning message can be ignored. For me, warning messages like that would have saved me considerable time and confusion in the past.

If it would be difficult to calculate an accurate percentage, an approximate one, or even just a warning of "only partially within the model", would still be useful.

Similar warnings would be really useful for all other features that can be specified outside the mesh, usually (in my case) indicating a user error: `&VENT` and `&SLCF` are examples. Some of these are currently ignored silently. (I would probably prefer a missing `&VENT` to be a fatal error, but warnings would be next best.) For a ```&VENT [...] SURF_ID='OPEN' \```, the warning message would presumably need to refer to a line number in the input file, but actually that's more convenient to me than a DEVC name.

The only feature that I commonly put partially outside the mesh on purpose is &OBST. Even then, I would prefer to see warning messages (maybe with a verbosity control).

**Comment by mcgratta** [comment]
Parameters within the `OBST` and `VENT` namelist groups are read and processed by their respective MPI processes. This means that a given process is unaware of the full extent of a given object. To make each process aware requires MPI message exchanges at the very start of the simulation which is complicated because the data structures are not all set up in the early stage because all geometric inputs must be read in before exchanges can be done safety. So this is a chicken and egg problem. I recently spent about a month coding up the ability to have devices span multiple meshes, and the logic for this is fairly complicated. I don't want to add to this for something that is not absolutely essential.
