### ISSUE TITLE
DEVC output is dumped at DT not at MIN(DT, DT_DEVC)

### ISSUE THREAD

**Issue by khalidmoinuddin** [firemodels/fds#7632]
DEVC output is dumped at DT not at MIN(DT, DT_DEVC)
[Resolution-Simple.txt](https://github.com/firemodels/fds/files/3667373/Resolution-Simple.txt)

**Comment by drjfloyd** [comment]
You can't write output at intervals smaller than the timestep.

**Comment by rmcdermo** [comment]
This was my fault, as I had not had enough coffee yet and told Khalid it should be min instead of max.

**Comment by khalidmoinuddin** [comment]
Hi Randy,

But we did get dumping at MIN (DT, DT_DEVC) for the attached case.

Kind regards

Khalid

**Comment by drjfloyd** [comment]
FDS cannot write output at frequencies smaller than the current timestep size.  The DT you set on MISC just sets the initial timestep. After that the timestep varies as needed to maintain stability per the Tech Guide. When executing FDS keeps track of the last time (T_L) it wrote to the devc file and will write output whenever T_CURRENT-T_L >=DT_DEVC.  If your DT_DEVC is smaller than the current timestep, FDS can ONLY write an output at the end of the timestep. FDS does not take a fractional step to get you output at the DT_DEVC you specify.

**Comment by rmcdermo** [comment]
@khalidmoinuddin I played with your case today and it seems to be working as expected.  Attached is what I would call a simple case.

[test.fds.txt](https://github.com/firemodels/fds/files/3672810/test.fds.txt)

I think your confusion may be coming because the output Time column when you set DT_DEVC=10, say, is not exactly at 10, 20, 30, etc.  FDS outputs the value as Jason mentioned above.  This may look more confusing if your DT, DT_INIT, and DT_DEVC are all close to the same value.

Anyway, again, for what you want to do, I would just set DT_DEVC=1E-6, and then you will get every time step output to the _devc file.

**Comment by khalidmoinuddin** [comment]
Thanks, Randy. In this test case first time step is 0.69642235 sec (essentially DT). When I don’t specify DT in the TIME line and set DT_DEVC=1E-6, the data are dumped at 0.69642235 sec interval. Subsequently the tiemestep is reduced to ~0.04 sec. So to get every time step, it will be better to set DT=0.04.
