### ISSUE TITLE
Heat transfer

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#7853]
Enclosed follows a case where I am testing heat transfer from a hot environment to the air inside a ventilation duct (based on "insulated_steel_column.fds").  With an environment temperature of 1000 oC , the mean temperature at the end of the duct is 369 oC with FDS 671 and 729 oC with FDS 673. 
Hand calculations indicate that the temperature is too high with FDS 673. What changes has been done to latest version ? 

[isc.txt](https://github.com/firemodels/fds/files/3934247/isc.txt)
[Result 671 vs 673.pdf](https://github.com/firemodels/fds/files/3934250/Result.671.vs.673.pdf)

**Comment by rmcdermo** [comment]
We will take a look.

**Comment by rmcdermo** [comment]
It's hard to know what exactly you are seeing.  The changes made for 6.7.3 are discussed here:

https://github.com/firemodels/fds/wiki/FDS-Release-Notes

Probably the change in CHECK_VN=T makes the difference in what you are seeing.

But I think you have problems with your setup and if this is how this input file has always been, then I would not trust the old results either.  Given that you set TMPA=1000, you never get the correct surface temperature (at least I never saw 10 C in the boundary file).

Also, you are better off just using BACKING='VOID' with TMP_BACK=1000.  You also need to set CHECK_HT=T if you want to resolve heat transfer through the walls in time.  Try this input file.  It will be slow because of CHECK_HT=T, but that shows you how inaccurate your other cases were.

[isc2.fds.txt](https://github.com/firemodels/fds/files/3942157/isc2.fds.txt)

**Comment by mcgratta** [comment]
I'm going to close this issue. It would be much better to have an experimental result or empirical correlation to compare the simulation to. It is very difficult to figure out why the code produces different results with different versions. Far better to compare to a known and trusted result.
