### ISSUE TITLE
Add Smokeview variables to .bashrc in Linux 

### ISSUE THREAD

**Issue by emanuelegissi** [firemodels/fds#7869]
The following wiki page describes the installation procedure on a Linux system:
[Installing-and-Running-FDS-on-a-Linux-Cluster](https://github.com/firemodels/fds/wiki/Installing-and-Running-FDS-on-a-Linux-Cluster)

It indicates adding the `source $HOME/FDS/FDS6/bin/FDS6VARS.sh` to the `.bashrc` file to automatically set up FDS environment variables.

I suggest adding the `source $HOME/FDS/FDS6/bin/SMV6VARS.sh` line, too, so that Smokeview environment variables are taken into account as well.

If you think that Smokeview is never going to be used on a Linux Cluster (the subject of the cited wiki page), I could contribute a short new wiki page describing the same process for a Linux Workstation, where Smokeview is likely to be needed.

Thank you!

**Comment by gforney** [comment]
saluti emanuele!  I updated the wiki, added references to SMV6 as you suggested.  actually, the reason for splitting the variables into FDS6 and SMV6 scripts was so that one could use smokeview and compile on a linux system at the same time (environment needed to run fds is not always compatible with the environment used to compile)
glenn

**Comment by emanuelegissi** [comment]
Great, thank you Glenn!
