### ISSUE TITLE
Consistent solutions on 1 and 2 meshes

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7935]
This one is a Susan special.  Trying to get identical solutions on 1 and 2 mesh simple case.  Attached are the input files and her description of the problem.  I changed the alignment of the meshes to avoid splitting the vent.  Still see a difference with GLMAT solver, which I think should be identical.

[DifferencesInRHS.pdf](https://github.com/firemodels/fds/files/4109995/DifferencesInRHS.pdf)
[p1.txt](https://github.com/firemodels/fds/files/4109994/p1.txt)
[p2.txt](https://github.com/firemodels/fds/files/4109996/p2.txt)

**Comment by mcgratta** [comment]
I fixed the non-zero FVY problem, at least for now. As for differences, did you sync up the color bar ranges? My comparisons of p1 and p2 are visually very similar when using a consistent color bar. I haven't looked at the numbers yet.

**Comment by rmcdermo** [comment]
No.  In theory, SMV is in research mode by default and uses the global min and max.  So if the colorbar is different, that is an indication that something about the data begin sent is different.

I did look at numbers and they are slightly different, but at this short time interval the difference was way out in the high decimal places.

**Comment by SusanKilian** [comment]
I simplified the input files again (inflow vent is now the complete XMIN, see attachment), but I really think it’s important to use the former subdivision (subdividing the vent) to figure out my troubles. Otherwise it doesn’t get obvious for me. 

Please have a special look at the values in TMP(1:,.,5) for the 1- and 2-mesh cases.
While they still are the same before WALL_BC is called in line 639 of main.f90, they differ afterwards (293.150 versus 293.135):

1-Mesh-case, TMP(0:3,.,5):    293.150  293.150  293.150  293.150  
2-Mesh-case, TMP(0:3,.,5):    293.150  293.135  293.135  293.135  

If I am right, this difference occurs for the first time after the call of 

TMP(II,JJ,KK) = PBAR_P(KK,ONE_D%PRESSURE_ZONE)/(RSUM0*RHOP(II,JJ,KK))

in line 571 of wall.f90 for  IW=81,  IOR=-3, ONE_D%IIG=1, ONE_D%JJG=1, ONE_D%KKG=4.

Now, in line 525 of divg.f90, these different values of TMP  are responsible for different values of KDTDZ(1:,.,4) 

1-Mesh-case, KDTDZ(0:3,.,4):   0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00  
2-Mesh-case, KDTDZ(0:3,.,4):   0.000000E+00 -0.390244E-02 -0.390244E-02 -0.390244E-02 

This in turn is causing different values for DDDT(1:,.,4)

1-Mesh-case, DDDT(0:3,.,4):  0.609280E+07 -0.809499E+00  0.000000E+00  0.000000E+00  
2-Mesh-case, DDDT(0:3,.,4):  0.609280E+07 -0.809609E+00 -0.109609E-03 -0.109609E-03 

finally causing different values for PRHS(1:,.,4)

1-Mesh-case, PRHS(1:4,.,4):  -0.199792E+05 -0.449293E-14 -0.449293E-14 -0.449293E-14 
2-Mesh-case, PRHS(1:4,.,4):  -0.199792E+05  0.109609E-03   0.109609E-03   0.109609E-03  

The resulting differences in the solution H(.,.,.) are not that big, but still in the range of  8.7e-06 , e.g. for H(1,.,4):

1-Mesh-case, H(1,.,4):   0.149843348521E+04
2-Mesh-case, H(1,.,4):   0.149843347651E+04 

These results are based on the GLMAT-solver. 

It would be great if you had a look at this. Many thanks, Susan

[t2.txt](https://github.com/firemodels/fds/files/4118125/t2.txt)
[t1.txt](https://github.com/firemodels/fds/files/4118126/t1.txt)

**Comment by mcgratta** [comment]
I have some time to look into this, and I ran the t1 and t2 input files in the previous post. I see no differences, and I see no change in temperature. The temperature appears to be exactly 20 C in both cases.

**Comment by SusanKilian** [comment]
Hi, Kevin, please have a look at the attached document. Thanks, Susan
[Consistency_Issue7935.pdf](https://github.com/firemodels/fds/files/4349341/Consistency_Issue7935.pdf)

**Comment by mcgratta** [comment]
The non-zero terms in `DDDT` are due to a correction term that is added. In short, after we update the velocity components, we replace the normal component of velocity at the mesh interface with the average of the values from the two abutting meshes. Because we make a change to the velocity component, we have to "correct" the divergence time derivative. It is explained in the Technical Reference Guide 4.3.4 Iterative Procedure for Updating Velocity.

**Comment by SusanKilian** [comment]
Kevin, thanks. I am basically familiar with this procedure, but obviously underestimated its effects or misinterpreted a few correlations. I will close the issue.
