### ISSUE TITLE
Could &HOLE have an option to be oversized automatically?

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#7967]
If a &HOLE is intended to allow flow through an &OBST, and the user writes coordinates that match, like this:
`&OBST XB= 4.0,4.2, 0.0,2.0, 0.0,2.0, SURF_ID='WALL-SOLID' /`
`&HOLE XB= 4.0,4.2, 0.5,1.5, 0.5,1.5 /`
then it typically works unless they adjoin a mesh-to-mesh boundary, and then it doesn't (https://github.com/firemodels/fds/issues/7962). So the advice in the User Guide is to define a slightly oversized &HOLE:
`&OBST XB= 4.0,4.2, 0.0,2.0, 0.0,2.0, SURF_ID='WALL-SOLID' /`
`&HOLE XB= 3.99,4.21, 0.5,1.5, 0.5,1.5 /`
or more safely:
`&OBST XB= 4.0,4.2, 0.0,2.0, 0.0,2.0, SURF_ID='WALL-SOLID' /`
`&HOLE XB= 3.99,4.21, 0.49,1.51, 0.49,1.51 /`

This is an extra step of arithmetic for the user. It makes it harder to see at a glance that the &HOLE is sized correctly.

Could the &HOLE line have an optional parameter called something like DELTA, that automatically expands the &HOLE in all directions? So then the following would be safe:
`&OBST XB= 4.0,4.2, 0.0,2.0, 0.0,2.0, SURF_ID='WALL-SOLID' /`
`&HOLE XB= 4.0,4.2, 0.5,1.5, 0.5,1.5, DELTA=0.01 /`
This would be equivalent to following the advice in the User Guide, but easier to write and debug in the *.fds file.

Another option would be a global setting HOLE_EXPANSION_DELTA in the &MISC line. I would use this all the time.

Thanks for considering this.
Ed

**Comment by mcgratta** [comment]
I would prefer to leave these sorts of usability issues to the GUIs. There are only three of us who code FDS on a daily basis, and these kinds of enhancements could easily consume 100% of our time. Even this relatively simple change would consume days or weeks of our time. That's not the actual initial coding, which would take a few minutes, but rather the bug reports that would inevitably follow. When we release new versions of FDS, we spend weeks fixing bugs that we have created in the previous version by trying to "improve" something. We are now much more careful about fixing things that may not actually be broken. 

I appreciate your interest and suggestions, but I know from past experience that these sorts of things sometimes cause more trouble rather than less. If there is a groundswell of support for something, we may consider it, but at the moment, we haven't had complaints about this functionality.
