### ISSUE TITLE
run error ffortl: severe (157)

### ISSUE THREAD

**Issue by zsmihi** [firemodels/fds#8246]
Hello, 
I'm running a model that stopped with this error message (i attached)
I restarted the model several times already,  but stopped again at the same place.
I don't know what's wrong.
I've run such a model, just the fire was higher (higher shelf, but x, y position is the same), it ran all the way.
Can someone tell me what's wrong?
It would be important and urgent!
[T4_0306_j.log](https://github.com/firemodels/fds/files/4474467/T4_0306_j.log)

**Comment by rmcdermo** [comment]
This question is best asked in the discussion forum.  The issue tracker is for demonstrated bugs, which is not (yet).  Please post your question to the forum.  However, we will need more than just the error file.  It looks to me like a write or read access violation, which might have something to do with your system.  Try to think what happens at that point in the simulation, are you dumping a RESTART?  Are you maybe out of memory?

**Comment by mcgratta** [comment]
Also, run the case with the latest version of FDS.

**Comment by zsmihi** [comment]
I've already run it in the latest fds, it stopped with that too

**Comment by mcgratta** [comment]
I will run the case that you posted to the Discussion Forum. It will take several days to get to the point where it failed for you. I'll watch the memory usage.

**Comment by zsmihi** [comment]
Thank you very much.

**Comment by mcgratta** [comment]
Your case is still running. It has reached about 430 s, which is a long way from when your job failed. This will take a week to run. If my job fails, it only confirms that there is a problem, but it probably will not indicate what the problem is. I agree that memory does not seem to be the issue (yet). However, whenever you have sprinklers, and there is a large amount of flow, there is always the possibility of a numerical instability or an array bound being exceeded. One thing you can try is to create a similar case to the one you are running and lower the RTI or increase the fire size, or both. Try to quickly open many sprinklers, and then if your case fails, we may be able to diagnose the problem. As it is now, it is difficult to know what could be wrong. Look for something dramatic in your simulation that occurs near the time of failure. That might be a clue.

**Comment by mcgratta** [comment]
The case is still running. It is currently at 842 s of simulation time. How long did you run this case before it failed?

**Comment by zsmihi** [comment]
This stopped at 1457,59 seconds, but I have already run several versions where I changed the mesh allocation at 1560 sec. 
I also ran one where I wiped out the sprinklers: if there’s no sprinkler in it at all, it runs smoothly.
[error.txt](https://github.com/firemodels/fds/files/4504200/error.txt)

**Comment by mcgratta** [comment]
Sorry, I should have asked how long in real time does your case run before failing?

**Comment by zsmihi** [comment]
14 days

**Comment by mcgratta** [comment]
The job failed at 1538 s with a segmentation fault. The only obvious problem with the simulation is that the limit of particles had been reached in one of the meshes (1 million). However, that in itself is not something that should cause a seg fault. My only advice is to create another case in which the fire ramps up quickly and the sprinklers activate quickly. Then we might be able to diagnose a problem without having to wait weeks for an outcome.

**Comment by zsmihi** [comment]
Thank you. 
The particle settings are set to: Droplets dissappear at Floor. it's worth going in the direction of setting the maximum particle size above 1 million, or it can't be done. 
What is the setting to reduce the particle number? e.g. at the sprinkler a size distribution?

**Comment by mcgratta** [comment]
You can increase the `MAXIMUM_PARTICLES` on the `DUMP` line beyond 1 million, but I do not think that this will solve the problem. I suggest that you create a test case in which the sprinkler(s) activate quickly, and if it fails, we can try different things to fix. It's really impossible to wait 14 days to test any given remedy.
