### ISSUE TITLE
Restarting a simulation with activation controls

### ISSUE THREAD

**Issue by FernandoV2020** [firemodels/fds#8267]
Hello,

I have a problem when I restart an analysis. If I have a control that activates a fan and an extraction at 5s and I stop the analysis at 20s, when I restart the analysis the fan and the extraction restart stopped.

If I run the file without  stopping, the file runs ok.
I have attached a simple model.

[Fan.txt](https://github.com/firemodels/fds/files/4496584/Fan.txt)

**Comment by mcgratta** [comment]
Jason -- it appears that `DU%FAN_ON_TIME` gets set back to `T_BEGIN` when the code restarts, yet `FAN_OPERATING` remains T, I think.

**Comment by FernandoV2020** [comment]
I re-run the same simple model without the wall that contains the extraction vent and the block that simulate the fan and works fine.
I have stopped the simulation and I have restarted and works. 
So, should I look for another way to simulate the activation if I need to stop and restart?
[Fan_2.txt](https://github.com/firemodels/fds/files/4497441/Fan_2.txt)

**Comment by mcgratta** [comment]
Do what you have to do. We'll try to find a work-around.

**Comment by FernandoV2020** [comment]
I have to activate an exhaust vent over an existing wall.

If I activate the vent with a new OBS over an existing one the restarting process doesnt work.
-existing wall--->&OBST ID='Wall', XB=-56.75,-56.25,-72.5,-59.5,0.0,3.0, SURF_ID='INERT'/ 
-activation of the vent in a zone of the wall--->&OBST ID='EA-01', XB=-56.75,-56.25,-62.5,-60.5,2.0,3.0, SURF_ID6='INERT','Extrac','INERT','INERT','INERT','INERT', DEVC_ID='TIMER->OUT'/ 

If I supress the existing wall the simulation stop and re-run with the vent working but I dont have the wall from the beginning.
Is there another way to activate a vent in a wall?

**Comment by drjfloyd** [comment]
The issue here is the DEVC_ID on the two OBST for the duct and wall vent.  

For an HVAC system, the physical duct is always there. What changes is the fan being on or off.  HVAC isn't setup to deal with VENTs that change state. An HVAC NODE with a VENT_ID always needs to find an active vent. Just have the DEVC_ID on the FAN.

For the wall vent you have overlapping obstacles:
&OBST ID='EA-01', XB=-56.75,-56.25,-62.5,-60.5,2.0,3.0, SURF_ID6='INERT','Extrac','INERT','INERT','INERT','INERT', DEVC_ID='TIMER->OUT'/
&OBST ID='Wall', XB=-56.75,-56.25,-72.5,-59.5,0.0,3.0, SURF_ID='INERT'/

Here is appears that how we handle obstruction priority is conflicting with the DEVC_ID.  Make the 'EA-01' a VENT and this works as well.

I'll add a note to the User's Guide that HVAC VENTs should not have DEVC_ID or CTRL_ID.

**Comment by FernandoV2020** [comment]
Here is the file with your indications.
Works perfectly and I can restart without problems.
Thank you very much for your time and support.
[Fan_3.txt](https://github.com/firemodels/fds/files/4499908/Fan_3.txt)
