### ISSUE TITLE
Segmentation fault occurring upon restart

### ISSUE THREAD

**Issue by desimoa1** [firemodels/fds#8395]
Hello, 

I am attempting to use the restart feature on a linux cluster and it always fails due to a segmentation fault. I tried to simplify my input file as much as possible and it would still fail upon restart. Then, tried using some of the example fds input files provided ("circular_burner.fds" and "adiabatic_surface_temperature.fds") and those both failed by segmentation fault upon restart as well. 

For additional context, the fds file runs fine initially, then I create a CHID.stop file to pause the simulation, add the line "&MISC RESTART = .TRUE." to the input file, and then attempt to run the simulation again. I am working with FDS 6.7.4. 

Please let me know if more information is needed. Any help would be appreciated.

**Comment by rmcdermo** [comment]
We will take a look.

**Comment by rmcdermo** [comment]
I tested `adiabatic_surface_temperature.fds` with 6.7.4 and it worked fine.  Is it possible you wrote out the `.restart` file with an earlier version of the code?  RESTART is fragile and not likely to be compatible with different code versions.  For example, the latest source and 6.7.4 are not even compatible because new variables are being written out.

In my opinion, this really needs an overhaul.  The original RESTART (which we still use) is just a core dump.  With all the effort being put in to Doxygen, a similar organization could make the restart files more organized and reasonably backward compatible.

**Comment by desimoa1** [comment]
Thanks for looking into this. I have been running the initial simulation using fds 6.7.4 and restarting using fds 6.7.4 as well, so I don't think that is the issue. I attached the terminal output below if that is at all helpful. 

Another note on this issue is that, when I use the restart feature on my windows desktop for this input file it restarts successfully (using fds 6.7.4). Also, when I use an older version of FDS available on my institution's linux cluster (fds 6.6.0) to run and then restart the simulation, it restarts successfully as well. I only have this issue using the latest version of fds on my institution's linux cluster. 

[terminalOutput.txt](https://github.com/firemodels/fds/files/4717400/terminalOutput.txt)

**Comment by mcgratta** [comment]
I'm going to test the case with Gnu Fortran. That appears to be the only difference between your case and ours.

**Comment by mcgratta** [comment]
I ran `Radiation/adiabatic_surface_temperature.fds` using Gnu Fortran 9.1.1.  I stopped the job about halfway through, then attempted to restart. I got a seg fault with the non-debug compile, but the case ran with the debug compile. I tracked down the seg fault to geom.f90
```
   ! Populate PHOPVN in regular faces of CCIMPREGION:
   ! IAXIS faces:
   X1AXIS = IAXIS
   DO IFACE=1,MESHES(NM)%IBM_NREGFACE_Z(X1AXIS)   <---- The loop dimension is 3

      I  = MESHES(NM)%IBM_REGFACE_IAXIS_Z(IFACE)%IJK(IAXIS)
      J  = MESHES(NM)%IBM_REGFACE_IAXIS_Z(IFACE)%IJK(JAXIS)
      K  = MESHES(NM)%IBM_REGFACE_IAXIS_Z(IFACE)%IJK(KAXIS)

      MESHES(NM)%IBM_REGFACE_IAXIS_Z(IFACE)%RHOPVN(-1:0) = RHO(I+FCELL-1:I+FCELL  ,J,K)

   ENDDO
```
This routine is called from main.f90 just after `READ_RESTART`. I cannot debug it from here. 

Marcos, can you take a look.

**Comment by marcosvanella** [comment]
Kevin, thanks. I'll look.

**Comment by marcosvanella** [comment]
Try the case now. Even though there are no geometries on this case the cut-cell init routine was not masked by the CC_IBM flag. The issue on optimized mode comes because the the numbers of regular faces IBM_NREGFACE_Z in the cut-cell region used for scalar transport were not being set to zero in mesh.f90, so they would get random initialization. In debug mode they would get set to zero by the compiler.

**Comment by mcgratta** [comment]
The bug seems to have been fixed. This was actually not a restart reading problem. Rather, just after reading in the data from the previous run, FDS called a new routine with an uninitialized variable. 

desimoa1 -- if you are compiling the source code yourself, try your case now and confirm if you can restart the case.

**Comment by desimoa1** [comment]
Great, thank you both for your help with this issue. I really appreciate it.

**Comment by mcgratta** [comment]
Don't thank us until you confirm that it actually works.

**Comment by desimoa1** [comment]
The restart feature is working for me now. Thanks again!

**Comment by mcgratta** [comment]
Thanks for confirming. Since we so rarely compile with Gnu or run with Open MPI, let us know if you find other issues. Also, if you use the makefile in the fds repository, are the compiler options still OK? It seems to me that there are some that have no effect or are deprecated. You can submit a pull request if you find compiler options that are inappropriate. It's hard to keep up with all the compilers on the various OS.
