### ISSUE TITLE
Error with multiple extruded GEOM

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8454]
The attached file has 4 GEOM that use EXTRUDE.  If I comment out all but one GEOM input, each GEOM will individually work. If I try and used more than one I get the error message 

ERROR: For extruded Polygon GEOM X : Node (  Y) not in the plane of the polygon. Check VERTS. (CHID: geotest3)

where X is the ID of the second active GEOM line and Y is either node 1 or node 4 depending on which set of GEOM I uncomment.

[geomtest3.fds.txt](https://github.com/firemodels/fds/files/4794979/geomtest3.fds.txt)

**Comment by marcosvanella** [comment]
Thank you Jason. I'll check.

**Comment by marcosvanella** [comment]
Jason, I'm working on this. The issue was an interesting one. The routine that extrudes the polygons is within the contains of the READ_GEOM subroutine. I was setting the centroid xyz and average normal for the plane of the polygon to zero in the contained routine declaration (EXTRUDE_POLY), these vars later used in recursive sums. It so happens that the second time you call the routine within the contains, these vars are not reinitialized from the declaration statement. Setting them to zero explicitly within the routine is necessary.
The next problem I've come across has to do with a special situation for object intersection the case poses. I'm working on that now, and will let you know.

**Comment by marcosvanella** [comment]
This case should run now. We have two issues:
1. Flow asymmetry in corners due to masked interpolation scheme, good case to work on this old issue. Lets keep it open.
2. @gforney I noted that running the following case, I don't see the BNDF plot in SMV if I try to load the boundary slice first. But if I load on top the regular temperature slice the boundary slice appears. For some reason the BNDF is not showing when trying to load alone. (SMV6.7.14-448-g2d264b51b-master in the Mac).

[geomtest3.fds.2.txt](https://github.com/firemodels/fds/files/4814319/geomtest3.fds.2.txt)

**Comment by drjfloyd** [comment]
I tried the CC_VELOBC_FLAG2=T for this case. Results are now symmetric; however, rather than the expected

**Comment by drjfloyd** [comment]
I know you are still working on it, but I tried the CC_VELOBC_FLAG2=T for this case and put a slice of CELL U part way down the tube from the contraction. It is now symmetric but shows a much different flow pattern. Rather than looking like a typical turbulent profile, it is a cross pattern.

![geotest3_0998](https://user-images.githubusercontent.com/12799217/88580582-d389ba80-d019-11ea-80b3-36da37aeff68.png)

[geomtest3.fds.txt](https://github.com/firemodels/fds/files/4983961/geomtest3.fds.txt)

**Comment by marcosvanella** [comment]
Hi Jason, is the angle on the convergent walls 45 deg? Seems the flow is accelerating faster towards the corners.
I'll get back to this once we get the particles going. The plan is to switch the way we get the stress components to a cartesian face basis (no normal direction).

**Comment by drjfloyd** [comment]
It is ~20 deg.  If I do the equivalent case using OBST I get the attached image. I'll get someone to do this with one of our commercial codes.

![geotest3_obst_0418](https://user-images.githubusercontent.com/12799217/88592980-dcd05280-d02c-11ea-80ab-28a0779d0bda.png)

[geomtest3_obst.fds.txt](https://github.com/firemodels/fds/files/4984479/geomtest3_obst.fds.txt)

**Comment by marcosvanella** [comment]
That would be interesting. My take is we are underpredicting values of stress and vorticity imposed in the contraction walls, and we end up having a less mixed flow than expected at the test section entrance. Thanks for posting the obst version, I will check edge OME_E and TAU_E among the two versions.

**Comment by drjfloyd** [comment]
Had someone run this using LES in Fluent. Nominally the same mesh size. 

![035d0908-852e-41fe-9554-6e02b523c914](https://user-images.githubusercontent.com/12799217/88931425-cef81880-d24a-11ea-8ac1-3f93b3c55de2.jpg)

**Comment by marcosvanella** [comment]
Interesting, so the flow does accelerate towards the corners in the convergent.

**Comment by marcosvanella** [comment]
Hi Jason, did this Fluent calculation end up being laminar or this pic is a time average? Thanks.

**Comment by drjfloyd** [comment]
The plot is a time average as was the FDS images I posted earlier.

**Comment by drjfloyd** [comment]
Something has changed with the smokview representation of this case. This case is four polygons that are extruded to form a conical inlet. Geom seems to be working fine and the velocity slice shows no velocity in the solid portion, but the Smokeview view is different. It is only showing the original polygons, and not the extrusion like is seen at the top of this thread.

![geotest3_0043](https://user-images.githubusercontent.com/12799217/231239709-3d910f58-de70-4c30-8247-711df2ef81f5.png)

**Comment by drjfloyd** [comment]
Thanks. That works. Was there a reason for that change?

When I go to Show/Hide->Geometry->Immersed I don't see any changes to the menu before/after typing q.  I had looked at this menu before posting thinking maybe it was a show/hide opion but there doesn't seem to be a menu option to toggle this. For OBST there is an actual/requested option.

**Comment by marcosvanella** [comment]
Good question, @gforney can we make the toggle option for OBSTS also work for geometries. 

The reason for the change was to keep things in sync with OBSTs, such that we plot CFACEs when we plot WALL cells (what FDS sees) vs the input objects. There were some cases with OBST GEOM intersection where things were coming mixed up.

**Comment by drjfloyd** [comment]
latest smokeview now has menu option for this.
