### ISSUE TITLE
Surface with Volume Flow and Heat Flux generates very high temperatures in 6.7.4

### ISSUE THREAD

**Issue by brianhardeman** [firemodels/fds#8517]
A user's model was generating unrealistically high temperatures using FDS 6.7.4. compared to 6.7.3.  We have generated a simple test model that demonstrates the same issue from the complex user model.  The temperatures above surface 'FluxSupply' in this test model are an order of magnitude higher than results with 6.7.3.  The velocity above FluxSupply is also much higher than calculated with 6.7.3.

&HEAD CHID='FluxTest'/
&TIME T_END=10.0/
&DUMP DT_RESTART=300.0, DT_SL3D=0.25/

&MESH ID='MESH', IJK=40,20,11, XB=0.0,10.0,0.0,5.0,0.0,2.75/

&SURF ID='HeatFlux',
      RGB=255,102,0,
      TMP_FRONT=50.0,
      CONVECTIVE_HEAT_FLUX=10.0/
&SURF ID='Supply',
      RGB=26,204,26,
      TMP_FRONT=50.0,
      VOLUME_FLOW=-1.0/
&SURF ID='FluxSupply',
      TMP_FRONT=50.0,
      CONVECTIVE_HEAT_FLUX=10.0,
      VOLUME_FLOW=-1.0/

&OBST ID='Obstruction', XB=1.0,2.0,2.0,3.0,0.0,0.25, SURF_IDS='HeatFlux','INERT','INERT'/ 
&OBST ID='Obstruction', XB=4.0,5.0,2.0,3.0,0.0,0.25, SURF_IDS='Supply','INERT','INERT'/ 
&OBST ID='Obstruction', XB=7.0,8.0,2.0,3.0,0.0,0.25, SURF_IDS='FluxSupply','INERT','INERT'/ 

&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=10.0,10.0,0.0,5.0,0.0,2.75/ 
&VENT ID='Mesh Vent: MESH [XMIN]', SURF_ID='OPEN', XB=0.0,0.0,0.0,5.0,0.0,2.75/ 
&VENT ID='Mesh Vent: MESH [YMAX]', SURF_ID='OPEN', XB=0.0,10.0,5.0,5.0,0.0,2.75/ 
&VENT ID='Mesh Vent: MESH [YMIN]', SURF_ID='OPEN', XB=0.0,10.0,0.0,0.0,0.0,2.75/ 
&VENT ID='Mesh Vent: MESH [ZMAX]', SURF_ID='OPEN', XB=0.0,10.0,0.0,5.0,2.75,2.75/ 

&SLCF QUANTITY='TEMPERATURE', PBY=2.5/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=2.5/

&TAIL /

**Comment by drjfloyd** [comment]
Specifying TMP_FRONT and a FLUX is overprescribing the input as to get the FLUX the temperature must be calculated.  I suspect that this is something like the older version of FDS that the TMP_FRONT wound up being applied and changes in input processing means the CONVECTIVE_FLUX is now being applied.   If you add BNDF files for WALL TEMPERATURE and CONVECTIVE HEAT FLUX you will see that the two end OBST have h~14 W/m/K which means you need a ~700 C temperature difference between the gas and the wall to get 10 kW/m2 convective flux.  The OBST exhausting air has near ambient temperature above and its WALL TEMPERATURE is 790 C which seems reasonable.  The OBST supplying air has 200 to 1500 C temperature immediately above it  and has WALL TEMPERATURE ranging from 1000 to 2100 C which also seems to be reasonable.  The case appears to be working fine.

**Comment by brianhardeman** [comment]
We have considered making temperature and flux specifications mutually exclusive in the GUI in the past, but have left it up to the user based on section 11.2.2 of the FDS User Guide (p87 Specifying the Heat Flux at a Solid Surface), which implies there are situations where both can be set.  However, even with the TMP_FRONT removed from the FluxSupply surface, the temperature is still an order of magnitude higher than when run using 6.7.3.

**Comment by rmcdermo** [comment]
@brianhardeman I think was @drjfloyd is saying is the 6.7.3 behavior is likely equivalent to removing the heat flux.  If you do that and leave TMP_FRONT, do you set similar temperatures to 6.7.3?

**Comment by drjfloyd** [comment]
I think that guide text needs to be updated.  For NET_HEAT_FLUX or CONVECTIVE_HEAT_FLUX, fds computes the wall temperature needed to get the desired flux.  For CONVECTIVE_HEAT_FLUX the temperature is set to get the convective flux, and the radiation emission from the wall is then determined by that temperature and the emissivity. For NET_HEAT_FLUX  the wall temperature is set so that the sum of radiation and convection equals the net flux. There isn't a way to strictly control radiation and convection independently of one another.

Randy is correct. What I was saying was your symptoms sound like 6.7.3 wasn't trying to apply the heat flux.

**Comment by brianhardeman** [comment]
@rmcdermo Yes, if I set 6.7.4 to only have TMP_FRONT with the VOLUME_FLOW, the results are closer to what 6.7.3 was producing with TMP_FRONT, CONVECTIVE_HEAT_FLUX, and VOLUME_FLOW. (This is the "Supply" surface case in the given example file vs the "FluxSupply" surface.)

However, even with only CONVECTIVE_HEAT_FLUX, and VOLUME_FLOW applied, 6.7.4 gives different results than 6.7.3, which is what I'm trying to get my head around.  Was the convective flux just not getting properly applied in previous versions?

Perhaps part of the confusion is the combination of VOLUME_FLOW and a heat flux?  Is there a physical use case for that?  Maybe this user should be using HVAC to add 10 kW to their flow instead, or using a fixed temperature volume inflow to model their heated supply.

**Comment by drjfloyd** [comment]
I don't generally like to unnecessarily predetermine what type of modeling people may or may not do with FDS. There is no reason from my point of view as developer to say you can't specify a flux with a volume flow. Yes, you could do this with an HVAC duct with an AIRCOIL, but why force the user to that extra complexity if they don't care about modeling where the air is coming from. These are two different boundary conditions: flux is temperature and volume flow is velocity. What your user needs to be aware of is that the default EMISSIVITY is 0.9 so that surface will be putting in more than just the convective flux. I think we should improve on the Guide discussion and we should try to see how we might trap the error of specifying both TMP_FRONT and a flux.  That being said, FDS 6.7.4 does not appear to be doing anything incorrect other than not trapping the conflict in specifying TMP_FRONT and a flux.  If I put devices for wall temperature, heat transfer coefficient, gas temperature, and volume flow I get a convective flux of 10 kW/m2 and a volume flow of 1 m3/s.

**Comment by rmcdermo** [comment]
Perhaps the confusion is in what "convective heat flux" means.  With mass flux we are more explicit: "total mass flux" is the advective + diffusive.  But with heat flux, actually, what we call "convective" is the diffusive part only.  The total heat flux is rho * u * h_s + HTC * (T_G-T_W).  Here u is the velocity taken from VOLUME_FLOW.  If a user wants to specify 10 kW/m2 coming from a supply vent, they need to think about both components.

**Comment by brianhardeman** [comment]
@drjfloyd I agree with your viewpoint on flexibility of specification.  We will likely leave our GUI as-is, other than perhaps clarify setting temperatures and fluxes simultaneously.

@rmcdermo I have one last confusion, which probably stems from me thinking of simple convection and advection in isolation...
Why does an increasing VOLUME_FLOW on a specified heat flux vent lead to ever higher gas and surface temperatures?  I understand the FDS results from a simple convection surface without volume flow, and a simple supply surface adding energy by advection, but if you put them both on the same vent/surface, you end up with very high temperatures.  I assume FDS is calculating the input flow temperature to be high, but that is unintuitive to me.

**Comment by drjfloyd** [comment]
I added error trapping for this and edited the User's Guide to reflect how we currently deal with the inputs of CONVECTIVE_FLUX and NET_HEAT_FLUX.

**Comment by rmcdermo** [comment]
OK, I've had time to play with your case.  I agree with Jason that I think the code is working as intended, but that we need more clarification in the user guide.  And should be clear that CONVECTIVE_HEAT_FLUX only pertains to HTC*(TMP_W - TMP_G).  If a supply vent is to add 10 kW/m2 in an HVAC system, this will mostly be from advection, the RHO * U_N * C_P * (TMP_W - TMP_REF) term.

@brianhardeman The reason why the TMP_W goes up with increasing VOLUME_FLOW (increasing U_N) is that the higher the volume flow the more the gas cell wants to be at TMP_W via advection.  Thus, since the specification of CONVECTIVE_HEAT_FLUX puts you in the part of boundary routine where TMP_F must be specified to match 10 kW/m2 (a Neumann bc does not care about the absolute value at the boundary, only the gradient), TMP_F has to get high enough to balance the dissipation of the plume to the ambient conditions, and this plume is more powerful the larger the value of VOLUME_FLOW.

**Comment by brianhardeman** [comment]
@rmcdermo Your explanation matches what we assumed was going on.  The fact that 6.7.3 and earlier didn't seem to properly apply the convective flux added a bit of confusion and distraction.  We will work with this user to make sure they get the conditions they intend to model.  I think we can close out this issue.  Thanks for your input!
