### ISSUE TITLE
NIST_Deposition_Gauge cases fail with seg fault

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8552]
All cases failed with seg fault in wall.f90. I couldn't figure out the problem. Pass the case on if you're not familiar with them.
```
   CASE (DNS_MODE)
      ITMP = MIN(4999,NINT(ONE_D%TMP_F))
      DO N=1,N_TRACKED_SPECIES
         ONE_D%RHO_D_F(N) = ONE_D%RHO_F*D_Z(ITMP,N)   <------ Seg fault here
      ENDDO
```

**Comment by drjfloyd** [comment]
I made these cases. They are a pretty simple set of inputs other than the soot deposition. Radiation is off and surfaces are adiabatic or isothermal. There are no HVAC, PART, REAC, or GEOM inputs. Flow is laminar so velocities are low. Scanning the logs since these inputs were committed in January I don't see a likely culprit. We'll probably have to do a bisect on this one.

**Comment by drjfloyd** [comment]
When did it fail for you? I'm running in debug on my laptop and started time stepping.

**Comment by mcgratta** [comment]
The case 
```
NIST_SDG-10p0-100-p39a.fds
```
fails after the first time step in debug mode. I think the others all failed on the same line I pointed out above.

**Comment by drjfloyd** [comment]
I was able to run NIST_SDG-10p0-100-p39a on my laptop in debug, dv, and release mode.

Tried on blaze. The first time running with 4 processes in release mode and it died during the first timestep. I compiled in debug and ran as a single process and it started time stepping. I tried 4 processes with debug and it started. I tried release mode again with a single process and it started. I tried release mode with 4 processes and it started and is up to a few hundred time steps.  Is there a problem with one of the nodes on blaze?

**Comment by mcgratta** [comment]
I'll see if maybe this has to do with the 6 meshes on 4 processes.

**Comment by mcgratta** [comment]
PR #8343 caused the seg fault, in particular the changes to read.f90. But I cannot figure out how these changes affect this case.

**Comment by mcgratta** [comment]
Ugh. I just realized that you and I are using different versions of the compiler on blaze. I am using Intel Fortran 20 update 1 and you are using 19 update 4. I just compiled using 19u4 and the case runs for me too. I tried to find the problem when using 20u1, but the seg faults from db and dv mode are different and do not seem to have anything to do with changes to read.f90 in May. 

I am going to run the cases with 6 MPI processes instead of 4. I can't think of anything else to do to get around the bug in the code or bug in the compiler.

**Comment by marcosvanella** [comment]
I tried the gnu db, dv targets for the NIST_SDG-10p0-100-p39a.fds case on 6 mesh/4 procs and both started without issues (just some units compatibility warnings).

**Comment by mcgratta** [comment]
Thanks. I think this is a bug in Intel Fortran 20u1, but I cannot pin down exactly what. I am just going to run the cases with 6 procs instead of 4.

**Comment by marcosvanella** [comment]
I'm compiling openmpi with intel20 here. Will let you know what I find. The segfault might be due to an ITMP interger out of bounds. Do you have a case that fails with only one mesh?
________________________________
De: Kevin McGrattan <notifications@github.com>
Enviado: lunes, 6 de julio de 2020 01:58 p. m.
Para: firemodels/fds <fds@noreply.github.com>
CC: marcosvanella <marcos_vanella@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [firemodels/fds] NIST_Deposition_Gauge cases fail with seg fault (#8552)


Thanks. I think this is a bug in Intel Fortran 20u1, but I cannot pin down exactly what. I am just going to run the cases with 6 procs instead of 4.

**Comment by mcgratta** [comment]
No, the problem (if there is one) is due to running 6 meshes over 4 MPI
processes.

>

**Comment by drjfloyd** [comment]
The unit warnings are expected as the cases uses CTRL functions to do data processing in FDS rather than needing a post-processing Matlab script. It involves using an AREA INTEGRAL with a QUANTITY that isn't a per area unit and that generates a warning. 

It is dying in the first timestep. If it was just a calculation always giving an ITMP out of bounds, then that should fail on any of the compilers. The fact that different compilers and different options with the same compiler results in failures in different locations suggests a compiler bug or possibly a pointer issue. Since these are being run with one thread per process it isn't going to be an OMP directive issue.

**Comment by mcgratta** [comment]
I've switched the ownership of this issue to me. I don't think there is anything wrong with the case set up. This might be a compiler bug, which I currently have a work-around for. When a new compiler comes out, I will try again. I spent hours trying to find the problem with the compiler, but could not. The seg faults result from internal issues that are not immediate apparent. In fact, I get different errors depending on the compiling mode, db vs dv. So let's not waste time on this now.

**Comment by marcosvanella** [comment]
The case with 6mesh/4 proc works in Mac OSX with Ifort 19.1.1.216 (Intel20u1) and openmpi, debug mode. The only difference besides the OS I see is having openmpi instead of intelmpi.   
Jason, yes, I meant having a garbage number in ITMP for that version of the compiler, problem coming from somewhere else.
Work around sounds good.

**Comment by mcgratta** [comment]
I'm closing this issue. I cannot pin down exactly where the compiler is having trouble, but it appears to be a compiler bug rather than an FDS bug.
