### ISSUE TITLE
GEOM obstruction at OPEN boundary

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8554]
[ground_vegetation_drag.txt](https://github.com/firemodels/fds/files/4879491/ground_vegetation_drag.txt)
The attached case has three small wind tunnels stacked on top of each other. The one on top has its floor made up with a GEOM OBST and the middle tunnel has a conventional OBST as a floor. The wind is "pushed" into the tunnel from the left, and it is applied to the entire opening. The GEOM OBST does not prevent flow from entering at the bottom of the inlet vent. The flow should see an obstruction there. Look at vector slices and compare the top and middle tunnels.

**Comment by mcgratta** [comment]
I also notice that the ground surface in the GEOM case does not drag as much as the OBST case. Even when I apply the wind at the free opening area, the GEOM does not drag as much.

**Comment by marcosvanella** [comment]
I'll take a look.

**Comment by rmcdermo** [comment]
Low friction coefficient is known.  We are working on it.

**Comment by marcosvanella** [comment]
Yes, also does the ground thickness define a force in the first velocity point off the wall that is not considered through TAU_E?

**Comment by rmcdermo** [comment]
@marcosvanella Not sure what you mean.  I doubt there is anything special about this case beyond what we are dealing with for channels.

**Comment by marcosvanella** [comment]
Just curious. I think I understand now, the change in the velocity field seen in the middle channel next to the floor is tied to 'Blade of Grass' PARTs, their drag is added to the Fx for first velocity points off the wall. We don't see that with the GEOM now, because that information is not baked into the forcing. That should be used in the change planned for the stress method.

Kevin, do you remember what we do when we have a face on an OPEN boundary that is also a face of an OBST (i.e. set to solid or null)?
Thanks.
________________________________
De: Randy McDermott <notifications@github.com>
Enviado: lunes, 6 de julio de 2020 03:33 p. m.
Para: firemodels/fds <fds@noreply.github.com>
CC: marcosvanella <marcos_vanella@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [firemodels/fds] GEOM obstruction at OPEN boundary (#8554)


@marcosvanella<https://github.com/marcosvanella> Not sure what you mean. I doubt there is anything special about this case beyond what we are dealing with for channels.

**Comment by mcgratta** [comment]
The special thing here is that we have particles in the first grid cell dragging on the flow, like vegetation. But even if you remove them, the drag by the GEOM ground is less than the OBST ground.

When an OBST abuts on OPEN boundary, the WALL cell on the exterior of the domain is turned to NULL_BOUNDARY. If the OBST is removed, FDS "remembers" what the original SURF_INDEX was.

**Comment by mcgratta** [comment]
I just committed a case to `Verification/WUI` that is easier to understand and more relevant (recompile FDS too). It is called `particle_surface_density.fds`. In this case 1 kg/m2 of vegetation mass is added to the first gas phase grid cell using the SURF parameter `PARTICLE_SURFACE_DENSITY`. There are two tunnels, each 100 m long, 10 wide, 10 high. The only difference between the tunnels is the use of a GEOM or an OBST as the ground. One thing I noticed right off. Look at the .out file and there are 1000 particles in the OBST case and 1100 in the GEOM case owing to looping over either WALL or CFACE cells (`INSERT_VENT_PARTICLES` in part.f90). I see that in the GEOM case, the last row of cells gets one extra particle. Not sure how. Check the logic in the CFACE particle insert.

**Comment by marcosvanella** [comment]
All right, I'll move to that case. I dealt with the OPEN and BLOW conditions when these wall cells are inside the solid (or boundary) for geometries switching them to null. Something I still note is a vertical velocity on that cell next to the inlet and geometry surface. It is an order of magnitude higher that the OBST case and seems tied to mass balance in that cell, I think eventually to the wall model in its faces. See pic (top is GEOM). If I set the condition to be slip in the geometry the normal velocity drops to OBST values.
This tells me we have to try defining stresses in the Cartesian mesh instead of forcing the velocities off the wall for scalar transport using a wall model. We've been discussing this with Randy. We compute velocities from NS in the Cartesian grid and flux match them to cut-faces for scalar transport. Things will be better aligned with the OBST way. Note we would only be doing IBM as no flux for solid faces inside the geometry.
![Screen Shot 2020-07-06 at 2 42 00 PM](https://user-images.githubusercontent.com/7450069/86627851-f125b000-bf96-11ea-8fff-95632ae01b56.png)

**Comment by marcosvanella** [comment]
About the double counting, the cells in the diagonal get two particles. Looks like we are inserting one part per CFACE, and we have two CFACEs per cell there due to the triangulation.

**Comment by mcgratta** [comment]
That's fine as long as we appropriately weight the particles based on their
relative area.

>

**Comment by marcosvanella** [comment]
All right, as discussed, the LP%PWT factor is tied to the CFACE area, so we should be fine. I'll work on the stress method for geoms next and get back to this once we've made progress.

**Comment by drjfloyd** [comment]
Updated the case for the current inputs in Verification/WUI. Pressure and velocity for the top (GEOM) and middle (OBST) cases are quite close. I think this can be closed.

[ground_vegetation_drag.txt](https://github.com/firemodels/fds/files/11223181/ground_vegetation_drag.txt)

![image](https://user-images.githubusercontent.com/12799217/231790235-cb096e16-3715-4f6d-bada-05280ce45bba.png)

**Comment by marcosvanella** [comment]
Ok, thank you Jason.
