### ISSUE TITLE
Numerical Instability Errors with Cinema Fire - FDS Code

### ISSUE THREAD

**Issue by jameschampion20** [firemodels/fds#8593]
Hi All,

I am having some issues with modelling a cinema fire coupled with a HVAC system in FDS. I have attached the code below and any help / suggestions with this would be great. To give a bit more background, the simulation runtime is set at 600 seconds and it seems to run fine for the first ~490 seconds, before crashing and giving the numerical error. Looking at some of the pressure slice files (also attached), the pressure changes dramatically around the extract ductwork between around 480 and 490 seconds (temperature also changes in this manner), and I believe that the extract ductwork is the problematic area. 

Please let me know your thoughts when you get a chance and if you require any further information. 

Many thanks for your help,

James

![Pressureat480seconds](https://user-images.githubusercontent.com/68464009/87850404-e00a6680-c8e7-11ea-8046-12d111c13308.PNG)
![Pressureat489seconds](https://user-images.githubusercontent.com/68464009/87850414-fdd7cb80-c8e7-11ea-8822-0c4c65e20bcd.PNG)

[622924_Auditorium_03_TEST03Jul-20.txt](https://github.com/firemodels/fds/files/4941426/622924_Auditorium_03_TEST03Jul-20.txt)

**Comment by rmcdermo** [comment]
James,
What this run with the latest release?
Thanks

**Comment by jameschampion20** [comment]
Hello,

Apologies, I should have said. Yes, this was indeed run on the latest release version 6.7.4. 

Many thanks,
James

**Comment by drjfloyd** [comment]
You need to define a pressure zone.

You don't actually need to have the OPEN area on the far side of the door.
Just specify the exterior node for the leakage as AMBIENT.

Don't model the ducts as hollow tubes Make them solid OBST and put HVAC
VENTs where the ducts supply of exhaust air from the domain. Model the
ducts themselves using the HVAC model. You need to have ~10 or more cells
across the width of a duct to be able to get the correct pressure drop at
inlets, outlets, and other duct fittings. The HVAC model is there so you
don't have to have that kind of resolution in your simulation.

If you have any HVAC duct where FDS Is predicting the flow rather than you
specifying the flow, you need to provide realistic values for the losses.
Your leak duct has only a roughness and no entrance or exit losses.

In your case you don't really need to use HVAC for the exhaust. You have 4
vents going into a plenum space that then get exhausted to ambient. They
are going to have roughly the same flow. You could save your self some
computational time by not modeling the plenum space and just putting four
VENTs with a SURF that has 1/4 of the VOLUME_FLOW of your fan.

**Comment by jameschampion20** [comment]
Hello,

Many thanks for your detailed response. Can you please let me know what a pressure zone is and where in the domain would be the best place to put this? How does one go about defining such a zone? 

Also, one of the aims of this study is to ascertain the temperature of the extract ductwork. What would be the best way of doing this please?

Many thanks,
James

**Comment by mcgratta** [comment]
Just search the User's Guide for the words pressure zone.

**Comment by drjfloyd** [comment]
Monitor temperature at the exhaust points.

**Comment by drjfloyd** [comment]
With no further comments, closing the issue.
