### ISSUE TITLE
Possible bug in droplet energy transfer routine

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8741]
Take a look at part.f90. There is a `TIME_ITERATION_LOOP` inside of which the timestep is DT_SUBSTEP. But there are also expressions evaluated with DT. Should these use DT_SUBSTEP as well?

**Comment by drjfloyd** [comment]
Most of those are all running sums to aggregate the subtimesteps.  If we want to get M_DOT_PPP over the timestep DT and we have two substeps of equal length  DT_1 amd DT_2 then we want:
M_DOT_PPP = TOTAL_MASS_EVAPORATED/DT 

If we used the subtimesteps in aggregation then we would have: 
M_DOT_PPP = M_VAP_1 / DT_1 + M_VAP_2/DT_2 

but DT_1 = DT_2 = DT/2 so:
2 (M_VAP1 + M_VAP2)/DT  /=  (M_VAP1 + M__VAP2)/DT 

we need the aggregation to use the full timestep.

I see one bug and that is the term LP%M_DOT which was added. It does not aggregate over subtimesteps and should look like the other terms.

This block I think might need some work. 

               ! Compute surface cooling

               IF (LP%WALL_INDEX>0 .OR. LP%CFACE_INDEX>0) THEN
                  R_DROP = LP%ONE_D%X(1)
                  A_DROP = WGT*PI*R_DROP**2
                  ONE_D%LP_TEMP(LPC%ARRAY_INDEX) = ONE_D%LP_TEMP(LPC%ARRAY_INDEX) + A_DROP*0.5_EB*(TMP_DROP+TMP_DROP_NEW)
                  ONE_D%LP_CPUA(LPC%ARRAY_INDEX) = ONE_D%LP_CPUA(LPC%ARRAY_INDEX) + &
                                                   (1._EB-LPC%RUNNING_AVERAGE_FACTOR_WALL)*WGT*Q_CON_WALL/(ONE_D%AREA*DT)
                  ONE_D%Q_RAD_IN = (ONE_D%AREA*DT*ONE_D%Q_RAD_IN - WGT*DT*Q_DOT_RAD) / (ONE_D%AREA*DT)
               ENDIF

I think these need to be moved after the end of the time loop as we are updating in each subtimestep rather than just once at the end, but we need to sum the Q_CON and Q_RAD over subtimesteps in side the loop.

**Comment by mcgratta** [comment]
OK. This block is what I was focusing on. I'm trying to think of a way to wet burning particles with water droplets using something like LP_CPUA as the transfer between the droplet routine and the 1-D conduction routine. Except LP_CPUA will have to be a function of the gas phase cell, not a wall or cface cell.

**Comment by drjfloyd** [comment]
I'll get that end bit cleaned up and fix LP%M_DOT.

**Comment by drjfloyd** [comment]
I think I have fixed it.

**Comment by mcgratta** [comment]
Follow Q_CON_WALL. It is calculated for a sub-timestep using DT_SUBSTEP
```
Q_CON_WALL = DT_SUBSTEP*A_DROP*H_WALL*0.5_EB*(TMP_WALL+TMP_WALL_NEW-TMP_DROP-TMP_DROP_NEW)
```
but then divided out by the whole time step.

```
Q_DOT(7,NM) = Q_DOT(7,NM) - (Q_CON_GAS + Q_CON_WALL + Q_RAD)*WGT/DT
```

**Comment by drjfloyd** [comment]
Q_CON_WALL is J.  It is the amount of heat transferred per sub timestep is based on DT_SUBSTEP
Q_DOT is in W.  Here we need the sum of the heat in J over all sub  timesteps divided by DT

**Comment by mcgratta** [comment]
Right -- but I don't see where Q_CON_WALL is being summed over the sub-time steps.

**Comment by drjfloyd** [comment]
This line is in the sub-time step loop. Every sub-time step it adds Q_CON_WALL for the sub-time step to Q_DOT:

Q_DOT(7,NM) = Q_DOT(7,NM) - (Q_CON_GAS + Q_CON_WALL + Q_RAD)*WGT/DT

**Comment by mcgratta** [comment]
Yup, now I see. Thanks.

>
