### ISSUE TITLE
Pressure Peaks

### ISSUE THREAD

**Issue by dimitrisFDS** [firemodels/fds#8750]
Hi all I am running a tunnel scenario using jet fans and I just pulled out the .q data and 
import them into tecplot. I am studying the pressure drop of the air. My question is why I do observe such pressure peaks of the jet fan plane. ty in regards Dimitris Fitsalos.
This is a simple version of my case the attached image is what my issue is about.

[pres_test1.zip](https://github.com/firemodels/fds/files/5243937/pres_test1.zip)
![Capture](https://user-images.githubusercontent.com/71487035/93567196-f770d900-f996-11ea-83c9-6b23909679bd.JPG)
The attached image is what my issue is about.

**Comment by rmcdermo** [comment]
I don't understand the problem.  What do you expect the pressure to be at the inlet and exit of a jet fan?  You ware showing units of Pascals on the y-axis.

**Comment by dimitrisFDS** [comment]
Excuse me my knowledge is incomplete.Just working on FDS a year and a half. I want to compare the pressure drop at the fans plane (green line) with the theoritical pressure drop at the same plane. I am wondering if there is something wrong with my code
because the divergence is too high(peaks)
a)Should I use pressure tollerance or limit the pressure itteration etc. ?
 b)Should I reconstruct my mesh?
Any advice would be usefull.PS the pressure Unit is Pa.

**Comment by rmcdermo** [comment]
I do not think the theoretical pressure drop across a jet fan is on a few Pa, as you are showing.  This is not a demonstrated bug in the code, and I think the discussion is better suited for the forum where those with good knowledge of jet fans can chime in.

**Comment by drjfloyd** [comment]
Look at the HVAC equation.  At steady state you are taking air that is going to be close to 0 m/s a short distance away from the inlet and accelerating it to ~21 m/s at the jet fan outlet.  You have at a minimum and entrance and an exit loss so the fan pressure is:

dP_fan = 1/2 K rho u^2 where K ~ 2.

This is ~500 Pa added by the fan.  It does not seem to be unreasonable that in the FDS domain that you see a couple dozen Pa across the OBST for then.

**Comment by dvswenson** [comment]
Dimitris,

I can add some graphs to clarify your results and some general comments about jet fans. 

Starting with the model you sent, I simplified it to one fan and one mesh. I ran the model for 10 s and made a plot of velocity. I also added two line devices that output the steady state velocity and pressure through the centerline of the fan. The images are attached. As @drjfloyd answered, the velocity and pressure on the centerline seem reasonable.

However, a more significant problem is that the velocity of the jet does not decay as predicted by the analytic solutions. This is because the resolution of the mesh is not sufficient to capture the downstream turbulence and transfer of momentum to the ambient air. This is a challenging problem. To do a good job you need about 20 cells across each edge of the outlet vent. I have an old post that needs to be updated that can supply some more background (https://support.thunderheadeng.com/tutorials/pyrosim/modeling-jet-fans/), but I do not have an ideal answer.

I played with splitting the jet and forcing a radial velocity at the outlets of the split jet. Other suggestions are to use a velocity patch downstream of the fan that imposes the flow that the analytic solution. This would avoid the requirement for a fine mesh.

Anyway, be cautious and make sure that you validate your jet fan model before applying to the tunnel.

All the best,
Dan Swenson
Thunderhead Engineering

![single model](https://user-images.githubusercontent.com/13338306/93647943-33279500-f9cf-11ea-89c8-27bae5336f6e.jpg)
![velocity at 10s](https://user-images.githubusercontent.com/13338306/93648000-5a7e6200-f9cf-11ea-95e3-f948f4f36d7d.png)
![steady state results](https://user-images.githubusercontent.com/13338306/93648010-5f431600-f9cf-11ea-9a35-a12ebf5e335b.png)
![comparison of FDS with analytic solutions](https://user-images.githubusercontent.com/13338306/93648331-248dad80-f9d0-11ea-9e99-7401914cceb7.png)
[single.fds.txt](https://github.com/firemodels/fds/files/5248424/single.fds.txt)
[jet fan FDS vs analytic.xlsx](https://github.com/firemodels/fds/files/5248443/jet.fan.FDS.vs.analytic.xlsx)
[jet fans split jets.zip](https://github.com/firemodels/fds/files/5248449/jet.fans.split.jets.zip)

**Comment by dimitrisFDS** [comment]
Thank you all for the answers were really helpful. I will run some tests and see if the results are compatible.Some previous work about jet fans has been made here. All my results are Timed-averaged except for the turbulence comparison which with no statistical analysis.
![mesh_res](https://user-images.githubusercontent.com/71487035/93663698-67a05d00-fa72-11ea-92ad-007d9a3d677c.JPG)
![Capture](https://user-images.githubusercontent.com/71487035/93663699-68d18a00-fa72-11ea-8aaa-a66630ed3728.JPG)
![trurb_comp](https://user-images.githubusercontent.com/71487035/93663700-68d18a00-fa72-11ea-9cf6-c3b146f19c34.JPG)
Talking about the mesh the strategy followed about the jet fan modelling was an idea from the thunderhead engineering study part 2.
What do you mean about that (To do a good job you need **about 20 cells across each edge of the outlet vent**.)
I am going to run your aproach @drjfloyd and I will contact with you again if necessary.

Have a nice day
Dimitris

**Comment by rmcdermo** [comment]
I'm closing this issue.  Please reopen if you clearly demonstrate a bug.

**Comment by Monika-Samy** [comment]
how to model  jet fan by velocity patch
