### ISSUE TITLE
Add RESTART verification case

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8827]
Jason,
Please select or create a case that you think touches as many code features as possible.  Then we will hand off to Glenn and me to set up in firebot.  Thanks

**Comment by gforney** [comment]
update your fds and bot repos.  I added a restart file test in firebot .  Two test cases are in the fds/Verification/Restart directory .  restart_test1a.fds runs to 5 s, stops and outputs a restart file.  restart_test1b.fds reads in the restart file and continues to 10 s.  restart_test1a.fds is run from FDS_Cases.sh .  restart_test1b.fds is in FDS_RESTART_Cases.sh (in the same directory) and is run after all test cases in FDS_Cases.sh have finished.  You'll want to changes these cases, they are just place holders now (plume5c from the smv repo).  The only checking firebot is doing is whatever is done for all other test cases.

One restart check I could do is to to add a smokeview script to generate an image during the time that the 2nd case runs.  If the 2nd case failed to run because of problems with the restart file smokeview would throw an error because it would not be able to generate an image. Let me know if you would like me to do this or if you have a better way of doing this kind of check

**Comment by rmcdermo** [comment]
Believe this is up and running.
