### ISSUE TITLE
AMPUA not picking up liquid water that hits a wall and falls to floor

### ISSUE THREAD

**Issue by mattbilson76** [firemodels/fds#8881]
I have a domain where a single nozzle is placed in the domain and I measure how much water reaches the floor of the domain.  There is some mass imbalance if the nozzle is in the center, and it gets worse if the nozzle moves toward a side wall.  When I extend the domain width so no drops hit the walls, then the imbalance becomes very small.  Details and results below as well as four input files.

FDS release: FDS6.7.5-0-g71f025606-release

-	Single nozzle operating at 79.2 L/min
-	Nozzle operating for one minute, simulation runs to 120 s to allow all water to reach floor, etc.
-	Droplet age is 60 s (enough time to make sure all droplets have reached a boundary)
-	Should see a total mass of 79.2 L/min * 1 min * 1 m3/1000 L * 997 kg/m3 = 79.0 kg
-	Water reaching floor of model recorded via AMPUA
-	There appears to be some water drops “lost” when the nozzle / spray hits the wall at the side and the drops fall to the floor (even though the drops visually fall down the wall and hit reach the floor, they do not appear to be counted in the AMPUA)…see cases below
-	In case TC3 virtually no water hit the side walls since the domain was made much wider so that the spray could not reach walls, and in this case the imbalance is small

Case TC1:
-	8.8 m wide, nozzle on centerline, no ventilation (open boundaries)
-	Accumulated mass of water = 76.7 kg
-	Imbalance = 2.3 kg
Case TC2:
-	8.8 m wide, nozzle offset from centerline, no ventilation (open boundaries)
-	Accumulated mass of water = 62.3 kg
-	Imbalance = 16.7 kg
Case TC3:
-	17.6 m wide, nozzle offset from centerline (same as TC2), no ventilation (open boundaries)
-	Accumulated mass of water = 78.5 kg
-	Imbalance = 0.5 kg
Case TC4:
-	8.8 m wide, nozzle offset from centerline (same as TC2), no ventilation (open boundaries), particle CFL on
-	Ran nozzle for 20 s (model runs slower with particle CFL on)
-	Accumulated mass of water = 21.3 kg
-	Imbalance = (26.3 – 21.3) = 5.0 kg

Input files for CHID TC1, TC2, TC3, TC4 are attached.

[TC3.txt](https://github.com/firemodels/fds/files/5436288/TC3.txt)
[TC4.txt](https://github.com/firemodels/fds/files/5436289/TC4.txt)
[TC1.txt](https://github.com/firemodels/fds/files/5436290/TC1.txt)
[TC2.txt](https://github.com/firemodels/fds/files/5436291/TC2.txt)

**Comment by drjfloyd** [comment]
This is the expected behavior of AMPUA.  AMPUA only counts a droplet that transitions from a gas cell to solid surface and not a droplet that moves from one solid cell to another solid cell. From the User's Guide:

Likewise, ’AMPUA’ is the Accumulated Mass Per Unit Area. Both of these are given in units of kg/m2. Think of these outputs as measures of the instantaneous mass density per unit area, and the accumulated total, respectively. These quantities are not identical measures. The quantity ’AMPUA’ is analogous to a “bucket test,” where the droplets are collected in buckets and the total mass determined at the end of a given time period. In this case each grid cell on the ﬂoor is considered its own bucket. **Each droplet is counted only once when it reaches the ﬂoor**. MPUA counts a droplet whenever it is on any solid surface, including the walls. If the droplet moves from one solid wall cell to another, it will be counted again.

What you could to have the droplets on the wall be counted when they reach the floor would be to have a one cell gap in the wall at the floor as shown below where S is a solid cell and G is a gas cell. A droplet moving down the wall would briefly re-enter the gas and then be counted again when it hits the floor.

S S G G G
S S G G G
S S G G G
S G G G G
S S S S S

Also keep in mind it takes droplets time to reach the floor once they leave the sprinkler. Some of your mass imbalance may be due to drops that haven't had time to reach the floor.  You may want to turn your sprinkler off before the end of the simulation and give drops time to reach  the floor to make sure all the water is being counted.

**Comment by mattbilson76** [comment]
Understood.  Thanks.  Tried using AMPUA on side walls and that worked ok for recording the balance.
