### ISSUE TITLE
Remove particles or droplets that get swept into a sucking vent

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8900]
Currently, if a droplet is sucked into a VENT that has a positive VEL, it sticks to the "solid" wall. We should make it so that if there is an inward velocity (of some non-negligible value) we should remove it.

**Comment by drjfloyd** [comment]
We should think about this. I don't think removing everything is the correct approach. For example if you have an HVAC system covered by a louver only relatively small drops will be capable of following the sudden change in streamline to avoid the solid portion of the louver and move into the open portion.

I was actually thinking about this some today while staring at the black line on the bottom of a pool. We could also use a series of related particle behaviors for solid particles on solid surfaces (do they stick, slide across the surface, or lift off again). This plus being able to sneak by a mesh opening or into a sub grid leak opening will be something we will need to predict how brands pile up around / enter homes.

**Comment by mcgratta** [comment]
Perhaps a SURF parameter that indicates some critical sucking velocity for which droplets and particles disappear, with the default being very large, which would mimic what we have now.

**Comment by drjfloyd** [comment]
A quick scholar search shows there is some literature out there on inertial separation of particles at louvers. Maybe someone already has a simple rule of thumb we can use.

**Comment by mcgratta** [comment]
I'm testing a simple parameter called `EXTRACTION_VELOCITY` on the `SURF` line that sets a lower bound for the normal velocity above which droplets and particles get sucked in. I'm also simplifying the logic by which we extract droplets from a `POROUS_FLOOR`, basically doing all these various extractions in one place, where we also sum up masses of particles that are sucked out. Any suggestion for the parameter name besides `EXTRACTION_VELOCITY`. I fear that will be confused with an exhaust velocity.

**Comment by drjfloyd** [comment]
PART_EXTRACTION_VELOCITY?

**Comment by mcgratta** [comment]
Yes, that's better. Hopefully won't confuse.

>

**Comment by mcgratta** [comment]
I added a feature by which particles can get drawn into extracting vents.

**Comment by mattbilson76** [comment]
I have downloaded the latest distro, checking out this feature to see what the results look like.

**Comment by mattbilson76** [comment]
I have been testing this out, and have a few results to report (I have uploaded the input files as well as my post processing files - don't expect anyone to look at these too closely, though in case you want to take a deeper dive into how I get results, these might be helpful).

**All cases:**
2.5 m/s upstream velocity, 40 m3/s exhaust per port positioned at tunnel ceiling (2 by 2 m by 2 m) – cases are modeled with and without the exhaust duct directly modeled (EVS-11-27 and EVS-11-28 use VENTs to represent the exhaust ports, and EVS-11-29 and EVS-11-30 resolve the duct above and the ports).

79.2 L/min/nozzle by 2 nozzles, droplet 0.65 mm, angles = 30.0 and 75.7, velocity = 15.2 m/s

Comments on model outcomes in italics

**EVS-11-27 – test a small extract velocity**
Extract velocity 0.01 m/s
85.4% water on road, 9.1% on sidewalls, 1.2% out of downstream portal, 4.9% through exhausts, 0.9% imbalance (more water)
_Results seem reasonable_

**EVS-11-28 – test a large extract velocity**
Extract velocity 50 m/s (unstable), 25 m/s (unstable), 9 m/s (ok, current case)
33.4% water on road, 3.6% on sidewalls, 0.2% out of downstream portal, 66.6% through exhausts, 3.7% imbalance (more water)
_Model goes unstable if the extract velocity is large (probably if it is greater than the vent velocity)_
_Seems odd that more water goes through the exhausts in this case rather than the case with a small velocity_

**EVS-11-29 – model the duct above, droplet velocity = 0 when on a solid**
43.7% water on road, 5.3% on sidewalls, 0.3% out of downstream portal, 51.2% through exhausts, 0.5% imbalance (more water)
_Results look reasonable, though they are different to the cases EVS-11-28 and EVS-11-27 where an extract velocity is used, and the duct is not modeled_

**EVS-11-30 – model the duct above, droplet velocity = default when on a solid**
43.8% water on road, 5.2% on sidewalls, 0.3% out of downstream portal, 55.6% through exhausts, 4.9% imbalance (more water)
_Similar results to EVS-11-29 in terms of water on the road, though now the imbalance has increased quite a lot – what could this be due to (only change was the droplet velocity on solid surfaces being non zero) – is it possible droplets move randomly on the duct slab and then fall through the exhaust ports later, getting counted twice?_


[EVS-11-28.txt](https://github.com/firemodels/fds/files/5561365/EVS-11-28.txt)
[EVS-11-29.txt](https://github.com/firemodels/fds/files/5561366/EVS-11-29.txt)
[EVS-11-30.txt](https://github.com/firemodels/fds/files/5561367/EVS-11-30.txt)
[EVS-11-27.txt](https://github.com/firemodels/fds/files/5561368/EVS-11-27.txt)

[Results.zip](https://github.com/firemodels/fds/files/5561375/Results.zip)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
Take a look at this simpler case below. The total mass of water on the floor, walls, and exhaust vents should be 66.6667 kg. I compute a value that is about 0.4% higher, probably due to a slight error in the ramping of the sprinkler mass flows. I set HUMIDITY=100 to eliminate water evaporation, and no water escapes through the portals. Let's start with this case and add complexity. I could not understand your input files exactly because of all the extraneous output.
```
&HEAD CHID='EVS-11-28-KM',TITLE='EVS-11-28' /

&MESH IJK=150,44,22,XB=-15.0,15.0,-4.4,4.4,0.0,4.4 /

&VENT XB=-1.0,1.0, 1.2, 3.2,4.4,4.4, SURF_ID='EXVENT' /
&VENT XB=-1.0,1.0,-1.2,-3.2,4.4,4.4, SURF_ID='EXVENT' /
&SURF ID='EXVENT', VOLUME_FLOW=40.0, RGB=100,20,20, PARTICLE_EXTRACTION_VELOCITY=0.01 /

&VENT XB=-15.0,-15.0,-4.4,4.4,0.0,4.4, SURF_ID='OPEN' /
&VENT XB= 15.0, 15.0,-4.4,4.4,0.0,4.4, SURF_ID='OPEN' /

&TIME T_END=50.0 /

&MISC CONSTANT_SPECIFIC_HEAT_RATIO=T, HUMIDITY=100 /

&SPEC ID='WATER VAPOR' /

&PART ID = 'WATERDROP',
      SPEC_ID='WATER VAPOR'
      DIAMETER = 650.0,
      COLOR = 'SKY BLUE',
      QUANTITIES = 'PARTICLE DIAMETER' /

&PROP ID = 'DV1',
      PART_ID = 'WATERDROP',
      FLOW_RATE = 80.,
      FLOW_RAMP = 'flow'
      PARTICLE_VELOCITY = 15.2,
      SPRAY_ANGLE = 30.0,75.7,
      PARTICLES_PER_SECOND = 5000,
      OFFSET = 0.03 /

&RAMP ID='flow', T= 0., F=1. /
&RAMP ID='flow', T=20., F=1. /
&RAMP ID='flow', T=30., F=0. /

&DEVC ID='DV-1A', XYZ=0.0, 2.2,4.3, QUANTITY='TIME', SETPOINT=0.0, PROP_ID='DV1' /
&DEVC ID='DV-1B', XYZ=0.0,-2.2,4.3, QUANTITY='TIME', SETPOINT=0.0, PROP_ID='DV1' /

&SLCF PBY=0.0,QUANTITY='VELOCITY', VECTOR=T /

&BNDF QUANTITY='AMPUA',PART_ID='WATERDROP' /

&DEVC XB=-15.0,15.0,-4.4,4.4,0.0,0.0,ID='ROADWAY-WATER',QUANTITY='AMPUA',PART_ID='WATERDROP',SPATIAL_STATISTIC='SURFACE INTEGRAL' /
&DEVC XB=-15.0,15.0,-4.4,-4.4,0.0,4.4,ID='SIDEW-WATER1',QUANTITY='AMPUA',PART_ID='WATERDROP',SPATIAL_STATISTIC='SURFACE INTEGRAL' /
&DEVC XB=-15.0,15.0,4.4,4.4,0.0,4.4,ID='SIDEW-WATER2',QUANTITY='AMPUA',PART_ID='WATERDROP',SPATIAL_STATISTIC='SURFACE INTEGRAL' /
&DEVC XB=-1.0,1.0,1.2,3.2,4.4,4.4,ID='EXW-WATER1',QUANTITY='AMPUA',PART_ID='WATERDROP',SPATIAL_STATISTIC='SURFACE INTEGRAL' /
&DEVC XB=-1.0,1.0,-1.2,-3.2,4.4,4.4,ID='EXW-WATER2',QUANTITY='AMPUA',PART_ID='WATERDROP',SPATIAL_STATISTIC='SURFACE INTEGRAL' /

&TAIL /
```

**Comment by mattbilson76** [comment]
Ok, thank you.  Running this now, will gradually add things.

**Comment by mattbilson76** [comment]
Ran three cases...imbalance gets worse with increasing extract velocity. I tweaked a few inputs around the nozzle timing, but nothing that should impact things.

**EVS-11-31 – test a small extract velocity**
0 m/s upstream velocity, 40 m3/s exhaust per port positioned at tunnel ceiling (2 by 2 m by 2 m)
Extract velocity 0.01 m/s
80 L/min/nozzle by 2 nozzles, droplet 0.65 mm, angles = 30.0 and 75.7, velocity = 15.2 m/s
21.6 kg on road, 3.4 kg on sidewalls, 28.5 kg through exhausts, 0.49% imbalance
_Results seem reasonable_

**EVS-11-32 – test a large extract velocity**
0 m/s upstream velocity, 40 m3/s exhaust per port positioned at tunnel ceiling (2 by 2 m by 2 m)
Extract velocity 9 m/s
80 L/min/nozzle by 2 nozzles, droplet 0.65 mm, angles = 30.0 and 75.7, velocity = 15.2 m/s
21.6 kg on road, 3.4 kg on sidewalls, 33.7 kg through exhausts, 9.7% imbalance
_Large imbalance for this case_ 

**EVS-11-33 – test a large extract velocity**
0 m/s upstream velocity, 40 m3/s exhaust per port positioned at tunnel ceiling (2 by 2 m by 2 m)
Extract velocity 12 m/s
80 L/min/nozzle by 2 nozzles, droplet 0.65 mm, angles = 30.0 and 75.7, velocity = 15.2 m/s
21.6 kg on road, 3.2 kg on sidewalls, 25,601 kg through exhausts, >>100% imbalance
_Large imbalance for this case_ 


[EVS-11-32.txt](https://github.com/firemodels/fds/files/5563643/EVS-11-32.txt)
[EVS-11-33.txt](https://github.com/firemodels/fds/files/5563644/EVS-11-33.txt)
[EVS-11-31.txt](https://github.com/firemodels/fds/files/5563645/EVS-11-31.txt)

**Comment by mcgratta** [comment]
The problem is the setting of `PARTICLE_EXTRACTION_VELOCITY`. In case 33, you set this to 12 m/s. The vent is drawing nominally air at 10 m/s. The logic of the extraction is that if the normal vent extraction velocity is greater than what you set for PEV, then the droplet is sucked in and is removed from the calculation. In your case, with 12 m/s, the droplet is being counted as hitting the vent, but then it is freed to drop, whereby it is allowed to be counted again if it hits another surface. So droplets are being counted again and again -- they are drawn to the vent, counted, freed, drop, drawn up again, counted, and so on. I suggest you set PEV to a low value so that all droplets that hit the vent get sucked in.

**Comment by mattbilson76** [comment]
Ok, that makes sense.  I was not trying to find anything specific with that case other than just pushing things to see where the limits were - I found that. Is it worth adding some text to the User Guide, something like:

" When specifying the particular extraction velocity, if droplets are to be removed, a value less than the normal vent extraction velocity should be set. To make sure that droplets are extracted the particle extraction velocity should be a very small number. If the velocity is too large, droplets will not be removed, but instead will drop away from the vent or move away on the solid surface (depending on the vent orientation)."

**Comment by mcgratta** [comment]
I added some text.

**Comment by mattbilson76** [comment]
Here's an update, tested cases with and without the duct above modeled, worked quite well:

EVS-11-31 - no duct modeled (use particle extraction with very low velocity)
21.6 kg on road, 3.4 kg on sidewalls, 28.5 kg through exhausts, 0.5% imbalance
(extract velocity 0.01 m/s, similar result at 1 m/s)

EVS-11-34 - duct above modeled
24.0 kg on road, 3.9 kg on sidewalls, 27.1 kg through exhausts, 3.2% imbalance

EVS-11-35 - duct above modeled, openings for the exhaust close up when sprinkler stops (stop droplets escaping and dropping back to road)
24.6 kg on road, 3.9 kg on sidewalls, 25.3 kg through exhausts, 1.1% imbalance

EVS-11-36 - duct above modeled, droplets have zero speed on surfaces
24.0 kg on road, 3.9 kg on sidewalls, 25.7 kg through exhausts, 0.7% imbalance

- Amount of water flow through exhausts with duct resolved = 52%
- Amount of water flow through exhausts using particle extraction (no duct modeled) = 47%

- When modeling the duct above, droplets can fall back through the exhaust ports, thus leading to greater imbalance

- The result can be influenced by whether particles fall back from the vent region or not; influenced by input parameters to a degree; need to take care droplets are not counted twice (since once a droplet goes "up" it is not really useful any more with respect to it's original purpose when injected at the nozzle), or, assume the mass flow is balanced and work out the water that goes into the exhaust based on: net water discharge from nozzle - sum of water landing on solid surfaces (except for vents)
