### ISSUE TITLE
Different particle evaporation behavior

### ISSUE THREAD

**Issue by mattbilson76** [firemodels/fds#8987]
When running a model with stationary particles in FDS 6.7.4 (FDS6.7.4-0-gbfaa110f1-release) and allowing them to evaporate (particle initial temperature 99 C, domain temperature 120 C), the change in enthalpy is 70.97 kJ, change in total mass in domain is 0.0379 kg, RH change is 1.84%.  Running the same case in FDS 6.7.5 (FDS6.7.5-517-g6a2fb83b5-nightly) the change in enthalpy is 5.79 kJ, change in total mass in domain is 0.0120 kg, RH change is 0.27%. I also downloaded the release version of FDS 6.7.5 (FDS6.7.5-0-g71f025606-release) and results were similar to the observed results with 6.7.5 (dm=0.012 kg, dh=5.75 kJ).  I ran the cases for 20 s each, but this is showing some difference so I did not run for longer.

Another piece of relevant info: when I ran a tunnel study, validating against full-scale test date with a deluge system running, I achieved very good agreement for temperature downstream of the fire (heat release rate was an input, not resolved by heat feedback) using FDS 6.7.4.  Runs with FDS 6.7.5 tended to over predict temperature - by a lot.

Here is the simple test case I used for results above:

&HEAD CHID='EVS-YY',TITLE='EVS-YY' /

&MESH IJK=20,20,20,XB=-1.0,1.0,-1.0,1.0,0.0,2.0 /

&SURF ID='WALLS',ADIABATIC=.TRUE.,DEFAULT=.TRUE. /

&TIME T_END=20.0 /

&MISC CONSTANT_SPECIFIC_HEAT_RATIO=T, HUMIDITY=0, TMPA=120, GVEC=0.0,0.0,0.0 /

&SPEC ID='WATER VAPOR' /

&PART ID = 'WATERDROP',
      SPEC_ID='WATER VAPOR'
      DIAMETER = 350.0,      
      COLOR = 'SKY BLUE',
	  MINIMUM_DIAMETER = 20.0,
      MONODISPERSE = .TRUE.,
      STATIC = .TRUE.,
      INITIAL_TEMPERATURE = 99.0,
      QUANTITIES = 'PARTICLE DIAMETER' /

&INIT PART_ID='WATERDROP',XB=-1.0,1.0,-1.0,1.0,0.0,2.0,N_PARTICLES=500,MASS_PER_VOLUME=0.005995 /

&SLCF PBY=0.0,QUANTITY='VELOCITY' /
&SLCF PBY=0.0,QUANTITY='TEMPERATURE' /

&DEVC XB=-1.0,1.0,-1.0,1.0,0.0,2.0,ID='MASS',QUANTITY='DENSITY',SPATIAL_STATISTIC='VOLUME INTEGRAL' /
&DEVC XB=-1.0,1.0,-1.0,1.0,0.0,2.0,ID='MASS F WV',QUANTITY='MASS FRACTION',SPEC_ID='WATER VAPOR',SPATIAL_STATISTIC='MEAN' /
&DEVC XB=-1.0,1.0,-1.0,1.0,0.0,2.0,ID='ENTHALPY',QUANTITY='ENTHALPY',SPATIAL_STATISTIC='VOLUME INTEGRAL' /
&DEVC XB=-1.0,1.0,-1.0,1.0,0.0,2.0,ID='RH',QUANTITY='RELATIVE HUMIDITY',SPATIAL_STATISTIC='MEAN' /

&TAIL /

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
Shortly after the new inputs for the heat and mass transfer coefficients were added a bug in the solver for evaporation was fixed. It is this bug fix that caused the difference. I have gone through the derivation for the solver again and I don't see any errors in the derivation. I did find a typo in the source code though (double credited the droplet weighting factor in one location). Fixing that brings the results back towards where they were in 6.7.4 but not completely. Hopefully this helps your full case.

I don't think the 6.7.4 results are plausible. In your test case, all the mass evaporates in ~0.4 s.  Since the equilibrium state is all the mass has evaporated, all the energy for phase change is coming from the gas. To evaporate the mass of water in 0.4 s means you need ~300 kW/m2 of heat transfer to the drops. The maximum radiative flux at 120 C is ~1 kW/m2 so we can consider all the heat transfer to be convective. 300 kW/m2 take a convective heat transfer coefficient over 2500 W/m2. Since the drops are static and gravity is turned off the Nusselt number for the drops will be 2 which means the heat transfer coefficient is around 200 W/m2. 6.7.4 was evaporating too quickly in this case.

After the latest fix the drops evaporate in ~16 s. I'll push this up and if it passes Firebot it will be in the nightly bundles.

**Comment by mattbilson76** [comment]
Thank you, I will download when available and start a run off to see what we get.

**Comment by mattbilson76** [comment]
Hi, just checking to see if this is in the bundle from last night?

**Comment by drjfloyd** [comment]
Firebot failed verification testing last night due to other changes made during the day yesterday. I suggest waiting for firebot to pass its verification checks.

**Comment by mattbilson76** [comment]
Ok, will standby.  Thanks.

**Comment by mattbilson76** [comment]
I downloaded the nightly release and tested this out.  Getting good results now - temperature downstream of the fire much closer to test data.  Thanks.

**Comment by drjfloyd** [comment]
Thanks for getting back to us with an update.
