### ISSUE TITLE
MPI error in geom_rad.fds

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9126]
Run `Radiation/geom_rad.fds` on blaze in debug mode with -check_mpi. I am getting a "fatal error" deadlock.

**Comment by marcosvanella** [comment]
I run the case with oneAPI and -check_mpi and could not reproduce this. I run in the firebot queue. 
Where do you see the deadlock? 
If it is a timeout deadlock we want there might be load imbalance at some point, compounded by the db and 50^3 grids. A way to check this is to increase the VT_DEADLOCK_TIMEOUT environment variable.

**Comment by mcgratta** [comment]
I launched all the verification cases at the same time. Maybe that was the problem. I'll try it alone.

**Comment by mcgratta** [comment]
I ran the case again and I still get the error. I used the debug version with the -check_mpi flag added to the list of options. The -check_mpi flag has not been committed. You have to add it. Then I ran
```
qfds.sh -p 2 -T db -q firebot geom_rad.fds
```
Make sure you clean the Build repo and completely compile fds_db.

**Comment by marcosvanella** [comment]
Did you get the two processes in two nodes?
I note I get different submission behavior using your command (qfds.sh from /usr/local/bin/qfds.sh) than using the fds/Utilities/Scripts/qfds.sh from the repo. The former puts two MPI processes in two nodes, while the repo version puts them in one node. 
With your command I see the timeout error.

**Comment by marcosvanella** [comment]
Actually, that is not correct. I see the timeout issue both ways now.

**Comment by mcgratta** [comment]
The job is hanging at geom.f90 line 27668 of your most recent commit. This is an MPI_BARRIER. First, I don't understand why you need this barrier, but that is probably not the issue. I added a print statement and I discovered that rank 0 (mesh 1) is reaching this barrier, but rank 1 never does, or at least it does not after 1 min of waiting, which is the default deadlock time out.

**Comment by mcgratta** [comment]
Both ranks enter `MAIN_MESH_LOOP` at 27043. But only rank 0 makes it out alive...  I can't follow things into the subroutines, but you need to find out where rank 1 gets stuck.

**Comment by marcosvanella** [comment]
That barrier is not needed, I'll change that. The MAIN_MESH_LOOP is where cut faces and cells are computed per mesh, the costliest operation at setup.  Changing the timeout time to 120sec the case goes through. 
Not clear why the over 60 sec difference between the 2 processes for this case, I'll look at the detailed the cc computation timings.

**Comment by marcosvanella** [comment]
The problem is imbalanced. It has two unconnected meshes, one with and one without geometries. Process 0 doesn't compute any cut-cells, process 1 does (11k cut-cells and 20k+ cut-faces) and takes 66 sec to go through this in db mode. This is why it is overrunning the 60 sec timeout up to the next MPI call. I will try running the case with 40^3 meshes.

**Comment by mcgratta** [comment]
How about just increasing the timeout time. Do you know how to access the configuration file?

**Comment by marcosvanella** [comment]
Let me try this. I think we would have to add the command:
export VT_DEADLOCK_TIMEOUT=120
in the .bashrc of the user running the case.

**Comment by marcosvanella** [comment]
This seems to work. The other option is to have qfds.sh feed the environment variable in the batch submission script (like I_MPI_DEBUG).

**Comment by marcosvanella** [comment]
The other option is to switch the geometry lines by these:

`&GEOM ID='BLOCK', SURF_ID='HOT',  SNAP_TO_GRID=T, XB=2.001,2.019,0.021,0.999,0.021,0.999 /`
`&GEOM ID='BLOCK', SURF_ID='COLD', SNAP_TO_GRID=T, XB=2.021,2.999,0.021,0.999,0.001,0.019 /`

The blocks are snapped out to the mesh and the cut-cell computation follows a scheme based on structured meshes instead of the general one. MPI_PROCESS 1 is taking <30 sec to define the cut-cells here. Either way I think we want to be able to have some control on the timeout time of the Vtune Tracer.
