### ISSUE TITLE
HT3D OBST crosses MESH Boundary

### ISSUE THREAD

**Issue by jet5678** [firemodels/fds#9235]
Hello all,
I have noticed in a model that when HT3D OBSTs cross a mesh boundary the heat conduction in the direction of the surface normal of the boundary is stopped. Compare attached picture. If a minimal example is needed, I can provide it.
The picture shows a HT3D OBST with hot gas flowing around it. The black lines are the mesh boundaries running through the object.
Is it possible to implement 3D heat transport across mesh boundaries?

Thanks a lot
With best regards

![Screenshot 2021-02-16 173106](https://user-images.githubusercontent.com/50654162/108095806-8dad4600-7080-11eb-944d-bff60444d117.png)

**Comment by drjfloyd** [comment]
Are you running with the most recent release of FDS? If you aren't try your case with the current release. If it is failing with the current release, please submit an input file.

**Comment by rmcdermo** [comment]
Should work.  There are verification cases for this.  For example,

https://github.com/firemodels/fds/blob/master/Verification/Heat_Transfer/ht3d_2mesh_x.fds

**Comment by jet5678** [comment]
I have created a minimal example in which the problem can be seen quite clearly. I have attached the code. I use FDS 6.7.5 with MPI 5.4.7 on CentOS version 8 Core.
[ht3d_obst_crossing_mesh_boundary.txt](https://github.com/firemodels/fds/files/5990960/ht3d_obst_crossing_mesh_boundary.txt)

**Comment by rmcdermo** [comment]
Ok, thanks, I'll take a look.

**Comment by rmcdermo** [comment]
I'm reproducing the problem.  Thanks for the report.

**Comment by rmcdermo** [comment]
I think in this case the problem is with assigning OPEN boundaries to a VENT using MB.  This is dangerous.  Though we do not make a big deal about it, we do mention in `10.4.1 Basics` to use `DB` (domain boundary) for multi-mesh cases.  Try that (works for me) and let me know if that works for you.
```
! OPEN boundaries:
&VENT DB='XMIN', SURF_ID='OPEN' /
&VENT DB='XMAX', SURF_ID='OPEN' /
&VENT DB='YMIN', SURF_ID='OPEN' /
&VENT DB='YMAX', SURF_ID='OPEN' /
&VENT DB='ZMAX', SURF_ID='OPEN' /
```

**Comment by jet5678** [comment]
Thanks you for the fast support, this was my fault. With the domain instead of the MESH bounardaries OPEN it works as expected. Sorry, for waisting your time.

**Comment by rmcdermo** [comment]
No problem.  It's not a trivial issue.  If not for the backward compatibility issues, we would probably consider just eliminating `MB`, but I am not sure that would go over very well.

**Comment by drjfloyd** [comment]
Being backwards compatible is a convenience for users, but if it means keeping around code that leads to problems then in my opinion we aren't really serving the user community. MB has been around since FDS 1 when there was just one MESH (well GRID at the time). MB for a long time was really just DB. Even now when people use MB, except in rare cases, they are really intending DB. We could consider keeping MB as a keyword so we can run old files, but just have MB set DB and then reset MB to NULL.  However, with FDS 7 on the horizon now is a good time to purge problematic inputs.

**Comment by rmcdermo** [comment]
I would be in agreement with that.  There is already a ERROR flag if NMESHES>1 and SURF_ID='PERIODIC'.  If we just remove the periodic part, that should do it.

**Comment by rmcdermo** [comment]
OK, I went through all the validation cases and looked at "MB=".  The trick is that we have this concept of `MB='XMIN', MESH_ID=...`, and this can often be used for multi-mesh calculations and the XMIN of MESH_ID may not be the domain boundary (DB).  So, I can't just throw an error on MB with NMESHES>1 and I can't just change all MB to DB.

I think we need to do some surgery and make sure that all internal mesh boundaries are set to INTERPOLATED_BOUNDARY if they are inside a solid.  That is the real crux of the problem here.  Probably something is getting left as NULL_BOUNDARY.  I'm going to leave this open until I get it sorted out.

**Comment by mcgratta** [comment]
That would cause trouble. I would add logic to identify the OBST as HT3D
and then set INTERPOLATED_BOUNDARY. There are many assumptions made about
INTERPOLATED_BOUNDARYs, one of which is that the cell is gas on the other
side.

>

**Comment by rmcdermo** [comment]
In theory I am doing what you say.  Else it would not work with DB either.  Somehow the OPEN bc is trumping INTERPOLATED in this case... I need to dig into it more...

**Comment by rmcdermo** [comment]
@mcgratta Here is a simplified version of the case we discussed. Note I have included the test.ini file below so that you automatically see the TMP slice inside the solid shown as outline only.

[test.zip](https://github.com/firemodels/fds/files/6012152/test.zip)

With the following vent lines you can see the heat transfer is blocked by the mesh boundary.
```
&VENT MB='XMIN', SURF_ID='OPEN'/
&VENT MB='XMAX', SURF_ID='OPEN'/
```
<img width="752" alt="Screen Shot 2021-02-19 at 1 24 55 PM" src="https://user-images.githubusercontent.com/4418497/108546008-866f7d80-72b6-11eb-97bb-c653d48104dd.png">

Changing to `DB` gives the correct result.
```
&VENT DB='XMIN', SURF_ID='OPEN'/
&VENT DB='XMAX', SURF_ID='OPEN'/
```
<img width="752" alt="Screen Shot 2021-02-19 at 1 22 05 PM" src="https://user-images.githubusercontent.com/4418497/108546129-b0c13b00-72b6-11eb-98a9-be4bfb443575.png">

**Comment by mcgratta** [comment]
The simple case works now. See the note in the PR.

**Comment by rmcdermo** [comment]
Yep, works now.  Thanks!
