### ISSUE TITLE
PROF output csv missing column names.

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#9359]
Along with some of the columns unlabeled, it looks like the last two columns are duplicates of the same Value data.

See attached for an example for material density (Value starts at 400 kg/m^3).
[tga_sample_prof_02.zip](https://github.com/firemodels/fds/files/6172363/tga_sample_prof_02.zip)

This is output from https://github.com/firemodels/fds/blob/master/Verification/Pyrolysis/tga_sample.fds

**Comment by mcgratta** [comment]
Comp 2 Density |   |   |   |   |  
-- | -- | -- | -- | -- | --
Time(s) | Npoints | Npoints x Depth (m) | Npoints x Value |   |  
  |   |   |   |   |  
0.00E+00 | 2 | 0.00E+00 | 1.00E-05 | 4.00E+02 | 4.00E+02
9.80E+00 | 2 | 0.00E+00 | 1.00E-05 | 4.00E+02 | 4.00E+02

This is the correct format. For each Time, there are two x values and two density values. This occurs if there is only one cell that makes up the solid. The x values are the top (0) and bottom (1e-5). The density is the same throughout.

The column titles don't line up because it is possible for the solid to have a changing number of cells, hence x values and quantity values. It's a bit awkward, but I could think of no better way to format this data.

**Comment by bwklein** [comment]
Fair enough, we will improve our plotting tool to handle this file type better.
