### ISSUE TITLE
Set 'EXTINCTION 1' as default for multiple REAC

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#9364]
Per the discussion thread, let's set E1 by default if N_REACTIONS>1 unless SUPPRESSION=F set explicitly by the user.

**Comment by rmcdermo** [comment]
I don't think this is complete.  I think we want E1 to be a simple model that basically puts out the fire when O2 gets below 15% no matter what fuels and reactions the user throws at it.  All the options Jason was mentioning to me could just as well be applied to E2, in which case why force the user to use E1 for multiple fuels?  But I also think we don't want to go back to the situation of having E1 ... E5 possibilities.

**Comment by mcgratta** [comment]
It's not as simple as that. E1 does account for the fact that a fire in a
hot compartment is going to still burn at O2 concentrations less than 15%,
as predicted by the basic theory. But if the grid is coarse, the E2
treatment does not work well because the actual flame temperatures are not
resolved. So E1 considers more the O2 and temperature "in the vicinity" of
the fire rather than actually in the flame. Way back when, we even probed
all the cells surrounding the cell in question looking for conditions that
would sustain the fire. If none were found, the cell was extinguished. This
captures the obvious cases where there just is not enough O2 available,
conditioned on the overall surrounding temperature. Thus, if you have a
little bit of fuel and O2 in the upper layer of a flashing compartment,
combustion is allowed, but if you have a candle in a jar, it is not. If you
look at the NIST_FSE and RSE cases, you see O2 going to 0 in the upper
layer, and whatever we do with extinction, we have to allow this to happen.
In my various variants of extinction models, the RSE and FSE cases would
usually trip me up.

>

**Comment by rmcdermo** [comment]
Kevin,
This is not done.

**Comment by mcgratta** [comment]
What do you want to do? For the maintenance release, I suggest we maintain the current configuration, but for version 7, we should make E1 the default for coarse cases, say VLES and SVLES.

**Comment by rmcdermo** [comment]
I don't think we have to wait for v7.  Since CRITICAL_FLAME_TEMPERATURE apparently only works with one reaction, I suggest we put this on COMB and require it to be set by the user for E1 or use CFT=1700 for E1, similar to how AIT=600 for E1.  If your argument is correct, that E1 is not sensitive to CFT, then this should be sufficient.

**Comment by rmcdermo** [comment]
One of my aims is to make sure we have some kind of reasonable extinction model for multiple reactions.  So, I would also set E1 by default if N_REACTIONS>1 and send a warning to the user, or at least make sure this is printed to the .out file.

**Comment by mcgratta** [comment]
I clarified the description of the two extinction models in the User Guide, including a list of the relevant parameters for each and the default values.

**Comment by rmcdermo** [comment]
OK, but I think we need to do something else with this line in EXTINCT_1:
```
Y_O2_LIM = REACTION(1)%Y_O2_MIN*TMP_FACTOR
```
It is confusing to see that the extinction is based on REACTION 1.  I think we need to convert this to some kind of global parameter.  E1_Y_O2_MIN or something

**Comment by mcgratta** [comment]
Yes, I agree. Currently, `LOWER_OXYGEN_INDEX` is specified on the `REAC` line, but I think it is more appropriate on the `COMB` line because it doesn't make sense to talk about the LOI for each reaction. But I'd rather leave it as is for the last (we hope) release of FDS 6, and then overhaul extinction and combustion stuff for 7.

**Comment by rmcdermo** [comment]
Sounds good.
