### ISSUE TITLE
TMPMAX works differently depending on how species declared

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9418]
[test1.txt](https://github.com/firemodels/fds/files/6261056/test1.txt)
[test2.txt](https://github.com/firemodels/fds/files/6261057/test2.txt)
Run these two single mesh cases for a few minutes and take a look at the temperatures in the devc file. The only difference in the cases is that in one case, OXYGEN and NITROGEN are explicitly declared species, and in the other, the default of AIR is the background. There are no reactions, but the temperatures are driven to high values. I can't figure out how to enforce the upper bound in the case with the explicitly declared species.

**Comment by drjfloyd** [comment]
In mass.f90, clipping uses the density value.   The temperature value is only used in wall.f90 to clip wall temperatures. Both test1 and test2 are getting clipped at rho=0.025. The two cases have different pressure profiles in the top compartment, and that is why the temperatures are different. If I take test1 and reduce HUMIDITY, then the results shift towards test2. I think this is due to radiative absorption by water vapor in test1 and no absorption in test2. My MVSWGR template files had the individual species since the original open box tests had red board that burned away in the box so I had two REAC lines for the redboard and for the metal vapor and just used N2 and O2 for the atmosphere. Looks like that water vapor might make a difference and should be included.

**Comment by mcgratta** [comment]
Makes sense. I assume I can add a bit of water vapor to the background nitrogen and not have to add another tracked species.

**Comment by drjfloyd** [comment]
Yes.  The typical value is 0.005941 kg/kg. The Y_O2_INFTY value in FDS is for dry air, so N2 and with added water vapor would be by (1-0.005941)*(1-Y_O2_INFTY) and (1-0.005941)*Y_O2_INFTY.

**Comment by drjfloyd** [comment]
Closing. I think we settled on no bug,
