### ISSUE TITLE
About Evac Problem in FDS6.7.6

### ISSUE THREAD

**Issue by godisreal** [firemodels/fds#9442]
I understand that Timo is trying to outsource evac from fds a little bit.  This is a good test version for evac in fds 6.7.6.  However, the recent changes seem to create a big barrier for ordinary users.  From user side I guess nobody wants to run an execuable three times with different MISC settings to finish one fds+evac case. From fds side the evac code is still twisted with fds.  From Timo's side there may be many complaints or reports for evac bugs in the future if users start to use fds6.7.6.  

So is it necessary to discuss a proposal or roadmap for outsourceing evac so that the things will benefit for everyone?  Many thanks.

**Comment by tkorhon1** [comment]
Yes, things are a little bit more complicated this way. Bat, actually, not much. I should do some programming of the input routines so that things will be easier (and more robust). I should add a FED-file and EFF-file names as a user input for the evacuation calculations and a XYZ-file input for the fire calculation that writes the fed-file. This way no need to rename/copy the files. And evacuation calculation does not overwrite the fire calculation files accidentally.

I think that making the evacuation as a two parts, initialization run + actual evacuation runs, is not a complication at all. You have been doing this anyhow. You calculate many (at least 10) evacuation calculations using the exactly same input to get some statistics. FDS+Evac is a stochastic programme, each run with the same input will produce different results: "random" initial positions, random body dimensions and walking speeds, some (tiny) random force,  etc. So, the EVACUATION_MC_MODE will be the only way to do evacuation calculation now.

I should program things so that an evacuation run does not overwrite old evacuation resuls (a keyword for this). If a output file name exists already => add _# (consecutive numbering).

Running the cases should not be too problematic, because many are using Linux computers and it is easy to use some batch scripts to do the renaming/copying files etc. And DOS users can use .bat scripts. And clusters need a queueing system batch script anyhow.

TimoK

**Comment by gjaeger** [comment]
> Running the cases should not be too problematic, because many are using Linux computers and it is easy to use some batch scripts to do the renaming/copying files etc. And DOS users can use .bat scripts. And clusters need a queueing system batch script anyhow.

@tkorhon1: I share your point of view. 

@godisreal: What is the specific problem in this issue? How can/should it be fixed? Isn't this question something for the [FDS and Smokeview Discussion Group](https://groups.google.com/g/fds-smv)?

**Comment by godisreal** [comment]
As Timo wrote "I think that making the evacuation as a two parts, initialization run + actual evacuation runs, is not a complication at all. "

Yes.  It will be helpful if Step 1 and Step 2 could be merged together by reading all the meshes into the program, both fire meshes and evac meshes.  In other words, the fire simulation read all the meshes to dump eff and fed (first run) so that evac read such data for evac simulation (second run).  I suppose in the second run you may omit fire meshes if you would like.

**Comment by tkorhon1** [comment]
Well, I have now done the 3 step procedure. But I'll change it so that one can manage all 3 steps using just one input fds file (havein just one CHID). The user just changes the MISC namelist keywords, when going through the 3 steps, when doing it interactively. If doing a batch script, then one should use sed or some other stream editor to change the input file. Or have three different input files, that have same CHID. Or have three different input files with different CHIDs and do the copying of the _evac.xyz, _evac.eff, _evac.fed files like one should do now.

**Comment by tkorhon1** [comment]
The latest version of the source code does this job already. EVACUATION_ALL_STEPS does this and one also gets CHID_evmc.smv aftern the third step "evacuation mc run", where you have both the fire and evacuation results in the same Smokeview.

TimoK
