### ISSUE TITLE
Spurious oscillations in a case with mechanical ventilation

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9451]
[NYX_VCD1.txt](https://github.com/firemodels/fds/files/6365714/NYX_VCD1.txt)

**Comment by mcgratta** [comment]
[NYX_VCD1_coarse4.txt](https://github.com/firemodels/fds/files/6367590/NYX_VCD1_coarse4.txt)
Jason -- take a look at this case. A small box with a small fire has two exhaust vents, both 30 m long, 6 cm in diameter. One has a loss coefficient of 20, the other 3. The room pressure oscillates wildly with both vents open; less so with only the 20 loss vent open. I suspect this is the general problem. I don't have a good feel for these loss coefficients. Do these seem reasonable?

**Comment by drjfloyd** [comment]
Try setting HVAC_PRES_RELAX=0 on MISC. Tightly sealed rooms with only HVAC are sometimes better with no pressure relaxation on the HVAC boundary condition.

Is your leakage area correct? You have a LEAK_AREA that is equivalent to an 0.3 mm diameter hole.

**Comment by mcgratta** [comment]
OK. I removed the leakage entirely in order to hone in on the problem. But, yes, that leak is pretty small.

**Comment by TiboDC** [comment]
Hi
My name is Tibo and  asked this question with respect to my master dissertation.

The leakage area is indeed correct. It is calculated based on experimental data, conforming the compartment is indeed airtight.
I have added: &MISC HVAC_PRES_RELAX=0/ to the input file and simulated with a coarse mesh size of 8cm instead of 2cm (to obtain the output more quickly)

The spurious oscillations are gone, but I obtain pressures above 3000Pa, which is way beyond the experimentally measured values of 25Pa.

![Pressure relax 0 output](https://user-images.githubusercontent.com/73659411/115926786-b1777880-a483-11eb-9925-b97f23adac1a.PNG)

**Comment by TiboDC** [comment]
Hi, I was wondering if there was any update yet?

**Comment by mcgratta** [comment]
No, but a question---why do your exhaust ducts have two very different loss
coefficients?

>

**Comment by TiboDC** [comment]
The loss coefficient r' is determined based on experimentally measured data according the following formula:
![image](https://user-images.githubusercontent.com/73659411/116415206-7eddcf00-a839-11eb-83d1-830a5885d9e4.png)
The duct temperature is measured --> using ideal gas law --> get density of the gas
Pressure drop over the duct and volume flow rate are also measured
The area of the ducts are also known

Note: he validation of experiments with mechanical ventilation was succesfull and quite accurately simulated in FDS

**Comment by TiboDC** [comment]
The loss coefficient r' is calculated using experimentally measured data with following formula

![image](https://user-images.githubusercontent.com/73659411/116415726-f7449000-a839-11eb-8351-a5e468167ef9.png)

The duct temperature is measured --> using ideal gas law --> get density of the gas
Duct area is known
Pressure drop over the duct and volume flow rate through the duct are also measured 

Note: the validation with mechanical ventilation (exhaust fan) was succesfull and quite accurately modelled in FDS

**Comment by mcgratta** [comment]
Yes, but your two exhaust ducts are the same length (32 m) and diameter (6
cm), but have loss coefficients of 20 and 3. It is possible that the
combination of parameters worked well with fans because there is no unique
set of parameters that produce good results. Is there something different
about these two ducts that lead to these different loss coefficients?

>

**Comment by TiboDC** [comment]
Density of the gas are the same for both (1.17 kg/m³)
The pressure drop over the ducts is for both 0.04 Pa (this is the relative pressure in the NYX compartment)

The only difference is the intiial ventilation flow rate (prior to fire conditions)
For the inlet: 0.00017 m³/s or 0.60 m³/h
For the outlet: 0.00042 m³/s or 1.51 m³/h

![image](https://user-images.githubusercontent.com/73659411/116427033-f1ec4300-a843-11eb-81fc-216eadd9fe77.png)

**Comment by mcgratta** [comment]
Is this experimental data? And if so, are you using this data to calculate the loss coefficients?

**Comment by TiboDC** [comment]
Yes and yes

**Comment by mcgratta** [comment]
And in this experiment, the two exhaust ducts were open to the atmosphere?
In other words, there were no fans, just 6 cm ducts, 32 m long?

**Comment by drjfloyd** [comment]
I put devices in for node pressure. I am not seeing a change for the internal nodes, i.e. they are not showing the rise seen with the PRESSURE DEVC. Not sure why at the moment.

**Comment by TiboDC** [comment]
@mcgratta 
Yes both inlet and exhaust duct were open to the atmosphere.
The fans were present inside the ducts, but shut down.

Small note: the ducts have different sections and segments. The total length is 32m and and representative diameter of 60mm is chosen. 
As seen from following formula, r'' is first calculated and then r', which depends on the duct area.
![image](https://user-images.githubusercontent.com/73659411/116436235-7cd13b80-a84c-11eb-9558-0361bf5bff66.png)

**Comment by drjfloyd** [comment]
Argh...I messed up and should have said HVAC_PRESS_RELAX=1 and not 0. 0 means just use the old pressure. This is why pressure kept increasing. Sorry about that.

Do you really have 32 m of duct length? The HVAC model has a 1/L term that modifies the acceleration of flow in a duct. 32 m is doing a lot of dampening.

**Comment by TiboDC** [comment]
I simulated with a coarse mesh size of 8cm and set HVAC_PRESS_RELAX=1.
This is the ouctome (still an oscillatory behaviour):
![image](https://user-images.githubusercontent.com/73659411/116455872-ddb73e80-a861-11eb-8f15-b1480d1ae24d.png)

This is a picture of the set-up and ductowork. Yes, 32m of total duct length.
![image](https://user-images.githubusercontent.com/73659411/116455936-f0ca0e80-a861-11eb-8cc0-ff240dad387b.png)

**Comment by TiboDC** [comment]
![Uploading image.png…]()

**Comment by TiboDC** [comment]
![image](https://user-images.githubusercontent.com/73659411/116456155-3686d700-a862-11eb-839e-78f58778791a.png)

**Comment by drjfloyd** [comment]
If I set the two duct LENGTH to 0.1 m the magnitude of the oscillation drops significantly. You have calibrated your loss based on measurement and aren't using the length along with a wall roughness for pressure drop. Dropping the length will just change the time constant of the HVAC system's response to pressure changes and not impact the loss. 

![image](https://user-images.githubusercontent.com/12799217/116554107-cc554d00-a8c8-11eb-8658-95988867cdde.png)

**Comment by mcgratta** [comment]
Jason -- in this case could one specify the actual length and diameter of
the duct(s) and set the LOSS coefficient based on the experimental data? I
ask because if the fans were turned on, wouldn't we want to leave in the
basic HVAC network?

>

**Comment by drjfloyd** [comment]
I am not sure I understand your question.

The LOSS coefficient in the input file is already set by the experimental data. They measured flow rate and pressure drop in both the supply and exhaust ducts. The duct has a varying diameter over its length. You could define individual duct segments for each unique diameter, but this is a bit of a waste of computational resources since the mass flow rate will be the same. TiboDC has followed standard practice and picked a representative diameter and used that with the measured pressure drop and flow rate to calculate the LOSS for each duct.  

The issue is the HVAC momentum equation has an acceleration term that uses the mass of air in the duct. With such a tightly sealed compartment and a long duct length, that acceleration term is doing a lot of dampening of flow in the duct and when coupled with the dP/dt = Q/V of the fire is resulting in some large oscillations with the flow in duct constantly chasing the compartment pressure. Changing the duct LENGTH isn't changing the mapping of the network. It is only adjusting the acceleration term and allowing the duct flow to more closely follow the compartment pressure.

**Comment by mcgratta** [comment]
Ah, yes, I see now. The choice of the duct length does not affect the
steady-state flow rate, just the time necessary to achieve it.

>

**Comment by TiboDC** [comment]
I'm not quite following.

The actual duct length is 32.4m, so changing it to 0.1m is not representative for reality. 
Is FDS not capable of simulating my case (no mechanical ventialtion, airtight compartment, ducts of 32.4m length).

The other cases with mechanical ventilation were no problem to validate, even with the 32.4m duct length. There were no oscillations perceived and the agreement was actually very accurate

**Comment by drjfloyd** [comment]
There is no storage of mass in the HVAC model. Length is used for drag if you specify a roughness (you just have LOSS) and to define how the duct responds over time to pressure changes. Dropping the length may result in a slight shift in the rise and fall of pressure. It doesn't change the equilibrium flow rate. I suggest you try this, and see what the results are. You may also want to investigate the impact of error in your pressure and volume flow measurements on the LOSS terms. 

With a fan, the dynamics are different. You have a forcing term in the equation from the fan that is likely outweighing the pressure perturbation in the compartment.

**Comment by mcgratta** [comment]
The issue here is that FDS solves for the pressure in each gas phase grid
cell in the room every time step. The HVAC solver then takes the pressure
nearest the vent as its boundary condition. If the response time to achieve
steady flow in the duct is relatively long, there can be a mismatch with
the FDS gas phase pressure solver. So this is a numerical issue of not
having the pressure solvers fully coupled. In most simulations, this is not
a problem and not noticeable, but in this case, with the actual length, it
is.

>

**Comment by TiboDC** [comment]
@mcgratta @drjfloyd 
Many thanks for the information. Things are more clear now.

The suggestion HVAC_PRES_RELAX=1 does not have an influence and it not of importance here or do I see this wrong?

**Comment by mcgratta** [comment]
If it makes no difference, I would leave it out.

>

**Comment by TiboDC** [comment]
Hi @mcgratta @drjfloyd 

I have some remaining questions .

The time constant of the HVAC system's response to pressure changes, is this represented by Lj in following equation?
![image](https://user-images.githubusercontent.com/73659411/116991721-46287480-acd5-11eb-87e2-dc29129a263e.png)

So the larger Lj, the larger the time constant, the more time it requires to reach a steady state value. It this required time is too much, there is no correct coupling between the FDS and HVAC solver anymore. Hence, numerical issue with pressure oscillations arise.

Is my reasoning correct? 


I was also not quite following with: "The HVAC model has a 1/L term that modifies the acceleration of flow in a duct. 32 m is doing a lot of dampening". I do not see the 1/L term in the technical reference guide and how this is linked to an acceleration.

**Comment by drjfloyd** [comment]
I was thinking of the equation with the L on the other side.  
du/dt = acceleration = 1/L * (...)

The rho L term represents the mass of gas in the duct.  The left hand side is mass times acceleration and the right hand side is the force or F = m a.  The underlying issue is that the pressure solution inside the MESH and the pressure solution inside the HVAC network are done at different times. The HVAC solver extrapolates the current MESH pressure solution to the end of the time step but this process isn't perfect since it is an extrapolation.  The large L means it takes some time for the duct to come to equilibrium with an applied pressure difference across the duct. With a growing fire the extrapolated pressure in the HVAC solver has some error. With the fairly tight compartment, this is resulting in overshoot of the compartment pressure. The velocity gets too high with the pressure overshoot and then as the pressure drops due to the velocity it undershoots the pressure again. This is the oscillations you were seeing. Reducing L is helping to limit the size of the overshoot/undershoot and is limiting the magnitude of the oscillations you are seeing.

**Comment by TiboDC** [comment]
Many thanks for the additional information
