### ISSUE TITLE
evacuation test case

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#9452]
timo,
I've made some changes in smokeview recently to improve particle file loading.  I need to test these changes with some evacuation test cases.  I think it would also be good to have an evacuation test case in smokebot so that I will know right away if any of my changes break evac visualization.  can you post a test case I can use to make sure smokeview is still working with evacuation. I tried the test cases in fds/Verification/Evacuation but didn't see any files that would have contained people.
thanks,
glenn

**Comment by gjaeger** [comment]
@gforney How can I help you? Should I just check a test case for functionality or should I embed it in the bot?

**Comment by tkorhon1** [comment]
Hi all! I was really bysy last spring/early summer (May-June) right up to the start of my summer vacation. Now back at work and now I do not have a high work load. At least, not yet. Might change soon, we have a couple of things waiting (peer reviews of fire engineering designs by fire consultans). These should usually be done ASAP and you do not exactly know, when the consultants are ready to send a report.

Now after the holidays I have already run my example cases and V&V cases with FDS 6.7.6 (Evac 2.6.0). Things seem to be running nicely. I should still put the .fds files (and some output files) to GitHub somewhere. Well, seems that these files are in my GitHub: tkorhon1/FDS-Evac-Guide/InputFiles. I'll update the files there. And I should update the  tkorhon1/FDS-Evac-Guide Readme.md so that it says that the up-to-date manual is nowadays in firemodels/fds/Manuals/FDS_Evacuation_Guide).

I will update the FDS+Evac LaTeX file (firemodels/fds/Manuals/FDS_Evacuation_Guide) soon. I put there the new V&V results and figures etc.

So, ToDo-list for me (you can comment if there is something not right with it, e.g., files/figures/latex should be somewhere else, I might not know exactly what things is kept where):

1) Put the example + V&V .fds files and outputs etc.: tkorhon1/FDS-Evac-Guide/InputFiles

2) Update tkorhon1/FDS-Evac-Guide Readme.md => firemodels/fds/Manuals/FDS_Evacuation_Guide

3) Update the FDS+Evacuation guide (first in tkorhon1/fds-fork, then commit to firemodels/fds). (Timo: Remember first to "remote update" etc.). Update includes: new V&V figures, new V&V number data inside the LaTeX.

4) Check that the example input files in the manual are in the form of Evac 2.6.0 (three step fire+evacuation calculation). I will not write the input files 3 times in the manual (having just different keyword on the MISC namelist. I put there three MISC namelists, one having the & and others not, and some comments how to perform the 3 step procedure.

5) Update the example input files that are in the manual: well, these are in the  tkorhon1/FDS-Evac-Guide/InputFiles/Examples, so this task is done, when the task 1) is done. I should just check that the information (in the manual? inteh readme-file?) where to find the files are correct.

Wbr,
Timo

**Comment by rmcdermo** [comment]
@tkorhon1 Thanks for the updates!

One thing that caught my attention is that you are committing pdf, png, etc., files for the FIGURES.  Do you not have a script that builds the plots from results?  Well, I suppose that is not part of your system now, but whoever is maintaining the manual should work toward building plots from the results.  It is not very convincing "verification" if the plots are made outside the repo.

**Comment by gforney** [comment]
timo, for figures generated from smokeview, I can help you create a smokeview script that generates the pngs.  I need to know 
1.  the fds input file
2.  what files you are loading 
3. what time you want to take the "snapshot"

I'll then give you a sample .ssf file.  it should be pretty easy then to adjust to exactly what you want

**Comment by tkorhon1** [comment]
Glenn: Well, I have had some troubles with the .ssf scripts and getting them to show the agents. I will put (somewhere) the .fds, .ini. .ssf files that I use to generate the .png pictures. the problem is that the .ssf is not working for agents right now. So, I should make an Smokeview Issue, where I put one example. I'll do that soon. Well, an example is here: Github: https://github.com/tkorhon1/FDS-Evac-Guide/tree/master/InputFiles/Verification/imo .  Run the CompTest6.fds or CompTest11.fds and try to get the .png automatically. 

Randy: Yes, you are right. I plot the figures using Excel. I should put the Excel files in  tkorhon1/FDS-Evac-Guide/InputFiles or something like that. And there a short Readme.txt how to use the Excels. They are not too nice (automatic), one should open first the .csv files and then the .xlsx so that the numbers are updated. I'm not too good in Excel. Most of the figures could easily be plotted by some other programme (Matlab), but last time I used Matlab is some 15 years ago.

Well, I should also put my shell scripts (bash) that collects the data of the fds outputs and also the bash script to used to run the cases. Some cases are run many times (stochastic programme).



1.    Put the example + V&V .fds files and outputs etc.: tkorhon1/FDS-Evac-Guide/InputFiles
      Already done: .fds (and .ssf,.ini) files are there.

 2.   Update tkorhon1/FDS-Evac-Guide Readme.md => firemodels/fds/Manuals/FDS_Evacuation_Guide

 3.   Update the FDS+Evacuation guide (first in tkorhon1/fds-fork, then commit to firemodels/fds). (Timo: Remember first to "remote update" etc.). Update includes: new V&V figures, new V&V number data inside the LaTeX.
       Done: the new .tex is in firemodels.
       ToDo: FIGURES: Write a short readme.txt which contains the information, which figures/numbers should be updated when the V&V runs (those that I run for each release version) and refer to tkorhon1/FDS-Evac-Guide.

 4.   Check that the example input files in the manual are in the form of Evac 2.6.0 (three step fire+evacuation calculation). I will not write the input files 3 times in the manual (having just different keyword on the MISC namelist. I put there three MISC namelists, one having the & and others not, and some comments how to perform the 3 step procedure.

 5.   Update the example input files that are in the manual: well, these are in the tkorhon1/FDS-Evac-Guide/InputFiles/Examples, so this task is done, when the task 1) is done. I should just check that the information (in the manual? inteh readme-file?) where to find the files are correct.

6. Edit dump.f90, evac.f90 so that the Phase 3 writes a smokeview file that also reads the fire data. Well, perhaps I'll make fourth .smv file (CHID_fire+evac.smv) that is the Phase 2 (fire calculation) .smv modified so that it contais the .prt5 files for the agents and other information that is needed to show the agents. The guiding flow fields for evacuation are not there. They can be seen opening the Phase 1 (or Phase 3) .smv file.

7. Put in tkorhon1/FDS-Evac/Guide the bash scripts that is used to run the examples and V&V cases. And put there also the bash script that is used to parse the V&V outputs and also the Excels that are used to plot the (parsed) results and also the Readme.txt giving guidance how to use these things to get the figures and numbers in the manual. (Later this shoud be more automatic, but this requires Matlab processing of the outputs). The first step is to make things so that some other person can make the same (arduous) steps to get the figures.

TimoK

**Comment by gjaeger** [comment]
@tkorhon1 With PR #10089 we should/can close this issue.
