### ISSUE TITLE
breaking and reforming zones

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#9475]
The attached case has three rooms with room 1 connected to room 2 by door 1, room 2 connected to room 3 by door 2, and room 3 connected to the ambient by door 3.  An air source is placed in room 1 and all the doors are initially closed.  At 10 s door 1 opens. At 20 s door 2 opens. At 30 s door 3 opens. So far everything works as expected. The pressure zones merge and zone pressures behave as expected.  At 40 s, door 1 closes.  The pressure zones remain merged and room 1, which is no sealed oof, does not re-pressurize.

In investigating this I tried a  variant where I kept door 1 closed (defined the ramp to be -1 for all times) and door 3 closed (defined the ramp to be 1 for all times) but kept door 2 opening at 20 s. In this case room 1 should just continuously pressurize. However, at 20 s when door 2 opens, all three pressure zones merge.

[zone_break_fast3.txt](https://github.com/firemodels/fds/files/6417318/zone_break_fast3.txt)

**Comment by mcgratta** [comment]
It works now. The inside cells of all the walls were assigned zone 1, even between zones 2 and 3. There were thus connection issues when the doors opened and closed.

**Comment by mcgratta** [comment]
My solution fixed the case at issue, but broke many more. The problem is that the current method of assigning pressure zones requires that all cells be assigned a PRESSURE_ZONE. Initially, PRESSURE_ZONE is set to -1 and the algorithm crawls through the domain again and again looking for non-assigned cells. Trouble is, when the crawler is inside a wall, it goes all through the domain assigning all the blocked interior connected spaces the same zone. Now when a door opens, the interior cells may not have the same zone number as the rooms on either side of the door, and the connectedness is not right. The simple solution would be to assign all unassigned zones to 0, but then it's possible that opening a door between two zones then connects them to ambient.

**Comment by mcgratta** [comment]
I added a line that sets any unassigned cells to have P_ZONE=0. Things seem to be working OK.
