### ISSUE TITLE
CHID_steps.csv file not filled during the run

### ISSUE THREAD

**Issue by andrea-paradiso** [firemodels/fds#9686]
FDS creates the CHID_steps.csv file at the start but doesn't fill it during the run. Example fds file attached.
[test_fds.txt](https://github.com/firemodels/fds/files/6838387/test_fds.txt)

**Comment by mcgratta** [comment]
This is a bug. By default, if the job involves more than 32 meshes, FDS writes an abridged set of diagnostic output to the .out file. The steps file was following this same rule, even though we really should write out the steps file for all cases because it is not alot of output. I'll fix, but for now, try setting `SUPPRESS_DIAGNOSTICS=F` on the `DUMP` line and see if that gives you back the steps info.
