### ISSUE TITLE
prohibitively large memory use by particles for veg

### ISSUE THREAD

**Issue by ruddymell** [firemodels/fds#9856]
In simulating the Camp Swift research burn in grass we need to test different representations of the grass species using the particle model in FDS. This can result in up to 16 different types of particles (e.g., blade of grass versus the stem; lower moist versus upper dry layer). 

The attached plot shows the memory used (kB per grid cell) for FDS runs (on a MacPro) with increasing number of particle types. These numbers are from the top command in OSX or the private memory use for the process using the activity monitor. The input file in also attached. 

For a 100 m x 100 m plot with 1 m tall grass veg, a 10 cm grid resolution, and 16 types of particles (this is our most demanding case) the required memory would be 2.4 TB (which is a show stopper). With a 25 cm grid the memory need is 152 GB (which is workable). 

Assuming these results and tests are correct, is there something that can be done reduce the memory usage for this application?
![Plot_PartMem](https://user-images.githubusercontent.com/12721870/131038495-5c9d9c36-28a9-439d-a865-9f8ff31a7706.png)
[input_PartMemTest.txt](https://github.com/firemodels/fds/files/7062801/input_PartMemTest.txt)

**Comment by mcgratta** [comment]
Probably. This might be a situation where we massively over-allocate something and never noticed until now. I'll take a look.

**Comment by mcgratta** [comment]
Is the issue here the total number of particles? Or the total number of particle types?

**Comment by mcgratta** [comment]
So far, the only thing I can suggest is to set `N_LAYER_CELLS_MAX(1)=1` on each `SURF` line. This limits the number of solid cells to 1, making these thermally thin. Currently, FDS uses 2 cells, but because of the potential for swelling, 5 cells are allocated. This reduced the memory by about 20%.

**Comment by drjfloyd** [comment]
With 10x10x10 meshes, you have 1000 grid cells per mesh and 600 wall cells per mesh. Is it potentially an issue with having to allocate arrays for mesh-to-mesh particle exchanges; does memory usage improve if just one mesh is used?

**Comment by ruddymell** [comment]
The issue is more with the total number of particle types.
The tests to date, and in the provided plot and in input file, were with one mesh

**Comment by mcgratta** [comment]
I ran with the same number of particles, but with 1 particle type instead of 18. This saved some, but not alot. Why do you think it has to do with particles types?

**Comment by ruddymell** [comment]
I should have clarified. From the practical point of view of FDS application I expect that we will run across this problem only when we need to use a (too) large number of particle types. When we represent the vegetation in Camp Swift by one particle type, then we don't have this memory problem. But the simulated fire behavior is wrong. We need to use more particle types to better represent the vegetation and better simulate the fire behavior. This is similar to simulations of the Douglas fir tree simulations where better results were obtained with more particle types (foliage and roundwood of three different sizes).

**Comment by mcgratta** [comment]
No, I get what you are doing. The question for me is what is using the memory -- the particles themselves or the particle types. Currently, you have 18 particles in each grid cell, and each particle is of a different particle type. Suppose you only define 1 particle type but still put 18 particles of this type in each grid cell?

**Comment by drjfloyd** [comment]
Ran with powers of 2 for particle classes; results below with FDS 6.7.6 on Windows. The particle classes with no INIT add little memory usage, but with one particle per cell it adds up. For each particle class we allocate storage in D_SOURCE, M_DOT_PPP, and some other gas arrays.  Then each particle itself has over 100 variables associated with it some of which are arrays in depth, all tracked species, or over all particle types. Most of these are pointers which requires additional memory. In this case, for the 16 particle classes all those variables add up to around 300 values per class. At 4 bytes for the value, 4 bytes for the memory location, plus additional over head for the pointers, I estimate 70 kB per cell for 16 particle classes which isn't too far off from the table below

One thing I notice is we are allocating space for particles for the ONE_D arrays LP_CPUA and the like which I don't think makes sense.  

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jfloyd/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jfloyd/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Classes | MB | kb/Cell | kb/Cell/Per class | MB No Init
-- | -- | -- | -- | --
0 | 18.9 | 0.0 | 0.0 | 18.9
1 | 24.7 | 5.8 | 5.8 | 21.7
2 | 32.8 | 13.9 | 7.0 | 21.8
4 | 53.0 | 34.1 | 8.5 | 22.1
8 | 89.0 | 70.1 | 8.8 | 22.9
16 | 142.0 | 123.1 | 7.7 | 24.4



</body>

</html>

**Comment by ruddymell** [comment]
I didn't check the scenario of more than one particle, say 10, of a the same type in a grid cell because I thought the physics in the code, for this scenario, would be based on a single, suitably weighted, particle that represents all 10 identical particles. Am I missing something?

**Comment by drjfloyd** [comment]
Every particle that you insert brings with it 100s of variables.

**Comment by mcgratta** [comment]
Normally, you would not put 10 particles of the same type in the same cell. I just was asking you do this as a test to see if the memory usage is due to the large number of particles and/or the large number of particle types.

**Comment by mcgratta** [comment]
Jason -- I don't think D_SOURCE etc are dimensioned by particle class. What arrays are you thinking of that are dimensioned by number of particle classes?

**Comment by mcgratta** [comment]
LP_CPUA doesn't make sense for particles, but it is used by WALL and CFACE's, which is why we put it in ONE_D. There are some variables like this, but at the moment, I cannot understand why the number of particle CLASSES, as opposed to the number of particles, would significantly increase memory. The amount of data stored in LAG_PART_CLASS is not that much. But if it is used to dimension something, then that might explain things.

**Comment by drjfloyd** [comment]
Yes you are right. Not looking at the code correctly.  I had searched for N_LP_ARRAY_INDICES, but the line with D_SOURCE and M_DOT_PPP isn't an allocation. There are the AVG_XXX arrays which are by class.

We may want to think about breaking ONE_D into two arrays.  Some variables I don't think make sense to track for particles like particle and aerosol accumulation variables and other variables like U_NORMAL that only apply for wall and cface.

**Comment by ruddymell** [comment]
If I run the same test but with one particle type and successively double the N_PARTICLES_PER_CELL in INIT (starting at 1 and ending with 16) I get similar memory use.

**Comment by drjfloyd** [comment]
It isn't solely number of classes. Look at my table. The last column is just the particle class definitions with no INIT lines. There is only a minor increase in memory.  But when we have 16 particle classes the LP_CPUA and other arrays in ONE_D are now dimensioned 16.  With 16 particle class ONE_D_TYPE and L_P_TYPE wind up storing about 300 numbers per particle. That adds up.

**Comment by drjfloyd** [comment]
With 16 classes LP_CPUA, LP_MPUA,LP_TEMP, A_LP_MPUA add 64 values to ONE_D.

**Comment by mcgratta** [comment]
I'll put these variables somewhere else and see if that helps.

**Comment by drjfloyd** [comment]
Should we scrub ONE_D for other WALL and CFACE only items like U_NORMAL(_S and _0), U_TAU, T_MATL_PART, PART_MASS (_ENTHALPY)? PRESSURE_ZONE?

**Comment by mcgratta** [comment]
Yes, but first I need to create the right data structure, and then it should be easy to move the variables out.

**Comment by mcgratta** [comment]
Commit a5329c0 splits the `ONE_D` derived type into two. The new derived type, called `BOUNDARY_PROPERTY` is used by `WALL` and `CFACE`, but not `PARTICLE`. I moved `LP_MPUA` etc out of `ONE_D` and hence out of `PARTICLE`. This will reduce the size of the particle memory. I'll look for more variables to move. Let me know if this helps.

**Comment by ruddymell** [comment]
I'm getting about 10% less memory use now.

**Comment by mcgratta** [comment]
OK, that's something. I'll look for more fat to trim.

**Comment by mcgratta** [comment]
I think I found the main source of fat. We are storing all 104 radiation angles for each particle, but these slots are only used if the particle is used as a "target". In your case, we just use the integrated intensity, not the angle-specific intensities. I need to do some restructuring to make this happen, but then I think the fat will be cut in half.

**Comment by shostikk** [comment]
That's a good catch. Do we need to store the ILW values even for targets?

**Comment by mcgratta** [comment]
I am moving ONE_D%ILW to BOUNDARY_PROPERTY%ILW, which is only used by WALL and CFACE. Currently, ILW is a child of the derived type BAND, and I am going to add BAND directly to the LAGRANGIAN_PARTICLE type. Only in cases where the particle class is a solid target or has a distinct ORIENTATION will the ILW array be allocated. This should cut the particle memory usage by about half.

BTW, do you ever use one or more ORIENTATIONs for solid particles that are not just targets? There is still significant machinery devoted to multiple ORIENTATIONs, but I have found that this is somewhat awkward to apply in practice.

**Comment by shostikk** [comment]
Only years ago have I used the ORIENTATIONs . I must check if guys at VTT do cables with this. I think we tried two years ago again, but not great success. 

Btw, all of our radiation codes would be much simpler, if we updated all the angles at once. The only reason we need to store IL values is because of this 'every-fifth-angle' update scheme.

**Comment by mcgratta** [comment]
Ruddy -- try your case again and let me know where things stand. It looks like the memory usage has dropped by about half.

**Comment by ruddymell** [comment]
For my test cases, the memory use is unchanged, still down about 10% from my original tests.

**Comment by mcgratta** [comment]
Are you sure you are running the latest source code? Look in the .out file. What do you see here:
```
 Lagrangian Particle Classes

   1 type1
     SURFace ID: type1
     # Reals: 121
     # Integers: 24
     # Logicals: 5

   2 type2
     SURFace ID: type2
     # Reals: 169
     # Integers: 24
     # Logicals: 5
```
For type1, I added `N_LAYER_CELLS_MAX = 1` to the SURF line.

**Comment by mcgratta** [comment]
Any progress?

**Comment by ruddymell** [comment]
No significant change in memory usage (still about 10% less than original estimates).

**Comment by ruddymell** [comment]
Hold on, I didn't see your latest request regarding the .out file

**Comment by ruddymell** [comment]
I'm still getting only a 10% memory reduction from the original. 
Here's my .out Lagrangian Particle Class info 
<img width="258" alt="image" src="https://user-images.githubusercontent.com/12721870/131926512-ed2277c2-bdb5-4893-b5cc-902ccdb14df6.png">

I have only one particle type but multiple particles per cell and used N_LAYER_CELLS_MAX=0 on SURF line

**Comment by mcgratta** [comment]
Do you mean `N_LAYER_CELLS_MAX=1`?

In any event, I'll check it out.

**Comment by ruddymell** [comment]
Yes, N_LAYER_CELLS_MAX=1 to force thermally-thin calc

**Comment by mcgratta** [comment]
I moved some more variables out of the ONE_D derived type, but there is still a bit too much fat. I'll keep trimming.

**Comment by mcgratta** [comment]
PR #9905 is a start of a reorganization of boundary-related variables. This should allow us to more carefully pick and choose variables that are appropriate for a given type of particle, wall, or cface cell. At the moment, this PR only involves name changes.

**Comment by mcgratta** [comment]
I am still working this issue. It is complex, but important. My latest idea, which hasn't been committed, is to remove the large 2D storage arrays that we use for particles, wall and cfaces. Then, instead of including ONE_D and other derived types within the WALL, CFACE, or LAGRANGIAN_PARTICLE derived types, I just create separate arrays of them, like MESHES(NM)%ONE_D%X(5), the 5th internal node coordinate, say. A WALL, CFACE, or LAGRANGIAN_PARTICLE will make a reference to it, like

```
DO IW=1,N_WALL_CELLS
   WC=>M%WALL(IW)
   ONE_D=>M%BOUNDARY_ONE_D(WC%OD_INDEX)
   ...
```
The guts of these wall and particle loops will remain the same; just the first few lines will be changed a bit. In this way, we can create new or different derived types associated with boundaries without having to assign each and every wall or particle with all this extra baggage. I was not able to figure out how to work this using polymorphic data structures, a Fortran 2003 addition that allows one to design more flexible derived types. As some point, we may be able to use them, and my current idea would be a step in that direction.

**Comment by shostikk** [comment]
Looks good. Do we need to define three different ONE_D structures ?

**Comment by mcgratta** [comment]
No -- WALLs, CFACEs and LPs will use the same ONE_D structure, and these would all be saved in the same array. At the moment, there are 3 derived types that can be used: BOUNDARY_COORD, ONE_D, and BOUNDARY_PROPERTY. My goal is to reorganize the variables within them so that a MASSLESS particle or an INERT WALL would only need to reference BOUNDARY_COORD, for example. ONE_D will change so that only thermally-thick walls and particles will use it. Now it is a catch-all for everything, and very wasteful.

**Comment by mcgratta** [comment]
Update -- I have implemented in my local repository the changes to the boundary data structures. All the verification cases run successfully, as do the serial validation cases. But I ran one of the UL_NFPRF rack storage cases and got a seg fault after about a day of running, with no traceback. Rats. So I am tracking that down now. This case involves multiple meshes, lots of sprinklers, lots of droplets, and box burn away. Very challenging keeping track of the creation and destruction of droplets and wall cells. Hopefully, I'll sort it out soon. Good news is that the new data structures use less memory and reduce the CPU time of boundary and particle processing.

**Comment by mcgratta** [comment]
Update -- we're going to do a maintenance release this week, and then I am going to push my changes related to boundary variables. I'd rather not push this change just before a release.

**Comment by mcgratta** [comment]
I just committed much of the work I've done on this issue over the past few months. Work still needs to be done to reduce the size of boundary arrays, but I'd like to merge what I have now.

**Comment by ericvmueller** [comment]
Taking a further look at this issue... I find that when you use all 16 particle classes in the example and start to increase the resolution (as a means of increasing the number of particles in the direction of what Ruddy would need), the startup time is an issue. With 100x100x10 cells (1.6E6 particles), the startup becomes prohibitive ...I gave up after an hour.

It seems like the hardcoding of M%NLPDIM is an issue. As the M%LAGRANGIAN_PARTICLE array gets larger new memory is added in chunks of 50 particles, so getting to 1E5 or 1E6 particles means a lot of allocation/deallocation/copying of big arrays just to add a small amount each time.

Modifying the initial value of M%NLPDIM to fit all the particles makes a huge difference (and doing something similar for the initial values of M%N_BOUNDARY_ONE_D_DIM, etc). The case can then initialize in about 10s and seems to use about 7GB of memory when stepping. 

I know it is probably not ideal to give users access to this variable, since I'm not sure that we check for over-allocation. It may be possible to pre-calculate the requirements, or at least add in bigger chunks when users specify an INIT volume with N_PARTICLES_PER_CELL. But whatever the solution, I think we need to address this to handle cases like Camp Swift.

[input_PartMemTest.txt](https://github.com/firemodels/fds/files/8620766/input_PartMemTest.txt)

**Comment by mcgratta** [comment]
Yes, I agree. The question is where to input this parameter. Currently, these arrays are defined for each mesh. We might end up allocating huge arrays to meshes with no particles. I'll see what can be done.

**Comment by drjfloyd** [comment]
Would this be better as an array M%(NLPDIM(N_LPC)) and set it on &PART?  Then could just make it bigger for particle classes where you know you will have lots of particles.

**Comment by mcgratta** [comment]
I think I have a solution which is similar. M%NLPDIM remains the same as before, but now when we call `ALLOCATE_STORAGE` in func.f90, we have something like 
```
IF (PRESENT(LP_INDEX)) THEN

   LPC => LAGRANGIAN_PARTICLE_CLASS(LPC_INDEX)
   SF => SURFACE(LPC%SURF_INDEX)
   IF (LP_INDEX>M%NLPDIM) THEN
      N_NEW_STORAGE_SLOTS = LPC%N_NEW_PARTICLES    ! Instead of 50
```
Then a few lines later
```
   IF (LPC%INCLUDE_BOUNDARY_COORD_TYPE) CALL ALLOCATE_BOUNDARY_COORD_ARRAYS(LCP%N_NEW_PARTICLES)
   IF (LPC%INCLUDE_BOUNDARY_ONE_D_TYPE) CALL ALLOCATE_BOUNDARY_ONE_D_ARRAYS(LCP%N_NEW_PARTICLES)
   IF (LPC%INCLUDE_BOUNDARY_PROPS_TYPE) CALL ALLOCATE_BOUNDARY_PROPS_ARRAYS(LCP%N_NEW_PARTICLES)
   IF (LPC%INCLUDE_BOUNDARY_RADIA_TYPE) CALL ALLOCATE_BOUNDARY_RADIA_ARRAYS(LCP%N_NEW_PARTICLES)
```
Something similar would be needed for WALL and CFACEs. For the moment we can leave them hardwired at 1000.

**Comment by ericvmueller** [comment]
Adding the option of `NEW_PARTICLE_INCREMENT` and setting it to 1E5 gets the particle initialization stage of startup down to ~140 s for the example. 
Increasing to 1E6 goes down to ~20 s. This gets into the territory of over-allocation, since it will reserve for 2E6 particles to accommodate the necessary 1.6E6 ...but it still looks to take about 7GB of memory when stepping.

@ruddymell can you take a look when you get a chance and see if we are getting closer to accommodating what is needed for the high-fidelity Camp Swift run?

**Comment by mcgratta** [comment]
Great -- remember to add the new parameter to the User's Guide. Somewhere in the chapter on particles, with maybe a note in the WUI chapter.
