### ISSUE TITLE
Issues with porous media variables

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#9869]
Two issues I've encountered with using the `POROUS MEDIA` drag law (in my case, to apply a permeability approach to model vegetation drag):

1. There is no error check for whether you define a `POROUS_VOLUME_FRACTION` on the `PART` line. As there is no default value, one can end up with strange behavior or memory access issues.

2. The attached example shows that in the initialization stage, particle mass is determined from the `POROUS_VOLUME_FRACTION`, taking a calculated effective length as described in the user guide. However, this mass is subsequently overwritten (I assume as the heat and mass transfer calculations begin). You can see the mass change in the smokeview output. 
If a `LENGTH` is defined on the `SURF` line, it will take that value after the initial step, but in this example we end up with a nonsensical mass.

For me, the ideal would really be to remove the `POROUS_VOLUME_FRACTION` variable altogether, and to calculate the necessary information from a length on the `SURF` line, and a `MASS_PER_VOLUME` on the `INIT` line. So one can effectively model vegetation in the 'usual' way we do, but just swap in a permeability-based drag model.
...but I recognize this might interfere with other uses for `POROUS MEDIA`

 
[Porous_drag_test.txt](https://github.com/firemodels/fds/files/7085356/Porous_drag_test.txt)

**Comment by mcgratta** [comment]
The `POROUS_VOLUME_FRACTION` would be easier for a user to obtain. Let's address any obvious errors in the existing POROUS model, and then discuss its extension to vegetation.

**Comment by drjfloyd** [comment]
Thanks for reporting issues.  Porous media inputs haven't seen much use by the user community so it doesn't surprise me that the error checking and implementation could use some work.

**Comment by drjfloyd** [comment]
I added a particle class parameter to store the characteristic length when the particle class is screen drag or porous. In wall where we updating the particle mass for pyrolysis we didn't have any checks if the particle was porous or screen drag, so the particle mass was being recomputed using the surface length and not the porous based length. I didn't want to use the surf length for this since I could see where one might want to use the same surf definition for different porous volume fractions.

I also added a check in read to make sure porous volume fraction or mass_per_volume on init was specified with the caveat that the init overwrites the particle class value. If you want different mass_per_volume in different regions for the same particle you will need different part inputs. I'll have to think a bit more on how best to deal with the same particle class being used in different init inputs with different mass_per_volume.

Something to note is that the FDS screen drag and porous drag calculations area based solely on the initial particles. If you assign pyrolysis properties to the particle, the drag will not decrease until the particle is consumed at which point there would just be no drag. 

I'll be pushing up changes shortly.

**Comment by ericvmueller** [comment]
Thanks for working on this! I will take a look shortly

**Comment by ericvmueller** [comment]
I'm still having the particle mass change after a few iterations in my test case.

Mass errors aside, with the current approach, If I just want to test out two drag models but leave everything else the same (as in these two examples)... 

- The `POROUS MEDIA` approach will have one particle per cell, which has a very large area to account for the `MASS_PER_VOLUME` 
- The `CYLINDER` approach will have one particle per cell which is small (based on the `SURF` length), but has a large weighting factor (`PWT`) to account for the `MASS_PER_VOLUME`. 

I haven't fully wrapped my head around whether this will matter at any point in terms of solving for heat and mass transfer. I imagine the weighting factor and surface area always show up as a product, and the only difference is in terms of outputs (e.g. what you would see if you output `PARTICLE MASS`). 
Anyhow, it was a bit confusing for me, and it is maybe worth sticking to one approach or the other?  

[Drag_test_cylinder.txt](https://github.com/firemodels/fds/files/7107255/Drag_test_cylinder.txt)
[Drag_test_porous_media.txt](https://github.com/firemodels/fds/files/7107256/Drag_test_porous_media.txt)

**Comment by drjfloyd** [comment]
Sorry about that. I apparently I must have done an undo in the editor after testing and reinserted the non-porous mass calc outside side the if block.

Provided you have the same velocity and temperature conditions, you should see the same heat and mass transfer. Particle heat and mass transfer is:
mass(or heat) flux * particle surface area * weight

For a non-porous cartesian or cylindrical particle the surface area is that of a single particle and the weight comes from the mass_per_volume
For a porous cartesian or cylindrical  particle the surface area is based on the mass_per_volume and the weight is 1

spherical particles get treated the same. porous just uses particle weight rather than length because there is no LENGTH input for a sphere only thickness or radius.

If you getting very different results then we probably have a bug somewhere.

**Comment by ericvmueller** [comment]
No worries, thanks for updating it! I can confirm the mass is correct in my test case now. 

That is what I figured, regarding the different approaches to weighting. I haven't implemented the porous media approach for any more complex cases with heat/mass transfer yet, as opposed to the non-porous cylinder ...but I will keep an eye on it when I do. In the meantime, I will close this.
