### ISSUE TITLE
FDS cluster issue on linux OS

### ISSUE THREAD

**Issue by Csabesz90** [firemodels/fds#9996]
Hi there!

I'm trying to run a case with cluster mode (4x same PC) on linux OS. Previously i run cases on Windows OS but after several times running problems (which were because of the Windows) i decided to swith the OS to linux. I followed the wiki page installation and running topic but after i tried to run the case i get the following error (see the attached file)
[error_on_linux.txt](https://github.com/firemodels/fds/files/7460968/error_on_linux.txt)
Let me describe the case i would like to do:
I wanna run a case with 32 mesh. I've got 4 x PC with the same hardwares the config:
•	processors: Intel Core i9-9900K 3.60GHz (8 cores; 16 logical processors)
•	graphic card: Intel UHD graphics 630  OpenGl version and GLSL version: 4.6.0 Build 26.20.100.7642
•	memory: 64GB
So every cores has 1 process to do. I shared my main node directory to the child nodes (with samba read and write permission).  On the shared directory i placed the files i saved from pyrosim. Could you help me please to settle this problem? Would you be so kind and help me with a step by step instruction guide for the script i have to use?
The script i made (see the attachment PBS_file.txt).
[PBS_file.txt](https://github.com/firemodels/fds/files/7461149/PBS_file.txt)

I look forward to receiving your reply.
 
Yours Sincerely
 
Csaba Sallai 
civil engineer, fire engineer

**Comment by mcgratta** [comment]
We cannot help you. You need someone who knows how your network works, how your computers are connected. What kind of Infiniband or network fabric you use for communications, etc. Typically linux clusters are designed, built, and configured so that one compiles and executes code according to the unique specifications of that particular framework. None of us here has the expertise to build a compute cluster from scratch. We bought our clusters from a vendor who installed all the software and network hardware, and we have systems experts who help us maintain it.
